#!/bin/sh

# Copyright (C) 2004, 2005, 2006, 2008, 2010 Free Software Foundation,
# Inc.
#
# Author: Simon Josefsson
#
# This file is part of GnuTLS.
#
# GnuTLS is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at
# your option) any later version.
#
# GnuTLS is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GnuTLS; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

srcdir=${srcdir:-.}
CERTTOOL=${CERTTOOL:-../../src/certtool}

ret=0
for p12 in 'client.p12 foobar' noclient.p12 unclient.p12 pkcs12_2certs.p12; do
    set -- $p12
    file=$1
    passwd=$2
    $CERTTOOL --p12-info --inder --password "$passwd" \
		--infile $srcdir/$file > out 2>&1
    rc=$?
    if test $rc != 0; then
	cat out
	echo "NEON PKCS12 FATAL $p12"
	ret=1
    else
	echo "NEON PKCS12 OK $p12"
    fi
done
rm -f out

echo "NEON PKCS12 DONE (rc $ret)"
exit $ret
