##############################################################################
#                                                                            #
#                       FOX:  A Free C++ Class Library for X                 #
#                                                                            #
##############################################################################
# Copyright (C) 1997,2005 by Jeroen van der Zijp.   All Rights Reserved.     #
##############################################################################
# $Id: Makefile.bc,v 1.26 2006/03/10 04:31:45 fox Exp $                      #
##############################################################################
# This library is free software; you can redistribute it and/or              #
# modify it under the terms of the GNU Library General Public                #
# License as published by the Free Software Foundation; either               #
# version 2 of the License, or (at your option) any later version.           #
#                                                                            #
# This library is distributed in the hope that it will be useful,            #
# but WITHOUT ANY WARRANTY; without even the implied warranty of             #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU          #
# Library General Public License for more details.                           #
#                                                                            #
# You should have received a copy of the GNU Library General Public          #
# License along with this library; if not, write to the Free                 #
# Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.         #
##############################################################################

# For use with Borland C++ Builder 3 or later
CXX       = bcc32
CXXFLAGS  = -5 -O2 -w-par -w-csu -w-aus
RM        = del
TOPDIR    = ..
DEFINES   = -DNDEBUG -DFOX_BIGENDIAN=0 -DWIN32 -D_WINDOWS -DHAVE_GL_H -DHAVE_GLU_H #-DHAVE_PNG_H -DHAVE_JPEG_H -DHAVE_TIFF_H -DXMD_H
LD	  = bcc32
LDFLAGS	  = -laa
GLLIBS    = -lopengl32 -lglu32
INCDIRS   = -I$(TOPDIR)\include
FOXLIB    = $(TOPDIR)\src\FOX-1.6.lib

PROGRAMS  = \
	rex.exe \
	minheritance.exe \
	expression.exe \
	memmap.exe \
	mditest.exe \
	table.exe \
	groupbox.exe \
	foursplit.exe \
	datatarget.exe \
	scribble.exe \
	splitter.exe \
	shutter.exe \
	image.exe \
	header.exe \
	hello.exe \
	hello2.exe \
	switcher.exe \
	iconlist.exe \
	tabbook.exe \
	dialog.exe \
	dirlist.exe \
	button.exe \
	dctest.exe \
	glviewer.exe \
	gltest.exe \
	wizard.exe \
	imageviewer.exe

.cpp.obj:
	$(CXX) -c $(INCDIRS) $(CXXFLAGS) $(DEFINES) $*.cpp

all: $(PROGRAMS)

rex.exe: $(FOXLIB) rex.obj
	$(LD) $(LDFLAGS) rex.obj $(FOXLIB)

minheritance.exe: $(FOXLIB) minheritance.obj
	$(LD) $(LDFLAGS) minheritance.obj $(FOXLIB)

expression.exe: $(FOXLIB) expression.obj
	$(LD) $(LDFLAGS) expression.obj $(FOXLIB)

memmap.exe: $(FOXLIB) memmap.obj
	$(LD) $(LDFLAGS) memmap.obj $(FOXLIB)

wizard.exe: $(FOXLIB) wizard.obj
	$(LD) $(LDFLAGS) wizard.obj $(FOXLIB)

foursplit.exe: $(FOXLIB) foursplit.obj
	$(LD) $(LDFLAGS) foursplit.obj $(FOXLIB)

tabbook.exe: $(FOXLIB) tabbook.obj
	$(LD) $(LDFLAGS) tabbook.obj $(FOXLIB)

table.exe: $(FOXLIB) table.obj
	$(LD) $(LDFLAGS) table.obj $(FOXLIB)

switcher.exe: $(FOXLIB) switcher.obj
	$(LD) $(LDFLAGS) switcher.obj $(FOXLIB)

button.exe: $(FOXLIB) button.obj
	$(LD) $(LDFLAGS) button.obj $(FOXLIB)

mditest.exe: $(FOXLIB) mditest.obj
	$(LD) $(LDFLAGS) mditest.obj $(FOXLIB)

datatarget.exe: $(FOXLIB) datatarget.obj
	$(LD) $(LDFLAGS) datatarget.obj $(FOXLIB)

imageviewer.exe: $(FOXLIB) imageviewer.obj
	$(LD) $(LDFLAGS) imageviewer.obj $(FOXLIB) #libpng.lib zlib.lib libjpeg.lib libtiff.lib

hello.exe: $(FOXLIB) hello.obj
	$(LD) $(LDFLAGS) hello.obj $(FOXLIB)

hello2.exe: $(FOXLIB) hello2.obj
	$(LD) $(LDFLAGS) hello2.obj $(FOXLIB)

dirlist.exe: $(FOXLIB) dirlist.obj
	$(LD) $(LDFLAGS) dirlist.obj $(FOXLIB)

groupbox.exe: $(FOXLIB) groupbox.obj
	$(LD) $(LDFLAGS) groupbox.obj $(FOXLIB)

scribble.exe: $(FOXLIB) scribble.obj
	$(LD) $(LDFLAGS) scribble.obj $(FOXLIB)

splitter.exe: $(FOXLIB) splitter.obj
	$(LD) $(LDFLAGS) splitter.obj $(FOXLIB)

iconlist.exe: $(FOXLIB) iconlist.obj
	$(LD) $(LDFLAGS) iconlist.obj $(FOXLIB)

header.exe: $(FOXLIB) header.obj
	$(LD) $(LDFLAGS) header.obj $(FOXLIB)

shutter.exe: $(FOXLIB) shutter.obj
	$(LD) $(LDFLAGS) shutter.obj $(FOXLIB)

image.exe: $(FOXLIB) image.obj
	$(LD) $(LDFLAGS) image.obj $(FOXLIB)

gltest.exe: $(FOXLIB) gltest.obj
	$(LD) $(LDFLAGS) gltest.obj $(FOXLIB) $(GLLIBS)

glviewer.exe: $(FOXLIB) glviewer.obj
	$(LD) $(LDFLAGS) glviewer.obj $(FOXLIB) $(GLLIBS)

dialog.exe: $(FOXLIB) dialog.obj
	$(LD) $(LDFLAGS) dialog.obj $(FOXLIB)

dctest.exe: $(FOXLIB) dctest.obj
	$(LD) $(LDFLAGS) dctest.obj $(FOXLIB)

clean:
	del *.obj
	del *.exe
	del *.tds
