/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "baa.h"

static ORBitSmallSkeleton get_skel_small_Foo_Child(POA_Foo_Child *servant,
const char *opname,gpointer *m_data, gpointer *impl)
{
switch(opname[0]) {
case 'b':
if(strcmp((opname + 1), "ar")) break;
*impl = (gpointer)servant->vepv->Foo_Child_epv->bar;
{ORBit_IInterface *volatile _t_=&Foo_Child__iinterface;*m_data = (gpointer)&_t_->methods._buffer [0];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_Foo_Child_bar;
break;
case 'f':
if(strcmp((opname + 1), "oo")) break;
*impl = (gpointer)servant->vepv->Foo_Parent_epv->foo;
{ORBit_IInterface *volatile _t_=&Foo_Parent__iinterface;*m_data = (gpointer)&_t_->methods._buffer [0];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_Foo_Parent_foo;
break;
default: break; 
}
return NULL;
}

void POA_Foo_Child__init(PortableServer_Servant servant,
CORBA_Environment *env)
{
  static PortableServer_ClassInfo class_info = {NULL, (ORBit_small_impl_finder)&get_skel_small_Foo_Child, "IDL:Foo/Child:1.0", &Foo_Child__classid, NULL, &Foo_Child__iinterface};
  PortableServer_ServantBase__init (       ((PortableServer_ServantBase *)servant), env);
  POA_Foo_Parent__init(servant, env);
   ORBit_skel_class_register (&class_info,
   (PortableServer_ServantBase *)servant, POA_Foo_Child__fini,
   ORBIT_VEPV_OFFSET (POA_Foo_Child__vepv, Foo_Child_epv),
(CORBA_unsigned_long) Foo_Parent__classid,
ORBIT_VEPV_OFFSET (POA_Foo_Child__vepv, Foo_Parent_epv),
   (CORBA_unsigned_long) 0);}

void POA_Foo_Child__fini(PortableServer_Servant servant,
CORBA_Environment *env)
{
  POA_Foo_Parent__fini(servant, env);
  PortableServer_ServantBase__fini(servant, env);
}

