

#if !defined(__BAA_COMPILATION) && defined(__ORBIT_IDL__)
%{
#pragma include_defs foo.h
%}
#pragma inhibit push
#endif

#include <foo.idl>

#if !defined(__BAA_COMPILATION) && defined(__ORBIT_IDL__)
#pragma inhibit pop
#endif

module Foo {
  interface Child : Parent {
    void bar ();
  };
};
