set -o pipefail
'opt' '-constprop' '-S' > '/private/var/chris/llvm-2.8/test/Assembler/Output/2002-04-07-HexFloatConstants.ll.tmp.1' < '/private/var/chris/llvm-2.8/test/Assembler/2002-04-07-HexFloatConstants.ll'  &&

'llvm-as' < '/private/var/chris/llvm-2.8/test/Assembler/2002-04-07-HexFloatConstants.ll' |
  'llvm-dis' |
  'llvm-as' |
  'opt' '-constprop' |
  'llvm-dis' > '/private/var/chris/llvm-2.8/test/Assembler/Output/2002-04-07-HexFloatConstants.ll.tmp.2'  &&

'diff' '/private/var/chris/llvm-2.8/test/Assembler/Output/2002-04-07-HexFloatConstants.ll.tmp.1' '/private/var/chris/llvm-2.8/test/Assembler/Output/2002-04-07-HexFloatConstants.ll.tmp.2'