set -o pipefail
'llvm-as' < '/private/var/chris/llvm-2.8/test/Assembler/2007-12-11-AddressSpaces.ll' |
  'llvm-dis' |
  'grep' 'addrspace(33)' |
  'count' '7'  &&

'llvm-as' < '/private/var/chris/llvm-2.8/test/Assembler/2007-12-11-AddressSpaces.ll' |
  'llvm-dis' |
  'grep' 'addrspace(42)' |
  'count' '2'  &&

'llvm-as' < '/private/var/chris/llvm-2.8/test/Assembler/2007-12-11-AddressSpaces.ll' |
  'llvm-dis' |
  'grep' 'addrspace(66)' |
  'count' '2'  &&

'llvm-as' < '/private/var/chris/llvm-2.8/test/Assembler/2007-12-11-AddressSpaces.ll' |
  'llvm-dis' |
  'grep' 'addrspace(11)' |
  'count' '6'  &&

'llvm-as' < '/private/var/chris/llvm-2.8/test/Assembler/2007-12-11-AddressSpaces.ll' |
  'llvm-dis' |
  'grep' 'addrspace(22)' |
  'count' '5'