set -o pipefail
'llvm-as' < '/private/var/chris/llvm-2.8/test/Assembler/AutoUpgradeIntrinsics.ll' |
  'llvm-dis' |
  'not' 'grep' 'i32 @llvm\.ct'  &&

'llvm-as' < '/private/var/chris/llvm-2.8/test/Assembler/AutoUpgradeIntrinsics.ll' |
  'llvm-dis' |
  'not' 'grep' 'llvm\.part\.set\.i[0-9]*\.i[0-9]*\.i[0-9]*'  &&

'llvm-as' < '/private/var/chris/llvm-2.8/test/Assembler/AutoUpgradeIntrinsics.ll' |
  'llvm-dis' |
  'not' 'grep' 'llvm\.part\.select\.i[0-9]*\.i[0-9]*'  &&

'llvm-as' < '/private/var/chris/llvm-2.8/test/Assembler/AutoUpgradeIntrinsics.ll' |
  'llvm-dis' |
  'not' 'grep' 'llvm\.bswap\.i[0-9]*\.i[0-9]*'  &&

'llvm-as' < '/private/var/chris/llvm-2.8/test/Assembler/AutoUpgradeIntrinsics.ll' |
  'llvm-dis' |
  'grep' 'llvm\.x86\.mmx\.ps' |
  'grep' '\<2 x i32\>' |
  'count' '6'