set -o pipefail
'llvm-as' < '/private/var/chris/llvm-2.8/test/Assembler/insertextractvalue.ll' |
  'llvm-dis' > '/private/var/chris/llvm-2.8/test/Assembler/Output/insertextractvalue.ll.tmp'  &&

'grep' 'insertvalue' '/private/var/chris/llvm-2.8/test/Assembler/Output/insertextractvalue.ll.tmp' |
  'count' '1'  &&

'grep' 'extractvalue' '/private/var/chris/llvm-2.8/test/Assembler/Output/insertextractvalue.ll.tmp' |
  'count' '1'