set -o pipefail
'llvm-as' < '/private/var/chris/llvm-2.8/test/Assembler/vector-shift.ll' |
  'llvm-dis' |
  'llvm-as' |
  'llvm-dis' |
  'grep' 'shl' |
  'count' '1'  &&

'llvm-as' < '/private/var/chris/llvm-2.8/test/Assembler/vector-shift.ll' |
  'llvm-dis' |
  'llvm-as' |
  'llvm-dis' |
  'grep' 'ashr' |
  'count' '1'  &&

'llvm-as' < '/private/var/chris/llvm-2.8/test/Assembler/vector-shift.ll' |
  'llvm-dis' |
  'llvm-as' |
  'llvm-dis' |
  'grep' 'lshr' |
  'count' '1'