#pragma inhibit push
#include "corba-defs.idl"
#pragma inhibit pop

#include "IIOP.idl"
#include "GIOP.idl"
#include "CSI.idl"
#include "CSIIOP.idl"
#include "BiDirPolicy.idl"
#include "conv_frame.idl"
#include "orbit-specific.idl"
