@c English version: 2011-03-28
@menu
* Funciones y variables para ggf::
@end menu

@node Funciones y variables para ggf,  , ggf, ggf
@section Funciones y variables para ggf


@defvr {Variable opcional} GGFINFINITY
Valor por defecto: 3

Variable opcional para la funci@'on @code{ggf}.

Cuando se calcula la fracci@'on continua de la funci@'on
generatriz, si un cociente parcial tiene grado estrictamente
mayor que @var{GGFINFINITY} ser@'a descartado y la convergencia
alcanzada hasta ese momento ser@'a considerada como exacta para
la funci@'on generatriz. Lo m@'as frecuente es que el grado de
todos los cocientes parciales sea 0 @'o 1, de modo que si se
utiliza un valor mayor se deber@'an dar m@'as t@'erminos para
conseguir un c@'alculo m@'as exacto.

V@'ease tambi@'en @code{ggf}.
@end defvr


@defvr {Variable opcional} GGFCFMAX
Valor por defeco: 3

Variable opcional para la funci@'on @code{ggf}.

Cuando se calcula la fracci@'on continua de la funci@'on
generatriz, si no se ha encontrado un resultado aceptable
(v@'ease la variable @var{GGFINFINITY}) despu@'es de haber 
calculado @var{GGFCFMAX} cocientes parciales, la funci@'on
generatriz ser@'a considerada no equivalente a una fracci@'on
racional y la funci@'on @code{ggf} se detendr@'a. Puede
asign@'arsele a @var{GGFCFMAX} un valor mayor para funciones
generatrices m@'as complicadas.

V@'ease tambi@'en @code{ggf}.
@end defvr

@deffn {Funci@'on} ggf (@var{l})
Calcula la funci@'on generatriz de una sucesi@'on de la que
se suministran tan solo los primeros valores y cuyo t@'ermino
general es una fracci@'on algebraica (cociente de dos
polinomios).

La soluci@'on se devuelve como una fracci@'on de polinomios. 
En caso de no poder encontrar una soluci@'on, se devuelve
@code{done}.

Esta funci@'on est@'a controlada por las variables globales 
@var{GGFINFINITY} y @var{GGFCFMAX}. V@'eanse tambi@'en @var{GGFINFINITY} y @var{GGFCFMAX}.

Antes de hacer uso de esta funci@'on ejec@'utese  @code{load("ggf")}.
@end deffn
