set -o pipefail
'llc' '-mtriple=thumbv7-apple-darwin10' '-march=thumb' '-mcpu=cortex-m3' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/cortex-fp.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/cortex-fp.ll' '-check-prefix=CORTEXM3'  &&

'llc' '-mtriple=thumbv7-apple-darwin10' '-march=thumb' '-mcpu=cortex-m4' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/cortex-fp.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/cortex-fp.ll' '-check-prefix=CORTEXM4'  &&

'llc' '-mtriple=thumbv7-apple-darwin10' '-march=thumb' '-mcpu=cortex-a8' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/cortex-fp.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/cortex-fp.ll' '-check-prefix=CORTEXA8'