set -o pipefail
'llc' '-march=thumb' '-mattr=+thumb2' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/div.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/div.ll' '-check-prefix=CHECK-THUMB'  &&

'llc' '-march=thumb' '-mcpu=cortex-m3' '-mattr=+thumb2' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/div.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/div.ll' '-check-prefix=CHECK-THUMBV7M'