set -o pipefail
'llc' '-march=thumb' '-mattr=+thumb2' '-mtriple=arm-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/large-stack.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/large-stack.ll' '-check-prefix=DARWIN'  &&

'llc' '-march=thumb' '-mattr=+thumb2' '-mtriple=arm-linux-gnueabi' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/large-stack.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/large-stack.ll' '-check-prefix=LINUX'