set -o pipefail
'llc' '-mtriple=thumbv7-apple-darwin' '-relocation-model=static' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/load-global.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/load-global.ll' '-check-prefix=STATIC'  &&

'llc' '-mtriple=thumbv7-apple-darwin' '-relocation-model=dynamic-no-pic' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/load-global.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/load-global.ll' '-check-prefix=DYNAMIC'  &&

'llc' '-mtriple=thumbv7-apple-darwin' '-relocation-model=pic' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/load-global.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/load-global.ll' '-check-prefix=PIC'  &&

'llc' '-mtriple=thumbv7-linux-gnueabi' '-relocation-model=pic' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/load-global.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/load-global.ll' '-check-prefix=LINUX'