set -o pipefail
'llc' '-mtriple=thumbv7-apple-darwin' '-mcpu=cortex-a8' '-disable-fp-elim' '-arm-vdup-splat' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/machine-licm-vdup.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/machine-licm-vdup.ll'  &&

'llc' '-mtriple=thumbv7-apple-darwin' '-mcpu=cortex-a8' '-relocation-model=pic' '-disable-fp-elim' '-arm-vdup-splat' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/machine-licm-vdup.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/machine-licm-vdup.ll'