set -o pipefail
'llc' '-march=thumb' '-mattr=+thumb2' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-ldr_ext.ll' |
  'grep' 'ldrb' |
  'count' '1'  &&

'llc' '-march=thumb' '-mattr=+thumb2' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-ldr_ext.ll' |
  'grep' 'ldrh' |
  'count' '1'  &&

'llc' '-march=thumb' '-mattr=+thumb2' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-ldr_ext.ll' |
  'grep' 'ldrsb' |
  'count' '1'  &&

'llc' '-march=thumb' '-mattr=+thumb2' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-ldr_ext.ll' |
  'grep' 'ldrsh' |
  'count' '1'