set -o pipefail
'llc' '-mtriple=thumbv7-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-tbb.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-tbb.ll'  &&

'llc' '-mtriple=thumbv7-apple-darwin' '-relocation-model=pic' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-tbb.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-tbb.ll'