set -o pipefail
'llc' '-march=thumb' '-mattr=+thumb2' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-add.ll' |
  'grep' 'add' |
  'grep' '#255'  &&

'llc' '-march=thumb' '-mattr=+thumb2' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-add.ll' |
  'grep' 'add' |
  'grep' '#256'  &&

'llc' '-march=thumb' '-mattr=+thumb2' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-add.ll' |
  'grep' 'add' |
  'grep' '#257'  &&

'llc' '-march=thumb' '-mattr=+thumb2' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-add.ll' |
  'grep' 'add' |
  'grep' '#4094'  &&

'llc' '-march=thumb' '-mattr=+thumb2' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-add.ll' |
  'grep' 'add' |
  'grep' '#4095'  &&

'llc' '-march=thumb' '-mattr=+thumb2' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-add.ll' |
  'grep' 'add' |
  'grep' '#4096'  &&

'llc' '-march=thumb' '-mattr=+thumb2' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-add.ll' |
  'grep' 'add'  &&

'llc' '-march=thumb' '-mattr=+thumb2' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-add.ll' |
  'grep' 'add' |
  'grep' 'lsl' |
  'grep' '#8'