set -o pipefail
'llc' '-march=thumb' '-mcpu=cortex-a8' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-uxtb.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-uxtb.ll' '-check-prefix=ARMv7A'  &&

'llc' '-march=thumb' '-mcpu=cortex-m3' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-uxtb.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-uxtb.ll' '-check-prefix=ARMv7M'