set -o pipefail
'llc' '-mtriple=thumbv7-apple-darwin' '-mattr=+thumb2' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-call-tc.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-call-tc.ll' '-check-prefix=DARWIN'  &&

'llc' '-mtriple=thumbv7-linux' '-mattr=+thumb2' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-call-tc.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/thumb2-call-tc.ll' '-check-prefix=LINUX'