set -o pipefail
'llc' '-mtriple=thumbv7-linux-gnueabi' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/tls1.ll' |
  'grep' 'i(tpoff)'  &&

'llc' '-mtriple=thumbv7-linux-gnueabi' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/tls1.ll' |
  'grep' '__aeabi_read_tp'  &&

'llc' '-mtriple=thumbv7-linux-gnueabi' '-relocation-model=pic' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/tls1.ll' |
  'grep' '__tls_get_addr'