set -o pipefail
'llc' '-mtriple=thumbv7-linux-gnueabi' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/tls2.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/tls2.ll' '-check-prefix=CHECK-NOT-PIC'  &&

'llc' '-mtriple=thumbv7-linux-gnueabi' '-relocation-model=pic' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/tls2.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb2/tls2.ll' '-check-prefix=CHECK-PIC'