// File: CONV_FRAME.idl
// From CORBA 2.3: Chapter 13, Interoperability Architecture

#ifndef _CONV_FRAME_IDL
#define _CONV_FRAME_IDL

#pragma prefix "omg.org"

module CONV_FRAME {
    typedef unsigned long CodeSetId;

    struct CodeSetComponent {
        CodeSetId               native_code_set;
        sequence<CodeSetId>     conversion_code_sets;
    };
    struct CodeSetComponentInfo {
        CodeSetComponent        ForCharData;
        CodeSetComponent        ForWcharData;
        };

    struct CodeSetContext {
        CodeSetId               char_data;
        CodeSetId               wchar_data;
    };
};
#endif // _CONV_FRAME_IDL

