@c @c Language: Brazilian Portuguese, Encoding: iso-8859-1
@c /f90.texi/1.1/Mon Feb 27 22:09:17 2006//
@menu
* Defini@value{cedilha}@~oes para f90::
@end menu

@node Defini@value{cedilha}@~oes para f90,  , f90, f90
@section Defini@value{cedilha}@~oes para f90


@deffn {Fun@value{cedilha}@~ao} f90 (@var{expr})
O comando f90 @'e uma actualiza@value{cedilha}@~ao do comando
@code{fortran} original do maxima. A principal diferen@value{cedilha}a
@'e na forma como s@~ao divididas as linhas muito compridas.

No exemplo seguinte, observe como o comando @code{fortran} divide linhas
no meio de s@'{@dotless{i}}mbolos. O comando @code{f90} nunca separa uma
linha no meio de um s@'{@dotless{i}}mbolo.

@example
(%i1) load("f90")$

(%i2) expr:expand((xxx+yyy+7)^4);
         4            3         3        2    2
(%o2) yyy  + 4 xxx yyy  + 28 yyy  + 6 xxx  yyy
             2          2        3             2
 + 84 xxx yyy  + 294 yyy  + 4 xxx  yyy + 84 xxx  yyy
                               4         3          2
 + 588 xxx yyy + 1372 yyy + xxx  + 28 xxx  + 294 xxx
 + 1372 xxx + 2401
(%i3) fortran(expr);
      yyy**4+4*xxx*yyy**3+28*yyy**3+6*xxx**2*yyy**2+84*xxx*yyy**2+294*yy
     1   y**2+4*xxx**3*yyy+84*xxx**2*yyy+588*xxx*yyy+1372*yyy+xxx**4+28*
     2   xxx**3+294*xxx**2+1372*xxx+2401
(%o3)                       done
(%i4) f90(expr);
yyy**4+4*xxx*yyy**3+28*yyy**3+6*xxx**2*yyy**2+84*xxx*yyy**2+294* &
     yyy**2+4*xxx**3*yyy+84*xxx**2*yyy+588*xxx*yyy+1372*yyy+xxx** &
     4+28*xxx**3+294*xxx**2+1372*xxx+2401
(%o4)                       done
@end example

A fun@,{c}@~ao @code{f90} foi criada como uma forma r@'apida de resolver
um problema. N@~ao ser@'a necessariamente um bom exemplo a seguir para
tradu@,{c}@~oes de outras linguagens de programa@value{cedilha}@~ao.

Para usar esta fun@value{cedilha}@~ao, use primeiro @code{load("f90")}.
@end deffn

