@c /ggf.texi/1.3/Tue Jul 25 12:01:54 2006//
@menu
* Defini@value{cedilha}@~oes para ggf::
@end menu

@node Defini@value{cedilha}@~oes para ggf,  , ggf, ggf
@section Defini@value{cedilha}@~oes para ggf

@defvr {Vari@'avel de Op@value{cedilha}@~ao} GGFINFINITY
Valor por omiss@~ao: 3

Essa @'e uma vari@'avel de op@value{cedilha}@~ao para a fun@value{cedilha}@~ao @code{ggf}.

Quando calculando a fra@value{cedilha}@~ao cont@'{@dotless{i}}nua da
fun@value{cedilha}@~ao geradora, um quociente parcial tendo um grau
(estritamente) maior que @var{GGFINFINITY} ser@'a descartado e
o convergente actual ser@'a considerado como o valor exato
da fun@value{cedilha}@~ao geradora; na grande mioria dos casos o grau de todos
os quocientes parciais ser@'a ou 0 ou 1; se usar um valor muito grande,
ent@~ao poder@'a fornecer termos suficientes com o objectivo de fazer o
c@'alculo preciso o bastante.

Veja tamb@'em @code{ggf}.
@end defvr

@defvr {Vari@'avel de op@value{cedilha}@~ao} GGFCFMAX
Valor por omiss@~ao: 3

Essa @'e uma vari@'avel de op@value{cedilha}@~ao para a fun@value{cedilha}@~ao @code{ggf}.

Quando calculando a fra@value{cedilha}@~ao cont@'{@dotless{i}}nua da
fun@value{cedilha}@~ao geradora, se nenhum bom resultado for encontrado (veja
o sinalizador @var{GGFINFINITY}) ap@'os se ter calculado uma quantidade de @var{GGFCFMAX} quocientes
parciais, a fun@value{cedilha}@~ao geradora ser@'a considerada como
n@~ao sendo uma fra@value{cedilha}@~ao de dois polin@'omios e a fun@value{cedilha}@~ao ir@'a
terminar. Coloque livemente um valor muito grande para fun@value{cedilha}@~oes geradoras
mais complicadas.

Veja tamb@'em @code{ggf}.
@end defvr

@deffn {Fun@value{cedilha}@~ao} ggf (@var{l})
Calcula a fun@value{cedilha}@~ao geradora (se for uma fra@value{cedilha}@~ao de dois
polin@'omios) de uma sequ@^encia, sendo dados seus primeiros termos. @var{l}
@'e uma lista de n@'umeros.

A solu@value{cedilha}@~ao @'e retornada como uma fra@value{cedilha}@~ao de dois polin@'omios.
Se nenhuma solu@value{cedilha}@~ao tiver sido encontrada, @'e retornado @code{done}.

Essa fun@value{cedilha}@~ao @'e controlada attrav@'es das vari@'aveis globais @var{GGFINFINITY} e @var{GGFCFMAX}. Veja tamb@'em @var{GGFINFINITY} e @var{GGFCFMAX}.

Para usar essa fun@value{cedilha}@~ao primeiro escreva @code{load("ggf")}.
@end deffn
