@c /Numerical.texi/1.24/Mon Feb 19 14:23:08 2007/-ko/
@menu
* Introdu@value{cedilha}@~ao a Num@'erico::
* Pacotes de Fourier::
* Defini@value{cedilha}@~oes para Num@'erico::
* Defini@value{cedilha}@~oes para S@'eries de Fourier::
@end menu

@node Introdu@value{cedilha}@~ao a Num@'erico, Pacotes de Fourier, Num@'erico, Num@'erico
@section Introdu@value{cedilha}@~ao a Num@'erico

@node Pacotes de Fourier, Defini@value{cedilha}@~oes para Num@'erico, Introdu@value{cedilha}@~ao a Num@'erico, Num@'erico
@section Pacotes de Fourier
O pacote @code{fft} compreende fun@value{cedilha}@~oes para computa@value{cedilha}@~ao num@'erica (n@~ao simb@'olica)
das transforma@value{cedilha}@~oes r@'apidas de Fourier.
@code{load ("fft")} chama esse pacote.
Veja @code{fft}.

O pacote @code{fourie} compreende fun@value{cedilha}@~oes para computa@value{cedilha}@~ao simb@'olica
de s@'eries de Fourier.
@code{load ("fourie")} chama esse pacote.
Existem fun@value{cedilha}@~oes no pacote @code{fourie} para calcular coeficientes da
integral de Fourier e algumas fun@value{cedilha}@~oes para manipula@value{cedilha}@~ao de express@~oes.
Veja @code{Defini@value{cedilha}@~oes para S@'eries}.

@c end concepts Numerical

@node Defini@value{cedilha}@~oes para Num@'erico, Defini@value{cedilha}@~oes para S@'eries de Fourier, Pacotes de Fourier, Num@'erico
@section Defini@value{cedilha}@~oes para Num@'erico
@c NOTE: Let's keep POLARTORECT, RECTTOPOLAR, and IFT before FFT
@c in this file. Otherwise DESCRIBE returns the FFT text (because
@c POLARTORECT, etc are list in the heading of FFT with @defunx).

@deffn {Fun@value{cedilha}@~ao} polartorect (@var{magnitude_array}, @var{phase_array})

Traduz valores complexos da forma @code{r %e^(%i t)} para a forma @code{a + b %i}.
@code{load ("fft")} chama essa fun@value{cedilha}@~ao dentro do Maxima. Veja tamb@'em @code{fft}.

O m@'odulo e a fase, @code{r} e @code{t}, S@~ao tomados de @var{magnitude_array} e
@var{phase_array}, respectivamente. Os valores originais de arrays de entrada s@~ao
substitu@'{@dotless{i}}dos pelas partes real e emagin@'aria, @code{a} e @code{b}, no retorno. As sa@'{@dotless{i}}das s@~ao
calculadas como

@example
a: r cos (t)
b: r sin (t)
@end example

Os arrays de entrada devem ter o mesmo tamanho  e ser unidimensionais.
O tamanho do array n@~ao deve ser uma pot@^encia de 2.

@code{polartorect} @'e a fun@value{cedilha}@~ao inversa de @code{recttopolar}.

@end deffn

@deffn {Fun@value{cedilha}@~ao} recttopolar (@var{real_array}, @var{imaginary_array})

Traduz valores complexos da forma @code{a + b %i} para a forma @code{r %e^(%i t)}.
@code{load ("fft")} chama essa fun@value{cedilha}@~ao dentro do Maxima. Veja tamb@'em @code{fft}.

As partes real e imagin@'aria, @code{a} e @code{b}, s@~ao tomadas de @var{real_array} e
@var{imaginary_array}, respectivamente. Os valores originais dos arrays de entrada
s@~ao substitu@'{@dotless{i}}dos pelo m@'odulo e pelo @^angulo, @code{r} e @code{t}, no retorno. As sa@'{@dotless{i}}das s@~ao
calculadas como

@example
r: sqrt (a^2 + b^2)
t: atan2 (b, a)
@end example

O @^angulo calculado encontra-se no intervalo de @code{-%pi} a @code{%pi}. 

Os arrays de entrada devem ter o mesmo tamanho e ser unidimensionais.
O tamanho do array n@~ao deve ser uma pot@^encia de 2.

@code{recttopolar} @'e a fun@value{cedilha}@~ao inversa de @code{polartorect}.

@end deffn

@deffn {Fun@value{cedilha}@~ao} ift (@var{real_array}, @var{imaginary_array})

Transforma@value{cedilha}@~ao r@'apida inversa discreta de Fourier . @code{load ("fft")} chama essa fun@value{cedilha}@~ao
dentro do Maxima.

@code{ift} realiza a transforma@value{cedilha}@~ao r@'apida complexa de Fourier sobre
arrays em ponto flutuante unidimensionais. A transforma@value{cedilha}@~ao inversa @'e definida como

@example
x[j]: sum (y[j] exp (+2 %i %pi j k / n), k, 0, n-1)
@end example

Veja @code{fft} para maiores detalhes.

@end deffn

@deffn {Fun@value{cedilha}@~ao} fft (@var{real_array}, @var{imaginary_array})
@deffnx {Fun@value{cedilha}@~ao} ift (@var{real_array}, @var{imaginary_array})
@deffnx {Fun@value{cedilha}@~ao} recttopolar (@var{real_array}, @var{imaginary_array})
@deffnx {Fun@value{cedilha}@~ao} polartorect (@var{magnitude_array}, @var{phase_array})

Transforma@value{cedilha}@~ao r@'apidada de Fourier e fun@value{cedilha}@~oes relacionadas. @code{load ("fft")}
chama essas fun@value{cedilha}@~oes dentro do Maxima.

@code{fft} e @code{ift} realiza transforma@value{cedilha}@~ao r@'apida complexa de Fourier e
a transforma@value{cedilha}@~ao inversa, respectivamente, sobre arrays em ponto flutuante
unidimensionais. O tamanho de @var{imaginary_array} deve ser igual ao tamanho de @var{real_array}.

@code{fft} e @code{ift} operam in-loco. Isto @'e, sobre o retorno de @code{fft} ou de @code{ift},
O conte@'udo original dos arrays de entrada @'e substitu@'{@dotless{i}}do pela sa@'{@dotless{i}}da.
A fun@value{cedilha}@~ao @code{fillarray} pode fazer uma c@'opia de um array, isso pode
ser necess@'ario.

A transforma@value{cedilha}@~ao discreta de Fourier e sua transforma@value{cedilha}@~ao inversa s@~ao definidas
como segue. Tome @code{x} sendo os dados originais, com

@example
x[i]: real_array[i] + %i imaginary_array[i]
@end example
  
Tome @code{y} sendo os dados transformados. A transforma@value{cedilha}@~ao normal e sua transforma@value{cedilha}@~ao inversa s@~ao

@example
y[k]: (1/n) sum (x[j] exp (-2 %i %pi j k / n), j, 0, n-1)

x[j]:       sum (y[j] exp (+2 %i %pi j k / n), k, 0, n-1)
@end example

Arrays adequadas podem ser alocadas pela fun@value{cedilha}@~ao @code{array}. Por exemplo:

@example
array (my_array, float, n-1)$
@end example

declara um array unidimensional com n elementos, indexado de 0 a
n-1 inclusive. O n@'umero de elementos n deve ser igual a 2^m para algum m.

@code{fft} pode ser aplicada a dados reais (todos os arrays imagin@'arios s@~ao iguais a zero) para obter
coeficientes seno e co-seno.  Ap@'os chamar @code{fft}, os coeficientes
seno e co-seno, digamos @code{a} e @code{b}, podem ser calculados como

@example
a[0]: real_array[0]
b[0]: 0
@end example

e

@example
a[j]: real_array[j] + real_array[n-j]
b[j]: imaginary_array[j] - imaginary_array[n-j]
@end example

para j variando de 1 a n/2-1, e

@example
a[n/2]: real_array[n/2]
b[n/2]: 0
@end example

@code{recttopolar} traduz valores complexos da forma @code{a + b %i} para
a forma @code{r %e^(%i t)}. Veja @code{recttopolar}.

@code{polartorect} traduz valores complexos da forma @code{r %e^(%i t)}
para a forma @code{a + b %i}. Veja @code{polartorect}.

@code{demo ("fft")} exibe uma demonstra@value{cedilha}@~ao do pacote @code{fft}.

@end deffn

@defvr {Vari@'avel de op@value{cedilha}@~ao} fortindent
Valor por omiss@~ao: 0

@code{fortindent} controla a margem esquerda de indenta@value{cedilha}@~ao de
express@~oes mostradas pelo comando @code{fortran}.  0 fornece indenta@value{cedilha}@~ao
normal (i.e., 6 espa@value{cedilha}os), e valores positivos far@~ao com que
express@~oes sejam mostrados mais al@'em para a direita.

@end defvr

@deffn {Fun@value{cedilha}@~ao} fortran (@var{expr})
Mostra @var{expr} como uma declara@value{cedilha}@~ao Fortran.
A linha de sa@'{@dotless{i}}da @'e indentada com espa@value{cedilha}os.
Se a linha for muito longa, @code{fortran} imprime linhas de continua@value{cedilha}@~ao.
@code{fortran} mostra o operador de exponencia@value{cedilha}@~ao @code{^} como @code{**},
e mostra um n@'umero complexo @code{a + b %i} na forma @code{(a,b)}.

@var{expr} pode ser uma equa@value{cedilha}@~ao. Nesse caso, @code{fortran} mostra uma declara@value{cedilha}@~ao de
atribui@value{cedilha}@~ao, atribuindo o primeiro membro (esquerda) da equa@value{cedilha}@~ao ao segundo membro (direita).
Em particular, se o primeiro membro @var{expr} @'e um nome de uma matriz,
ent@~ao @code{fortran} mostra uma declara@value{cedilha}@~ao de atribui@value{cedilha}@~ao para cada elemento da matriz.

Se @var{expr} n@~ao for alguma coisa reconhecida por @code{fortran},
a express@~ao @'e mostrada no formato @code{grind} sem reclama@value{cedilha}@~ao.
@code{fortran} n@~ao conhece listas, arrays ou fun@value{cedilha}@~oes.

@code{fortindent} controla o margem esquerda das linhas mostradas.
0 @'e a margem normal (i.e., indentada 6 espa@value{cedilha}os). Incrementando @code{fortindent}
faz com que express@~oes sejam mostradas adiante para a direita.

quando @code{fortspaces} for @code{true}, @code{fortran} preenche
cada linha mostrada com espa@value{cedilha}os em branco at@'e completar 80 columas.

@code{fortran} avalia seus argumentos;
colocando um ap@'ostrofo em um argumento evita avalia@value{cedilha}@~ao.
@code{fortran} sempre retorna @code{done}.

Exemplos:

@example
(%i1) expr: (a + b)^12$
(%i2) fortran (expr);
      (b+a)**12                                                                 
(%o2)                         done
(%i3) fortran ('x=expr);
      x = (b+a)**12                                                             
(%o3)                         done
(%i4) fortran ('x=expand (expr));
      x = b**12+12*a*b**11+66*a**2*b**10+220*a**3*b**9+495*a**4*b**8+792        
     1   *a**5*b**7+924*a**6*b**6+792*a**7*b**5+495*a**8*b**4+220*a**9*b        
     2   **3+66*a**10*b**2+12*a**11*b+a**12                                     
(%o4)                         done
(%i5) fortran ('x=7+5*%i);
      x = (7,5)                                                                 
(%o5)                         done
(%i6) fortran ('x=[1,2,3,4]);
      x = [1,2,3,4]                                                             
(%o6)                         done
(%i7) f(x) := x^2$
(%i8) fortran (f);
      f                                                                         
(%o8)                         done
@end example

@end deffn

@defvr {Vari@'avel de op@value{cedilha}@~ao} fortspaces
Valor por omiss@~ao: @code{false}

Quando @code{fortspaces} for @code{true}, @code{fortran} preenche
cada linha mostrada com espa@value{cedilha}os em branco at@'e completar 80 columas.

@end defvr

@deffn {Fun@value{cedilha}@~ao} horner (@var{expr}, @var{x})
@deffnx {Fun@value{cedilha}@~ao} horner (@var{expr})
Retorna uma representa@value{cedilha}@~ao rearranjada de @var{expr} como
na regra de Horner, usando @var{x} como vari@'avel principal se isso for especificado.
@code{x} pode ser omitido e nesse caso a vari@'avel principal da forma de express@~ao racional
can@'onica de @var{expr} @'e usada.

@code{horner} algumas vezes melhora a estabilidade se @code{expr} for
ser numericamente avaliada.  Isso tamb@'em @'e @'util se Maxima @'e usado para
gerar programas para rodar em Fortran. Veja tamb@'em @code{stringout}.

@example
(%i1) expr: 1e-155*x^2 - 5.5*x + 5.2e155;
                           2
(%o1)            1.0E-155 x  - 5.5 x + 5.2E+155
(%i2) expr2: horner (%, x), keepfloat: true;
(%o2)            (1.0E-155 x - 5.5) x + 5.2E+155
(%i3) ev (expr, x=1e155);
Maxima encountered a Lisp error:

 floating point overflow

Automatically continuing.
To reenable the Lisp debugger set *debugger-hook* to nil.
(%i4) ev (expr2, x=1e155);
(%o4)                       7.0E+154
@end example

@end deffn

@c NEEDS WORK
@deffn {Fun@value{cedilha}@~ao} find_root (@var{f}(@var{x}), @var{x}, @var{a}, @var{b})
@deffnx {Fun@value{cedilha}@~ao} find_root (@var{f}, @var{a}, @var{b})
Encontra a ra@'{@dotless{i}}z da fun@value{cedilha}@~ao @var{f} com a vari@'avel @var{x} percorrendo o intervalo @code{[@var{a}, @var{b}]}.
A fun@value{cedilha}@~ao deve ter um
sinal diferente em cada ponto final.  Se essa condi@value{cedilha}@~ao n@~ao for alcan@value{cedilha}ada, a
action of the function is governed by @code{find_root_error}.  If
@code{find_root_error} is @code{true} then an error occurs, otherwise the value of
@code{find_root_error} is returned (thus for plotting @code{find_root_error} might be set to
0.0).  De outra forma (dado que Maxima pode avaliar o primeiro argumento
no intervalo especificado, e que o intervalo @'e cont@'{@dotless{i}}nuo) @code{find_root} @'e
garantido vir para cima com a ra@'{@dotless{i}}z (ou um deles se existir mais
que uma ra@'{@dotless{i}}z).  A precis@~ao de @code{find_root} @'e governada por
@code{intpolabs} e @code{intpolrel} os quais devem ser n@'umeros em ponto flutuante
n@~ao negativos.  @code{find_root} encerrar@'a quando o primeiro argumento avaliar para
alguma coisa menor que ou igual a @code{intpolabs} ou se sucessivas
aproxima@value{cedilha}@~oes da ra@'{@dotless{i}}z diferirem por n@~ao mais que @code{intpolrel * <um dos aproximandos>}.
O valor padr@~ao de @code{intpolabs} e @code{intpolrel} s@~ao
0.0 de forma que @code{find_root} pega como boa uma resposta como for poss@'{@dotless{i}}vel com a
precis@~ao aritm@'etica simples que tivermos.  O primeiro argumento pode ser uma
equa@value{cedilha}@~ao.  A ordem dos dois @'ultimos argumentos @'e irrelevante.  Dessa forma

@example
find_root (sin(x) = x/2, x, %pi, 0.1);
@end example

@'e equivalente a

@example
find_root (sin(x) = x/2, x, 0.1, %pi);
@end example

O m@'etodo usado @'e uma busca bin@'aria no intervalo especificado pelos @'ultimos
dois argumentos.  Quando o resultado da busca for encontrado a fun@value{cedilha}@~ao @'e fechada o suficiente para ser
linear, isso inicia usando interpola@value{cedilha}@~ao linear.

Examples:
@c ===beg===
@c f(x):=(mode_declare(x,float),sin(x)-x/2.0);
@c find_root(sin(x)-x/2,x,0.1,%pi)       time= 60 msec
@c find_root(f(x),x,0.1,%pi);            time= 68 msec
@c translate(f);
@c find_root(f(x),x,0.1,%pi);            time= 26 msec
@c find_root(f,0.1,%pi);                 time=  5 msec
@c
@c STUFF BELOW GENERATED FROM THE FOLLOWING
@c f(x) := sin(x) - x/2;
@c find_root (sin(x) - x/2, x, 0.1, %pi);
@c find_root (sin(x) = x/2, x, 0.1, %pi);
@c find_root (f(x), x, 0.1, %pi);
@c find_root (f, 0.1, %pi);
@example
(%i1) f(x) := sin(x) - x/2;
                                        x
(%o1)                  f(x) := sin(x) - -
                                        2
(%i2) find_root (sin(x) - x/2, x, 0.1, %pi);
(%o2)                   1.895494267033981
(%i3) find_root (sin(x) = x/2, x, 0.1, %pi);
(%o3)                   1.895494267033981
(%i4) find_root (f(x), x, 0.1, %pi);
(%o4)                   1.895494267033981
(%i5) find_root (f, 0.1, %pi);
(%o5)                   1.895494267033981
@end example

@end deffn

@defvr {Vari@'avel de op@value{cedilha}@~ao} find_root_abs
Valor por omiss@~ao: 0.0

@code{find_root_abs} @'e a precis@~ao do comando @code{find_root}. A precis@~ao @'e
governada por @code{find_root_abs} e @code{find_root_rel} que devem ser
n@'umeros n@~ao negativos em ponto flutuante.  @code{find_root} terminar@'a quando o
primeiro argumento avaliar para alguma coisa menor que ou igual a @code{find_root_abs} ou se
sucessivos aproximandos para a ra@'{@dotless{i}}z diferirem por n@~ao mais que @code{find_root_rel * <um dos aproximandos>}.
Os valores padr@~ao de @code{find_root_abs} e
@code{find_root_rel} s@~ao 0.0 de forma que @code{find_root} tome como boa uma resposta que for poss@'{@dotless{i}}vel
com a precis@~ao aritm@'etica simples que tivermos.

@end defvr

@defvr {Vari@'avel de op@value{cedilha}@~ao} find_root_error
Valor por omiss@~ao: @code{true}

@code{find_root_error} governa o comportamento de @code{find_root}.
Quando @code{find_root} for chamada, ela determina se a fun@value{cedilha}@~ao
a ser resolvida satisfaz ou n@~ao a condi@value{cedilha}@~ao que os valores da
fun@value{cedilha}@~ao nos pontos finais do intervalo de interpola@value{cedilha}@~ao s@~ao opostos
em sinal.  Se eles forem de sinais opostos, a interpola@value{cedilha}@~ao prossegue.
Se eles forem de mesmo sinal, e @code{find_root_error} for @code{true}, ent@~ao um erro @'e
sinalizado.  Se eles forem de mesmo sinal e @code{find_root_error} n@~ao for @code{true}, o
valor de @code{find_root_error} @'e retornado.  Dessa forma para montagem de gr@'afico, @code{find_root_error}
pode ser escolhida para 0.0.

@end defvr

@defvr {Vari@'avel de op@value{cedilha}@~ao} find_root_rel
Valor por omiss@~ao: 0.0

@code{find_root_rel} @'e a precis@~ao do comando @code{find_root} e @'e
governada por @code{find_root_abs} e @code{find_root_rel} que devem ser
n@'umeros n@~ao negativos em ponto flutuante.  @code{find_root} terminar@'a quando o
primeiro argumento avaliar para alguma coisa menor que ou igual a @code{find_root_abs} ou se
sucessivos aproximandos para a ra@'{@dotless{i}}z diferirem de n@~ao mais que @code{find_root_rel * <um dos aproximandos>}.
Os valores padr@~ao de @code{find_root_labs} e
@code{find_root_rel} @'e 0.0 de forma que @code{find_root} toma como boa uma resposta que for poss@'{@dotless{i}}vel
com a precis@~ao aritm@'etica simples que tivermos.

@end defvr

@deffn {Fun@value{cedilha}@~ao} newton (@var{expr}, @var{x}, @var{x_0}, @var{eps})
Retorna uma solu@value{cedilha}@~ao aproximada de @code{@var{expr} = 0} atrav@'es do m@'etodo de Newton,
considerando @var{expr} como sendo uma fun@value{cedilha}@~ao de uma vari@'avel, @var{x}.
A busca pela solu@value{cedilha}@~ao come@value{cedilha}a com @code{@var{x} = @var{x_0}}
e prossegue at@'e @code{abs(@var{expr}) < @var{eps}}
(com @var{expr} avaliada para o valor corrente de @var{x}).

@code{newton} permite que vari@'aveis indefinidas apare@value{cedilha}am em @var{expr},
contanto que o teste de termina@value{cedilha}@~ao @code{abs(@var{expr}) < @var{eps}} avalie
para @code{true} ou @code{false}.
Dessa forma n@~ao @'e necess@'ario que @var{expr} avalie para um n@'umero.

@code{load(newton1)} chama essa fun@value{cedilha}@~ao.

Veja tamb@'em @code{realroots}, @code{allroots}, @code{find_root}, e @code{mnewton}.

Exemplos:

@c ===beg===
@c load (newton1);
@c newton (cos (u), u, 1, 1/100);
@c ev (cos (u), u = %);
@c assume (a > 0);
@c newton (x^2 - a^2, x, a/2, a^2/100);
@c ev (x^2 - a^2, x = %);
@c ===end===
@example
(%i1) load (newton1);
(%o1) /usr/share/maxima/5.10.0cvs/share/numeric/newton1.mac
(%i2) newton (cos (u), u, 1, 1/100);
(%o2)                   1.570675277161251
(%i3) ev (cos (u), u = %);
(%o3)                 1.2104963335033528E-4
(%i4) assume (a > 0);
(%o4)                        [a > 0]
(%i5) newton (x^2 - a^2, x, a/2, a^2/100);
(%o5)                  1.00030487804878 a
(%i6) ev (x^2 - a^2, x = %);
                                           2
(%o6)                6.098490481853958E-4 a
@end example

@end deffn

@node Defini@value{cedilha}@~oes para S@'eries de Fourier, , Defini@value{cedilha}@~oes para Num@'erico, Num@'erico
@section Defini@value{cedilha}@~oes para S@'eries de Fourier

@c REPHRASE
@deffn {Fun@value{cedilha}@~ao} equalp (@var{x}, @var{y})
Retorna @code{true} se @code{equal (@var{x}, @var{y})} de outra forma @code{false} (n@~ao fornece uma
mensagem de erro como @code{equal (x, y)} poderia fazer nesse caso).

@c NEEDS EXAMPLES
@end deffn

@deffn {Fun@value{cedilha}@~ao} remfun (@var{f}, @var{expr})
@deffnx {Fun@value{cedilha}@~ao} remfun (@var{f}, @var{expr}, @var{x})
@code{remfun (@var{f}, @var{expr})}
substitue todas as ocorr@^encias de @code{@var{f} (@var{arg})} por @var{arg} em @var{expr}.

@code{remfun (@var{f}, @var{expr}, @var{x})}
substitue todas as ocorr@^encias de @code{@var{f} (@var{arg})} por @var{arg} em @var{expr}
somente se @var{arg} contiver a vari@'avel @var{x}.

@c NEEDS EXAMPLES
@end deffn

@deffn {Fun@value{cedilha}@~ao} funp (@var{f}, @var{expr})
@deffnx {Fun@value{cedilha}@~ao} funp (@var{f}, @var{expr}, @var{x})
@code{funp (@var{f}, @var{expr})}
retorna @code{true} se @var{expr} cont@'em a fun@value{cedilha}@~ao @var{f}.

@code{funp (@var{f}, @var{expr}, @var{x})}
retorna @code{true} se @var{expr} cont@'em a fun@value{cedilha}@~ao @var{f} e a vari@'avel
@var{x} em algum lugar no argumento de uma das inst@^ancias de @var{f}.

@c NEEDS EXAMPLES
@end deffn

@deffn {Fun@value{cedilha}@~ao} absint (@var{f}, @var{x}, @var{halfplane})
@deffnx {Fun@value{cedilha}@~ao} absint (@var{f}, @var{x})
@deffnx {Fun@value{cedilha}@~ao} absint (@var{f}, @var{x}, @var{a}, @var{b})
@code{absint (@var{f}, @var{x}, @var{halfplane})}
retorna a integral indefinida de @var{f} com rela@value{cedilha}@~ao a
@var{x} no dado semi-plano (@code{pos}, @code{neg}, ou @code{both}).
@var{f} pode conter express@~oes da forma
@code{abs (x)}, @code{abs (sin (x))}, @code{abs (a) * exp (-abs (b) * abs (x))}.

@code{absint (@var{f}, @var{x})} @'e equivalente a @code{absint (@var{f}, @var{x}, pos)}.

@code{absint (@var{f}, @var{x}, @var{a}, @var{b})}
retorna a integral definida de @var{f} com rela@value{cedilha}@~ao a @var{x} de @var{a} at@'e @var{b}.
@c SAME LIST AS ABOVE ??
@var{f} pode incluir valores absolutos.

@c NEEDS EXAMPLES
@end deffn

@c NEEDS EXPANSION
@deffn {Fun@value{cedilha}@~ao} fourier (@var{f}, @var{x}, @var{p})
Retorna uma lista de coeficientes de Fourier de @code{@var{f}(@var{x})} definidos
sobre o intervalo @code{[-p, p]}.

@c NEEDS EXAMPLES
@end deffn

@c NEES EXPANSION. WHAT IS THE ARGUMENT l ??
@deffn {Fun@value{cedilha}@~ao} foursimp (@var{l})
Simplifica @code{sin (n %pi)} para 0 se @code{sinnpiflag} for @code{true} e
@code{cos (n %pi)} para @code{(-1)^n} se @code{cosnpiflag} for @code{true}.

@c NEEDS EXAMPLES
@end deffn

@defvr {Vari@'avel de op@value{cedilha}@~ao} sinnpiflag
Valor por omiss@~ao: @code{true}

Veja @code{foursimp}.

@end defvr

@defvr {Vari@'avel de op@value{cedilha}@~ao} cosnpiflag
Valor por omiss@~ao: @code{true}

Veja @code{foursimp}.

@end defvr

@c NEEDS EXPANSION. EXPLAIN x AND p HERE (DO NOT REFER SOMEWHERE ELSE)
@deffn {Fun@value{cedilha}@~ao} fourexpand (@var{l}, @var{x}, @var{p}, @var{limit})
Constr@'oi e retorna a s@'erie de Fourier partindo da lista de
coeficientes de Fourier @var{l} at@'e (up through) @var{limit} termos (@var{limit}
pode ser @code{inf}). @var{x} e @var{p} possuem o mesmo significado que em
@code{fourier}.

@c NEEDS EXAMPLES
@end deffn

@c NEEDS EXPANSION. WHAT IS THE ARGUMENT p ??
@deffn {Fun@value{cedilha}@~ao} fourcos (@var{f}, @var{x}, @var{p})
Retorna os coeficientes do co-seno de Fourier para @code{@var{f}(@var{x})} definida sobre @code{[0, %pi]}.

@c NEEDS EXAMPLES
@end deffn

@c NEEDS EXPANSION
@deffn {Fun@value{cedilha}@~ao} foursin (@var{f}, @var{x}, @var{p})
Retorna os coeficientes do seno de Fourier para @code{@var{f}(@var{x})} definida sobre @code{[0, @var{p}]}.

@c NEEDS EXAMPLES
@end deffn

@c NEEDS EXPANSION
@deffn {Fun@value{cedilha}@~ao} totalfourier (@var{f}, @var{x}, @var{p})
Retorna @code{fourexpand (foursimp (fourier (@var{f}, @var{x}, @var{p})), @var{x}, @var{p}, 'inf)}.

@c NEEDS EXAMPLES
@end deffn

@c NEEDS EXPANSION
@deffn {Fun@value{cedilha}@~ao} fourint (@var{f}, @var{x})
Constr@'oi e retorna uma lista de coeficientes de integral de Fourier de @code{@var{f}(@var{x})}
definida sobre @code{[minf, inf]}.

@c NEEDS EXAMPLES
@end deffn

@c NEEDS EXPANSION
@deffn {Fun@value{cedilha}@~ao} fourintcos (@var{f}, @var{x})
Retorna os coeficientes da integral do co-seno de Fourier para @code{@var{f}(@var{x})} on @code{[0, inf]}.

@c NEEDS EXAMPLES
@end deffn

@c NEEDS EXPANSION
@deffn {Fun@value{cedilha}@~ao} fourintsin (@var{f}, @var{x})
Retorna os coeficientes da integral do seno de Fourier para @code{@var{f}(@var{x})} on @code{[0, inf]}.

@c NEEDS EXAMPLES
@end deffn
