@c /stirling.texi/1.1/Mon Feb 27 22:09:17 2006//
@menu
* Defini@value{cedilha}@~oes para stirling::
@end menu

@node Defini@value{cedilha}@~oes para stirling,  , stirling, stirling
@section Defini@value{cedilha}@~oes para stirling

@deffn {Fun@value{cedilha}@~ao} stirling (@var{z},@var{n})
Substitui @code{gamma(x)} pela f@'ormula de Stirling @math{O(1/x^(2n-1))}. Quando @var{n} for
um inteiro estritamente negativo, sinaliza um erro.

Refer@^encia: Abramowitz & Stegun, " Handbook of mathematical functions", 6.1.40.

Exemplos:
@example
(%i1) load (stirling)$

(%i2) stirling(gamma(%alpha+x)/gamma(x),1);
       1/2 - x             x + %alpha - 1/2
(%o2) x        (x + %alpha)
                                   1           1
                            --------------- - ---- - %alpha
                            12 (x + %alpha)   12 x
                          %e
(%i3) taylor(%,x,inf,1);
                    %alpha       2    %alpha
          %alpha   x       %alpha  - x       %alpha
(%o3)/T/ x       + -------------------------------- + . . .
                                 2 x
(%i4) map('factor,%);
                                       %alpha - 1
         %alpha   (%alpha - 1) %alpha x
(%o4)   x       + -------------------------------
                                  2
@end example

A fun@value{cedilha}@~ao @code{stirling} conhece a diferen@value{cedilha}a entre a vari@'avel @var{gamma} e
a fun@value{cedilha}@~ao @code{gamma}:

@example
(%i5) stirling(gamma + gamma(x),0);
                                    x - 1/2   - x
(%o5)    gamma + sqrt(2) sqrt(%pi) x        %e
(%i6) stirling(gamma(y) + gamma(x),0);
                         y - 1/2   - y
(%o6) sqrt(2) sqrt(%pi) y        %e
                                              x - 1/2   - x
                         + sqrt(2) sqrt(%pi) x        %e
@end example

Para usar essa fun@value{cedilha}@~ao escreva primeiro @code{load("stirling")}.
@end deffn
