@c /zeilberger.texi/1.5/Thu Dec 28 05:44:18 2006//
@menu
* Introdu@value{cedilha}@~ao a zeilberger::
* Defini@value{cedilha}@~oes para zeilberger::
@end menu

@node Introdu@value{cedilha}@~ao a zeilberger, Defini@value{cedilha}@~oes para zeilberger, zeilberger, zeilberger
@section Introdu@value{cedilha}@~ao a zeilberger

@code{zeilberger} @'e uma implementa@value{cedilha}@~ao do algoritmo de Zeilberger
para somat@'orio hipergeom@'etricos definidos, e tamb@'em 
para o algoritmo de Gosper para somat@'orios hipergeom@'etricos
indefinidos.

@code{zeilberger} faz uso do m@'etodo de optimiza@value{cedilha}@~ao "filtering" desenvolvido por Axel Riese.

@code{zeilberger} foi desenvolvido por Fabrizio Caruso.

@code{load (zeilberger)} torna esse pacote dispon@'{@dotless{i}}vel para uso.

@subsubsection O problema dos somat@'orios hipergeom@'etricos indefinidos

@code{zeilberger} implementa o algoritmo de Gosper
para somat@'orio hipergeom@'etrico indefinido.
Dado um termo hipergeom@'etrico @math{F_k} em @math{k} queremos encontrar sua anti-diferen@value{cedilha}a
hipergeom@'etrica, isto @'e, um termo hipergeom@'etrico @math{f_k} tal que @math{F_k = f_(k+1) - f_k}.

@subsubsection O problema dos somat@'orios hipergeom@'etricos definidos

@code{zeilberger} implementa o algoritmo de Zeilberger
para somat@'orio hipergeom@'etrico definido.
Dado um termo hipergeom@'etrico apropriado (em @math{n} e @math{k}) @math{F_(n,k)} e um
inteiro positivo @math{d} queremos encontrar um @math{d}-@'esima ordem de recorr@^encia
linear com coeficientes polinomiais (em @math{n}) para @math{F_(n,k)}
e uma fun@value{cedilha}@~ao racional @math{R} em @math{n} e @math{k} tal que

@math{a_0 F_(n,k) + ... + a_d F_(n+d),k = Delta_K(R(n,k) F_(n,k))}

onde @math{Delta_k} @'e o @math{k}-seguinte operador de diferen@value{cedilha}a, i.e.,
@math{Delta_k(t_k) := t_(k+1) - t_k}.

@subsection N@'{@dotless{i}}veis de detalhe nas informa@value{cedilha}@~oes

Existe tamb@'em vers@~oes de n@'{@dotless{i}}veis de detalhe fornecidos pelos comandos
que s@~ao chamados (os n@'{@dotless{i}}veis) atrav@'es da adi@value{cedilha}@~ao de um dos seguintes prefixos:

@table @code
@item Summary
Apenas um sum@'ario @'e mostrado no final
@item Verbose
Algumas informa@value{cedilha}@~oes nos passos interm@'edios
@item VeryVerbose
Muita informa@value{cedilha}@~ao
@item Extra
Muito mais informa@value{cedilha}@~ao incluindo informa@value{cedilha}@~ao sobre
o sistema linear no algoritmo de Zeilberger
@end table

Por exemplo:
@code{GosperVerbose}, @code{parGosperVeryVerbose},
@code{ZeilbergerExtra}, @code{AntiDifferenceSummary}.


@node Defini@value{cedilha}@~oes para zeilberger, , Introdu@value{cedilha}@~ao a zeilberger, zeilberger
@section Defini@value{cedilha}@~oes para zeilberger

@deffn {Fun@value{cedilha}@~ao} AntiDifference (@var{F_k}, @var{k})

Retorna a anti-diferen@value{cedilha}a hipergeom@'etrica
de @var{F_k}, se essa anti-diferen@value{cedilha}a.
De outra forma @code{AntiDifference} retorna @code{no_hyp_antidifference}.
@end deffn

@deffn {Fun@value{cedilha}@~ao} Gosper (@var{F_k}, @var{k})
Retorna o certificado racional @var{R(k)} para @var{F_k}, isto @'e,
uma fun@value{cedilha}@~ao racional tal que

@math{F_k = R(k+1) F_(k+1) - R(k) F_k}
 
se essa fun@value{cedilha}@~ao racional exitir.
De outra forma, @code{Gosper} retorna @code{no_hyp_sol}.
@end deffn

@deffn {Fun@value{cedilha}@~ao} GosperSum (@var{F_k}, @var{k}, @var{a}, @var{b}) 

Retorna o somat@'orio de @var{F_k} de @math{@var{k} = @var{a}} a @math{@var{k} = @var{b}}
se @var{F_k} tiver ma diferen@value{cedilha}a hipergeom@'etrica.
De outra forma, @code{GosperSum} retorna @code{nongosper_summable}.

Exemplos:

@c ===beg===
@c load (zeilberger);
@c GosperSum ((-1)^k*k / (4*k^2 - 1), k, 1, n);
@c GosperSum (1 / (4*k^2 - 1), k, 1, n);
@c GosperSum (x^k, k, 1, n);
@c GosperSum ((-1)^k*a! / (k!*(a - k)!), k, 1, n);
@c GosperSum (k*k!, k, 1, n);
@c GosperSum ((k + 1)*k! / (k + 1)!, k, 1, n);
@c GosperSum (1 / ((a - k)!*k!), k, 1, n);
@c ===end===
@example
(%i1) load (zeilberger);
(%o1)  /usr/share/maxima/share/contrib/Zeilberger/zeilberger.mac
(%i2) GosperSum ((-1)^k*k / (4*k^2 - 1), k, 1, n);

Dependent equations eliminated:  (1)
                           3       n + 1
                      (n + -) (- 1)
                           2               1
(%o2)               - ------------------ - -
                                  2        4
                      2 (4 (n + 1)  - 1)
(%i3) GosperSum (1 / (4*k^2 - 1), k, 1, n);
                                3
                          - n - -
                                2       1
(%o3)                  -------------- + -
                                2       2
                       4 (n + 1)  - 1
(%i4) GosperSum (x^k, k, 1, n);
                          n + 1
                         x          x
(%o4)                    ------ - -----
                         x - 1    x - 1
(%i5) GosperSum ((-1)^k*a! / (k!*(a - k)!), k, 1, n);
                                n + 1
                a! (n + 1) (- 1)              a!
(%o5)       - ------------------------- - ----------
              a (- n + a - 1)! (n + 1)!   a (a - 1)!
(%i6) GosperSum (k*k!, k, 1, n);

Dependent equations eliminated:  (1)
(%o6)                     (n + 1)! - 1
(%i7) GosperSum ((k + 1)*k! / (k + 1)!, k, 1, n);
                  (n + 1) (n + 2) (n + 1)!
(%o7)             ------------------------ - 1
                          (n + 2)!
(%i8) GosperSum (1 / ((a - k)!*k!), k, 1, n);
(%o8)                  nonGosper_summable
@end example
@end deffn

@deffn {Fun@value{cedilha}@~ao} parGosper (@var{F_@{n,k@}}, @var{k}, @var{n}, @var{d})
Tenta encontrar uma recorr@^encia de @var{d}-@'esima ordem para @var{F_@{n,k@}}.

O algoritmo retorna uma sequ@^encia
@math{[s_1, s_2, ..., s_m]} de solu@value{cedilha}@~oes.
Cada solu@value{cedilha}@~ao tem a forma

@math{[R(n, k), [a_0, a_1, ..., a_d]]}

@code{parGosper} retorna @code{[]} caso n@~ao consiga encontrar uma recorr@^encia.
@end deffn

@deffn {Fun@value{cedilha}@~ao} Zeilberger (@var{F_@{n,k@}}, @var{k}, @var{n})
Tenta calcular o somat@'orio hipergeom@'etrico indefinido de @var{F_@{n,k@}}.

@code{Zeilberger} primeiro invoca @code{Gosper}, e se @code{Gosper} n@~ao conseguir encontrar uma solu@value{cedilha}@~ao, ent@~ao @code{Zeilberger} invoca
@code{parGosper}com ordem 1, 2, 3, ..., acima de @code{MAX_ORD}.
Se Zeilberger encontrar uma solu@value{cedilha}@~ao antes de esticar @code{MAX_ORD},
Zeilberger para e retorna a solu@value{cedilha}@~ao.

O algoritmo retorna uma sequ@^encia
@math{[s_1, s_2, ..., s_m]} de solu@value{cedilha}@~oes.
Cada solu@value{cedilha}@~ao tem a forma

@math{[R(n,k), [a_0, a_1, ..., a_d]]}

@code{Zeilberger} retorna @code{[]} se n@~ao conseguir encontrar uma solu@value{cedilha}@~ao.

@code{Zeilberger} invoca @code{Gosper} somente se @code{gosper_in_zeilberger} for @code{true}.
@end deffn

@section Vari@'aveis globais gerais

@defvr {Vari@'avel global} MAX_ORD
Valor por omiss@~ao: 5

@code{MAX_ORD} @'e a ordem m@'axima de recorr@^encia tentada por @code{Zeilberger}.
@end defvr

@defvr {Vari@'avel global} simplified_output
Valor por omiss@~ao: @code{false}

Quando @code{simplified_output} for @code{true},
fun@value{cedilha}@~oes no pacote @code{zeilberger} tentam
simplifica@value{cedilha}@~ao adicional da solu@value{cedilha}@~ao.
@end defvr

@defvr {Vari@'avel global} linear_solver
Valor por omiss@~ao: @code{linsolve}

@code{linear_solver} nomeia o resolvedor que @'e usado para resolver o sistema
de equa@value{cedilha}@~oes no algoritmo de Zeilberger.
@end defvr

@defvr {Vari@'avel global} warnings
Valor por omiss@~ao: @code{true}

Quando @code{warnings} for @code{true},
fun@value{cedilha}@~oes no pacote @code{zeilberger} imprimem
mensagens de alerta durante a execu@value{cedilha}@~ao.
@end defvr

@defvr {Vari@'avel global} gosper_in_zeilberger
Valor por omiss@~ao: @code{true}

Quando @code{gosper_in_zeilberger} for @code{true},
a fun@value{cedilha}@~ao @code{Zeilberger} chama @code{Gosper} antes de chamar @code{parGosper}.
De outra forma, @code{Zeilberger} vai imediatamente para @code{parGosper}.
@end defvr

@defvr {Vari@'avel global} trivial_solutions
Valor por omiss@~ao: @code{true}

Quando @code{trivial_solutions} for @code{true},
@code{Zeilberger} retorna solu@value{cedilha}@~oes
que possuem certificado igual a zero, ou todos os coeficientes iguais a zero.
@end defvr

@section Vari@'aveis relacionadas ao teste modular

@defvr {Vari@'avel global} mod_test
Valor por omiss@~ao: @code{false}

Quando @code{mod_test} for @code{true},
@code{parGosper} executa um
teste modular discartando sistemas sem solu@value{cedilha}@~ao.
@end defvr

@defvr {Vari@'avel global} modular_linear_solver
Valor por omiss@~ao: @code{linsolve}

@code{modular_linear_solver} nomeia o resolvedor linear usado pelo  teste modular em @code{parGosper}.
@end defvr

@defvr {Vari@'avel global} ev_point
Valor por omiss@~ao: @code{big_primes[10]}

@code{ev_point} @'e o valor no qual a vari@'avel @var{n} @'e avaliada
no momento da execu@value{cedilha}@~ao do teste modular em @code{parGosper}.
@end defvr

@defvr {Vari@'avel global} mod_big_prime
Valor por omiss@~ao: @code{big_primes[1]}

@code{mod_big_prime} @'e o m@'odulo usado pelo teste modular em @code{parGosper}.
@end defvr

@defvr {Vari@'avel global} mod_threshold
Valor por omiss@~ao: 4

@code{mod_threshold} is the
maior ordem para a qual o teste modular em @code{parGosper} @'e tentado.
@end defvr

