static const char client_html[] =
  "<!DOCTYPE html>\n"
  "<html>\n"
  "<head>\n"
  "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf8\" />\n"
  "<title>broadway 2.0</title>\n"
  "<script type=\"text/javascript\" src=\"broadway.js\"></script>\n"
  "<style type=\"text/css\">\n"
  "\n"
  ".frame-window {\n"
  "    background-color: rgb(248, 248, 248);\n"
  "    background-image: -moz-linear-gradient(rgb(255, 255, 255) 1px, rgb(247, 247, 247) 1px, rgb(237, 236, 235) 32px);\n"
  "/*    background-image: -webkit-gradient(linear, left top, left 50, from(rgba(250, 253, 255, 0.9)), to(rgba(250, 253, 255, 0)), color-stop(88%, rgba(250, 253, 255, 0.75))); */\n"
  "    border-radius: 5px 5px 0 0;\n"
  "    -moz-border-radius: 5px 5px 0 0;\n"
  "    border: 1px solid rgb(142, 142, 142);\n"
  "    padding: 0 0 3px;\n"
  "}\n"
  "\n"
  ".frame-contents {\n"
  "    clear: both;\n"
  "    position: relative;\n"
  "}\n"
  "\n"
  ".frame-close {\n"
  "    margin: 0 0 4px;\n"
  "    background-color: #BFC1C1;\n"
  "    background-image: -moz-linear-gradient(#D1D2D2 0%, #BABBBC 65%, #D4D4D5 100%);\n"
  "/*    background-image: -webkit-gradient(linear, left top, left bottom, from(rgba(255, 255, 255, 0.35)), to(rgba(255, 255, 255, 0.5)), color-stop(50%, rgba(255, 255, 255, 0.5)), color-stop(50%, rgba(255, 255, 255, 0))); */\n"
  "    border-radius: 0 4px 0 5px;\n"
  "/*    border-top-left-radius: 0;\n"
  "    border-top-right-radius: 4px;\n"
  "    -moz-border-radius: 2px;\n"
  "    -moz-border-top-left-radius: 0;\n"
  "    -moz-border-top-right-radius: 0; */\n"
  "    border-top: none;\n"
  "    border-right: none;\n"
  "    border-bottom: 1px solid #BEBEBE;\n"
  "    border-left: 1px solid #8E8E8E;\n"
  "    float: right;\n"
  "    color: white;\n"
  "    line-height: 30px;\n"
  "    width: 30px;\n"
  "    text-shadow: 0 1px 0 #8E8E8E;\n"
  "    font-weight: bold;\n"
  "    font-family: sans-serif;\n"
  "    font-size: 190%;\n"
  "    cursor: pointer;\n"
  "    -webkit-user-select: none;\n"
  "    -khtml-user-select: none;\n"
  "    -moz-user-select: none;\n"
  "    -o-user-select: none;\n"
  "    user-select: none;\n"
  "}\n"
  "\n"
  ".frame-close.frame-hover {\n"
  "    background-image: -moz-linear-gradient(#E8E8E8 0%, #C7C8C9 65%, #D6D6D6 100%);\n"
  "}\n"
  "\n"
  ".frame-close.frame-active {\n"
  "    background-image: -moz-linear-gradient(#8E8E8E 1px, #BEBEBE 100%);\n"
  "    text-shadow: none;\n"
  "    /* this is a gross hack, remove if it break things */\n"
  "    margin: -1px 0 4px;\n"
  "    padding-top: 1px;\n"
  "}\n"
  "\n"
  "</style>\n"
  "</head>\n"
  "\n"
  "<body onload=\"connect()\">\n"
  "</body>\n"
  "</html>\n";
