set -o pipefail
'llvm-as' < '/private/var/chris/llvm-2.8/test/Feature/forwardreftest.ll' |
  'llvm-dis' > '/private/var/chris/llvm-2.8/test/Feature/Output/forwardreftest.ll.tmp1.ll'  &&

'llvm-as' '/private/var/chris/llvm-2.8/test/Feature/Output/forwardreftest.ll.tmp1.ll' '-o' '-' |
  'llvm-dis' > '/private/var/chris/llvm-2.8/test/Feature/Output/forwardreftest.ll.tmp2.ll'  &&

'diff' '/private/var/chris/llvm-2.8/test/Feature/Output/forwardreftest.ll.tmp1.ll' '/private/var/chris/llvm-2.8/test/Feature/Output/forwardreftest.ll.tmp2.ll'