set -o pipefail
'llvm-as' < '/private/var/chris/llvm-2.8/test/Feature/packed_struct.ll' |
  'llvm-dis' > '/private/var/chris/llvm-2.8/test/Feature/Output/packed_struct.ll.tmp1.ll'  &&

'llvm-as' '/private/var/chris/llvm-2.8/test/Feature/Output/packed_struct.ll.tmp1.ll' '-o' '-' |
  'llvm-dis' > '/private/var/chris/llvm-2.8/test/Feature/Output/packed_struct.ll.tmp2.ll'  &&

'diff' '/private/var/chris/llvm-2.8/test/Feature/Output/packed_struct.ll.tmp1.ll' '/private/var/chris/llvm-2.8/test/Feature/Output/packed_struct.ll.tmp2.ll'  &&

'not' 'grep' 'cast' '/private/var/chris/llvm-2.8/test/Feature/Output/packed_struct.ll.tmp2.ll'  &&

'grep' '}>' '/private/var/chris/llvm-2.8/test/Feature/Output/packed_struct.ll.tmp2.ll'