set -o pipefail
'llvm-as' < '/private/var/chris/llvm-2.8/test/Feature/ppcld.ll' |
  'llvm-dis' > '/private/var/chris/llvm-2.8/test/Feature/Output/ppcld.ll.tmp'  &&

'llvm-as' < '/private/var/chris/llvm-2.8/test/Feature/Output/ppcld.ll.tmp' |
  'llvm-dis' > '/private/var/chris/llvm-2.8/test/Feature/Output/ppcld.ll.tmp2'  &&

'diff' '/private/var/chris/llvm-2.8/test/Feature/Output/ppcld.ll.tmp' '/private/var/chris/llvm-2.8/test/Feature/Output/ppcld.ll.tmp2'