set -o pipefail
'opt' '-std-compile-opts' '-S' < '/private/var/chris/llvm-2.8/test/Feature/weak_constant.ll' > '/private/var/chris/llvm-2.8/test/Feature/Output/weak_constant.ll.tmp'  &&

'grep' 'undef' '/private/var/chris/llvm-2.8/test/Feature/Output/weak_constant.ll.tmp' |
  'count' '1'  &&

'grep' '5' '/private/var/chris/llvm-2.8/test/Feature/Output/weak_constant.ll.tmp' |
  'count' '1'  &&

'grep' '7' '/private/var/chris/llvm-2.8/test/Feature/Output/weak_constant.ll.tmp' |
  'count' '1'  &&

'grep' '9' '/private/var/chris/llvm-2.8/test/Feature/Output/weak_constant.ll.tmp' |
  'count' '1'