#define FUNCNAME_nulcmd 0
#define FUNCNAME_quitfm 1
#define FUNCNAME_accessKey 2
#define FUNCNAME_adBmark 3
#define FUNCNAME_setAlarm 4
#define FUNCNAME_backBf 5
#define FUNCNAME_goLineF 6
#define FUNCNAME_ldBmark 7
#define FUNCNAME_ctrCsrH 8
#define FUNCNAME_ctrCsrV 9
#define FUNCNAME_docCSet 10
#define FUNCNAME_closeT 11
#define FUNCNAME_closeTMs 12
#define FUNCNAME_execCmd 13
#define FUNCNAME_cooLst 14
#define FUNCNAME_defCSet 15
#define FUNCNAME_defKey 16
#define FUNCNAME_deletePrevBuf 17
#define FUNCNAME_dictword 18
#define FUNCNAME_dictwordat 19
#define FUNCNAME_dispI 20
#define FUNCNAME_ldown1 21
#define FUNCNAME_svSrc 22
#define FUNCNAME_ldDL 23
#define FUNCNAME_editBf 24
#define FUNCNAME_editScr 25
#define FUNCNAME_goLineL 26
#define FUNCNAME_escbmap 27
#define FUNCNAME_escmap 28
#define FUNCNAME_execsh 29
#define FUNCNAME_extbrz 31
#define FUNCNAME_linkbrz 32
#define FUNCNAME_rFrame 33
#define FUNCNAME_goURL 34
#define FUNCNAME_goLine 35
#define FUNCNAME_followA 36
#define FUNCNAME_gorURL 37
#define FUNCNAME_ldhelp 38
#define FUNCNAME_ldHist 39
#define FUNCNAME_pginfo 40
#define FUNCNAME_susp 41
#define FUNCNAME_isrchfor 42
#define FUNCNAME_isrchbak 43
#define FUNCNAME_col1L 44
#define FUNCNAME_linbeg 45
#define FUNCNAME_linend 46
#define FUNCNAME_curlno 47
#define FUNCNAME_topA 48
#define FUNCNAME_lastA 49
#define FUNCNAME_linkMn 50
#define FUNCNAME_linkLst 51
#define FUNCNAME_listMn 52
#define FUNCNAME_ldfile 53
#define FUNCNAME_mainMn 54
#define FUNCNAME__mark 55
#define FUNCNAME_chkNMID 56
#define FUNCNAME_chkURL 57
#define FUNCNAME_chkWORD 58
#define FUNCNAME_menuMs 60
#define FUNCNAME_mouse 61
#define FUNCNAME_msToggle 62
#define FUNCNAME_movD 63
#define FUNCNAME_movD1 64
#define FUNCNAME_movL 65
#define FUNCNAME_movL1 66
#define FUNCNAME_movlistMn 67
#define FUNCNAME_movMs 68
#define FUNCNAME_movR 69
#define FUNCNAME_movR1 70
#define FUNCNAME_movU 71
#define FUNCNAME_movU1 72
#define FUNCNAME_msgs 73
#define FUNCNAME_multimap 74
#define FUNCNAME_newT 75
#define FUNCNAME_nextBf 76
#define FUNCNAME_nextD 77
#define FUNCNAME_nextL 78
#define FUNCNAME_nextLU 79
#define FUNCNAME_nextA 80
#define FUNCNAME_nextMk 81
#define FUNCNAME_pgFore 82
#define FUNCNAME_nextR 83
#define FUNCNAME_nextRD 84
#define FUNCNAME_nextT 85
#define FUNCNAME_nextU 86
#define FUNCNAME_nextVA 87
#define FUNCNAME_movRW 88
#define FUNCNAME_ldOpt 91
#define FUNCNAME_pcmap 92
#define FUNCNAME_curURL 93
#define FUNCNAME_peekIMG 94
#define FUNCNAME_peekURL 95
#define FUNCNAME_pipeBuf 96
#define FUNCNAME_pipesh 97
#define FUNCNAME_prevBf 98
#define FUNCNAME_prevA 99
#define FUNCNAME_prevMk 100
#define FUNCNAME_pgBack 101
#define FUNCNAME_prevT 102
#define FUNCNAME_prevVA 103
#define FUNCNAME_movLW 104
#define FUNCNAME_svBuf 105
#define FUNCNAME_qquitfm 106
#define FUNCNAME_readsh 107
#define FUNCNAME_redoPos 108
#define FUNCNAME_rdrwSc 109
#define FUNCNAME_reMark 110
#define FUNCNAME_reinit 111
#define FUNCNAME_reload 112
#define FUNCNAME_reshape 113
#define FUNCNAME_col1R 114
#define FUNCNAME_svI 116
#define FUNCNAME_svA 117
#define FUNCNAME_srchfor 119
#define FUNCNAME_srchbak 120
#define FUNCNAME_srchnxt 122
#define FUNCNAME_srchprv 123
#define FUNCNAME_selBuf 124
#define FUNCNAME_selMn 125
#define FUNCNAME_setEnv 126
#define FUNCNAME_setOpt 127
#define FUNCNAME_shiftl 129
#define FUNCNAME_shiftr 130
#define FUNCNAME_vwSrc 131
#define FUNCNAME_stopI 132
#define FUNCNAME_submitForm 133
#define FUNCNAME_tabURL 135
#define FUNCNAME_tabrURL 136
#define FUNCNAME_tabL 137
#define FUNCNAME_tabA 138
#define FUNCNAME_tabMn 139
#define FUNCNAME_tabMs 140
#define FUNCNAME_tabR 141
#define FUNCNAME_undoPos 142
#define FUNCNAME_lup1 143
#define FUNCNAME_dispVer 144
#define FUNCNAME_followI 147
#define FUNCNAME_wrapToggle 149
