#include "hash.h"
#include <stdio.h>
#include "html.h"
static HashItem_si MyHashItem[] = {
    /* 0 */ {"option_int", HTML_OPTION_INT, &MyHashItem[1]},
    /* 1 */ {"/form_int", HTML_N_FORM_INT, &MyHashItem[2]},
    /* 2 */ {"/kbd", HTML_NOP, &MyHashItem[3]},
    /* 3 */ {"dd", HTML_DD, &MyHashItem[4]},
    /* 4 */ {"/dir", HTML_N_UL, NULL},
    /* 5 */ {"/body", HTML_N_BODY, &MyHashItem[6]},
    /* 6 */ {"noframes", HTML_NOFRAMES, NULL},
    /* 7 */ {"bdo", HTML_BDO, &MyHashItem[8]},
    /* 8 */ {"base", HTML_BASE, NULL},
    /* 9 */ {"/div", HTML_N_DIV, NULL},
    /* 10 */ {"big", HTML_BIG, &MyHashItem[11]},
    /* 11 */ {"tbody", HTML_TBODY, &MyHashItem[12]},
    /* 12 */ {"meta", HTML_META, &MyHashItem[13]},
    /* 13 */ {"i", HTML_I, NULL},
    /* 14 */ {"label", HTML_LABEL, &MyHashItem[15]},
    /* 15 */ {"/_symbol", HTML_N_SYMBOL, &MyHashItem[16]},
    /* 16 */ {"sup", HTML_SUP, &MyHashItem[17]},
    /* 17 */ {"/p", HTML_N_P, NULL},
    /* 18 */ {"/q", HTML_N_Q, NULL},
    /* 19 */ {"input_alt", HTML_INPUT_ALT, &MyHashItem[20]},
    /* 20 */ {"dl", HTML_DL, NULL},
    /* 21 */ {"/tbody", HTML_N_TBODY, &MyHashItem[22]},
    /* 22 */ {"/s", HTML_N_S, NULL},
    /* 23 */ {"/label", HTML_N_LABEL, &MyHashItem[24]},
    /* 24 */ {"del", HTML_DEL, &MyHashItem[25]},
    /* 25 */ {"xmp", HTML_XMP, &MyHashItem[26]},
    /* 26 */ {"br", HTML_BR, NULL},
    /* 27 */ {"iframe", HTML_IFRAME, &MyHashItem[28]},
    /* 28 */ {"link", HTML_LINK, &MyHashItem[29]},
    /* 29 */ {"/u", HTML_N_U, &MyHashItem[30]},
    /* 30 */ {"em", HTML_EM, NULL},
    /* 31 */ {"title_alt", HTML_TITLE_ALT, &MyHashItem[32]},
    /* 32 */ {"caption", HTML_CAPTION, &MyHashItem[33]},
    /* 33 */ {"plaintext", HTML_PLAINTEXT, &MyHashItem[34]},
    /* 34 */ {"p", HTML_P, NULL},
    /* 35 */ {"q", HTML_Q, &MyHashItem[36]},
    /* 36 */ {"blockquote", HTML_BLQ, &MyHashItem[37]},
    /* 37 */ {"menu", HTML_UL, NULL},
    /* 38 */ {"fieldset", HTML_FIELDSET, &MyHashItem[39]},
    /* 39 */ {"/colgroup", HTML_N_COLGROUP, &MyHashItem[40]},
    /* 40 */ {"dfn", HTML_NOP, NULL},
    /* 41 */ {"s", HTML_S, &MyHashItem[42]},
    /* 42 */ {"strong", HTML_STRONG, NULL},
    /* 43 */ {"dt", HTML_DT, NULL},
    /* 44 */ {"u", HTML_U, NULL},
    /* 45 */ {"/map", HTML_N_MAP, &MyHashItem[46]},
    /* 46 */ {"/frameset", HTML_N_FRAMESET, &MyHashItem[47]},
    /* 47 */ {"/ol", HTML_N_OL, NULL},
    /* 48 */ {"noscript", HTML_NOSCRIPT, &MyHashItem[49]},
    /* 49 */ {"legend", HTML_LEGEND, &MyHashItem[50]},
    /* 50 */ {"/td", HTML_N_TD, NULL},
    /* 51 */ {"li", HTML_LI, NULL},
    /* 52 */ {"html", HTML_BODY, &MyHashItem[53]},
    /* 53 */ {"hr", HTML_HR, NULL},
    /* 54 */ {"/strong", HTML_N_STRONG, NULL},
    /* 55 */ {"small", HTML_SMALL, &MyHashItem[56]},
    /* 56 */ {"/th", HTML_N_TH, &MyHashItem[57]},
    /* 57 */ {"option", HTML_OPTION, &MyHashItem[58]},
    /* 58 */ {"/span", HTML_N_SPAN, &MyHashItem[59]},
    /* 59 */ {"kbd", HTML_NOP, &MyHashItem[60]},
    /* 60 */ {"dir", HTML_UL, NULL},
    /* 61 */ {"col", HTML_COL, NULL},
    /* 62 */ {"param", HTML_PARAM, NULL},
    /* 63 */ {"/small", HTML_N_SMALL, &MyHashItem[64]},
    /* 64 */ {"/legend", HTML_N_LEGEND, &MyHashItem[65]},
    /* 65 */ {"/caption", HTML_N_CAPTION, &MyHashItem[66]},
    /* 66 */ {"div", HTML_DIV, NULL},
    /* 67 */ {"/abbr", HTML_N_ABBR, &MyHashItem[68]},
    /* 68 */ {"head", HTML_HEAD, &MyHashItem[69]},
    /* 69 */ {"ol", HTML_OL, &MyHashItem[70]},
    /* 70 */ {"/ul", HTML_N_UL, NULL},
    /* 71 */ {"/ins", HTML_N_INS, &MyHashItem[72]},
    /* 72 */ {"area", HTML_AREA, NULL},
    /* 73 */ {"pre_plain", HTML_PRE_PLAIN, &MyHashItem[74]},
    /* 74 */ {"button", HTML_BUTTON, &MyHashItem[75]},
    /* 75 */ {"td", HTML_TD, &MyHashItem[76]},
    /* 76 */ {"/option", HTML_N_OPTION, NULL},
    /* 77 */ {"/noframes", HTML_N_NOFRAMES, NULL},
    /* 78 */ {"/tr", HTML_N_TR, &MyHashItem[79]},
    /* 79 */ {"nobr", HTML_NOBR, NULL},
    /* 80 */ {"img_alt", HTML_IMG_ALT, &MyHashItem[81]},
    /* 81 */ {"table_alt", HTML_TABLE_ALT, &MyHashItem[82]},
    /* 82 */ {"th", HTML_TH, &MyHashItem[83]},
    /* 83 */ {"script", HTML_SCRIPT, &MyHashItem[84]},
    /* 84 */ {"/tt", HTML_NOP, NULL},
    /* 85 */ {"code", HTML_NOP, NULL},
    /* 86 */ {"optgroup", HTML_OPTGROUP, &MyHashItem[87]},
    /* 87 */ {"samp", HTML_NOP, NULL},
    /* 88 */ {"textarea", HTML_TEXTAREA, NULL},
    /* 89 */ {"textarea_int", HTML_TEXTAREA_INT, NULL},
    /* 90 */ {"table", HTML_TABLE, &MyHashItem[91]},
    /* 91 */ {"img", HTML_IMG, &MyHashItem[92]},
    /* 92 */ {"/blockquote", HTML_N_BLQ, NULL},
    /* 93 */ {"applet", HTML_APPLET, &MyHashItem[94]},
    /* 94 */ {"map", HTML_MAP, &MyHashItem[95]},
    /* 95 */ {"ul", HTML_UL, NULL},
    /* 96 */ {"basefont", HTML_BASEFONT, &MyHashItem[97]},
    /* 97 */ {"/script", HTML_N_SCRIPT, &MyHashItem[98]},
    /* 98 */ {"center", HTML_CENTER, NULL},
    /* 99 */ {"/table", HTML_N_TABLE, &MyHashItem[100]},
    /* 100 */ {"cite", HTML_NOP, &MyHashItem[101]},
    /* 101 */ {"/h1", HTML_N_H, NULL},
    /* 102 */ {"/fieldset", HTML_N_FIELDSET, &MyHashItem[103]},
    /* 103 */ {"tr", HTML_TR, &MyHashItem[104]},
    /* 104 */ {"/h2", HTML_N_H, NULL},
    /* 105 */ {"image", HTML_IMG, &MyHashItem[106]},
    /* 106 */ {"/h3", HTML_N_H, NULL},
    /* 107 */ {"pre_int", HTML_PRE_INT, &MyHashItem[108]},
    /* 108 */ {"/font", HTML_N_FONT, &MyHashItem[109]},
    /* 109 */ {"tt", HTML_NOP, &MyHashItem[110]},
    /* 110 */ {"/h4", HTML_N_H, NULL},
    /* 111 */ {"body", HTML_BODY, &MyHashItem[112]},
    /* 112 */ {"/form", HTML_N_FORM, &MyHashItem[113]},
    /* 113 */ {"/h5", HTML_N_H, NULL},
    /* 114 */ {"/h6", HTML_N_H, NULL},
    /* 115 */ {"frame", HTML_FRAME, NULL},
    /* 116 */ {"/textarea_int", HTML_N_TEXTAREA_INT, &MyHashItem[117]},
    /* 117 */ {"/noscript", HTML_N_NOSCRIPT, &MyHashItem[118]},
    /* 118 */ {"/img_alt", HTML_N_IMG_ALT, &MyHashItem[119]},
    /* 119 */ {"/center", HTML_N_CENTER, NULL},
    /* 120 */ {"/pre", HTML_N_PRE, NULL},
    /* 121 */ {"tfoot", HTML_TFOOT, NULL},
    /* 122 */ {"ins", HTML_INS, NULL},
    /* 123 */ {"/var", HTML_NOP, NULL},
    /* 124 */ {"h1", HTML_H, NULL},
    /* 125 */ {"/tfoot", HTML_N_TFOOT, &MyHashItem[126]},
    /* 126 */ {"input", HTML_INPUT, &MyHashItem[127]},
    /* 127 */ {"h2", HTML_H, NULL},
    /* 128 */ {"h3", HTML_H, NULL},
    /* 129 */ {"h4", HTML_H, NULL},
    /* 130 */ {"h5", HTML_H, NULL},
    /* 131 */ {"internal", HTML_INTERNAL, &MyHashItem[132]},
    /* 132 */ {"h6", HTML_H, NULL},
    /* 133 */ {"div_int", HTML_DIV_INT, &MyHashItem[134]},
    /* 134 */ {"select_int", HTML_SELECT_INT, &MyHashItem[135]},
    /* 135 */ {"/pre_int", HTML_N_PRE_INT, NULL},
    /* 136 */ {"/menu", HTML_N_UL, NULL},
    /* 137 */ {"form_int", HTML_FORM_INT, &MyHashItem[138]},
    /* 138 */ {"/sub", HTML_N_SUB, NULL},
    /* 139 */ {"style", HTML_STYLE, &MyHashItem[140]},
    /* 140 */ {"address", HTML_BR, NULL},
    /* 141 */ {"/optgroup", HTML_N_OPTGROUP, NULL},
    /* 142 */ {"/textarea", HTML_N_TEXTAREA, NULL},
    /* 143 */ {"/input_alt", HTML_N_INPUT_ALT, &MyHashItem[144]},
    /* 144 */ {"span", HTML_SPAN, NULL},
    /* 145 */ {"doctype", HTML_DOCTYPE, &MyHashItem[146]},
    /* 146 */ {"/style", HTML_N_STYLE, NULL},
    /* 147 */ {"/html", HTML_N_BODY, NULL},
    /* 148 */ {"pre", HTML_PRE, &MyHashItem[149]},
    /* 149 */ {"title", HTML_TITLE, NULL},
    /* 150 */ {"abbr", HTML_ABBR, &MyHashItem[151]},
    /* 151 */ {"select", HTML_SELECT, NULL},
    /* 152 */ {"/bdo", HTML_N_BDO, &MyHashItem[153]},
    /* 153 */ {"acronym", HTML_ACRONYM, NULL},
    /* 154 */ {"/div_int", HTML_N_DIV_INT, &MyHashItem[155]},
    /* 155 */ {"var", HTML_NOP, NULL},
    /* 156 */ {"/big", HTML_N_BIG, &MyHashItem[157]},
    /* 157 */ {"/title", HTML_N_TITLE, NULL},
    /* 158 */ {"embed", HTML_EMBED, &MyHashItem[159]},
    /* 159 */ {"/sup", HTML_N_SUP, &MyHashItem[160]},
    /* 160 */ {"colgroup", HTML_COLGROUP, &MyHashItem[161]},
    /* 161 */ {"/head", HTML_N_HEAD, &MyHashItem[162]},
    /* 162 */ {"isindex", HTML_ISINDEX, NULL},
    /* 163 */ {"strike", HTML_S, &MyHashItem[164]},
    /* 164 */ {"listing", HTML_LISTING, NULL},
    /* 165 */ {"bgsound", HTML_BGSOUND, NULL},
    /* 166 */ {"/address", HTML_BR, NULL},
    /* 167 */ {"object", HTML_OBJECT, &MyHashItem[168]},
    /* 168 */ {"thead", HTML_THEAD, &MyHashItem[169]},
    /* 169 */ {"wbr", HTML_WBR, &MyHashItem[170]},
    /* 170 */ {"/del", HTML_N_DEL, &MyHashItem[171]},
    /* 171 */ {"/nobr", HTML_N_NOBR, &MyHashItem[172]},
    /* 172 */ {"/select", HTML_N_SELECT, &MyHashItem[173]},
    /* 173 */ {"frameset", HTML_FRAMESET, &MyHashItem[174]},
    /* 174 */ {"/xmp", HTML_N_XMP, NULL},
    /* 175 */ {"/code", HTML_NOP, NULL},
    /* 176 */ {"_symbol", HTML_SYMBOL, &MyHashItem[177]},
    /* 177 */ {"/thead", HTML_N_THEAD, &MyHashItem[178]},
    /* 178 */ {"/samp", HTML_NOP, &MyHashItem[179]},
    /* 179 */ {"/dfn", HTML_NOP, &MyHashItem[180]},
    /* 180 */ {"_id", HTML_NOP, NULL},
    /* 181 */ {"/strike", HTML_N_S, &MyHashItem[182]},
    /* 182 */ {"/a", HTML_N_A, NULL},
    /* 183 */ {"/select_int", HTML_N_SELECT_INT, &MyHashItem[184]},
    /* 184 */ {"sub", HTML_SUB, &MyHashItem[185]},
    /* 185 */ {"/b", HTML_N_B, NULL},
    /* 186 */ {"/internal", HTML_N_INTERNAL, NULL},
    /* 187 */ {"/acronym", HTML_N_ACRONYM, NULL},
    /* 188 */ {"/pre_plain", HTML_N_PRE_PLAIN, &MyHashItem[189]},
    /* 189 */ {"font", HTML_FONT, &MyHashItem[190]},
    /* 190 */ {"/dl", HTML_N_DL, NULL},
    /* 191 */ {"form", HTML_FORM, &MyHashItem[192]},
    /* 192 */ {"/cite", HTML_NOP, &MyHashItem[193]},
    /* 193 */ {"a", HTML_A, NULL},
    /* 194 */ {"b", HTML_B, NULL},
    /* 195 */ {"/listing", HTML_N_LISTING, &MyHashItem[196]},
    /* 196 */ {"/em", HTML_N_EM, &MyHashItem[197]},
    /* 197 */ {"/i", HTML_N_I, NULL},
};

static HashItem_si *MyHashItemTbl[] = {
    &MyHashItem[0],
    &MyHashItem[5],
    NULL,
    &MyHashItem[7],
    &MyHashItem[9],
    &MyHashItem[10],
    &MyHashItem[14],
    &MyHashItem[18],
    &MyHashItem[19],
    &MyHashItem[21],
    &MyHashItem[23],
    &MyHashItem[27],
    &MyHashItem[31],
    &MyHashItem[35],
    &MyHashItem[38],
    &MyHashItem[41],
    &MyHashItem[43],
    &MyHashItem[44],
    &MyHashItem[45],
    NULL,
    &MyHashItem[48],
    &MyHashItem[51],
    &MyHashItem[52],
    &MyHashItem[54],
    &MyHashItem[55],
    NULL,
    &MyHashItem[61],
    &MyHashItem[62],
    &MyHashItem[63],
    NULL,
    &MyHashItem[67],
    &MyHashItem[71],
    &MyHashItem[73],
    &MyHashItem[77],
    &MyHashItem[78],
    NULL,
    &MyHashItem[80],
    &MyHashItem[85],
    &MyHashItem[86],
    &MyHashItem[88],
    &MyHashItem[89],
    &MyHashItem[90],
    &MyHashItem[93],
    NULL,
    &MyHashItem[96],
    &MyHashItem[99],
    &MyHashItem[102],
    &MyHashItem[105],
    &MyHashItem[107],
    &MyHashItem[111],
    &MyHashItem[114],
    &MyHashItem[115],
    &MyHashItem[116],
    &MyHashItem[120],
    &MyHashItem[121],
    &MyHashItem[122],
    &MyHashItem[123],
    &MyHashItem[124],
    &MyHashItem[125],
    &MyHashItem[128],
    &MyHashItem[129],
    &MyHashItem[130],
    &MyHashItem[131],
    NULL,
    &MyHashItem[133],
    &MyHashItem[136],
    NULL,
    NULL,
    &MyHashItem[137],
    &MyHashItem[139],
    &MyHashItem[141],
    &MyHashItem[142],
    &MyHashItem[143],
    &MyHashItem[145],
    &MyHashItem[147],
    NULL,
    NULL,
    &MyHashItem[148],
    &MyHashItem[150],
    &MyHashItem[152],
    &MyHashItem[154],
    &MyHashItem[156],
    &MyHashItem[158],
    &MyHashItem[163],
    &MyHashItem[165],
    &MyHashItem[166],
    &MyHashItem[167],
    NULL,
    NULL,
    &MyHashItem[175],
    &MyHashItem[176],
    &MyHashItem[181],
    &MyHashItem[183],
    NULL,
    &MyHashItem[186],
    &MyHashItem[187],
    &MyHashItem[188],
    &MyHashItem[191],
    &MyHashItem[194],
    &MyHashItem[195],
};

Hash_si tagtable = { 100, MyHashItemTbl };
