.PU
.TH wvSummary 1 
.SH NAME
wvSummary \- view word document's summary info 
.SH SYNOPSIS
.ll +8
.B wvSumamry word_doc
.ll -8
.br
.SH DESCRIPTION
wvSummary displays the summary info included
in all MSWord documents. This often includes
the Author, time created, etc...
.SH MORE INFORMATION
http://wvware.sourceforge.net
.SH "SEE ALSO"
.BR wvAbw(1),
.BR wvWare(1),
.BR wvHtml(1),
.BR wvLatex(1),
.BR wvCleanLatex(1),
.BR wvPDF(1),
.BR wvDVI(1),
.BR wvMime(1),
.BR wvRTF(1),
.BR wvText(1),
.BR wvWml(1),
.BR catdoc(1), 
.BR word2x(1)
.SH "AUTHOR"
 Dom Lachowicz (current author and maintainer) 
 WEB: http://wvware.sourceforge.net
 MAIL: cinamod@hotmail.com
