.PU
.TH wvVersion 1 
.SH NAME
wvVersion \- view word document's version #
.SH SYNOPSIS
.ll +8
.B wvVersion word_doc
.ll -8
.br
.SH DESCRIPTION
wvVersion displays the word version number of
a MSWord document. 8=Word97, 7=Word95, ... 
.SH MORE INFORMATION
http://wvware.sourceforge.net
.SH "SEE ALSO"
.BR wvAbw(1),
.BR wvWare(1),
.BR wvHtml(1),
.BR wvLatex(1),
.BR wvCleanLatex(1),
.BR wvPS(1),
.BR wvPDF(1),
.BR wvDVI(1),
.BR wvRTF(1),
.BR wvText(1),
.BR wvWml(1),
.BR wvMime(1),
.BR catdoc(1), 
.BR word2x(1)
.SH "AUTHOR"
 Dom Lachowicz (current author and maintainer) 
 WEB: http://wvware.sourceforge.net
 MAIL: cinamod@hotmail.com
