---
abstract: 'a simple generic namespace support class'
author:
  - 'Robin Berjon, robin@knowscape.com, with lots of it having been done'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-NamespaceSupport
no_index:
  directory:
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/perigrin/xml-namespacesupport.git
version: 1.11
