#! /bin/sh

set -e

. ${srcdir}/common

case ${MACHTYPE} in
*-msys)
    # Make sure path doesn't get mangled on MSYS
    ARGS="--define-variable=includedir=\\/includedir/ --cflags simple"
    ;;
*)
    ARGS="--define-variable=includedir=/includedir/ --cflags simple"
    ;;
esac
RESULT="-I/includedir/"

run_test
