#! /bin/sh

set -e

. ${srcdir}/common

ARGS="--libs simple"
if [ "$list_indirect_deps" = "yes" ]; then
    RESULT="-lsimple -lm"
else
    RESULT="-lsimple"
fi
run_test

ARGS="--libs fields-blank"
RESULT=""
run_test
