$(OPENMCL_MAXIMA) : maxima-package.lisp
$(OPENMCL_MAXIMA) : autoconf-variables.lisp
$(OPENMCL_MAXIMA) : nregex.lisp
$(OPENMCL_MAXIMA) : intl.lisp
$(OPENMCL_MAXIMA) : cl-info.lisp
$(OPENMCL_MAXIMA) : sloop.lisp
$(OPENMCL_MAXIMA) : lmdcls.lisp
$(OPENMCL_MAXIMA) : letmac.lisp
$(OPENMCL_MAXIMA) : generr.lisp
$(OPENMCL_MAXIMA) : clmacs.lisp
$(OPENMCL_MAXIMA) : commac.lisp
$(OPENMCL_MAXIMA) : mormac.lisp
$(OPENMCL_MAXIMA) : compat.lisp
$(OPENMCL_MAXIMA) : transm.lisp
$(OPENMCL_MAXIMA) : getopt.lisp
$(OPENMCL_MAXIMA) : command-line.lisp
$(OPENMCL_MAXIMA) : defcal.lisp
$(OPENMCL_MAXIMA) : maxmac.lisp
$(OPENMCL_MAXIMA) : mopers.lisp
$(OPENMCL_MAXIMA) : mforma.lisp
$(OPENMCL_MAXIMA) : mrgmac.lisp
$(OPENMCL_MAXIMA) : rzmac.lisp
$(OPENMCL_MAXIMA) : strmac.lisp
$(OPENMCL_MAXIMA) : displm.lisp
$(OPENMCL_MAXIMA) : ratmac.lisp
$(OPENMCL_MAXIMA) : mhayat.lisp
$(OPENMCL_MAXIMA) : opers.lisp
$(OPENMCL_MAXIMA) : utils.lisp
$(OPENMCL_MAXIMA) : sumcon.lisp
$(OPENMCL_MAXIMA) : sublis.lisp
$(OPENMCL_MAXIMA) : merror.lisp
$(OPENMCL_MAXIMA) : mformt.lisp
$(OPENMCL_MAXIMA) : mutils.lisp
$(OPENMCL_MAXIMA) : outmis.lisp
$(OPENMCL_MAXIMA) : ar.lisp
$(OPENMCL_MAXIMA) : comm.lisp
$(OPENMCL_MAXIMA) : comm2.lisp
$(OPENMCL_MAXIMA) : mlisp.lisp
$(OPENMCL_MAXIMA) : mmacro.lisp
$(OPENMCL_MAXIMA) : buildq.lisp
$(OPENMCL_MAXIMA) : numerical/f2cl-package.lisp
$(OPENMCL_MAXIMA) : numerical/slatec.lisp
$(OPENMCL_MAXIMA) : numerical/f2cl-lib.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/fdump.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/j4save.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/xercnt.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/xerhlt.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/xgetua.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/xerprn.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/xersve.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/xermsg.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/initds.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dcsevl.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/d9lgmc.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dgamlm.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dgamma.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dgamln.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dlngam.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/d9b0mp.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/d9b1mp.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbesj0.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbesj1.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/djairy.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dasyjy.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbesj.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbsi0e.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbsi1e.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbesi0.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbesi1.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dasyik.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbesi.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zabs.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zdiv.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zexp.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zmlt.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zsqrt.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zasyi.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zuchk.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zlog.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zunik.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zunhj.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zuoik.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zuni1.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zkscl.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zshch.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zbknu.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zmlri.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zs1s2.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zseri.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zacai.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zairy.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zuni2.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zbuni.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zrati.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zwrsk.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zbinu.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zbesi.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zbesj.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbesy0.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbesy1.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbsynu.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dyairy.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbesy.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zacon.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zunk1.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zunk2.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zbunk.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zbesh.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zbesy.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbsk0e.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbesk0.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbsk1e.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbesk1.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbsknu.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbesk.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zbesk.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/d9aimp.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/daie.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dai.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbie.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dbi.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/zbiry.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/derfc.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/derf.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/de1.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dei.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/d9upak.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dspenc.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqwgtf.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqcheb.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqk15w.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqwgts.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqwgtc.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dgtsl.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqk15.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqk31.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqk41.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqk51.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqk61.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqk21.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqk15i.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqelg.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqpsrt.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqc25s.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqmomo.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqc25c.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqc25f.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqage.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqagie.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqagpe.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqagp.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqagse.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqawoe.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqawfe.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqawse.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqawce.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqng.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqag.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqags.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqagi.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqawf.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqawo.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqaws.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/dqawc.lisp
$(OPENMCL_MAXIMA) : numerical/slatec/quadpack.lisp
$(OPENMCL_MAXIMA) : simp.lisp
$(OPENMCL_MAXIMA) : float.lisp
$(OPENMCL_MAXIMA) : csimp.lisp
$(OPENMCL_MAXIMA) : csimp2.lisp
$(OPENMCL_MAXIMA) : zero.lisp
$(OPENMCL_MAXIMA) : logarc.lisp
$(OPENMCL_MAXIMA) : rpart.lisp
$(OPENMCL_MAXIMA) : numeric.lisp
$(OPENMCL_MAXIMA) : server.lisp
$(OPENMCL_MAXIMA) : macsys.lisp
$(OPENMCL_MAXIMA) : mload.lisp
$(OPENMCL_MAXIMA) : suprv1.lisp
$(OPENMCL_MAXIMA) : dskfn.lisp
$(OPENMCL_MAXIMA) : lesfac.lisp
$(OPENMCL_MAXIMA) : factor.lisp
$(OPENMCL_MAXIMA) : algfac.lisp
$(OPENMCL_MAXIMA) : nalgfa.lisp
$(OPENMCL_MAXIMA) : ufact.lisp
$(OPENMCL_MAXIMA) : result.lisp
$(OPENMCL_MAXIMA) : ifactor.lisp
$(OPENMCL_MAXIMA) : rat3a.lisp
$(OPENMCL_MAXIMA) : rat3b.lisp
$(OPENMCL_MAXIMA) : rat3d.lisp
$(OPENMCL_MAXIMA) : rat3c.lisp
$(OPENMCL_MAXIMA) : rat3e.lisp
$(OPENMCL_MAXIMA) : nrat4.lisp
$(OPENMCL_MAXIMA) : ratout.lisp
$(OPENMCL_MAXIMA) : transl.lisp
$(OPENMCL_MAXIMA) : transs.lisp
$(OPENMCL_MAXIMA) : trans1.lisp
$(OPENMCL_MAXIMA) : trans2.lisp
$(OPENMCL_MAXIMA) : trans3.lisp
$(OPENMCL_MAXIMA) : trans4.lisp
$(OPENMCL_MAXIMA) : trans5.lisp
$(OPENMCL_MAXIMA) : transf.lisp
$(OPENMCL_MAXIMA) : troper.lisp
$(OPENMCL_MAXIMA) : trutil.lisp
$(OPENMCL_MAXIMA) : trmode.lisp
$(OPENMCL_MAXIMA) : trdata.lisp
$(OPENMCL_MAXIMA) : trpred.lisp
$(OPENMCL_MAXIMA) : transq.lisp
$(OPENMCL_MAXIMA) : acall.lisp
$(OPENMCL_MAXIMA) : fcall.lisp
$(OPENMCL_MAXIMA) : evalw.lisp
$(OPENMCL_MAXIMA) : trprop.lisp
$(OPENMCL_MAXIMA) : mdefun.lisp
$(OPENMCL_MAXIMA) : trigi.lisp
$(OPENMCL_MAXIMA) : trigo.lisp
$(OPENMCL_MAXIMA) : trgred.lisp
$(OPENMCL_MAXIMA) : bessel.lisp
$(OPENMCL_MAXIMA) : ellipt.lisp
$(OPENMCL_MAXIMA) : airy.lisp
$(OPENMCL_MAXIMA) : plasma.lisp
$(OPENMCL_MAXIMA) : intpol.lisp
$(OPENMCL_MAXIMA) : nparse.lisp
$(OPENMCL_MAXIMA) : displa.lisp
$(OPENMCL_MAXIMA) : nforma.lisp
$(OPENMCL_MAXIMA) : grind.lisp
$(OPENMCL_MAXIMA) : spgcd.lisp
$(OPENMCL_MAXIMA) : ezgcd.lisp
$(OPENMCL_MAXIMA) : option.lisp
$(OPENMCL_MAXIMA) : macdes.lisp
$(OPENMCL_MAXIMA) : inmis.lisp
$(OPENMCL_MAXIMA) : db.lisp
$(OPENMCL_MAXIMA) : compar.lisp
$(OPENMCL_MAXIMA) : askp.lisp
$(OPENMCL_MAXIMA) : sinint.lisp
$(OPENMCL_MAXIMA) : sin.lisp
$(OPENMCL_MAXIMA) : risch.lisp
$(OPENMCL_MAXIMA) : hayat.lisp
$(OPENMCL_MAXIMA) : defint.lisp
$(OPENMCL_MAXIMA) : residu.lisp
$(OPENMCL_MAXIMA) : specfn.lisp
$(OPENMCL_MAXIMA) : mat.lisp
$(OPENMCL_MAXIMA) : linnew.lisp
$(OPENMCL_MAXIMA) : matrix.lisp
$(OPENMCL_MAXIMA) : sprdet.lisp
$(OPENMCL_MAXIMA) : newinv.lisp
$(OPENMCL_MAXIMA) : newdet.lisp
$(OPENMCL_MAXIMA) : schatc.lisp
$(OPENMCL_MAXIMA) : matcom.lisp
$(OPENMCL_MAXIMA) : matrun.lisp
$(OPENMCL_MAXIMA) : nisimp.lisp
$(OPENMCL_MAXIMA) : tlimit.lisp
$(OPENMCL_MAXIMA) : limit.lisp
$(OPENMCL_MAXIMA) : solve.lisp
$(OPENMCL_MAXIMA) : psolve.lisp
$(OPENMCL_MAXIMA) : algsys.lisp
$(OPENMCL_MAXIMA) : polyrz.lisp
$(OPENMCL_MAXIMA) : cpoly.lisp
$(OPENMCL_MAXIMA) : mtrace.lisp
$(OPENMCL_MAXIMA) : mdebug.lisp
$(OPENMCL_MAXIMA) : scs.lisp
$(OPENMCL_MAXIMA) : asum.lisp
$(OPENMCL_MAXIMA) : fortra.lisp
$(OPENMCL_MAXIMA) : optim.lisp
$(OPENMCL_MAXIMA) : marray.lisp
$(OPENMCL_MAXIMA) : mdot.lisp
$(OPENMCL_MAXIMA) : irinte.lisp
$(OPENMCL_MAXIMA) : series.lisp
$(OPENMCL_MAXIMA) : numth.lisp
$(OPENMCL_MAXIMA) : laplac.lisp
$(OPENMCL_MAXIMA) : pade.lisp
$(OPENMCL_MAXIMA) : homog.lisp
$(OPENMCL_MAXIMA) : combin.lisp
$(OPENMCL_MAXIMA) : nset.lisp
$(OPENMCL_MAXIMA) : rand-mt19937.lisp
$(OPENMCL_MAXIMA) : maxmin.lisp
$(OPENMCL_MAXIMA) : nummod.lisp
$(OPENMCL_MAXIMA) : conjugate.lisp
$(OPENMCL_MAXIMA) : expintegral.lisp
$(OPENMCL_MAXIMA) : gamma.lisp
$(OPENMCL_MAXIMA) : mstuff.lisp
$(OPENMCL_MAXIMA) : pois2.lisp
$(OPENMCL_MAXIMA) : pois3.lisp
$(OPENMCL_MAXIMA) : desoln.lisp
$(OPENMCL_MAXIMA) : elim.lisp
$(OPENMCL_MAXIMA) : invert.lisp
$(OPENMCL_MAXIMA) : hypgeo.lisp
$(OPENMCL_MAXIMA) : hyp.lisp
$(OPENMCL_MAXIMA) : todd-coxeter.lisp
$(OPENMCL_MAXIMA) : mactex.lisp
$(OPENMCL_MAXIMA) : plot.lisp
$(OPENMCL_MAXIMA) : gnuplot_def.lisp
$(OPENMCL_MAXIMA) : xmaxima_def.lisp
$(OPENMCL_MAXIMA) : autol.lisp
$(OPENMCL_MAXIMA) : max_ext.lisp
$(OPENMCL_MAXIMA) : share-subdirs.lisp
$(OPENMCL_MAXIMA) : init-cl.lisp

