#ifndef __LibtUtilities_H
#define __LibtUtilities_H

///////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 1997-2008 Morgan Stanley All rights reserved.
// See .../src/LICENSE for terms of distribution.
//
//
///////////////////////////////////////////////////////////////////////////////

extern A tp_a_object(char *recbuf, A fields);
extern C *libtMakeClasses(A clss);
extern A libtMakeFields(A clss);

#endif
