set -o pipefail
'bugpoint' '-load' '/private/var/chris/llvm-2.8/Release/lib/BugpointPasses.dylib' '/private/var/chris/llvm-2.8/test/BugPoint/metadata.ll' '-output-prefix' '/private/var/chris/llvm-2.8/test/BugPoint/Output/metadata.ll.tmp' '-bugpoint-crashcalls' '-silence-passes' > '/dev/null'  &&

'llvm-dis' '/private/var/chris/llvm-2.8/test/BugPoint/Output/metadata.ll.tmp-reduced-simplified.bc' '-o' '-' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/BugPoint/metadata.ll'