set -o pipefail
'bugpoint' '-load' '/private/var/chris/llvm-2.8/Release/lib/BugpointPasses.dylib' '/private/var/chris/llvm-2.8/test/BugPoint/remove_arguments_test.ll' '-output-prefix' '/private/var/chris/llvm-2.8/test/BugPoint/Output/remove_arguments_test.ll.tmp' '-bugpoint-crashcalls' '-silence-passes'  &&

'llvm-dis' '/private/var/chris/llvm-2.8/test/BugPoint/Output/remove_arguments_test.ll.tmp-reduced-simplified.bc' '-o' '-' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/BugPoint/remove_arguments_test.ll'