set -o pipefail
'llc' '-O0' '-asm-verbose' < '/private/var/chris/llvm-2.8/test/DebugInfo/2010-04-13-PubType.ll' > '/private/var/chris/llvm-2.8/test/DebugInfo/Output/2010-04-13-PubType.ll.tmp'  &&

'grep' 'External Name' '/private/var/chris/llvm-2.8/test/DebugInfo/Output/2010-04-13-PubType.ll.tmp' |
  'grep' '-v' 'X'  &&

'grep' 'External Name' '/private/var/chris/llvm-2.8/test/DebugInfo/Output/2010-04-13-PubType.ll.tmp' |
  'grep' 'Y' |
  'count' '1'