set -o pipefail
'llc' '-asm-verbose' '-O0' '-o' '/private/var/chris/llvm-2.8/test/DebugInfo/Output/2010-04-19-FramePtr.ll.tmp' < '/private/var/chris/llvm-2.8/test/DebugInfo/2010-04-19-FramePtr.ll'  &&

'grep' 'DW_AT_APPLE_omit_frame_ptr' '/private/var/chris/llvm-2.8/test/DebugInfo/Output/2010-04-19-FramePtr.ll.tmp'  &&

'llc' '-disable-fp-elim' '-asm-verbose' '-O0' '-o' '/private/var/chris/llvm-2.8/test/DebugInfo/Output/2010-04-19-FramePtr.ll.tmp' < '/private/var/chris/llvm-2.8/test/DebugInfo/2010-04-19-FramePtr.ll'  &&

'grep' '-v' 'DW_AT_APPLE_omit_frame_ptr' '/private/var/chris/llvm-2.8/test/DebugInfo/Output/2010-04-19-FramePtr.ll.tmp'