#!/bin/sh -e
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

. ./defs

outputdirfile=`mktemp ii53-XXXXXXXX`
cp ${testdir}/ii-0053-input-dir-file $outputdirfile

# Have to handle newlines in input dir entries, too.
${install_info} ${testdir}/ii-0053-input-info-file $outputdirfile
diff ${testdir}/ii-0053-expected-dir-file $outputdirfile

rm -f $outputdirfile
exit 0
