/* This is auto-generated code. Edit at your own peril. */
#include "testing/testing.h"

DECLARE_SETUP (create_credential);
DECLARE_TEARDOWN (create_credential);
DECLARE_TEST (create_credential_ok_password);
DECLARE_TEST (create_credential_bad_password_then_cancel);
DECLARE_TEST (create_credentiaol_cancel_immediately);
DECLARE_SETUP (init_pin);
DECLARE_TEARDOWN (init_pin);
DECLARE_TEST (init_pin_ok_password);
DECLARE_SETUP (login_auto);
DECLARE_TEARDOWN (login_auto);
DECLARE_TEST (login_auto_specific);
DECLARE_TEST (login_auto_user_token);
DECLARE_TEST (login_auto_unlock_keyring);
DECLARE_TEST (login_did_unlock_fail);
DECLARE_SETUP (login_keyring);
DECLARE_TEARDOWN (login_keyring);
DECLARE_TEST (login_is_usable);
DECLARE_TEST (login_usable_fail_open_session);
DECLARE_TEST (login_usable_fail_not_trusted);
DECLARE_TEST (login_usable_fail_locked);
DECLARE_TEST (login_lookup_secret_no_match);
DECLARE_TEST (login_lookup_secret_and_match);
DECLARE_TEST (login_lookup_store_secret);
DECLARE_TEST (login_lookup_store_secret_overwrite);
DECLARE_TEST (login_lookup_store_null_secret);
DECLARE_TEST (login_lookup_store_no_attributes_not_stored);
DECLARE_TEST (login_lookup_remove_present);
DECLARE_TEST (login_lookup_remove_no_attributes);
DECLARE_SETUP (login_specific);
DECLARE_TEARDOWN (login_specific);
DECLARE_TEST (login_specific_ok_password);
DECLARE_TEST (login_specific_bad_password_then_cancel);
DECLARE_TEST (login_specific_cancel_immediately);
DECLARE_SETUP (login_user);
DECLARE_TEARDOWN (login_user);
DECLARE_TEST (login_fail_unsupported_so);
DECLARE_TEST (login_skip_prompt_because_pin);
DECLARE_TEST (login_user_ok_password);
DECLARE_TEST (login_user_bad_password_then_cancel);
DECLARE_TEST (login_user_cancel_immediately);
DECLARE_TEST (login_user_fail_get_session_info);
DECLARE_TEST (login_user_fail_get_token_info);
DECLARE_SETUP (set_pin);
DECLARE_TEARDOWN (set_pin);
DECLARE_TEST (set_pin_ok_passwords);

