set -o pipefail
'llvm-as' '/private/var/chris/llvm-2.8/test/Integer/2007-01-19-TruncSext.ll' '-o' '-' |
  'llvm-dis' > '/private/var/chris/llvm-2.8/test/Integer/Output/2007-01-19-TruncSext.ll.tmp1.ll'  &&

'llvm-as' '/private/var/chris/llvm-2.8/test/Integer/Output/2007-01-19-TruncSext.ll.tmp1.ll' '-o' '-' |
  'llvm-dis' > '/private/var/chris/llvm-2.8/test/Integer/Output/2007-01-19-TruncSext.ll.tmp2.ll'  &&

'diff' '/private/var/chris/llvm-2.8/test/Integer/Output/2007-01-19-TruncSext.ll.tmp1.ll' '/private/var/chris/llvm-2.8/test/Integer/Output/2007-01-19-TruncSext.ll.tmp2.ll'  &&

'llvm-as' < '/private/var/chris/llvm-2.8/test/Integer/2007-01-19-TruncSext.ll' |
  'lli' '--force-interpreter=true' |
  'grep' '--' '-255'