set -o pipefail
'llvm-as' '/private/var/chris/llvm-2.8/test/Integer/properties_bt.ll' '-o' '-' |
  'llvm-dis' > '/private/var/chris/llvm-2.8/test/Integer/Output/properties_bt.ll.tmp1.ll'  &&

'llvm-as' '/private/var/chris/llvm-2.8/test/Integer/Output/properties_bt.ll.tmp1.ll' '-o' '-' |
  'llvm-dis' > '/private/var/chris/llvm-2.8/test/Integer/Output/properties_bt.ll.tmp2.ll'  &&

'diff' '/private/var/chris/llvm-2.8/test/Integer/Output/properties_bt.ll.tmp1.ll' '/private/var/chris/llvm-2.8/test/Integer/Output/properties_bt.ll.tmp2.ll'