.ad l
.nh
.TH identify 1 "1 May 1994" "ImageMagick"
.SH NAME
identify - describe the format and characteristics of one or more image
files.
.SH SYNOPSIS
.B "identify"
[ \fIoptions\fP ... ] \fIfile\fP [ \fIfile\fP ... ]
.SH DESCRIPTION
\fBidentify\fP describes the format and characteristics of one or more image
files.  It will also report if an image is incomplete or corrupt.
The information displayed includes the scene number, the file name, the
width and height of the image, whether the image is colormapped or not,
the number of colors in the image, the number of bytes in the image, the
format of the image (JPEG, PNM, etc.), and finally the number of seconds
it took to read and process the image.  An example line output from
\fBidentify\fP follows:

.nf
     images/aquarium.miff 640x480 PseudoClass 256c 308135b MIFF 1s
.fi

If \fB-verbose\fP is set, expect additional output including any image
comment:

.nf
     Image: images/aquarium.miff
       class: PseudoClass
       colors: 256
       signature: eb5dca81dd93ae7e6ffae99a5275a53e
       matte: False
       geometry: 640x480
       depth: 8
       bytes: 308135
       format: MIFF
       comments:

         Imported from MTV raster image:  aquarium.mtv
.fi
.SH OPTIONS
.TP
.B "-ping"
efficiently determine image characteristics.

This is a more efficient and less memory intensive way to query if an image
exists and what its size is.  Note, only the size of the first image in
a multi-frame image file is returned.
.TP
.B "-size \fI<width>x<height>+<offset>\fP"
width and height of the image.

Use this option to specify the width and height of raw images whose
dimensions are unknown such as \fBGRAY\fP, \fBRGB\fP, or \fBCMYK\fP.
In addition to width and height, use \fB-size\fP to skip any header
information in the image or tell the number of colors in a \fBMAP\fP
image file, (e.g. -size 640x512+256).

For Photo CD images, choose from these sizes:

.nf
      192x128
      384x256
      768x512
     1536x1024
     3072x2048
.fi

Finally, use this option to choose a particular resolution layer of a JBIG
or JPEG image (e.g. -size 1024x768).
.TP
.B -verbose
print detailed information about the image.

This information is printed:  image name;  the image class
(\fIDirectClass\fP or \fIPseudoClass\fP);  the total number of unique
colors; whether there is a matte associated with the image; the number
of runlength packets; the image size; the depth of the image; the image
format; the image scene; and finally any image comment.  Refer to
\fBmiff(1)\fP for a description of the image class.
.SH SEE ALSO
.B
display(1), animate(1), montage(1), mogrify(1), convert(1), combine(1), xtp(1)
.SH COPYRIGHT
1998 1998 E. I. du Pont de Nemours and Company

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files ("ImageMagick"),
to deal in ImageMagick without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of ImageMagick, and to permit persons to whom the
ImageMagick is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of ImageMagick.

The software is provided "as is", without warranty of any kind, express or
implied, including but not limited to the warranties of merchantability,
fitness for a particular purpose and noninfringement.  In no event shall
E. I. du Pont de Nemours and Company be liable for any claim, damages or
other liability, whether in an action of contract, tort or otherwise,
arising from, out of or in connection with ImageMagick or the use or other
dealings in ImageMagick.

Except as contained in this notice, the name of the E. I. du Pont de
Nemours and Company shall not be used in advertising or otherwise to
promote the sale, use or other dealings in ImageMagick without prior
written authorization from the E. I. du Pont de Nemours and Company.
.SH AUTHORS
John Cristy, E.I. du Pont De Nemours and Company Incorporated
