set -o pipefail
'tblgen' '-I' '/private/var/chris/llvm-2.8/test/LLVMC/../../include' '--gen-llvmc' '/private/var/chris/llvm-2.8/test/LLVMC/ForwardValue.td' '-o' '/private/var/chris/llvm-2.8/test/LLVMC/Output/ForwardValue.td.tmp'  &&

'FileCheck' '-input-file' '/private/var/chris/llvm-2.8/test/LLVMC/Output/ForwardValue.td.tmp' '/private/var/chris/llvm-2.8/test/LLVMC/ForwardValue.td'  &&

'g++' '-I/private/var/chris/llvm-2.8/include' '-I/private/var/chris/llvm-2.8/test' '-DNDEBUG' '-D_GNU_SOURCE' '-D__STDC_LIMIT_MACROS' '-D__STDC_CONSTANT_MACROS' '-O3' '-fno-rtti' '-fno-common' '-Woverloaded-virtual' '-Wcast-qual' '-pedantic' '-Wno-long-long' '-Wall' '-W' '-Wno-unused-parameter' '-Wwrite-strings' '-c' '-x' 'c++' '/private/var/chris/llvm-2.8/test/LLVMC/Output/ForwardValue.td.tmp'