set -o pipefail
'llvm-dis' < '/private/var/chris/llvm-2.8/test/Bitcode/AutoUpgradeIntrinsics.ll.bc' |
  'not' 'grep' 'i32 @llvm\.ct'  &&

'llvm-dis' < '/private/var/chris/llvm-2.8/test/Bitcode/AutoUpgradeIntrinsics.ll.bc' |
  'not' 'grep' 'llvm\.part\.set\.i[0-9]*\.i[0-9]*\.i[0-9]*'  &&

'llvm-dis' < '/private/var/chris/llvm-2.8/test/Bitcode/AutoUpgradeIntrinsics.ll.bc' |
  'not' 'grep' 'llvm\.part\.select\.i[0-9]*\.i[0-9]*'  &&

'llvm-dis' < '/private/var/chris/llvm-2.8/test/Bitcode/AutoUpgradeIntrinsics.ll.bc' |
  'not' 'grep' 'llvm\.bswap\.i[0-9]*\.i[0-9]*'