set -o pipefail
'llvm-as' < '/private/var/chris/llvm-2.8/test/Bitcode/flags.ll' |
  'llvm-dis' > '/private/var/chris/llvm-2.8/test/Bitcode/Output/flags.ll.tmp0'  &&

'opt' '-S' < '/private/var/chris/llvm-2.8/test/Bitcode/flags.ll' > '/private/var/chris/llvm-2.8/test/Bitcode/Output/flags.ll.tmp1'  &&

'diff' '/private/var/chris/llvm-2.8/test/Bitcode/Output/flags.ll.tmp0' '/private/var/chris/llvm-2.8/test/Bitcode/Output/flags.ll.tmp1'