/* xmlrpc_amconfig.h is generated by 'configure' from the template
   xmlrpc_amconfig.h.in, by virtue of the AM_CONFIG_HEADER() macro in
   configure.in.

   We'd like to replace it some day with something that doesn't use
   such a special tool, to make the build understandable by dumber
   developers.  
*/

/* Define to `unsigned' if <sys/types.h> doesn't define.  */
/* #undef size_t */

/* Define if you have the setgroups function.  */
/* #undef HAVE_SETGROUPS */

#define HAVE_ASPRINTF 1

/* Define if you have the wcsncmp function.  */
/* #undef HAVE_WCSNCMP */

/* Define if you have the <stdarg.h> header file.  */
#define HAVE_STDARG_H 1

/* Define if you have the <sys/filio.h> header file.  */
#define HAVE_SYS_FILIO_H 1

/* Define if you have the <sys/ioctl.h> header file.  */
#define HAVE_SYS_IOCTL_H 1

/* Define if you have the <wchar.h> header file.  */
#define HAVE_WCHAR_H 1

/* Define if you have the socket library (-lsocket).  */
/* #undef HAVE_LIBSOCKET */

/* Name of package */
/* #undef PACKAGE */
