.\" Process this file with groff -man -Tascii links.1
.TH LINKS 1 "Aug, 2006"
.SH NAME
links \- lynx-like alternative character mode WWW browser
.SH SYNOPSIS
.B links
.I "[options] URL"
.SH DESCRIPTION
.B links
is a text mode WWW browser with ncurses interface, supporting
colors, correct table rendering, background downloading, menu
driven configuration interface and slim code.
.P 
Frames are supported. You can have different file formats 
associated with external viewers. mailto: and telnet:
are supported via external clients.
.P
.I links
can handle local (file://) or remote (http:// or ftp://) URLs.
.PP

.SH OPTIONS
Most options can be set in the user
interface or config file, so usually you do not need to care about them.

.TP
\f3-g\f1
Run Links in graphics mode. If not given, Links will run in text mode.
Running in graphics mode means that Links will probe all compiled-in graphics
devices and run on the first found. If none found, links will not run in
graphics mode. This option works only if --enable-graphics was given
to ./configure.

.TP
\f3-no-g\f1
Run in text mode (overrides previous -g).

.TP
\f3-driver \f2<driver name>\f1
Graphics driver to use. Drivers are: x, svgalib, fb, directfb, pmshell,
atheos.
List of drivers will be shown if you give it an unknown driver.
Available drivers depend on your operating system and available libraries.

.TP
\f3-mode \f2<parameter>\f1
Pass a parameter to the graphics driver. On SVGAlib, this is widthxheightxdepth,
(where depth is 16, 256, 32K, 64K, 16M or 16M32) and defines the graphics mode, on X the format is WIDTHxHEIGHT and defines the
window size.

.TP
\f3-display \f2<x-display>\f1
Set Xwindow display.

.TP
\f3-force-html\f1
Treat files with unknown type as html rather than text.
(can be toggled with '\\' key)

.TP
\f3-source \f2<url>\f1
Write unformatted data stream to stdout.

.TP
\f3-dump \f2<url>\f1
Write formatted document to stdout.

.TP
\f3-width \f2<number>\f1
For dump, document will be formatted to this screen width (but it can still
exceed it if lines can't be broken).

.TP
\f3-codepage \f2<codepage>\f1
For dump, convert output to specified character set --
for eaxmple iso-8859-2, windows-1250.

.TP
\f3-anonymous\f1
Restrict links so that it can run on an anonymous account.
No local file browsing. No downloads. Executing of viewers
is allowed, but user can't add or modify entries in
association table.

.TP
\f3-no-connect\f1
Runs links as a separate instance - instead of connecting to
existing instance.

.TP
\f3-download-utime \f2<0>/<1>\f1
Set time of downloaded files to last modification time reported by server.

.TP
\f3-async-dns \f2<0>/<1>\f1
Asynchronous DNS resolver on(1)/off(0). 

.TP
\f3-max-connections \f2<max>\f1
Maximum number of concurrent connections.
(default: 10)

.TP
\f3-max-connections-to-host \f2<max>\f1
Maximum number of concurrent connection to a given host.
(default: 2)

.TP
\f3-retries \f2<retry>\f1
Number of retries.
(default: 3)

.TP
\f3-receive-timeout \f2<sec>\f1
Timeout on receive.
(default: 120)

.TP
\f3-unrestartable-receive-timeout \f2<sec>\f1
Timeout on non restartable connections.
(default: 600)

.TP
\f3-format-cache-size \f2<num>\f1
Number of formatted document pages cached.
(default: 5)

.TP
\f3-memory-cache-size \f2<bytes>\f1
Cache memory in Kilobytes.
(default: 1024)

.TP
\f3-image-cache-size \f2<bytes>\f1
Cache memory in Kilobytes.
(default: 1024)

.TP
\f3-http-proxy \f2<host:port>\f1
Host and port number of the HTTP proxy, or blank.
(default: blank)

.TP
\f3-ftp-proxy \f2<host:port>\f1
Host and port number of the FTP proxy, or blank.
(default: blank)

.TP
\f3-socks-proxy \f2<user@host:port>\f1
Userid, host and port of Socks4a, or blank.
(default: blank)

.TP
\f3-append-text-to-dns-lookups \f2<text>\f1
Append text to dns lookups. It is useful for specifying fixed tor exit node.
(default: blank)

.TP
\f3-only-proxies \f2<0>/<1>\f1
"1" causes that Links won't initiate any non-proxy connection.
It is useful for anonymization with tor or similar networks.

.TP
\f3-download-dir \f2<path>\f1
Default download directory.
(default: actual dir)

.TP
\f3-aggressive-cache \f2<0>/<1>\f1
Always cache everything regardless of server's caching recomendations.
Many servers deny caching even if their content is not changing
just to get more hits and more money from ads.

.TP
\f3-language \f2<language>\f1
Set user interface language.

.TP
\f3-http-bugs.http10 \f2<0>/<1>\f1
(default 0) "1" forces using only HTTP/1.0 protocol. (useful for buggy servers
that claim to be HTTP/1.1 compliant but are not)
"0" enables using both HTTP/1.0 and HTTP/1.1.

.TP
\f3-http-bugs.allow-blacklist \f2<0>/<1>\f1
(default 1)
"1" defaults to using list of servers that have broken HTTP/1.1 support.
When links finds such server, it will retry the request with HTTP/1.0.

.TP
\f3-http-bugs.bug-302-redirect \f2<0>/<1>\f1
(default 1)
Process 302 redirect in a way that is incompatible with RFC1945 and RFC2068,
but the same as Netscape and MSIE. Many pages depend on it.

.TP
\f3-http-bugs.bug-post-no-keepalive \f2<0>/<1>\f1
(default 0)
No keepalive connection after post requests. For some buggy servers.

.TP
\f3-http-bugs.bug-no-accept-charset \f2<0>/<1>\f1
(default 0)
Do not send Accept-Charset field of HTTP header. Because it is too long
some servers will deny the request. Other servers will convert content
to plain ascii when Accept-Charset is missing.

.TP
\f3-http-bugs.no-compression \f2<0>/<1>\f1
(default 0) "1" causes that links won't advertise HTTP compression support (but
it will still accept compressed data). Use it when you communicate with server
that has broken compression support.

.TP
\f3-http-bugs.retry-internal-errors \f2<0>/<1>\f1
(default 0)
Retry on internal server errors (50x).

.TP
\f3-http.referer \f2<0>/<1>/<2>/<3>/<4>\f1
(default 0)
0 - do not send referer.
1 - send the requested URL as referer.
2 - send fake referer.
3 - send real referer.
4 - send real referer only to the same server.

.TP
\f3-http.fake-referer \f2<string>\f1
Fake referer value.

.TP
\f3-http.fake-user-agent \f2<string>\f1
Fake user agent value.

.TP
\f3-http.extra-header \f2<string>\f1
Extra string added to HTTP header.

.TP
\f3-ftp.anonymous-password \f2<string>\f1
Password for anonymous ftp access.

.TP
\f3-ftp.use-passive \f2<0>/<1>\f1
Use ftp PASV command to bypass firewalls.

.TP
\f3-ftp.fast \f2<0>/<1>\f1
Send more ftp commands simultaneously. Faster response when
browsing ftp directories, but it is incompatible with RFC
and some servers don't like it.

.TP
\f3-menu-font-size \f2<size>\f1
Size of font in menu.

.TP
\f3-background-color \f20xRRGGBB\f1
Set menu background color in graphics mode. RRGGBB are hex.

.TP
\f3-foreground-color \f20xRRGGBB\f1
Set menu foreground color in graphics mode. RRGGBB are hex.

.TP
\f3-scroll-bar-area-color \f20xRRGGBB\f1
Set color of scroll bar area. RRGGBB are hex.

.TP
\f3-scroll-bar-bar-color \f20xRRGGBB\f1
Set color of scroll bar. RRGGBB are hex.

.TP
\f3-scroll-bar-frame-color \f20xRRGGBB\f1
Set color of scroll bar frame. RRGGBB are hex.

.TP
\f3-display-red-gamma \f2<fp-value>\f1
Red gamma of display. (default 2.2)

.TP
\f3-display-green-gamma \f2<fp-value>\f1
Green gamma of display. (default 2.2)

.TP
\f3-display-blue-gamma \f2<fp-value>\f1
Blue gamma of display. (default 2.2)

.TP
\f3-user-gamma \f2<fp-value>\f1
Additional gamma. (defult 1)

.TP
\f3-bfu-aspect \f2<fp-value>\f1
Display aspect ration.

.TP
\f3-aspect-on \f2<0>/<1>\f1
Enable aspect ratio correction.

.TP
\f3-dither-letters \f2<0>/<1>\f1
Do letter dithering.

.TP
\f3-dither-images \f2<0>/<1>\f1
Do image dithering.

.TP
\f3-display-optimize \f2<0>/<1>/<2>\f1
Optimize for CRT (0), LCD RGB (1), LCD BGR (2).

.TP
\f3-gamma-correction \f2<0>/<1>/<2>\f1
Type of gamma correction:
(default 2)
0 - 8-bit (fast).
1 - 16-bit (slow).
2 - automatically detect according to speed of FPU.

.\".TP
.\"\f3-enable-javascript \f2<0>/<1>\f1
.\"Enable javascript.
.\"
.\".TP
.\"\f3-js.verbose-errors \f2<0>/<1>\f1
.\"Display javascript errors.
.\"
.\".TP
.\"\f3-js.verbose-warnings \f2<0>/<1>\f1
.\"Display javascript warnings.
.\"
.\".TP
.\"\f3-js.enable-all-conversions \f2<0>/<1>\f1
.\"Enable conversions between all types in javascript.
.\"
.\".TP
.\"\f3-js.enable-global-resolution \f2<0>/<1>\f1
.\"Resolve global names.
.\"
.\".TP
.\"\f3-js.manual-confirmation \f2<0>/<1>\f1
.\"Ask user to confirm potentially dangerous operations.
.\"(opening windows, going to url etc.) Default 1.
.\"
.\".TP
.\"\f3-js.recursion-depth \f2<integer>\f1
.\"Depth of javascript call stack.
.\"
.\".TP
.\"\f3-js.memory-limit \f2<memory amount>\f1
.\"Amount of kilobytes the javascript may allocate.
.\"
.TP
\f3-bookmarks-codepage \f2<codepage>\f1
Character set of bookmarks file.

.TP
\f3-bookmarks-file \f2<file>\f1
File to store bookmarks.

.TP
\f3-html-assume-codepage \f2<codepage>\f1
Use the given codepage when the webpage did not specify
its codepage. (default: ISO 8859-1)

.TP
\f3-html-hard-assume \f2<0>/<1>\f1
Use always character set from "-html-assume-codepage" no matter
what server sent.

.TP
\f3-html-tables \f2<0>/<1>\f1
Render tables. (0) causes tables being rendered like in lynx.

.TP
\f3-html-frames \f2<0>/<1>\f1
Render frames. (0) causes frames  rendered like in lynx.

.TP
\f3-html-images \f2<0>/<1>\f1
Display links to unnamed images as [IMG]

.TP
\f3-html-image-names \f2<0>/<1>\f1
Display filename of an image instead of [IMG].

.TP
\f3-html-display-images \f2<0>/<1>\f1
Display images in graphics mode.

.TP
\f3-html-image-scale \f2<percent>\f1
Scale images in graphics mode.

.TP
\f3-html-bare-image-autoscale \f2<0>/<1>\f1
Autoscale images displayed in full screen.

.TP
\f3-html-numbered-links \f2<0>/<1>\f1
Number links in text mode. Allow quick link selection by typing
link number and enter.

.TP
\f3-html-table-order \f2<0>/<1>\f1
In text mode, walk through table by rows (0) or columns (1).

.TP
\f3-html-auto-refresh \f2<0>/<1>\f1
Process refresh to other page (1), or display link to that page (0).

.TP
\f3-html-target-in-new-window \f2<0>/<1>\f1
Allow opening new windows from html.

.TP
\f3-html-margin \f2<number of spaces>\f1
Margin in text mode.

.TP
\f3-html-user-font-size \f2<size>\f1
Size of font on pages in graphics mode.

.TP
\f3-lookup \f2<hostname>\f1
Does name lookup, like command "host".

.TP
\f3-version\f1
Prints the 
.I links
version number and exit.

.TP
\f3-help\f1
Printf a help screen

.PP
More options can be seen with links -h

.SH NAVIGATION KEYS
The keys you may use while navigating are
.TP
.B ESC
menu/escape
.TP
.B F9
menu
.TP
.B F10
file menu
.TP
.B TAB
next frame
.TP
.B PGDN
page down
.TP
.B Space
page down
.TP
.B PGUP
page up
.TP
.B b
page up
.TP
.B B
page up
.TP
.B CursorDOWN
next link/down (text mode), scroll down (graphics mode)
.TP
.B CursorUP
prev link/up (text mode), up (graphics mode)
.TP
.B ^INS
copy to clipboard
.TP
.B ^C
copy to clipboard (OS/2 only)
.TP
.B INS
scroll up (text mode only)
.TP
.B ^P
scroll up
.TP
.B DEL
scroll down
.TP
.B ^N
scroll down
.TP
.B [
scroll left
.TP
.B ]
scroll right
.TP
.B HOME
home
.TP
.B END
end of page
.TP
.B CursorRIGHT
enter link/press button (text mode), scroll right (graphics mode)
.TP
.B ENTER
enter link/press button
.TP
.B CursorLEFT
go back (text mode), scroll left (graphics mode)
.TP
.B d
download link (text mode only)
.TP
.B D
download link (text mode only)
.TP
.B /
search in the page
.TP
.B ?
search back in the page
.TP
.B n
find next match
.TP
.B N
find next match backwards
.TP
.B f
zoom actual frame
.TP
.B F
zoom actual frame
.TP
.B ^R
reload page
.TP
.B g
go to URL
.TP
.B G
edit the current URL and goto the result
.TP
.B s
bookmark manager
.TP
.B S
bookmark manager
.TP
.B q
quit, close window if more windows are open
.TP
.B Q
quit, close window if more windows are open
.TP
.B =
document informations
.TP
.B \e
toggle HTML source/rendered view

.SH EDITING KEYS
The following keys can be used while editing a line/jumping to a URL:
.TP
.B CursorRIGHT
move right
.TP
.B CursorLEFT
move left
.TP
.B HOME
jump at the beginning
.TP
.B ^A
jump at the beginning
.TP
.B END
jump at the end
.TP
.B ^E
jump at the end
.TP
.B ^X
cut to clipboard
.TP
.B ^V
paste from clipboard
.TP
.B ENTER
enter line
.TP
.B BACKSPACE
delete back character
.TP
.B ^H
delete back character
.TP
.B DEL
delete character
.TP
.B ^D
delete character
.TP
.B ^U
delete from beginning of the line
.TP
.B ^K
delete to the end of the line or delete line (in textarea)
.TP
.B ^W
auto complete line





.SH FILES
.TP
.IP "~/.links/links.cfg"
Per-user configfile, automatically created by
.B links.
.SH PLATFORMS
.B links
is known to work on Linux, FreeBSD, Solaris, IRIX, HPUX, Digital Unix, AIX,
OS/2 and BeOS.
Port for Win32 is in state of beta testing.
.SH BUGS
You can't upload large files; it takes _lots_ of memory.
.PP
Please report any other bugs you find to Mikulas Patocka
<mikulas@artax.karlin.mff.cuni.cz>

.SH LICENSE
.B links
is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

.SH AUTHOR
.I links
was written by 
.B Mikulas Patocka, Karel 'Clock' Kulhavy, Petr 'Brain' Kulhavy, and Martin 'PerM' Pergel.
See file 
.I AUTHORS
for a list of people contributing to this project.
.P
The homepage of links can be found at
.BI http://atrey.karlin.mff.cuni.cz/~clock/twibright/links
.P
This manual page was written by Peter Gervai <grin@tolna.net>,
using excerpts from a (yet?) unknown
.I links
fan
for the Debian GNU/Linux system (but may be used by others). Updated by Karel Kulhavy.

.SH "SEE ALSO"
.BR lynx (1),
.BR w3m (1)
