#ifndef MSBuiltinVectorHEADER
#define MSBuiltinVectorHEADER

///////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 1997-2008 Morgan Stanley All rights reserved. 
// See .../src/LICENSE for terms of distribution
//
//
///////////////////////////////////////////////////////////////////////////////


#include <MSTypes/MSFloatVector.H>
#include <MSTypes/MSIntVector.H>
#include <MSTypes/MSLongVector.H>
#include <MSTypes/MSCharVector.H>
#include <MSTypes/MSUnsignedVector.H>
#include <MSTypes/MSUnsignedLongVector.H>

#endif
