#ifndef MSSpecializedVectorHEADER
#define MSSpecializedVectorHEADER

///////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 1997-2008 Morgan Stanley All rights reserved. 
// See .../src/LICENSE for terms of distribution
//
//
///////////////////////////////////////////////////////////////////////////////


#include <MSTypes/MSBuiltinVector.H>
#include <MSTypes/MSStringVector.H>
#include <MSTypes/MSSymbolVector.H>

#endif
