#define ICON_DIR "/usr/local/share/pixmaps"
#ifndef PROGRAM_VERSION
#define PROGRAM_VERSION "0.5.2~pre1"
#endif
#define MENU_CUSTOM_SIZE 20
#define HOTKEY_HAS_DEFINE
#define MENU_COPY
#define MENU_PASTE
#define MENU_SELECT_ALL
#define MENU_TAB_ADD
#define MENU_TAB_REMOVE
#define MENU_OPEN_NEW_WINDOW
#define MENU_QUIT
#define MENU_FONT_BIGGER
#define MENU_FONT_SMALLER
#define MENU_FONT_DEFAULT_SIZE
#define MENU_RESET_TERMINAL
#define MENU_RESET_AND_CLEAR
#define MENU_SEPARATOR
#define MENU_TOGGLE_SCROLLBAR
#define MENU_TOGGLE_STATUS_BAR
#define MENU_TOGGLE_TABBAR
