/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2012-2-20: 21h:29m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/option.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#ifndef ATS_LIBATS_LEX_LEXING_SATS
#define ATS_LIBATS_LEX_LEXING_SATS
typedef struct {
  ats_clo_ptr_type free ;
  ats_clo_ptr_type getc ;
} atslex_infile_t ; // end of [typedef]
#endif // end of [ATS_LIBATS_LEX_LEXING_SATS]
/* external codes at top */

//
extern void free (void*) ;
//
ATSinline()
ats_void_type
table_ptr_free (ats_ptr_type p) { free (p) ; return ; }
//

//
ATSinline()
ats_int_type
ats_int_of_int16 (ats_int16_type i) { return i ; }
//

/* type definitions */
typedef struct {
ats_ptr_type atslab_0 ;
ats_int_type atslab_1 ;
} anairiats_sum_0 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2libats_2lex_2tables_2edats__tblopt_some) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2libats_2lex_2tables_2edats__tblopt_none) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_int_type, atspre_add_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_sub_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_mul_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_asl_int_int1) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, new_tbloptref_some) (ats_ptr_type, ats_int_type) ;
ATSextern_fun(ats_void_type, table_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, __accept_table_make_fun) (ats_int_type, ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_int_type, ats_int_of_int16) (ats_int16_type) ;
ATSextern_fun(ats_ptr_type, __transition_table_make_fun) (ats_int_type, ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* sum constructor declarations */
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2libats_2lex_2tables_2edats__tblopt_some) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2libats_2lex_2tables_2edats__tblopt_none) ;

/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_ptr_type ref_01026_ats_ptr_type (ats_ptr_type arg0) ;
static
ats_void_type tbloptref_free_2 (ats_ptr_type arg0) ;
static
ats_ptr_type __ats_fun_5 (ats_int_type env0, ats_int_type env1, ats_ptr_type arg0) ;
static
ats_clo_ptr_type __ats_fun_5_closure_make (ats_int_type env0, ats_int_type env1) ;
static
ats_ptr_type __ats_fun_5_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) ;
static
ats_clo_ptr_type __ats_fun_4 (ats_int_type env0, ats_int_type arg0) ;
static
ats_clo_ptr_type __ats_fun_4_closure_make (ats_int_type env0) ;
static
ats_clo_ptr_type __ats_fun_4_clofun (ats_clo_ptr_type cloptr, ats_int_type arg0) ;
static
ats_ptr_type __ats_fun_9 (ats_int_type env0, ats_ptr_type arg0) ;
static
ats_clo_ptr_type __ats_fun_9_closure_make (ats_int_type env0) ;
static
ats_ptr_type __ats_fun_9_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/chris/ats-lang-anairiats-0.2.6/prelude/DATS/reference.dats: 1828(line=57, offs=18) -- 1902(line=59, offs=4)
*/
ATSstaticdec()
ats_ptr_type
ref_01026_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;

__ats_lab_ref_01026_ats_ptr_type:
/* ats_ptr_type tmp3 ; */
tmp3 = arg0 ;
tmp2 = atspre_ref_make_elt_tsz ((&tmp3), sizeof(ats_ptr_type)) ;
return (tmp2) ;
} /* end of [ref_01026_ats_ptr_type] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/lex/tables.dats: 2010(line=62, offs=30) -- 2094(line=64, offs=4)
*/
ATSglobaldec()
ats_ptr_type
new_tbloptref_some (ats_ptr_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp0) ;
ATSlocal (ats_ptr_type, tmp1) ;

__ats_lab_new_tbloptref_some:
tmp1 = ATS_MALLOC(sizeof(anairiats_sum_0)) ;
ats_selptrset_mac(anairiats_sum_0, tmp1, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_0, tmp1, atslab_1, arg1) ;
tmp0 = ref_01026_ats_ptr_type (tmp1) ;
return (tmp0) ;
} /* end of [new_tbloptref_some] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/lex/tables.dats: 2465(line=86, offs=4) -- 2783(line=95, offs=4)
*/
ATSstaticdec()
ats_void_type
tbloptref_free_2 (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp4) ;
ATSlocal (ats_ptr_type, tmp5) ;
ATSlocal (ats_ptr_type, tmp6) ;
ATSlocal (ats_ptr_type, tmp7) ;
// ATSlocal_void (tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;

__ats_lab_tbloptref_free_2:
tmp5 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, arg0), atslab_1) ;
tmp6 = ats_ptrget_mac(ats_ptr_type, tmp5) ;
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (tmp6 == (ats_sum_ptr_type)0) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp7 = ats_caselptr_mac(anairiats_sum_0, tmp6, atslab_0) ;
ATS_FREE(tmp6) ;
/* tmp8 = */ table_ptr_free (tmp7) ;
tmp9 = (ats_sum_ptr_type)0 ;
ats_ptrget_mac(ats_ptr_type, tmp5) = tmp9 ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
// if (tmp6 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_1_1:
break ;
} while (0) ;
return /* (tmp4) */ ;
} /* end of [tbloptref_free_2] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/lex/tables.dats: 3106(line=110, offs=15) -- 3154(line=110, offs=63)
*/
ATSstaticdec()
ats_ptr_type
__ats_fun_5 (ats_int_type env0, ats_int_type env1, ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp12) ;

__ats_lab___ats_fun_5:
tmp12 = __accept_table_make_fun (env0, env1, arg0) ;
return (tmp12) ;
} /* end of [__ats_fun_5] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_int_type closure_env_0 ;
ats_int_type closure_env_1 ;
} __ats_fun_5_closure_type ;

ats_ptr_type
__ats_fun_5_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) {
return __ats_fun_5 (((__ats_fun_5_closure_type*)cloptr)->closure_env_0, ((__ats_fun_5_closure_type*)cloptr)->closure_env_1, arg0) ;
} /* end of function */

ATSinline()
ats_void_type
__ats_fun_5_closure_init (__ats_fun_5_closure_type *p_clo, ats_int_type env0, ats_int_type env1) {
p_clo->closure_fun = (ats_fun_ptr_type)&__ats_fun_5_clofun ;
p_clo->closure_env_0 = env0 ;
p_clo->closure_env_1 = env1 ;
return ;
} /* end of function */

ats_clo_ptr_type
__ats_fun_5_closure_make (ats_int_type env0, ats_int_type env1) {
__ats_fun_5_closure_type *p_clo = ATS_MALLOC(sizeof(__ats_fun_5_closure_type)) ;
__ats_fun_5_closure_init (p_clo, env0, env1) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/lex/tables.dats: 3094(line=110, offs=3) -- 3154(line=110, offs=63)
*/
ATSstaticdec()
ats_clo_ptr_type
__ats_fun_4 (ats_int_type env0, ats_int_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp11) ;

__ats_lab___ats_fun_4:
tmp11 = __ats_fun_5_closure_make (env0, arg0) ;
return (tmp11) ;
} /* end of [__ats_fun_4] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_int_type closure_env_0 ;
} __ats_fun_4_closure_type ;

ats_clo_ptr_type
__ats_fun_4_clofun (ats_clo_ptr_type cloptr, ats_int_type arg0) {
return __ats_fun_4 (((__ats_fun_4_closure_type*)cloptr)->closure_env_0, arg0) ;
} /* end of function */

ATSinline()
ats_void_type
__ats_fun_4_closure_init (__ats_fun_4_closure_type *p_clo, ats_int_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&__ats_fun_4_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

ats_clo_ptr_type
__ats_fun_4_closure_make (ats_int_type env0) {
__ats_fun_4_closure_type *p_clo = ATS_MALLOC(sizeof(__ats_fun_4_closure_type)) ;
__ats_fun_4_closure_init (p_clo, env0) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/lex/tables.dats: 3083(line=109, offs=21) -- 3154(line=110, offs=63)
*/
ATSglobaldec()
ats_clo_ptr_type
ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats____accept_table_make (ats_int_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp10) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats____accept_table_make:
tmp10 = __ats_fun_4_closure_make (arg0) ;
return (tmp10) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats____accept_table_make] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/lex/tables.dats: 3223(line=114, offs=21) -- 3265(line=114, offs=63)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats____accept_table_free (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp13) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats____accept_table_free:
/* tmp13 = */ tbloptref_free_2 (arg0) ;
return /* (tmp13) */ ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats____accept_table_free] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/lex/tables.dats: 3540(line=133, offs=3) -- 4625(line=167, offs=4)
*/
ATSglobaldec()
ats_int_type
ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats__accept_table_get (ats_ptr_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp14) ;
ATSlocal (ats_int_type, tmp15) ;
ATSlocal (ats_int_type, tmp16) ;
ATSlocal (ats_ptr_type, tmp17) ;
ATSlocal (ats_ptr_type, tmp19) ;
ATSlocal (ats_ptr_type, tmp20) ;
ATSlocal (ats_int_type, tmp21) ;
ATSlocal (ats_bool_type, tmp22) ;
ATSlocal (ats_bool_type, tmp23) ;
ATSlocal (ats_int_type, tmp24) ;
ATSlocal (ats_int16_type, tmp25) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats__accept_table_get:
/* ats_int_type tmp15 ; */
tmp15 = 0 ;
/* ats_int_type tmp16 ; */
tmp16 = 0 ;
tmp17 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, arg0), atslab_1) ;
tmp19 = ats_ptrget_mac(ats_ptr_type, tmp17) ;
do {
/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (tmp19 != (ats_sum_ptr_type)0) { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
tmp16 = 1 ;
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
// if (tmp19 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_3_1:
tmp20 = ats_caselptr_mac(anairiats_sum_0, tmp19, atslab_0) ;
tmp21 = ats_caselptr_mac(anairiats_sum_0, tmp19, atslab_1) ;
tmp22 = atspre_ilt (ats_castfn_mac(ats_int_type, arg1), 0) ;
if (tmp22) {
tmp16 = 2 ;
} else {
tmp23 = atspre_igte (ats_castfn_mac(ats_int_type, arg1), tmp21) ;
if (tmp23) {
tmp16 = 3 ;
} else {
tmp25 = ats_caselind_mac(ats_int16_type, tmp20, [ats_castfn_mac(ats_int_type, arg1)]) ;
tmp24 = ats_int_of_int16 (tmp25) ;
tmp15 = tmp24 ;
} /* end of [if] */
} /* end of [if] */
break ;
} while (0) ;
do {
/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (tmp16 != 1) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
/* tmp14 = */ ats_exit_errmsg (1, ATSstrcst("lexing: accept_table_get: table is not available\n")) ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
if (tmp16 != 2) { goto __ats_lab_6_0 ; }
__ats_lab_5_1:
/* tmp14 = */ ats_exit_errmsg (1, ATSstrcst("lexing: accept_table_get: state number is illegal\n")) ;
break ;

/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (tmp16 != 3) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
/* tmp14 = */ ats_exit_errmsg (1, ATSstrcst("lexing: accept_table_get: state number is illegal\n")) ;
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
__ats_lab_7_1:
tmp14 = tmp15 ;
break ;
} while (0) ;
return (tmp14) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats__accept_table_get] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/lex/tables.dats: 5066(line=185, offs=3) -- 5109(line=185, offs=46)
*/
ATSstaticdec()
ats_ptr_type
__ats_fun_9 (ats_int_type env0, ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp27) ;

__ats_lab___ats_fun_9:
tmp27 = __transition_table_make_fun (env0, arg0) ;
return (tmp27) ;
} /* end of [__ats_fun_9] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_int_type closure_env_0 ;
} __ats_fun_9_closure_type ;

ats_ptr_type
__ats_fun_9_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) {
return __ats_fun_9 (((__ats_fun_9_closure_type*)cloptr)->closure_env_0, arg0) ;
} /* end of function */

ATSinline()
ats_void_type
__ats_fun_9_closure_init (__ats_fun_9_closure_type *p_clo, ats_int_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&__ats_fun_9_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

ats_clo_ptr_type
__ats_fun_9_closure_make (ats_int_type env0) {
__ats_fun_9_closure_type *p_clo = ATS_MALLOC(sizeof(__ats_fun_9_closure_type)) ;
__ats_fun_9_closure_init (p_clo, env0) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/lex/tables.dats: 5058(line=184, offs=25) -- 5109(line=185, offs=46)
*/
ATSglobaldec()
ats_clo_ptr_type
ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats____transition_table_make (ats_int_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp26) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats____transition_table_make:
tmp26 = __ats_fun_9_closure_make (arg0) ;
return (tmp26) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats____transition_table_make] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/lex/tables.dats: 5145(line=188, offs=25) -- 5182(line=188, offs=62)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats____transition_table_free (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp28) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats____transition_table_free:
/* tmp28 = */ tbloptref_free_2 (arg0) ;
return /* (tmp28) */ ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats____transition_table_free] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/lex/tables.dats: 5216(line=191, offs=22) -- 7134(line=251, offs=4)
*/
ATSglobaldec()
ats_int_type
ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats__transition_table_get (ats_ptr_type arg0, ats_int_type arg1, ats_int_type arg2) {
/* local vardec */
ATSlocal (ats_int_type, tmp29) ;
ATSlocal (ats_int_type, tmp30) ;
ATSlocal (ats_int_type, tmp31) ;
ATSlocal (ats_ptr_type, tmp32) ;
ATSlocal (ats_ptr_type, tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (ats_int_type, tmp36) ;
ATSlocal (ats_int_type, tmp37) ;
ATSlocal (ats_bool_type, tmp38) ;
ATSlocal (ats_int_type, tmp39) ;
ATSlocal (ats_int_type, tmp40) ;
ATSlocal (ats_int_type, tmp41) ;
ATSlocal (ats_int_type, tmp42) ;
ATSlocal (ats_int_type, tmp43) ;
ATSlocal (ats_int_type, tmp44) ;
ATSlocal (ats_int_type, tmp45) ;
ATSlocal (ats_bool_type, tmp46) ;
ATSlocal (ats_bool_type, tmp47) ;
ATSlocal (ats_int_type, tmp48) ;
ATSlocal (ats_int16_type, tmp49) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats__transition_table_get:
/* ats_int_type tmp30 ; */
tmp30 = 0 ;
/* ats_int_type tmp31 ; */
tmp31 = 0 ;
tmp32 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, arg0), atslab_1) ;
tmp34 = ats_ptrget_mac(ats_ptr_type, tmp32) ;
do {
/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (tmp34 != (ats_sum_ptr_type)0) { goto __ats_lab_9_0 ; }
__ats_lab_8_1:
tmp31 = 1 ;
break ;

/* branch: __ats_lab_9 */
__ats_lab_9_0:
// if (tmp34 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_9_1:
tmp35 = ats_caselptr_mac(anairiats_sum_0, tmp34, atslab_0) ;
tmp36 = ats_caselptr_mac(anairiats_sum_0, tmp34, atslab_1) ;
tmp39 = atspre_asl_int_int1 (1, 7) ;
tmp38 = atspre_lt_int_int (arg2, tmp39) ;
if (tmp38) {
tmp37 = arg2 ;
} else {
tmp37 = 0 ;
} /* end of [if] */
tmp40 = atspre_add_int_int (tmp37, 1) ;
tmp43 = atspre_sub_int_int (arg1, 1) ;
tmp45 = atspre_asl_int_int1 (1, 7) ;
tmp44 = atspre_add_int_int (tmp45, 1) ;
tmp42 = atspre_mul_int_int (tmp43, tmp44) ;
tmp41 = atspre_add_int_int (tmp42, tmp40) ;
tmp46 = atspre_ilt (ats_castfn_mac(ats_int_type, tmp41), 0) ;
if (tmp46) {
tmp31 = 2 ;
} else {
tmp47 = atspre_igte (ats_castfn_mac(ats_int_type, tmp41), tmp36) ;
if (tmp47) {
tmp31 = 3 ;
} else {
tmp49 = ats_caselind_mac(ats_int16_type, tmp35, [ats_castfn_mac(ats_int_type, tmp41)]) ;
tmp48 = ats_int_of_int16 (tmp49) ;
tmp30 = tmp48 ;
} /* end of [if] */
} /* end of [if] */
break ;
} while (0) ;
do {
/* branch: __ats_lab_10 */
__ats_lab_10_0:
if (tmp31 != 1) { goto __ats_lab_11_0 ; }
__ats_lab_10_1:
/* tmp29 = */ ats_exit_errmsg (1, ATSstrcst("lexing: transition_table_get: table is not available\n")) ;
break ;

/* branch: __ats_lab_11 */
__ats_lab_11_0:
if (tmp31 != 2) { goto __ats_lab_12_0 ; }
__ats_lab_11_1:
/* tmp29 = */ ats_exit_errmsg (1, ATSstrcst("lexing: transition_table_get: state number is illegal\n")) ;
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
if (tmp31 != 3) { goto __ats_lab_13_0 ; }
__ats_lab_12_1:
/* tmp29 = */ ats_exit_errmsg (1, ATSstrcst("lexing: transition_table_get: state number is illegal\n")) ;
break ;

/* branch: __ats_lab_13 */
__ats_lab_13_0:
__ats_lab_13_1:
tmp29 = tmp30 ;
break ;
} while (0) ;
return (tmp29) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats__transition_table_get] */

/* static load function */

extern ats_void_type ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e6_2prelude_2DATS_2reference_2edats__staload (void) ;

ats_void_type
ATS_2d0_2e2_2e6_2libats_2lex_2tables_2edats__staload () {
static int ATS_2d0_2e2_2e6_2libats_2lex_2tables_2edats__staload_flag = 0 ;
if (ATS_2d0_2e2_2e6_2libats_2lex_2tables_2edats__staload_flag) return ;
ATS_2d0_2e2_2e6_2libats_2lex_2tables_2edats__staload_flag = 1 ;

ATS_2d0_2e2_2e6_2libats_2lex_2lexing_2esats__staload () ;
ATS_2d0_2e2_2e6_2prelude_2DATS_2reference_2edats__staload () ;

// ATS_2d0_2e2_2e6_2libats_2lex_2tables_2edats__tblopt_some.tag = 0 ;
ATS_2d0_2e2_2e6_2libats_2lex_2tables_2edats__tblopt_none.tag = 1 ;
return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
// extern ats_int_type ATS_2d0_2e2_2e6_2libats_2lex_2tables_2edats__dynload_flag ;

ats_void_type
ATS_2d0_2e2_2e6_2libats_2lex_2tables_2edats__dynload () {
// ATS_2d0_2e2_2e6_2libats_2lex_2tables_2edats__dynload_flag = 1 ;
ATS_2d0_2e2_2e6_2libats_2lex_2tables_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */


#define NBITS_PER_BYTE 8
#define NUMBER_OF_CHARS ((1 << NBITS_PER_BYTE - 1) + 1)

extern void *malloc (size_t bsz) ;
extern void *calloc (size_t n, size_t tsz) ;

ats_ptr_type
__accept_table_make_fun (
  ats_int_type ntot, ats_int_type nfin, ats_ptr_type s0
) {
  int i, nstate, irule, sz ;
  ats_int16_type *p0 ; ats_uchar_type *s ; ats_ptr_type res ;
//
  s = (ats_uchar_type*)s0;
/*
// [calloc] is used as only integers are to be stored; thus,
// there is no need to scan the allocated memory during GC;
// the allocated memory is freed by a call to [free]
*/
  sz = ntot + 1 ; p0 = calloc(sz, sizeof(ats_int16_type)) ;  
//
  for (i = 0 ; i < nfin ; ++i) {
    nstate = (s[0] << NBITS_PER_BYTE) + s[1] ;
    s += 2 ;
    p0[nstate] = (s[0] << NBITS_PER_BYTE) + s[1] ;
    s += 2 ; 
/*
    fprintf (stdout, "%i -> %i\n", nstate, p0[nstate]) ;
*/
  } /* end of [for] */
//
  res = new_tbloptref_some (p0, sz) ;
//
/*
  fprintf (stdout, "__accept_table_make_fun: sz = %i\n", sz);
  fprintf (stdout, "__accept_table_make_fun: ptr = %p\n", p0);
  fprintf (stdout, "__accept_table_make_fun: res = %p\n", res);
*/
  return res ;
} /* end of [__accept_table_make_fun] */

ats_ptr_type
__transition_table_make_fun (ats_int_type n, ats_ptr_type s0) {
  int i, j, c, sz;
  ats_int16_type *p0, *p ; ats_uchar_type *s ;
  ats_ptr_type res ;
//
  sz = n * NUMBER_OF_CHARS ;
/*
// [malloc] is used to allocate memory for storing integers;
// thus, there is no need to scan the allocated memory during GC;
// the allocated memory is freed by a call to [free]
*/
  p0 = malloc (sz*sizeof(ats_int16_type)) ; p = p0 ;
//
  s = (ats_uchar_type*)s0;
//
  for (i = 0 ; i < n ; ++i) {
    for (j = 0 ; j < NUMBER_OF_CHARS ; ++j) {
      *p = (s[0] << NBITS_PER_BYTE) + s[1] ;
/*
      fprintf (stdout, "__transition_table_make_fun: %i: *p = %i\n", j, *p);
*/
      s += 2 ; ++p ;
    } /* end of [for] */
  } /* end of [for] */

  res = new_tbloptref_some (p0, sz) ;
/*
  fprintf (stdout, "__transition_table_make_fun: sz = %i\n", sz);
  fprintf (stdout, "__transition_table_make_fun: ptr = %p\n", p0);
  fprintf (stdout, "__transition_table_make_fun: res = %p\n", res);
*/
  return res ;
} /* end of [__transition_table_make_fun] */


/* external codes at bot */

/* ****** ****** */

/* end of [/home/chris/ats-lang-anairiats-0.2.6/ccomp/lib/output/_2fhome_2fchris_2fats_2dlang_2danairiats_2d0_2e2_2e6_2flibats_2flex_2ftables_2edats.c] */
