/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2012-2-20: 21h:28m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/option.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "libc/CATS/gmp.cats"

#include "libats/CATS/intinf.cats"

#include "libc/CATS/gmp.cats"
/* external codes at top */

#include "libc/CATS/gmp.cats"

/* type definitions */
/* external typedefs */
/* external dynamic constructor declarations */
/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_assert_errmsg) (ats_bool_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_stdout_get) () ;
ATSextern_fun(ats_void_type, atspre_stdout_view_set) () ;
ATSextern_fun(ats_double_type, atspre_double_of_llint) (ats_llint_type) ;
ATSextern_fun(ats_ulint_type, atspre_ulint_of_int) (ats_int_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size_int) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_void_type, atslib_mpz_init_set_str_exn) (ats_ref_type, ats_ptr_type, ats_int_type) ;
ATSextern_fun(ats_void_type, atslib_mpz_mul2_mpz) (ats_ref_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinfptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__fprint_intinf) (ats_ref_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__fprint_intinf_base) (ats_ref_type, ats_int_type, ats_ref_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e6_2prelude_2basics_dyn_2esats__file_mode_lte_w_w_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e6_2libats_2DATS_2intinf_2edats__lemma_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e6_2libats_2DATS_2intinf_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 1839(line=57, offs=21) -- 1980(line=62, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinf_make_int (ats_int_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp0) ;
ATSlocal (ats_ptr_type, tmp1) ;
ATSlocal (ats_ptr_type, tmp2) ;
// ATSlocal_void (tmp3) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinf_make_int:
tmp1 = atspre_ptr_alloc_tsz (sizeof(ats_mpz_viewt0ype)) ;
tmp2 = ats_selsin_mac(tmp1, atslab_2) ;
/* tmp3 = */ atslib_mpz_init_set_int (tmp2, arg0) ;
tmp0 = tmp2 ;
return (tmp0) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinf_make_int] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 2037(line=65, offs=18) -- 2272(line=71, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinf_make_lint (ats_lint_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp4) ;
ATSlocal (ats_ptr_type, tmp5) ;
ATSlocal (ats_ptr_type, tmp6) ;
// ATSlocal_void (tmp7) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinf_make_lint:
tmp5 = atspre_ptr_alloc_tsz (sizeof(ats_mpz_viewt0ype)) ;
tmp6 = ats_selsin_mac(tmp5, atslab_2) ;
/* tmp7 = */ atslib_mpz_init_set_lint (tmp6, ats_castfn_mac(ats_lint_type, arg0)) ;
tmp4 = tmp6 ;
return (tmp4) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinf_make_lint] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 2331(line=74, offs=19) -- 2604(line=81, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinf_make_llint (ats_llint_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_ptr_type, tmp10) ;
ATSlocal (ats_double_type, tmp11) ;
// ATSlocal_void (tmp12) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinf_make_llint:
tmp9 = atspre_ptr_alloc_tsz (sizeof(ats_mpz_viewt0ype)) ;
tmp10 = ats_selsin_mac(tmp9, atslab_2) ;
tmp11 = atspre_double_of_llint (ats_castfn_mac(ats_llint_type, arg0)) ;
/* tmp12 = */ atslib_mpz_init_set_double (tmp10, tmp11) ;
tmp8 = tmp10 ;
return (tmp8) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinf_make_llint] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 2665(line=84, offs=20) -- 2846(line=89, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinf_make_double (ats_double_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp13) ;
ATSlocal (ats_ptr_type, tmp14) ;
ATSlocal (ats_ptr_type, tmp15) ;
// ATSlocal_void (tmp16) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinf_make_double:
tmp14 = atspre_ptr_alloc_tsz (sizeof(ats_mpz_viewt0ype)) ;
tmp15 = ats_selsin_mac(tmp14, atslab_2) ;
/* tmp16 = */ atslib_mpz_init_set_double (tmp15, arg0) ;
tmp13 = tmp15 ;
return (tmp13) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinf_make_double] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 2908(line=92, offs=20) -- 3106(line=97, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinf_make_string (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp17) ;
ATSlocal (ats_ptr_type, tmp18) ;
ATSlocal (ats_ptr_type, tmp19) ;
// ATSlocal_void (tmp20) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinf_make_string:
tmp18 = atspre_ptr_alloc_tsz (sizeof(ats_mpz_viewt0ype)) ;
tmp19 = ats_selsin_mac(tmp18, atslab_2) ;
/* tmp20 = */ atslib_mpz_init_set_str_exn (tmp19, arg0, 10) ;
tmp17 = tmp19 ;
return (tmp17) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinf_make_string] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 3185(line=102, offs=16) -- 3264(line=103, offs=58)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinfptr_free (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp21) ;
// ATSlocal_void (tmp22) ;
// ATSlocal_void (tmp23) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinfptr_free:
tmp21 = ats_selsin_mac(arg0, atslab_2) ;
/* tmp23 = */ atslib_mpz_clear (tmp21) ;
/* tmp22 = */ atspre_ptr_free (tmp21) ;
return /* (tmp22) */ ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinfptr_free] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 3340(line=110, offs=3) -- 3402(line=110, offs=65)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__fprint_intinf (ats_ref_type arg0, ats_ref_type arg1) {
/* local vardec */
// ATSlocal_void (tmp24) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__fprint_intinf:
/* tmp24 = */ ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__fprint_intinf_base (arg0, 10, arg1) ;
return /* (tmp24) */ ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__fprint_intinf] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 3453(line=113, offs=24) -- 3497(line=113, offs=68)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__print_intinf (ats_ref_type arg0) {
/* local vardec */
// ATSlocal_void (tmp25) ;
ATSlocal (ats_ptr_type, tmp26) ;
ATSlocal (ats_ptr_type, tmp27) ;
// ATSlocal_void (tmp28) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__print_intinf:
tmp26 = atspre_stdout_get () ;
tmp27 = ats_selsin_mac(tmp26, atslab_1) ;
/* tmp28 = */ ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__fprint_intinf (tmp27, arg0) ;
/* tmp25 = */ atspre_stdout_view_set () ;
return /* (tmp25) */ ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__print_intinf] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 3530(line=117, offs=3) -- 3694(line=120, offs=2)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__fprint_intinf_base (ats_ref_type arg0, ats_int_type arg1, ats_ref_type arg2) {
/* local vardec */
// ATSlocal_void (tmp29) ;
ATSlocal (ats_size_type, tmp30) ;
ATSlocal (ats_bool_type, tmp31) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__fprint_intinf_base:
tmp30 = atslib_mpz_out_str (arg0, arg1, arg2) ;
tmp31 = atspre_gt_size_int (tmp30, 0) ;
/* tmp29 = */ atspre_assert_errmsg (tmp31, ATSstrcst("exit(ATS): [fprint_intinf_base] failed.\n")) ;
return /* (tmp29) */ ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__fprint_intinf_base] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 3755(line=123, offs=19) -- 3968(line=130, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__print_intinf_base (ats_int_type arg0, ats_ref_type arg1) {
/* local vardec */
// ATSlocal_void (tmp32) ;
ATSlocal (ats_ptr_type, tmp33) ;
ATSlocal (ats_ptr_type, tmp34) ;
// ATSlocal_void (tmp35) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__print_intinf_base:
tmp33 = atspre_stdout_get () ;
tmp34 = ats_selsin_mac(tmp33, atslab_1) ;
/* tmp35 = */ ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__fprint_intinf_base (tmp34, arg0, arg1) ;
/* tmp32 = */ atspre_stdout_view_set () ;
return /* (tmp32) */ ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__print_intinf_base] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 4043(line=135, offs=13) -- 4213(line=140, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__pred_intinf (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp36) ;
ATSlocal (ats_ptr_type, tmp37) ;
ATSlocal (ats_ptr_type, tmp38) ;
// ATSlocal_void (tmp39) ;
// ATSlocal_void (tmp40) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__pred_intinf:
tmp37 = atspre_ptr_alloc_tsz (sizeof(ats_mpz_viewt0ype)) ;
tmp38 = ats_selsin_mac(tmp37, atslab_2) ;
/* tmp39 = */ atslib_mpz_init (tmp38) ;
/* tmp40 = */ atslib_mpz_sub3_int (tmp38, arg0, 1) ;
tmp36 = tmp38 ;
return (tmp36) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__pred_intinf] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 4261(line=143, offs=13) -- 4431(line=148, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__succ_intinf (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp41) ;
ATSlocal (ats_ptr_type, tmp42) ;
ATSlocal (ats_ptr_type, tmp43) ;
// ATSlocal_void (tmp44) ;
// ATSlocal_void (tmp45) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__succ_intinf:
tmp42 = atspre_ptr_alloc_tsz (sizeof(ats_mpz_viewt0ype)) ;
tmp43 = ats_selsin_mac(tmp42, atslab_2) ;
/* tmp44 = */ atslib_mpz_init (tmp43) ;
/* tmp45 = */ atslib_mpz_add3_int (tmp43, arg0, 1) ;
tmp41 = tmp43 ;
return (tmp41) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__succ_intinf] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 4503(line=153, offs=16) -- 4676(line=158, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__add_intinf_int (ats_ref_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp46) ;
ATSlocal (ats_ptr_type, tmp47) ;
ATSlocal (ats_ptr_type, tmp48) ;
// ATSlocal_void (tmp49) ;
// ATSlocal_void (tmp50) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__add_intinf_int:
tmp47 = atspre_ptr_alloc_tsz (sizeof(ats_mpz_viewt0ype)) ;
tmp48 = ats_selsin_mac(tmp47, atslab_2) ;
/* tmp49 = */ atslib_mpz_init (tmp48) ;
/* tmp50 = */ atslib_mpz_add3_int (tmp48, arg0, arg1) ;
tmp46 = tmp48 ;
return (tmp46) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__add_intinf_int] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 4733(line=161, offs=19) -- 4920(line=166, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__add_intinf_intinf (ats_ref_type arg0, ats_ref_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp51) ;
ATSlocal (ats_ptr_type, tmp52) ;
ATSlocal (ats_ptr_type, tmp53) ;
// ATSlocal_void (tmp54) ;
// ATSlocal_void (tmp55) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__add_intinf_intinf:
tmp52 = atspre_ptr_alloc_tsz (sizeof(ats_mpz_viewt0ype)) ;
tmp53 = ats_selsin_mac(tmp52, atslab_2) ;
/* tmp54 = */ atslib_mpz_init (tmp53) ;
/* tmp55 = */ atslib_mpz_add3_mpz (tmp53, arg0, arg1) ;
tmp51 = tmp53 ;
return (tmp51) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__add_intinf_intinf] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 4998(line=171, offs=16) -- 5171(line=176, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__sub_intinf_int (ats_ref_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp56) ;
ATSlocal (ats_ptr_type, tmp57) ;
ATSlocal (ats_ptr_type, tmp58) ;
// ATSlocal_void (tmp59) ;
// ATSlocal_void (tmp60) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__sub_intinf_int:
tmp57 = atspre_ptr_alloc_tsz (sizeof(ats_mpz_viewt0ype)) ;
tmp58 = ats_selsin_mac(tmp57, atslab_2) ;
/* tmp59 = */ atslib_mpz_init (tmp58) ;
/* tmp60 = */ atslib_mpz_sub3_int (tmp58, arg0, arg1) ;
tmp56 = tmp58 ;
return (tmp56) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__sub_intinf_int] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 5228(line=179, offs=19) -- 5415(line=184, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__sub_intinf_intinf (ats_ref_type arg0, ats_ref_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp61) ;
ATSlocal (ats_ptr_type, tmp62) ;
ATSlocal (ats_ptr_type, tmp63) ;
// ATSlocal_void (tmp64) ;
// ATSlocal_void (tmp65) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__sub_intinf_intinf:
tmp62 = atspre_ptr_alloc_tsz (sizeof(ats_mpz_viewt0ype)) ;
tmp63 = ats_selsin_mac(tmp62, atslab_2) ;
/* tmp64 = */ atslib_mpz_init (tmp63) ;
/* tmp65 = */ atslib_mpz_sub3_mpz (tmp63, arg0, arg1) ;
tmp61 = tmp63 ;
return (tmp61) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__sub_intinf_intinf] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 5499(line=189, offs=22) -- 5723(line=195, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__mul_int_intinf (ats_int_type arg0, ats_ref_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp66) ;
ATSlocal (ats_ptr_type, tmp67) ;
ATSlocal (ats_ptr_type, tmp68) ;
// ATSlocal_void (tmp69) ;
// ATSlocal_void (tmp70) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__mul_int_intinf:
tmp67 = atspre_ptr_alloc_tsz (sizeof(ats_mpz_viewt0ype)) ;
tmp68 = ats_selsin_mac(tmp67, atslab_2) ;
/* tmp69 = */ atslib_mpz_init (tmp68) ;
/* tmp70 = */ atslib_mpz_mul3_int (tmp68, arg1, arg0) ;
tmp66 = tmp68 ;
return (tmp66) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__mul_int_intinf] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 5783(line=198, offs=22) -- 6007(line=204, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__mul_intinf_int (ats_ref_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp71) ;
ATSlocal (ats_ptr_type, tmp72) ;
ATSlocal (ats_ptr_type, tmp73) ;
// ATSlocal_void (tmp74) ;
// ATSlocal_void (tmp75) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__mul_intinf_int:
tmp72 = atspre_ptr_alloc_tsz (sizeof(ats_mpz_viewt0ype)) ;
tmp73 = ats_selsin_mac(tmp72, atslab_2) ;
/* tmp74 = */ atslib_mpz_init (tmp73) ;
/* tmp75 = */ atslib_mpz_mul3_int (tmp73, arg0, arg1) ;
tmp71 = tmp73 ;
return (tmp71) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__mul_intinf_int] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 6070(line=207, offs=25) -- 6304(line=213, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__mul_intinf_intinf (ats_ref_type arg0, ats_ref_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp76) ;
ATSlocal (ats_ptr_type, tmp77) ;
ATSlocal (ats_ptr_type, tmp78) ;
// ATSlocal_void (tmp79) ;
// ATSlocal_void (tmp80) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__mul_intinf_intinf:
tmp77 = atspre_ptr_alloc_tsz (sizeof(ats_mpz_viewt0ype)) ;
tmp78 = ats_selsin_mac(tmp77, atslab_2) ;
/* tmp79 = */ atslib_mpz_init (tmp78) ;
/* tmp80 = */ atslib_mpz_mul3_mpz (tmp78, arg0, arg1) ;
tmp76 = tmp78 ;
return (tmp76) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__mul_intinf_intinf] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 6385(line=218, offs=19) -- 6615(line=225, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__square_intinf (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp81) ;
ATSlocal (ats_ptr_type, tmp82) ;
ATSlocal (ats_ptr_type, tmp83) ;
// ATSlocal_void (tmp84) ;
// ATSlocal_void (tmp85) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__square_intinf:
tmp82 = atspre_ptr_alloc_tsz (sizeof(ats_mpz_viewt0ype)) ;
tmp83 = ats_selsin_mac(tmp82, atslab_2) ;
/* tmp84 = */ atslib_mpz_init_set_mpz (tmp83, arg0) ;
/* tmp85 = */ atslib_mpz_mul2_mpz (tmp83, arg0) ;
tmp81 = tmp83 ;
return (tmp81) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__square_intinf] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 6696(line=230, offs=23) -- 7068(line=239, offs=4)
*/
ATSglobaldec()
ats_ptr_type
atslib_fdiv_intinf_int (ats_ref_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp86) ;
ATSlocal (ats_ptr_type, tmp87) ;
ATSlocal (ats_ptr_type, tmp88) ;
// ATSlocal_void (tmp89) ;
ATSlocal (ats_ulint_type, tmp90) ;
ATSlocal (ats_ulint_type, tmp91) ;

__ats_lab_atslib_fdiv_intinf_int:
tmp87 = atspre_ptr_alloc_tsz (sizeof(ats_mpz_viewt0ype)) ;
tmp88 = ats_selsin_mac(tmp87, atslab_2) ;
/* tmp89 = */ atslib_mpz_init (tmp88) ;
tmp90 = atspre_ulint_of_int (arg1) ;
tmp91 = atslib_mpz_fdiv3_q_ulint (tmp88, arg0, tmp90) ;
tmp86 = tmp88 ;
return (tmp86) ;
} /* end of [atslib_fdiv_intinf_int] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/intinf.dats: 7130(line=242, offs=23) -- 7703(line=257, offs=4)
*/
ATSglobaldec()
ats_int_type
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__fmod_intinf_int (ats_ref_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp92) ;
ATSlocal (ats_ptr_type, tmp93) ;
ATSlocal (ats_ptr_type, tmp94) ;
// ATSlocal_void (tmp95) ;
ATSlocal (ats_ulint_type, tmp96) ;
ATSlocal (ats_ulint_type, tmp97) ;
ATSlocal (ats_int_type, tmp98) ;
// ATSlocal_void (tmp99) ;
ATSlocal (ats_ptr_type, tmp100) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__fmod_intinf_int:
tmp93 = atspre_ptr_alloc_tsz (sizeof(ats_mpz_viewt0ype)) ;
tmp94 = ats_selsin_mac(tmp93, atslab_2) ;
/* tmp95 = */ atslib_mpz_init (tmp94) ;
tmp96 = atspre_ulint_of_int (arg1) ;
tmp97 = atslib_mpz_mod3_ulint (tmp94, arg0, tmp96) ;
tmp98 = atslib_mpz_get_int (tmp94) ;
tmp100 = tmp94 ;
/* tmp99 = */ ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__intinfptr_free (tmp100) ;
tmp92 = ats_castfn_mac(ats_int_type, tmp98) ;
return (tmp92) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__fmod_intinf_int] */

/* static load function */

extern ats_void_type ATS_2d0_2e2_2e6_2libc_2SATS_2gmp_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__staload (void) ;

ats_void_type
ATS_2d0_2e2_2e6_2libats_2DATS_2intinf_2edats__staload () {
static int ATS_2d0_2e2_2e6_2libats_2DATS_2intinf_2edats__staload_flag = 0 ;
if (ATS_2d0_2e2_2e6_2libats_2DATS_2intinf_2edats__staload_flag) return ;
ATS_2d0_2e2_2e6_2libats_2DATS_2intinf_2edats__staload_flag = 1 ;

ATS_2d0_2e2_2e6_2libc_2SATS_2gmp_2esats__staload () ;
ATS_2d0_2e2_2e6_2libats_2SATS_2intinf_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type ATS_2d0_2e2_2e6_2libats_2DATS_2intinf_2edats__dynload_flag ;

ats_void_type
ATS_2d0_2e2_2e6_2libats_2DATS_2intinf_2edats__dynload () {
ATS_2d0_2e2_2e6_2libats_2DATS_2intinf_2edats__dynload_flag = 1 ;
ATS_2d0_2e2_2e6_2libats_2DATS_2intinf_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e6_2prelude_2basics_dyn_2esats__file_mode_lte_w_w_prfck () ;
ATS_2d0_2e2_2e6_2libats_2DATS_2intinf_2edats__lemma_prfck () ;
ATS_2d0_2e2_2e6_2libats_2DATS_2intinf_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [/home/chris/ats-lang-anairiats-0.2.6/ccomp/lib/output/_2fhome_2fchris_2fats_2dlang_2danairiats_2d0_2e2_2e6_2flibats_2fDATS_2fintinf_2edats.c] */
