/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2012-2-20: 21h:24m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* prologues from statically loaded files */
/* external codes at top */
/* type definitions */
/* external typedefs */
/* sum constructor declarations */
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__unit) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__box) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__box_vt) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__list0_cons) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__list0_nil) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__list_cons) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__list_nil) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__option0_some) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__option0_none) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__None) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__Some) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__list_vt_cons) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__list_vt_nil) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__None_vt) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__Some_vt) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__stream_nil) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__stream_cons) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__stream_vt_nil) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__stream_vt_cons) ;

/* exn constructor declarations */
/* static load function */

ats_void_type
ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__staload () {
static int ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__staload_flag = 0 ;
if (ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__staload_flag) return ;
ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__staload_flag = 1 ;

ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__unit.tag = 0 ;
// ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__box.tag = 0 ;
// ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__box_vt.tag = 0 ;
// ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__list0_cons.tag = 0 ;
ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__list0_nil.tag = 1 ;
// ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__list_cons.tag = 0 ;
ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__list_nil.tag = 1 ;
// ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__option0_some.tag = 0 ;
ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__option0_none.tag = 1 ;
ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__None.tag = 0 ;
// ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__Some.tag = 1 ;
// ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__list_vt_cons.tag = 0 ;
ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__list_vt_nil.tag = 1 ;
ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__None_vt.tag = 0 ;
// ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__Some_vt.tag = 1 ;
ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__stream_nil.tag = 0 ;
// ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__stream_cons.tag = 1 ;
ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__stream_vt_nil.tag = 0 ;
// ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__stream_vt_cons.tag = 1 ;
return ;
} /* staload function */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [/home/chris/ats-lang-anairiats-0.2.6/ccomp/lib/output/_2fhome_2fchris_2fats_2dlang_2danairiats_2d0_2e2_2e6_2fprelude_2fbasics_5fsta_2esats.c] */
