/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2012-2-20: 21h:29m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/option.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "libats/CATS/linbitvec.cats"
/* external codes at top */

//
// declared in [string.h]
//
#ifndef memset
extern void *memset (void *buf, int chr, size_t n) ;
#endif
//
ats_ptr_type
atslib_linbitvec_bitvec_make
  (ats_size_type nbit) {
  uintptr_t *p_vec ; size_t nwrd ;
  nwrd = (nbit + NBIT_PER_WORD - 1) >> NBIT_PER_WORD_LOG ;
  p_vec = ATS_CALLOC (nwrd, NBYTE_PER_WORD) ; // initialized to zero
  return p_vec ;
} // end of [atslib_linbitvec_bitvec_make]
//
ats_ptr_type // HX: same as [atslib_linbitvec_bitvec_make] for now
atslib_linbitvec_bitvec_make_nil
  (ats_size_type nbit) {
  uintptr_t *p_vec ; size_t nwrd ;
  nwrd = (nbit + NBIT_PER_WORD - 1) >> NBIT_PER_WORD_LOG ;
  p_vec = ATS_CALLOC (nwrd, NBYTE_PER_WORD) ; // initialized to zero
  return p_vec ;
} // end of [atslib_linbitvec_bitvec_make_nil]
//
ats_ptr_type
atslib_linbitvec_bitvec_make_all
  (ats_size_type nbit) {
  uintptr_t *p_vec, zc; size_t nwrd ; int next ;
  nwrd = (nbit + NBIT_PER_WORD - 1) >> NBIT_PER_WORD_LOG ;
  next = (nwrd << NBIT_PER_WORD_LOG) - nbit ; // extra bits
  p_vec = ATS_CALLOC (nwrd, NBYTE_PER_WORD) ; // initialized to zero
  memset (p_vec, 0xFF, nwrd * NBYTE_PER_WORD) ;
/*
** extra bits, which are in the front, must be set to zero!!!
*/
  if (nwrd > 0) { zc = ~0; p_vec[nwrd-1] &= (zc >> next) ; }
  return p_vec ;
} // end of [atslib_linbitvec_bitvec_make_all]
//
ats_void_type
atslib_linbitvec_bitvec_free
  (ats_ptr_type p_vec) { ATS_FREE (p_vec) ; return ; }
// end of [atslib_linbitvec_bitvec_free]
//

//
ats_bool_type
atslib_linbitvec_bitvec_is_nil (
  ats_ptr_type p0, ats_size_type nbit
) {
  int nwrd = (nbit + NBIT_PER_WORD - 1) >> NBIT_PER_WORD_LOG ;
  uintptr_t *p = p0 ;
  if (!nwrd) return ats_true_bool ;
  if (*p != 0) return ats_false_bool ;
  while (--nwrd > 0) { if (*++p != 0) return ats_false_bool ; }
  return ats_true_bool ;
} // end of [atslib_linbitvec_bitvec_is_nil]
//
ats_bool_type
atslib_linbitvec_bitvec_is_all (
  ats_ptr_type p0, ats_size_type nbit
) {
  int nwrd = (nbit + NBIT_PER_WORD - 1) >> NBIT_PER_WORD_LOG ;
  int next = (nwrd << NBIT_PER_WORD_LOG) - nbit ; // extra bits
  uintptr_t *p = p0, zc = ~0 ;
  while (nwrd > 1) {
    if (*p != zc) return ats_false_bool ; --nwrd ; ++p ;
  } ;
/*
** extra bits, which are in the front, must be zero!!!
*/
  if (nwrd) { if (*p != (zc >> next)) return ats_false_bool ; } ;
  return ats_true_bool ;  
} // end of [atslib_linbitvec_bitvec_is_all]
//

//
ats_bool_type
atslib_linbitvec_bitvec_equal (
  ats_ptr_type p10, ats_ptr_type p20, ats_size_type nbit
) {
  int nwrd = (nbit + NBIT_PER_WORD - 1) >> NBIT_PER_WORD_LOG ;
  uintptr_t *p1 = p10, *p2 = p20 ;
  if (!nwrd) return ats_true_bool ;
  if (*p1 != *p2) return ats_false_bool ;
  while (--nwrd > 0) { if (*++p1 != *++p2) return ats_false_bool ; } ;
  return ats_true_bool ;  
} // end of [atslib_linbitvec_bitvec_copy]
//

//
ats_void_type
atslib_linbitvec_bitvec_copy (
  ats_ptr_type p10, ats_ptr_type p20, ats_size_type nbit
) {
  int nwrd = (nbit + NBIT_PER_WORD - 1) >> NBIT_PER_WORD_LOG ;
  uintptr_t *p1 = p10, *p2 = p20 ;
  if (!nwrd) return ;
  *p1 = *p2 ; while (--nwrd > 0) { *(++p1) = *(++p2) ; }
  return ;  
} // end of [atslib_linbitvec_bitvec_copy]
//

//
ats_void_type
atslib_linbitvec_bitvec_neg (
  ats_ptr_type p0, ats_size_type nbit
) {
  int nwrd = (nbit + NBIT_PER_WORD - 1) >> NBIT_PER_WORD_LOG ;
  int next = (nwrd << NBIT_PER_WORD_LOG) - nbit ; // extra bits
  uintptr_t *p = p0, zc = ~0 ;
  while (nwrd > 1) {
    *p = ~(*p) ; --nwrd ; ++p ;
  }
/*
** extra bits, which are in the front, must be set to zero!!!
*/
  if (nwrd > 0) { *p = ~(*p) ; *p &= (zc >> next) ; }
  return ;  
} // end of [atslib_linbitvec_bitvec_neg]
//
ats_void_type
atslib_linbitvec_bitvec_or (
  ats_ptr_type p10, ats_ptr_type p20, ats_size_type nbit
) {
  int nwrd = (nbit + NBIT_PER_WORD - 1) >> NBIT_PER_WORD_LOG ;
  uintptr_t *p1 = p10, *p2 = p20 ;
  if (!nwrd) return ;
  *p1 |= *p2 ; while (--nwrd > 0) { *(++p1) |= *(++p2) ; }
  return ;  
} // end of [atslib_linbitvec_bitvec_or]
//
ats_void_type
atslib_linbitvec_bitvec_and (
  ats_ptr_type p10, ats_ptr_type p20, ats_size_type nbit
) {
  int nwrd = (nbit + NBIT_PER_WORD - 1) >> NBIT_PER_WORD_LOG ;
  uintptr_t *p1 = p10, *p2 = p20 ;
  if (!nwrd) return ;
  *p1 &= *p2 ; while (--nwrd > 0) { *(++p1) &= *(++p2) ; }
  return ;  
} // end of [atslib_linbitvec_bitvec_and]
//
ats_void_type
atslib_linbitvec_bitvec_xor ( // symmetric difference
  ats_ptr_type p10, ats_ptr_type p20, ats_size_type nbit
) {
  int nwrd = (nbit + NBIT_PER_WORD - 1) >> NBIT_PER_WORD_LOG ;
  uintptr_t *p1 = p10, *p2 = p20 ;
  if (!nwrd) return ;
  *p1 ^= *p2 ; while (--nwrd > 0) { *(++p1) ^= *(++p2) ; }
  return ;  
} // end of [atslib_linbitvec_bitvec_xor]
//
ats_void_type
atslib_linbitvec_bitvec_diff ( // difference
  ats_ptr_type p10, ats_ptr_type p20, ats_size_type nbit
) {
  int nwrd = (nbit + NBIT_PER_WORD - 1) >> NBIT_PER_WORD_LOG ;
  uintptr_t *p1 = p10, *p2 = p20 ;
  if (!nwrd) return ;
  *p1 &= ~(*p2) ; while (--nwrd > 0) { *(++p1) &= ~(*(++p2)) ; }
  return ;  
} // end of [atslib_linbitvec_bitvec_diff]
//

/* type definitions */
/* external typedefs */
/* external dynamic constructor declarations */
/* external dynamic constant declarations */
ATSextern_fun(ats_bool_type, atspre_neg_bool) (ats_bool_type) ;
ATSextern_fun(ats_bool_type, atslib_linbitvec_bitvec_is_nil) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atslib_linbitvec_bitvec_is_all) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atslib_linbitvec_bitvec_equal) (ats_ref_type, ats_ref_type, ats_size_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/linbitvec.dats: 1558(line=40, offs=28) -- 1592(line=40, offs=62)
*/
ATSglobaldec()
ats_bool_type
ATS_2d0_2e2_2e6_2libats_2SATS_2linbitvec_2esats__bitvec_isnot_nil (ats_ref_type arg0, ats_size_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp0) ;
ATSlocal (ats_bool_type, tmp1) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2linbitvec_2esats__bitvec_isnot_nil:
tmp1 = atslib_linbitvec_bitvec_is_nil (arg0, arg1) ;
tmp0 = atspre_neg_bool (tmp1) ;
return (tmp0) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2linbitvec_2esats__bitvec_isnot_nil] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/linbitvec.dats: 1620(line=41, offs=28) -- 1654(line=41, offs=62)
*/
ATSglobaldec()
ats_bool_type
ATS_2d0_2e2_2e6_2libats_2SATS_2linbitvec_2esats__bitvec_isnot_all (ats_ref_type arg0, ats_size_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp2) ;
ATSlocal (ats_bool_type, tmp3) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2linbitvec_2esats__bitvec_isnot_all:
tmp3 = atslib_linbitvec_bitvec_is_all (arg0, arg1) ;
tmp2 = atspre_neg_bool (tmp3) ;
return (tmp2) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2linbitvec_2esats__bitvec_isnot_all] */

/*
// /home/chris/ats-lang-anairiats-0.2.6/libats/DATS/linbitvec.dats: 1703(line=45, offs=27) -- 1750(line=45, offs=74)
*/
ATSglobaldec()
ats_bool_type
ATS_2d0_2e2_2e6_2libats_2SATS_2linbitvec_2esats__bitvec_notequal (ats_ref_type arg0, ats_ref_type arg1, ats_size_type arg2) {
/* local vardec */
ATSlocal (ats_bool_type, tmp4) ;
ATSlocal (ats_bool_type, tmp5) ;

__ats_lab_ATS_2d0_2e2_2e6_2libats_2SATS_2linbitvec_2esats__bitvec_notequal:
tmp5 = atslib_linbitvec_bitvec_equal (arg0, arg1, arg2) ;
tmp4 = atspre_neg_bool (tmp5) ;
return (tmp4) ;
} /* end of [ATS_2d0_2e2_2e6_2libats_2SATS_2linbitvec_2esats__bitvec_notequal] */

/* static load function */

// extern ats_void_type ATS_2d0_2e2_2e6_2libats_2SATS_2linbitvec_2esats__staload (void) ;

ats_void_type
ATS_2d0_2e2_2e6_2libats_2DATS_2linbitvec_2edats__staload () {
static int ATS_2d0_2e2_2e6_2libats_2DATS_2linbitvec_2edats__staload_flag = 0 ;
if (ATS_2d0_2e2_2e6_2libats_2DATS_2linbitvec_2edats__staload_flag) return ;
ATS_2d0_2e2_2e6_2libats_2DATS_2linbitvec_2edats__staload_flag = 1 ;

// ATS_2d0_2e2_2e6_2libats_2SATS_2linbitvec_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
// extern ats_int_type ATS_2d0_2e2_2e6_2libats_2DATS_2linbitvec_2edats__dynload_flag ;

ats_void_type
ATS_2d0_2e2_2e6_2libats_2DATS_2linbitvec_2edats__dynload () {
// ATS_2d0_2e2_2e6_2libats_2DATS_2linbitvec_2edats__dynload_flag = 1 ;
ATS_2d0_2e2_2e6_2libats_2DATS_2linbitvec_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [/home/chris/ats-lang-anairiats-0.2.6/ccomp/lib/output/_2fhome_2fchris_2fats_2dlang_2danairiats_2d0_2e2_2e6_2flibats_2fDATS_2flinbitvec_2edats.c] */
