// File: CORBA_ORB_init.idl
// CORBA 3.0, Chapter 4

// Note: This PIDL does not compile. Don't even try.
//       It defines an operation not in an interface, which is illegal. 
//       As a result, this file is not "included" anywhere.
//       It is included for completeness' sake.

// PIDL
module CORBA {
        typedef string ORBid;
        typedef sequence <string> arg_list;
        ORB ORB_init (inout arg_list argv, in ORBid orb_identifier);
};
