.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH GSF 1 "29 November 2009" gsf "GNOME"
.SH NAME
gsf \- archiving utility using the G Structured File library

.SH SYNOPSIS
\fBgsf\fR [\fIOPTION...\fR] \fISUBCOMMAND\fR \fIARCHIVE...\fR

.SH DESCRIPTION
This manual page briefly documents the \fBgsf\fR command.

\fBgsf\fR is a simple archive utility, somewhat similar to \fBtar\fR(1). It
operates on files following one of the structured file formats understood by
the G Structured File library, for example, Microsoft Excel(TM) files.

.\".SH "RETURN VALUE"
.\".SH "EXIT STATUS"
.\".SH "ERROR HANDLING"
.\".SH ERRORS
.SH OPTIONS
.SS "Options"
.TP
.B \-?, \-\-help
Show help options
.TP
.B \-v, \-\-version
Display gsf's version

.SS "Subcommands"
.TP
.B cat
Output one or more files in archive
.TP
.B dump
Dump one or more files in archive as formatted hexadecimal
.TP
.B help
List subcommands
.TP
.B list
List files in archive
.TP
.B props
Archive list of property names

.\".SH USAGE
.SH EXAMPLES
To list the content structure of a Microsoft Excel(TM) file \fIarrays.xls\fR:
.PP
gsf list arrays.xls
.PP
To dump Workbook, an individual data stream in arrays.xls:
.PP
gsf dump arrays.xls Workbook
.PP
.\".SH FILES
.\".SH ENVIRONMENT
.\".SH DIAGNOSTICS
.\".SH SECURITY
.\".SH CONFORMING TO
.\".SH NOTES
.\".SH BUGS

.\".SH LICENSE
.\"
.\"\fBgsf-office-thumbnailer\fR is licensed under the terms of version 2.1 of
.\"the GNU Lesser General Public License (LGPL) as published by the Free
.\"Software Foundation. For information on this license look at the source code
.\"that came with the software or see the
.\".UR http://www.gnu.org
.\"GNU project page
.\".UE
.\"at http://www.gnu.org/.

.SH AUTHORS

\fBgsf\fR's primary authors are Morten Welinder <terra@gnome.org> and Jody
Goldberg <jody@gnome.org>.

The initial version of this manpage was written by J.H.M. Dassen (Ray)
<jdassen@debian.org>.

.SH SEE ALSO
\fBgnumeric\fR(1)

.URL "http://www.gnome.org/projects/gnumeric/" "The Gnumeric homepage"

.URL "http://www.gnome.org/" "The GNOME project page"
