set -o pipefail
'llvm-ar' 'x' '/private/var/chris/llvm-2.8/test/Archive/GNU.a' 'very_long_bytecode_file_name.bc'  &&

'diff' '/private/var/chris/llvm-2.8/test/Archive/very_long_bytecode_file_name.bc' 'very_long_bytecode_file_name.bc' > '/dev/null' 2> '/dev/null'  &&

'llvm-ar' 'x' '/private/var/chris/llvm-2.8/test/Archive/MacOSX.a' 'very_long_bytecode_file_name.bc'  &&

'diff' '/private/var/chris/llvm-2.8/test/Archive/very_long_bytecode_file_name.bc' 'very_long_bytecode_file_name.bc' > '/dev/null' 2> '/dev/null'  &&

'llvm-ar' 'x' '/private/var/chris/llvm-2.8/test/Archive/SVR4.a' 'very_long_bytecode_file_name.bc'  &&

'diff' '/private/var/chris/llvm-2.8/test/Archive/very_long_bytecode_file_name.bc' 'very_long_bytecode_file_name.bc' > '/dev/null' 2> '/dev/null'  &&

'llvm-ar' 'x' '/private/var/chris/llvm-2.8/test/Archive/xpg4.a' 'very_long_bytecode_file_name.bc'  &&

'diff' '/private/var/chris/llvm-2.8/test/Archive/very_long_bytecode_file_name.bc' 'very_long_bytecode_file_name.bc' > '/dev/null' 2> '/dev/null'