/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2011-10-15: 19h:52m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/option.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"
/* external codes at top */
/* type definitions */
typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_0 ;

typedef struct {
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_int_type atslab_2 ;
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_sum_1 ;

typedef struct {
ats_int_type atslab_0 ;
} anairiats_sum_2 ;

typedef struct {
ats_ptr_type atslab_0 ;
} anairiats_sum_3 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_int_type atslab_2 ;
} anairiats_sum_4 ;

typedef struct {
ats_ptr_type atslab_branch_lab ;
ats_ptr_type atslab_branch_inss ;
} anairiats_rec_5 ;

typedef struct {
ats_ptr_type atslab_instr_loc ;
ats_ptr_type atslab_instr_node ;
} anairiats_rec_6 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_int_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_7 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_int_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
} anairiats_sum_8 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
} anairiats_sum_9 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_10 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_11 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
ats_ptr_type atslab_5 ;
ats_ptr_type atslab_6 ;
ats_ptr_type atslab_7 ;
} anairiats_sum_12 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_int_type atslab_3 ;
} anairiats_sum_13 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_14 ;

typedef struct {
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
} anairiats_sum_15 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__list_cons) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__list_nil) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__None_vt) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__Some_vt) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_hiexp_2esats__TMPVAROPTsome) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_hiexp_2esats__TMPVAROPTnone) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRarr_heap) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRarr_stack) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRassgn_clo) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRcall) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRcond) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRfunction) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRload_ptr) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRload_ptr_offs) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRload_var) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRload_var_offs) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRloop) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRmove_con) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRmove_lazy_delay) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRmove_lazy_force) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRmove_rec_box) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRmove_rec_flt) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRmove_ref) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRmove_val) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRraise) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRselect) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRselcon) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRselcon_ptr) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRswitch) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRtrywith) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__INSTRvardec) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__TAILJOINLSTcons) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__TAILJOINLSTnil) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_map_lin_2edats__BSTcons) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_map_lin_2edats__BSTnil) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_map_lin_2edats__MAP) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_util_2edats__ENVcon) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_util_2edats__ENVcon) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_int_type, atspre_add_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_icompare) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_string) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e6_2src_2ats_map_lin_2esats__map_make) (ats_ptr_type) ;
ATSextern_fun(ats_int_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__compare_tmpvar_tmpvar) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__tmpvar_get_root) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__tmpvar_get_typ) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__tmpvar_is_void) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__emit_tmpvar) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__emit_hityp) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instr_tmpvarmap_add) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instrlst_tmpvarmap_add) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_env_2esats__funentry_get_ret) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_env_2esats__funentry_get_body) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, atsopt_map_lin_dice) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_void_type, atsopt_tmpvar_set_top) (ats_ptr_type, ats_int_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* sum constructor declarations */
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_util_2edats__ENVcon) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_ccomp_util_2edats__ENVcon) ;

/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_ptr_type bst_search_056_ats_ptr_type_2cats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_ptr_type map_search_01634_ats_ptr_type_2cats_int_type (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_int_type bst_size_028_ats_ptr_type_2cats_int_type (ats_ptr_type arg0) ;
static
ats_ptr_type bst_insert_atroot_033_ats_ptr_type_2cats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2, ats_ptr_type arg3) ;
static
ats_ptr_type bst_insert_random_067_ats_ptr_type_2cats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2, ats_ptr_type arg3) ;
static
ats_void_type map_insert_01632_ats_ptr_type_2cats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) ;
static
ats_void_type tmpvarmap_add_0 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_void_type tmpvarmap_add_root_7 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_void_type tmpvarmap_addlst_8 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_void_type f_10 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) ;
static
ats_void_type bst_foreach_inf_0131_ats_ptr_type_2cats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_void_type map_foreach_inf_01637_ats_ptr_type_2cats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_int_type _emit_tmpvarmap_dec_9 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) ;
static
ats_void_type f_14 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) ;
static
ats_int_type _emit_tmpvarmap_markroot_13 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_void_type bst_free_024_ats_ptr_type_2cats_int_type (ats_ptr_type arg0) ;
static
ats_void_type map_free_01630_ats_ptr_type_2cats_int_type (ats_ptr_type arg0) ;
static
ats_void_type aux_branchlst_20 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_void_type loop_27 (ats_ref_type arg0, ats_ptr_type arg1) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/Research/Anairiats/src/ats_map_lin.dats: 3687(line=114, offs=26) -- 4129(line=123, offs=4)
*/
ATSstaticdec()
ats_ptr_type
bst_search_056_ats_ptr_type_2cats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp5) ;
ATSlocal (ats_ptr_type, tmp6) ;
ATSlocal (ats_int_type, tmp7) ;
ATSlocal (ats_ptr_type, tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_int_type, tmp10) ;
ATSlocal (ats_ptr_type, tmp11) ;
ATSlocal (ats_ptr_type, tmp12) ;

__ats_lab_bst_search_056_ats_ptr_type_2cats_int_type:
#line 116 "ats_map_lin.dats"
do {
/* branch: __ats_lab_0 */
#line 117 "ats_map_lin.dats"
__ats_lab_0_0:
#line 117 "ats_map_lin.dats"
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_4_0 ; }
#line 117 "ats_map_lin.dats"
__ats_lab_0_1:
#line 117 "ats_map_lin.dats"
tmp6 = ats_caselptr_mac(anairiats_sum_1, arg0, atslab_1) ;
#line 117 "ats_map_lin.dats"
tmp7 = ats_caselptr_mac(anairiats_sum_1, arg0, atslab_2) ;
#line 117 "ats_map_lin.dats"
tmp8 = &ats_caselptr_mac(anairiats_sum_1, arg0, atslab_3) ;
#line 117 "ats_map_lin.dats"
tmp9 = &ats_caselptr_mac(anairiats_sum_1, arg0, atslab_4) ;
#line 117 "ats_map_lin.dats"
tmp10 = ((ats_int_type(*)(ats_ptr_type, ats_ptr_type))arg2) (arg1, tmp6) ;
#line 117 "ats_map_lin.dats"
do {
/* branch: __ats_lab_1 */
#line 118 "ats_map_lin.dats"
__ats_lab_1_0:
#line 118 "ats_map_lin.dats"
if (tmp10 != -1) { goto __ats_lab_2_0 ; }
#line 118 "ats_map_lin.dats"
__ats_lab_1_1:
#line 118 "ats_map_lin.dats"
tmp11 = ats_ptrget_mac(ats_ptr_type, tmp8) ;
#line 118 "ats_map_lin.dats"
arg0 = tmp11 ;
#line 118 "ats_map_lin.dats"
arg1 = arg1 ;
#line 118 "ats_map_lin.dats"
arg2 = arg2 ;
#line 118 "ats_map_lin.dats"
goto __ats_lab_bst_search_056_ats_ptr_type_2cats_int_type ; // tail call
break ;

/* branch: __ats_lab_2 */
#line 119 "ats_map_lin.dats"
__ats_lab_2_0:
#line 119 "ats_map_lin.dats"
if (tmp10 != 1) { goto __ats_lab_3_0 ; }
#line 119 "ats_map_lin.dats"
__ats_lab_2_1:
#line 119 "ats_map_lin.dats"
tmp12 = ats_ptrget_mac(ats_ptr_type, tmp9) ;
#line 119 "ats_map_lin.dats"
arg0 = tmp12 ;
#line 119 "ats_map_lin.dats"
arg1 = arg1 ;
#line 119 "ats_map_lin.dats"
arg2 = arg2 ;
#line 119 "ats_map_lin.dats"
goto __ats_lab_bst_search_056_ats_ptr_type_2cats_int_type ; // tail call
break ;

/* branch: __ats_lab_3 */
#line 120 "ats_map_lin.dats"
__ats_lab_3_0:
#line 120 "ats_map_lin.dats"
// if (tmp10 != 0) { ats_deadcode_failure_handle () ; }
#line 120 "ats_map_lin.dats"
__ats_lab_3_1:
#line 120 "ats_map_lin.dats"
tmp5 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, tmp5, atslab_0, tmp7) ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_4 */
#line 122 "ats_map_lin.dats"
__ats_lab_4_0:
#line 122 "ats_map_lin.dats"
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 122 "ats_map_lin.dats"
__ats_lab_4_1:
#line 122 "ats_map_lin.dats"
tmp5 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp5) ;
} /* end of [bst_search_056_ats_ptr_type_2cats_int_type] */

/*
// /home/hwxi/Research/Anairiats/src/ats_map_lin.dats: 9876(line=342, offs=12) -- 9988(line=347, offs=4)
*/
ATSstaticdec()
ats_ptr_type
map_search_01634_ats_ptr_type_2cats_int_type (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;
ATSlocal (ats_ptr_type, tmp4) ;
ATSlocal (ats_ptr_type, tmp13) ;

__ats_lab_map_search_01634_ats_ptr_type_2cats_int_type:
#line 343 "ats_map_lin.dats"
// 
#line 343 "ats_map_lin.dats"
tmp3 = ats_caselptr_mac(anairiats_sum_0, arg0, atslab_0) ;
#line 343 "ats_map_lin.dats"
tmp4 = &ats_caselptr_mac(anairiats_sum_0, arg0, atslab_1) ;
#line 344 "ats_map_lin.dats"
tmp13 = ats_ptrget_mac(ats_ptr_type, tmp4) ;
#line 344 "ats_map_lin.dats"
tmp2 = bst_search_056_ats_ptr_type_2cats_int_type (tmp13, arg1, tmp3) ;
return (tmp2) ;
} /* end of [map_search_01634_ats_ptr_type_2cats_int_type] */

/*
// /home/hwxi/Research/Anairiats/src/ats_map_lin.dats: 2219(line=70, offs=18) -- 2335(line=71, offs=71)
*/
ATSstaticdec()
ats_int_type
bst_size_028_ats_ptr_type_2cats_int_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp39) ;
ATSlocal (ats_int_type, tmp40) ;

__ats_lab_bst_size_028_ats_ptr_type_2cats_int_type:
#line 70 "ats_map_lin.dats"
do {
/* branch: __ats_lab_9 */
#line 71 "ats_map_lin.dats"
__ats_lab_9_0:
#line 71 "ats_map_lin.dats"
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_10_0 ; }
#line 71 "ats_map_lin.dats"
__ats_lab_9_1:
#line 71 "ats_map_lin.dats"
tmp40 = ats_caselptr_mac(anairiats_sum_1, arg0, atslab_0) ;
#line 71 "ats_map_lin.dats"
tmp39 = tmp40 ;
break ;

/* branch: __ats_lab_10 */
#line 71 "ats_map_lin.dats"
__ats_lab_10_0:
#line 71 "ats_map_lin.dats"
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 71 "ats_map_lin.dats"
__ats_lab_10_1:
#line 71 "ats_map_lin.dats"
tmp39 = 0 ;
break ;
} while (0) ;
return (tmp39) ;
} /* end of [bst_size_028_ats_ptr_type_2cats_int_type] */

/*
// /home/hwxi/Research/Anairiats/src/ats_map_lin.dats: 2614(line=83, offs=33) -- 3587(line=109, offs=4)
*/
ATSstaticdec()
ats_ptr_type
bst_insert_atroot_033_ats_ptr_type_2cats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2, ats_ptr_type arg3) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp25) ;
ATSlocal (ats_ptr_type, tmp26) ;
ATSlocal (ats_ptr_type, tmp27) ;
ATSlocal (ats_ptr_type, tmp28) ;
ATSlocal (ats_ptr_type, tmp29) ;
ATSlocal (ats_bool_type, tmp30) ;
ATSlocal (ats_int_type, tmp31) ;
ATSlocal (ats_ptr_type, tmp32) ;
ATSlocal (ats_ptr_type, tmp33) ;
ATSlocal (ats_ptr_type, tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (ats_ptr_type, tmp36) ;
ATSlocal (ats_int_type, tmp37) ;
ATSlocal (ats_int_type, tmp38) ;
ATSlocal (ats_ptr_type, tmp41) ;
ATSlocal (ats_ptr_type, tmp42) ;
ATSlocal (ats_int_type, tmp43) ;
ATSlocal (ats_int_type, tmp44) ;
ATSlocal (ats_ptr_type, tmp45) ;
ATSlocal (ats_ptr_type, tmp46) ;
ATSlocal (ats_ptr_type, tmp47) ;
ATSlocal (ats_ptr_type, tmp48) ;
ATSlocal (ats_ptr_type, tmp49) ;
ATSlocal (ats_int_type, tmp50) ;
ATSlocal (ats_int_type, tmp51) ;
ATSlocal (ats_ptr_type, tmp52) ;
ATSlocal (ats_ptr_type, tmp53) ;
ATSlocal (ats_int_type, tmp54) ;
ATSlocal (ats_int_type, tmp55) ;
ATSlocal (ats_ptr_type, tmp56) ;
ATSlocal (ats_ptr_type, tmp57) ;

__ats_lab_bst_insert_atroot_033_ats_ptr_type_2cats_int_type:
#line 88 "ats_map_lin.dats"
do {
/* branch: __ats_lab_8 */
#line 89 "ats_map_lin.dats"
__ats_lab_8_0:
#line 89 "ats_map_lin.dats"
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_11_0 ; }
#line 89 "ats_map_lin.dats"
__ats_lab_8_1:
#line 89 "ats_map_lin.dats"
tmp26 = &ats_caselptr_mac(anairiats_sum_1, arg0, atslab_0) ;
#line 89 "ats_map_lin.dats"
tmp27 = ats_caselptr_mac(anairiats_sum_1, arg0, atslab_1) ;
#line 89 "ats_map_lin.dats"
tmp28 = &ats_caselptr_mac(anairiats_sum_1, arg0, atslab_3) ;
#line 89 "ats_map_lin.dats"
tmp29 = &ats_caselptr_mac(anairiats_sum_1, arg0, atslab_4) ;
#line 90 "ats_map_lin.dats"
tmp31 = ((ats_int_type(*)(ats_ptr_type, ats_ptr_type))arg3) (arg1, tmp27) ;
#line 90 "ats_map_lin.dats"
tmp30 = atspre_ilte (tmp31, 0) ;
#line 90 "ats_map_lin.dats"
if (tmp30) {
#line 91 "ats_map_lin.dats"
tmp33 = ats_ptrget_mac(ats_ptr_type, tmp28) ;
#line 91 "ats_map_lin.dats"
tmp32 = bst_insert_atroot_033_ats_ptr_type_2cats_int_type (tmp33, arg1, arg2, arg3) ;
#line 92 "ats_map_lin.dats"
// if (tmp32 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 92 "ats_map_lin.dats"
tmp34 = &ats_caselptr_mac(anairiats_sum_1, tmp32, atslab_0) ;
#line 92 "ats_map_lin.dats"
tmp35 = &ats_caselptr_mac(anairiats_sum_1, tmp32, atslab_3) ;
#line 92 "ats_map_lin.dats"
tmp36 = &ats_caselptr_mac(anairiats_sum_1, tmp32, atslab_4) ;
#line 93 "ats_map_lin.dats"
tmp37 = ats_ptrget_mac(ats_int_type, tmp26) ;
#line 93 "ats_map_lin.dats"
tmp41 = ats_ptrget_mac(ats_ptr_type, tmp35) ;
#line 93 "ats_map_lin.dats"
tmp38 = bst_size_028_ats_ptr_type_2cats_int_type (tmp41) ;
#line 95 "ats_map_lin.dats"
tmp42 = ats_ptrget_mac(ats_ptr_type, tmp36) ;
#line 95 "ats_map_lin.dats"
ats_ptrget_mac(ats_ptr_type, tmp28) = tmp42 ;
#line 95 "ats_map_lin.dats"
tmp43 = atspre_isub (tmp37, tmp38) ;
#line 95 "ats_map_lin.dats"
ats_ptrget_mac(ats_int_type, tmp26) = tmp43 ;
#line 96 "ats_map_lin.dats"
ats_ptrget_mac(ats_ptr_type, tmp36) = arg0 ;
#line 96 "ats_map_lin.dats"
tmp44 = atspre_iadd (tmp37, 1) ;
#line 96 "ats_map_lin.dats"
ats_ptrget_mac(ats_int_type, tmp34) = tmp44 ;
#line 96 "ats_map_lin.dats"
tmp25 = tmp32 ;
} else {
#line 98 "ats_map_lin.dats"
tmp46 = ats_ptrget_mac(ats_ptr_type, tmp29) ;
#line 98 "ats_map_lin.dats"
tmp45 = bst_insert_atroot_033_ats_ptr_type_2cats_int_type (tmp46, arg1, arg2, arg3) ;
#line 99 "ats_map_lin.dats"
// if (tmp45 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 99 "ats_map_lin.dats"
tmp47 = &ats_caselptr_mac(anairiats_sum_1, tmp45, atslab_0) ;
#line 99 "ats_map_lin.dats"
tmp48 = &ats_caselptr_mac(anairiats_sum_1, tmp45, atslab_3) ;
#line 99 "ats_map_lin.dats"
tmp49 = &ats_caselptr_mac(anairiats_sum_1, tmp45, atslab_4) ;
#line 100 "ats_map_lin.dats"
tmp50 = ats_ptrget_mac(ats_int_type, tmp26) ;
#line 100 "ats_map_lin.dats"
tmp52 = ats_ptrget_mac(ats_ptr_type, tmp49) ;
#line 100 "ats_map_lin.dats"
tmp51 = bst_size_028_ats_ptr_type_2cats_int_type (tmp52) ;
#line 102 "ats_map_lin.dats"
tmp53 = ats_ptrget_mac(ats_ptr_type, tmp48) ;
#line 102 "ats_map_lin.dats"
ats_ptrget_mac(ats_ptr_type, tmp29) = tmp53 ;
#line 102 "ats_map_lin.dats"
tmp54 = atspre_isub (tmp50, tmp51) ;
#line 102 "ats_map_lin.dats"
ats_ptrget_mac(ats_int_type, tmp26) = tmp54 ;
#line 103 "ats_map_lin.dats"
ats_ptrget_mac(ats_ptr_type, tmp48) = arg0 ;
#line 103 "ats_map_lin.dats"
tmp55 = atspre_iadd (tmp50, 1) ;
#line 103 "ats_map_lin.dats"
ats_ptrget_mac(ats_int_type, tmp47) = tmp55 ;
#line 103 "ats_map_lin.dats"
tmp25 = tmp45 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_11 */
#line 106 "ats_map_lin.dats"
__ats_lab_11_0:
#line 106 "ats_map_lin.dats"
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 106 "ats_map_lin.dats"
__ats_lab_11_1:
#line 107 "ats_map_lin.dats"
tmp56 = (ats_sum_ptr_type)0 ;
#line 107 "ats_map_lin.dats"
tmp57 = (ats_sum_ptr_type)0 ;
#line 107 "ats_map_lin.dats"
tmp25 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
ats_selptrset_mac(anairiats_sum_1, tmp25, atslab_0, 1) ;
ats_selptrset_mac(anairiats_sum_1, tmp25, atslab_1, arg1) ;
ats_selptrset_mac(anairiats_sum_1, tmp25, atslab_2, arg2) ;
ats_selptrset_mac(anairiats_sum_1, tmp25, atslab_3, tmp56) ;
ats_selptrset_mac(anairiats_sum_1, tmp25, atslab_4, tmp57) ;
break ;
} while (0) ;
return (tmp25) ;
} /* end of [bst_insert_atroot_033_ats_ptr_type_2cats_int_type] */

/*
// /home/hwxi/Research/Anairiats/src/ats_map_lin.dats: 4580(line=147, offs=33) -- 5265(line=168, offs=4)
*/
ATSstaticdec()
ats_ptr_type
bst_insert_random_067_ats_ptr_type_2cats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2, ats_ptr_type arg3) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp18) ;
ATSlocal (ats_ptr_type, tmp19) ;
ATSlocal (ats_ptr_type, tmp20) ;
ATSlocal (ats_ptr_type, tmp21) ;
ATSlocal (ats_ptr_type, tmp22) ;
ATSlocal (ats_bool_type, tmp23) ;
ATSlocal (ats_int_type, tmp24) ;
ATSlocal (ats_bool_type, tmp58) ;
ATSlocal (ats_int_type, tmp59) ;
ATSlocal (ats_ptr_type, tmp60) ;
ATSlocal (ats_ptr_type, tmp61) ;
ATSlocal (ats_int_type, tmp62) ;
ATSlocal (ats_int_type, tmp63) ;
ATSlocal (ats_ptr_type, tmp64) ;
ATSlocal (ats_ptr_type, tmp65) ;
ATSlocal (ats_int_type, tmp66) ;
ATSlocal (ats_int_type, tmp67) ;
ATSlocal (ats_ptr_type, tmp68) ;
ATSlocal (ats_ptr_type, tmp69) ;

__ats_lab_bst_insert_random_067_ats_ptr_type_2cats_int_type:
#line 152 "ats_map_lin.dats"
do {
/* branch: __ats_lab_7 */
#line 153 "ats_map_lin.dats"
__ats_lab_7_0:
#line 153 "ats_map_lin.dats"
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_12_0 ; }
#line 153 "ats_map_lin.dats"
__ats_lab_7_1:
#line 153 "ats_map_lin.dats"
tmp19 = &ats_caselptr_mac(anairiats_sum_1, arg0, atslab_0) ;
#line 153 "ats_map_lin.dats"
tmp20 = ats_caselptr_mac(anairiats_sum_1, arg0, atslab_1) ;
#line 153 "ats_map_lin.dats"
tmp21 = &ats_caselptr_mac(anairiats_sum_1, arg0, atslab_3) ;
#line 153 "ats_map_lin.dats"
tmp22 = &ats_caselptr_mac(anairiats_sum_1, arg0, atslab_4) ;
#line 154 "ats_map_lin.dats"
tmp24 = ats_ptrget_mac(ats_int_type, tmp19) ;
#line 154 "ats_map_lin.dats"
tmp23 = atsopt_map_lin_dice (1, tmp24) ;
#line 154 "ats_map_lin.dats"
if (tmp23) {
#line 155 "ats_map_lin.dats"
tmp18 = bst_insert_atroot_033_ats_ptr_type_2cats_int_type (arg0, arg1, arg2, arg3) ;
} else {
#line 157 "ats_map_lin.dats"
tmp59 = ((ats_int_type(*)(ats_ptr_type, ats_ptr_type))arg3) (arg1, tmp20) ;
#line 157 "ats_map_lin.dats"
tmp58 = atspre_ilte (tmp59, 0) ;
#line 157 "ats_map_lin.dats"
if (tmp58) {
#line 158 "ats_map_lin.dats"
tmp61 = ats_ptrget_mac(ats_ptr_type, tmp21) ;
#line 158 "ats_map_lin.dats"
tmp60 = bst_insert_random_067_ats_ptr_type_2cats_int_type (tmp61, arg1, arg2, arg3) ;
#line 158 "ats_map_lin.dats"
ats_ptrget_mac(ats_ptr_type, tmp21) = tmp60 ;
#line 159 "ats_map_lin.dats"
tmp63 = ats_ptrget_mac(ats_int_type, tmp19) ;
#line 159 "ats_map_lin.dats"
tmp62 = atspre_iadd (tmp63, 1) ;
#line 159 "ats_map_lin.dats"
ats_ptrget_mac(ats_int_type, tmp19) = tmp62 ;
#line 159 "ats_map_lin.dats"
tmp18 = arg0 ;
} else {
#line 161 "ats_map_lin.dats"
tmp65 = ats_ptrget_mac(ats_ptr_type, tmp22) ;
#line 161 "ats_map_lin.dats"
tmp64 = bst_insert_random_067_ats_ptr_type_2cats_int_type (tmp65, arg1, arg2, arg3) ;
#line 161 "ats_map_lin.dats"
ats_ptrget_mac(ats_ptr_type, tmp22) = tmp64 ;
#line 162 "ats_map_lin.dats"
tmp67 = ats_ptrget_mac(ats_int_type, tmp19) ;
#line 162 "ats_map_lin.dats"
tmp66 = atspre_iadd (tmp67, 1) ;
#line 162 "ats_map_lin.dats"
ats_ptrget_mac(ats_int_type, tmp19) = tmp66 ;
#line 162 "ats_map_lin.dats"
tmp18 = arg0 ;
} /* end of [if] */
} /* end of [if] */
break ;

/* branch: __ats_lab_12 */
#line 165 "ats_map_lin.dats"
__ats_lab_12_0:
#line 165 "ats_map_lin.dats"
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 165 "ats_map_lin.dats"
__ats_lab_12_1:
#line 166 "ats_map_lin.dats"
tmp68 = (ats_sum_ptr_type)0 ;
#line 166 "ats_map_lin.dats"
tmp69 = (ats_sum_ptr_type)0 ;
#line 166 "ats_map_lin.dats"
tmp18 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
ats_selptrset_mac(anairiats_sum_1, tmp18, atslab_0, 1) ;
ats_selptrset_mac(anairiats_sum_1, tmp18, atslab_1, arg1) ;
ats_selptrset_mac(anairiats_sum_1, tmp18, atslab_2, arg2) ;
ats_selptrset_mac(anairiats_sum_1, tmp18, atslab_3, tmp68) ;
ats_selptrset_mac(anairiats_sum_1, tmp18, atslab_4, tmp69) ;
break ;
} while (0) ;
return (tmp18) ;
} /* end of [bst_insert_random_067_ats_ptr_type_2cats_int_type] */

/*
// /home/hwxi/Research/Anairiats/src/ats_map_lin.dats: 10043(line=350, offs=12) -- 10162(line=353, offs=4)
*/
ATSstaticdec()
ats_void_type
map_insert_01632_ats_ptr_type_2cats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) {
/* local vardec */
// ATSlocal_void (tmp14) ;
ATSlocal (ats_ptr_type, tmp15) ;
ATSlocal (ats_ptr_type, tmp16) ;
ATSlocal (ats_ptr_type, tmp17) ;
ATSlocal (ats_ptr_type, tmp70) ;

__ats_lab_map_insert_01632_ats_ptr_type_2cats_int_type:
#line 351 "ats_map_lin.dats"
// 
#line 351 "ats_map_lin.dats"
tmp15 = ats_caselptr_mac(anairiats_sum_0, arg0, atslab_0) ;
#line 351 "ats_map_lin.dats"
tmp16 = &ats_caselptr_mac(anairiats_sum_0, arg0, atslab_1) ;
#line 352 "ats_map_lin.dats"
tmp70 = ats_ptrget_mac(ats_ptr_type, tmp16) ;
#line 352 "ats_map_lin.dats"
tmp17 = bst_insert_random_067_ats_ptr_type_2cats_int_type (tmp70, arg1, arg2, tmp15) ;
#line 352 "ats_map_lin.dats"
ats_ptrget_mac(ats_ptr_type, tmp16) = tmp17 ;
return /* (tmp14) */ ;
} /* end of [map_insert_01632_ats_ptr_type_2cats_int_type] */

/*
// /home/hwxi/Research/Anairiats/src/ats_ccomp_util.dats: 1791(line=54, offs=4) -- 1957(line=58, offs=4)
*/
ATSstaticdec()
ats_void_type
tmpvarmap_add_0 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp0) ;
ATSlocal (ats_ptr_type, tmp1) ;

__ats_lab_tmpvarmap_add_0:
#line 56 "ats_ccomp_util.dats"
tmp1 = map_search_01634_ats_ptr_type_2cats_int_type (ats_ptrget_mac(ats_ptr_type, arg0), arg1) ;
#line 56 "ats_ccomp_util.dats"
do {
/* branch: __ats_lab_5 */
#line 57 "ats_ccomp_util.dats"
__ats_lab_5_0:
#line 57 "ats_ccomp_util.dats"
if (tmp1 == (ats_sum_ptr_type)0) { goto __ats_lab_6_0 ; }
#line 57 "ats_ccomp_util.dats"
__ats_lab_5_1:
#line 57 "ats_ccomp_util.dats"
ATS_FREE(tmp1) ;
break ;

/* branch: __ats_lab_6 */
#line 57 "ats_ccomp_util.dats"
__ats_lab_6_0:
#line 57 "ats_ccomp_util.dats"
// if (tmp1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 57 "ats_ccomp_util.dats"
__ats_lab_6_1:
#line 57 "ats_ccomp_util.dats"
/* tmp0 = */ map_insert_01632_ats_ptr_type_2cats_int_type (ats_ptrget_mac(ats_ptr_type, arg0), arg1, 0) ;
break ;
} while (0) ;
return /* (tmp0) */ ;
} /* end of [tmpvarmap_add_0] */

/*
// /home/hwxi/Research/Anairiats/src/ats_ccomp_util.dats: 1988(line=60, offs=4) -- 2293(line=69, offs=4)
*/
ATSstaticdec()
ats_void_type
tmpvarmap_add_root_7 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp71) ;
ATSlocal (ats_ptr_type, tmp72) ;
ATSlocal (ats_ptr_type, tmp73) ;
ATSlocal (ats_ptr_type, tmp74) ;
ATSlocal (ats_ptr_type, tmp75) ;

__ats_lab_tmpvarmap_add_root_7:
#line 63 "ats_ccomp_util.dats"
tmp73 = ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__tmpvar_get_root (arg1) ;
#line 63 "ats_ccomp_util.dats"
do {
/* branch: __ats_lab_13 */
#line 64 "ats_ccomp_util.dats"
__ats_lab_13_0:
#line 64 "ats_ccomp_util.dats"
if (tmp73 == (ats_sum_ptr_type)0) { goto __ats_lab_14_0 ; }
#line 64 "ats_ccomp_util.dats"
__ats_lab_13_1:
#line 64 "ats_ccomp_util.dats"
tmp74 = ats_caselptr_mac(anairiats_sum_3, tmp73, atslab_0) ;
#line 64 "ats_ccomp_util.dats"
tmp72 = tmp74 ;
break ;

/* branch: __ats_lab_14 */
#line 64 "ats_ccomp_util.dats"
__ats_lab_14_0:
#line 64 "ats_ccomp_util.dats"
// if (tmp73 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 64 "ats_ccomp_util.dats"
__ats_lab_14_1:
#line 64 "ats_ccomp_util.dats"
tmp72 = arg1 ;
break ;
} while (0) ;
#line 67 "ats_ccomp_util.dats"
tmp75 = map_search_01634_ats_ptr_type_2cats_int_type (ats_ptrget_mac(ats_ptr_type, arg0), tmp72) ;
#line 67 "ats_ccomp_util.dats"
do {
/* branch: __ats_lab_15 */
#line 68 "ats_ccomp_util.dats"
__ats_lab_15_0:
#line 68 "ats_ccomp_util.dats"
if (tmp75 == (ats_sum_ptr_type)0) { goto __ats_lab_16_0 ; }
#line 68 "ats_ccomp_util.dats"
__ats_lab_15_1:
#line 68 "ats_ccomp_util.dats"
ATS_FREE(tmp75) ;
break ;

/* branch: __ats_lab_16 */
#line 68 "ats_ccomp_util.dats"
__ats_lab_16_0:
#line 68 "ats_ccomp_util.dats"
// if (tmp75 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 68 "ats_ccomp_util.dats"
__ats_lab_16_1:
#line 68 "ats_ccomp_util.dats"
/* tmp71 = */ map_insert_01632_ats_ptr_type_2cats_int_type (ats_ptrget_mac(ats_ptr_type, arg0), tmp72, 0) ;
break ;
} while (0) ;
return /* (tmp71) */ ;
} /* end of [tmpvarmap_add_root_7] */

/*
// /home/hwxi/Research/Anairiats/src/ats_ccomp_util.dats: 2321(line=71, offs=5) -- 2550(line=78, offs=4)
*/
ATSstaticdec()
ats_void_type
tmpvarmap_addlst_8 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp76) ;
ATSlocal (ats_ptr_type, tmp77) ;
ATSlocal (ats_ptr_type, tmp78) ;
// ATSlocal_void (tmp79) ;

__ats_lab_tmpvarmap_addlst_8:
#line 73 "ats_ccomp_util.dats"
do {
/* branch: __ats_lab_17 */
#line 74 "ats_ccomp_util.dats"
__ats_lab_17_0:
#line 74 "ats_ccomp_util.dats"
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_18_0 ; }
#line 74 "ats_ccomp_util.dats"
__ats_lab_17_1:
#line 74 "ats_ccomp_util.dats"
tmp77 = ats_caselptr_mac(anairiats_sum_0, arg1, atslab_0) ;
#line 74 "ats_ccomp_util.dats"
tmp78 = ats_caselptr_mac(anairiats_sum_0, arg1, atslab_1) ;
#line 75 "ats_ccomp_util.dats"
/* tmp79 = */ tmpvarmap_add_0 (arg0, tmp77) ;
#line 75 "ats_ccomp_util.dats"
arg0 = arg0 ;
#line 75 "ats_ccomp_util.dats"
arg1 = tmp78 ;
#line 75 "ats_ccomp_util.dats"
goto __ats_lab_tmpvarmap_addlst_8 ; // tail call
break ;

/* branch: __ats_lab_18 */
#line 77 "ats_ccomp_util.dats"
__ats_lab_18_0:
#line 77 "ats_ccomp_util.dats"
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 77 "ats_ccomp_util.dats"
__ats_lab_18_1:
break ;
} while (0) ;
return /* (tmp76) */ ;
} /* end of [tmpvarmap_addlst_8] */

/*
// /home/hwxi/Research/Anairiats/src/ats_ccomp_util.dats: 3051(line=104, offs=6) -- 4328(line=137, offs=6)
*/
ATSstaticdec()
ats_void_type
f_10 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
// ATSlocal_void (tmp82) ;
ATSlocal (ats_ptr_type, tmp83) ;
ATSlocal (ats_ptr_type, tmp84) ;
ATSlocal (ats_int_type, tmp85) ;
// ATSlocal_void (tmp86) ;
ATSlocal (ats_bool_type, tmp87) ;
ATSlocal (ats_int_type, tmp88) ;
ATSlocal (ats_int_type, tmp89) ;
ATSlocal (ats_bool_type, tmp90) ;
// ATSlocal_void (tmp91) ;
ATSlocal (ats_bool_type, tmp92) ;
// ATSlocal_void (tmp93) ;
ATSlocal (ats_bool_type, tmp94) ;
// ATSlocal_void (tmp95) ;
// ATSlocal_void (tmp96) ;
ATSlocal (ats_bool_type, tmp97) ;
// ATSlocal_void (tmp98) ;
ATSlocal (ats_bool_type, tmp99) ;
// ATSlocal_void (tmp100) ;
ATSlocal (ats_ptr_type, tmp101) ;
// ATSlocal_void (tmp102) ;
// ATSlocal_void (tmp103) ;

__ats_lab_f_10:
#line 106 "ats_ccomp_util.dats"
// 
#line 106 "ats_ccomp_util.dats"
tmp83 = ats_caselptr_mac(anairiats_sum_4, arg2, atslab_0) ;
#line 106 "ats_ccomp_util.dats"
tmp84 = ats_caselptr_mac(anairiats_sum_4, arg2, atslab_1) ;
#line 106 "ats_ccomp_util.dats"
tmp85 = ats_caselptr_mac(anairiats_sum_4, arg2, atslab_2) ;
#line 110 "ats_ccomp_util.dats"
tmp87 = atspre_eq_int_int (tmp85, 1) ;
#line 110 "ats_ccomp_util.dats"
if (tmp87) {
#line 110 "ats_ccomp_util.dats"
/* tmp86 = */ atsopt_tmpvar_set_top (arg0, 1) ;
} else {
/* empty */
} /* end of [if] */
#line 112 "ats_ccomp_util.dats"
tmp89 = ats_ptrget_mac(ats_int_type, tmp84) ;
#line 112 "ats_ccomp_util.dats"
tmp88 = atspre_add_int_int (tmp89, 1) ;
#line 112 "ats_ccomp_util.dats"
ats_ptrget_mac(ats_int_type, tmp84) = tmp88 ;
#line 114 "ats_ccomp_util.dats"
do {
/* branch: __ats_lab_19 */
#line 115 "ats_ccomp_util.dats"
__ats_lab_19_0:
#line 115 "ats_ccomp_util.dats"
__ats_lab_19_1:
#line 115 "ats_ccomp_util.dats"
tmp90 = ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__tmpvar_is_void (arg0) ;
#line 115 "ats_ccomp_util.dats"
if (!tmp90) { goto __ats_lab_20_1 ; }
#line 116 "ats_ccomp_util.dats"
tmp92 = atspre_eq_int_int (tmp85, 0) ;
#line 116 "ats_ccomp_util.dats"
if (tmp92) {
#line 117 "ats_ccomp_util.dats"
/* tmp91 = */ atspre_fprint_string (tmp83, ATSstrcst("// ATSlocal_void (")) ;
} else {
/* empty */
} /* end of [if] */
#line 118 "ats_ccomp_util.dats"
tmp94 = atspre_eq_int_int (tmp85, 1) ;
#line 118 "ats_ccomp_util.dats"
if (tmp94) {
#line 119 "ats_ccomp_util.dats"
/* tmp93 = */ atspre_fprint_string (tmp83, ATSstrcst("// ATSstatic_void (")) ;
} else {
/* empty */
} /* end of [if] */
#line 120 "ats_ccomp_util.dats"
/* tmp95 = */ ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__emit_tmpvar (tmp83, arg0) ;
#line 121 "ats_ccomp_util.dats"
/* tmp82 = */ atspre_fprint_string (tmp83, ATSstrcst(") ;\n")) ;
break ;

/* branch: __ats_lab_20 */
#line 125 "ats_ccomp_util.dats"
__ats_lab_20_0:
#line 125 "ats_ccomp_util.dats"
__ats_lab_20_1:
#line 126 "ats_ccomp_util.dats"
tmp97 = atspre_eq_int_int (tmp85, 0) ;
#line 126 "ats_ccomp_util.dats"
if (tmp97) {
#line 127 "ats_ccomp_util.dats"
/* tmp96 = */ atspre_fprint_string (tmp83, ATSstrcst("ATSlocal (")) ;
} else {
/* empty */
} /* end of [if] */
#line 128 "ats_ccomp_util.dats"
tmp99 = atspre_eq_int_int (tmp85, 1) ;
#line 128 "ats_ccomp_util.dats"
if (tmp99) {
#line 129 "ats_ccomp_util.dats"
/* tmp98 = */ atspre_fprint_string (tmp83, ATSstrcst("ATSstatic (")) ;
} else {
/* empty */
} /* end of [if] */
#line 130 "ats_ccomp_util.dats"
tmp101 = ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__tmpvar_get_typ (arg0) ;
#line 130 "ats_ccomp_util.dats"
/* tmp100 = */ ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__emit_hityp (tmp83, tmp101) ;
#line 131 "ats_ccomp_util.dats"
/* tmp102 = */ atspre_fprint_string (tmp83, ATSstrcst(", ")) ;
#line 132 "ats_ccomp_util.dats"
/* tmp103 = */ ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__emit_tmpvar (tmp83, arg0) ;
#line 133 "ats_ccomp_util.dats"
/* tmp82 = */ atspre_fprint_string (tmp83, ATSstrcst(") ;\n")) ;
break ;
} while (0) ;
return /* (tmp82) */ ;
} /* end of [f_10] */

/*
// /home/hwxi/Research/Anairiats/src/ats_map_lin.dats: 8937(line=300, offs=25) -- 9308(line=314, offs=4)
*/
ATSstaticdec()
ats_void_type
bst_foreach_inf_0131_ats_ptr_type_2cats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
// ATSlocal_void (tmp108) ;
ATSlocal (ats_ptr_type, tmp109) ;
ATSlocal (ats_int_type, tmp110) ;
ATSlocal (ats_ptr_type, tmp111) ;
ATSlocal (ats_ptr_type, tmp112) ;
// ATSlocal_void (tmp113) ;
ATSlocal (ats_ptr_type, tmp114) ;
// ATSlocal_void (tmp115) ;
ATSlocal (ats_ptr_type, tmp116) ;

__ats_lab_bst_foreach_inf_0131_ats_ptr_type_2cats_int_type:
#line 305 "ats_map_lin.dats"
do {
/* branch: __ats_lab_21 */
#line 306 "ats_map_lin.dats"
__ats_lab_21_0:
#line 306 "ats_map_lin.dats"
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_22_0 ; }
#line 306 "ats_map_lin.dats"
__ats_lab_21_1:
#line 306 "ats_map_lin.dats"
tmp109 = ats_caselptr_mac(anairiats_sum_1, arg0, atslab_1) ;
#line 306 "ats_map_lin.dats"
tmp110 = ats_caselptr_mac(anairiats_sum_1, arg0, atslab_2) ;
#line 306 "ats_map_lin.dats"
tmp111 = &ats_caselptr_mac(anairiats_sum_1, arg0, atslab_3) ;
#line 306 "ats_map_lin.dats"
tmp112 = &ats_caselptr_mac(anairiats_sum_1, arg0, atslab_4) ;
#line 307 "ats_map_lin.dats"
tmp114 = ats_ptrget_mac(ats_ptr_type, tmp111) ;
#line 307 "ats_map_lin.dats"
/* tmp113 = */ bst_foreach_inf_0131_ats_ptr_type_2cats_int_type (tmp114, arg1, arg2) ;
#line 308 "ats_map_lin.dats"
/* tmp115 = */ ((ats_void_type(*)(ats_ptr_type, ats_int_type, ats_ptr_type))arg1) (tmp109, tmp110, arg2) ;
#line 309 "ats_map_lin.dats"
tmp116 = ats_ptrget_mac(ats_ptr_type, tmp112) ;
#line 309 "ats_map_lin.dats"
arg0 = tmp116 ;
#line 309 "ats_map_lin.dats"
arg1 = arg1 ;
#line 309 "ats_map_lin.dats"
arg2 = arg2 ;
#line 309 "ats_map_lin.dats"
goto __ats_lab_bst_foreach_inf_0131_ats_ptr_type_2cats_int_type ; // tail call
break ;

/* branch: __ats_lab_22 */
#line 313 "ats_map_lin.dats"
__ats_lab_22_0:
#line 313 "ats_map_lin.dats"
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 313 "ats_map_lin.dats"
__ats_lab_22_1:
break ;
} while (0) ;
return /* (tmp108) */ ;
} /* end of [bst_foreach_inf_0131_ats_ptr_type_2cats_int_type] */

/*
// /home/hwxi/Research/Anairiats/src/ats_map_lin.dats: 11800(line=406, offs=17) -- 11939(line=411, offs=4)
*/
ATSstaticdec()
ats_void_type
map_foreach_inf_01637_ats_ptr_type_2cats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
// ATSlocal_void (tmp106) ;
ATSlocal (ats_ptr_type, tmp107) ;
ATSlocal (ats_ptr_type, tmp117) ;

__ats_lab_map_foreach_inf_01637_ats_ptr_type_2cats_int_type:
#line 407 "ats_map_lin.dats"
// 
#line 407 "ats_map_lin.dats"
tmp107 = &ats_caselptr_mac(anairiats_sum_0, arg0, atslab_1) ;
#line 408 "ats_map_lin.dats"
tmp117 = ats_ptrget_mac(ats_ptr_type, tmp107) ;
#line 408 "ats_map_lin.dats"
/* tmp106 = */ bst_foreach_inf_0131_ats_ptr_type_2cats_int_type (tmp117, arg1, arg2) ;
return /* (tmp106) */ ;
} /* end of [map_foreach_inf_01637_ats_ptr_type_2cats_int_type] */

/*
// /home/hwxi/Research/Anairiats/src/ats_ccomp_util.dats: 2779(line=94, offs=4) -- 4581(line=145, offs=4)
*/
ATSstaticdec()
ats_int_type
_emit_tmpvarmap_dec_9 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_int_type, tmp80) ;
ATSlocal (ats_int_type, tmp81) ;
ATSlocal (ats_ptr_type, tmp104) ;
// ATSlocal_void (tmp105) ;

__ats_lab__emit_tmpvarmap_dec_9:
#line 101 "ats_ccomp_util.dats"
/* ats_int_type tmp81 ; */
#line 101 "ats_ccomp_util.dats"
tmp81 = 0 ;
#line 138 "ats_ccomp_util.dats"
tmp104 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
ats_selptrset_mac(anairiats_sum_4, tmp104, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_4, tmp104, atslab_1, (&tmp81)) ;
ats_selptrset_mac(anairiats_sum_4, tmp104, atslab_2, arg1) ;
#line 140 "ats_ccomp_util.dats"
/* tmp105 = */ map_foreach_inf_01637_ats_ptr_type_2cats_int_type (arg2, &f_10, tmp104) ;
#line 142 "ats_ccomp_util.dats"
// 
#line 142 "ats_ccomp_util.dats"
ATS_FREE(tmp104) ;
#line 144 "ats_ccomp_util.dats"
tmp80 = tmp81 ;
return (tmp80) ;
} /* end of [_emit_tmpvarmap_dec_9] */

/*
// /home/hwxi/Research/Anairiats/src/ats_ccomp_util.dats: 4968(line=160, offs=6) -- 5646(line=177, offs=6)
*/
ATSstaticdec()
ats_void_type
f_14 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
// ATSlocal_void (tmp120) ;
ATSlocal (ats_ptr_type, tmp121) ;
ATSlocal (ats_ptr_type, tmp122) ;
ATSlocal (ats_int_type, tmp123) ;
ATSlocal (ats_int_type, tmp124) ;
ATSlocal (ats_bool_type, tmp125) ;
// ATSlocal_void (tmp126) ;
// ATSlocal_void (tmp127) ;
// ATSlocal_void (tmp128) ;
// ATSlocal_void (tmp129) ;
ATSlocal (ats_ptr_type, tmp130) ;

__ats_lab_f_14:
#line 162 "ats_ccomp_util.dats"
// 
#line 162 "ats_ccomp_util.dats"
tmp121 = ats_caselptr_mac(anairiats_sum_0, arg2, atslab_0) ;
#line 162 "ats_ccomp_util.dats"
tmp122 = ats_caselptr_mac(anairiats_sum_0, arg2, atslab_1) ;
#line 163 "ats_ccomp_util.dats"
tmp124 = ats_ptrget_mac(ats_int_type, tmp122) ;
#line 163 "ats_ccomp_util.dats"
tmp123 = atspre_add_int_int (tmp124, 1) ;
#line 163 "ats_ccomp_util.dats"
ats_ptrget_mac(ats_int_type, tmp122) = tmp123 ;
#line 164 "ats_ccomp_util.dats"
do {
/* branch: __ats_lab_23 */
#line 165 "ats_ccomp_util.dats"
__ats_lab_23_0:
#line 165 "ats_ccomp_util.dats"
__ats_lab_23_1:
#line 165 "ats_ccomp_util.dats"
tmp125 = ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__tmpvar_is_void (arg0) ;
#line 165 "ats_ccomp_util.dats"
if (!tmp125) { goto __ats_lab_24_1 ; }
break ;

/* branch: __ats_lab_24 */
#line 165 "ats_ccomp_util.dats"
__ats_lab_24_0:
#line 165 "ats_ccomp_util.dats"
__ats_lab_24_1:
#line 166 "ats_ccomp_util.dats"
/* tmp126 = */ atspre_fprint_string (tmp121, ATSstrcst("ATS_GC_MARKROOT(&")) ;
#line 167 "ats_ccomp_util.dats"
/* tmp127 = */ ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__emit_tmpvar (tmp121, arg0) ;
#line 168 "ats_ccomp_util.dats"
/* tmp128 = */ atspre_fprint_string (tmp121, ATSstrcst(", sizeof(")) ;
#line 169 "ats_ccomp_util.dats"
tmp130 = ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__tmpvar_get_typ (arg0) ;
#line 169 "ats_ccomp_util.dats"
/* tmp129 = */ ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__emit_hityp (tmp121, tmp130) ;
#line 170 "ats_ccomp_util.dats"
/* tmp120 = */ atspre_fprint_string (tmp121, ATSstrcst(")) ;\n")) ;
break ;
} while (0) ;
return /* (tmp120) */ ;
} /* end of [f_14] */

/*
// /home/hwxi/Research/Anairiats/src/ats_ccomp_util.dats: 4726(line=153, offs=4) -- 5891(line=185, offs=4)
*/
ATSstaticdec()
ats_int_type
_emit_tmpvarmap_markroot_13 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp118) ;
ATSlocal (ats_int_type, tmp119) ;
ATSlocal (ats_ptr_type, tmp131) ;
// ATSlocal_void (tmp132) ;

__ats_lab__emit_tmpvarmap_markroot_13:
#line 157 "ats_ccomp_util.dats"
/* ats_int_type tmp119 ; */
#line 157 "ats_ccomp_util.dats"
tmp119 = 0 ;
#line 178 "ats_ccomp_util.dats"
tmp131 = ATS_MALLOC(sizeof(anairiats_sum_0)) ;
ats_selptrset_mac(anairiats_sum_0, tmp131, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_0, tmp131, atslab_1, (&tmp119)) ;
#line 180 "ats_ccomp_util.dats"
/* tmp132 = */ map_foreach_inf_01637_ats_ptr_type_2cats_int_type (arg1, &f_14, tmp131) ;
#line 182 "ats_ccomp_util.dats"
// 
#line 182 "ats_ccomp_util.dats"
ATS_FREE(tmp131) ;
#line 184 "ats_ccomp_util.dats"
tmp118 = tmp119 ;
return (tmp118) ;
} /* end of [_emit_tmpvarmap_markroot_13] */

/*
// /home/hwxi/Research/Anairiats/src/ats_ccomp_util.dats: 6020(line=194, offs=15) -- 6078(line=195, offs=54)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__tmpvarmap_nil () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp133) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__tmpvarmap_nil:
#line 195 "ats_ccomp_util.dats"
tmp133 = ATS_2d0_2e2_2e6_2src_2ats_map_lin_2esats__map_make (&ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__compare_tmpvar_tmpvar) ;
return (tmp133) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__tmpvarmap_nil] */

/*
// /home/hwxi/Research/Anairiats/src/ats_map_lin.dats: 2005(line=62, offs=3) -- 2140(line=65, offs=4)
*/
ATSstaticdec()
ats_void_type
bst_free_024_ats_ptr_type_2cats_int_type (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp137) ;
ATSlocal (ats_ptr_type, tmp138) ;
ATSlocal (ats_ptr_type, tmp139) ;
// ATSlocal_void (tmp140) ;

__ats_lab_bst_free_024_ats_ptr_type_2cats_int_type:
#line 62 "ats_map_lin.dats"
do {
/* branch: __ats_lab_25 */
#line 63 "ats_map_lin.dats"
__ats_lab_25_0:
#line 63 "ats_map_lin.dats"
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_26_0 ; }
#line 63 "ats_map_lin.dats"
__ats_lab_25_1:
#line 63 "ats_map_lin.dats"
tmp138 = ats_caselptr_mac(anairiats_sum_1, arg0, atslab_3) ;
#line 63 "ats_map_lin.dats"
tmp139 = ats_caselptr_mac(anairiats_sum_1, arg0, atslab_4) ;
#line 63 "ats_map_lin.dats"
ATS_FREE(arg0) ;
#line 63 "ats_map_lin.dats"
/* tmp140 = */ bst_free_024_ats_ptr_type_2cats_int_type (tmp138) ;
#line 63 "ats_map_lin.dats"
arg0 = tmp139 ;
#line 63 "ats_map_lin.dats"
goto __ats_lab_bst_free_024_ats_ptr_type_2cats_int_type ; // tail call
break ;

/* branch: __ats_lab_26 */
#line 64 "ats_map_lin.dats"
__ats_lab_26_0:
#line 64 "ats_map_lin.dats"
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 64 "ats_map_lin.dats"
__ats_lab_26_1:
break ;
} while (0) ;
return /* (tmp137) */ ;
} /* end of [bst_free_024_ats_ptr_type_2cats_int_type] */

/*
// /home/hwxi/Research/Anairiats/src/ats_map_lin.dats: 9593(line=329, offs=10) -- 9649(line=330, offs=51)
*/
ATSstaticdec()
ats_void_type
map_free_01630_ats_ptr_type_2cats_int_type (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp135) ;
ATSlocal (ats_ptr_type, tmp136) ;

__ats_lab_map_free_01630_ats_ptr_type_2cats_int_type:
#line 330 "ats_map_lin.dats"
// 
#line 330 "ats_map_lin.dats"
tmp136 = ats_caselptr_mac(anairiats_sum_0, arg0, atslab_1) ;
#line 330 "ats_map_lin.dats"
ATS_FREE(arg0) ;
#line 330 "ats_map_lin.dats"
/* tmp135 = */ bst_free_024_ats_ptr_type_2cats_int_type (tmp136) ;
return /* (tmp135) */ ;
} /* end of [map_free_01630_ats_ptr_type_2cats_int_type] */

/*
// /home/hwxi/Research/Anairiats/src/ats_ccomp_util.dats: 6132(line=198, offs=26) -- 6160(line=198, offs=54)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__tmpvarmap_free (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp134) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__tmpvarmap_free:
#line 198 "ats_ccomp_util.dats"
/* tmp134 = */ map_free_01630_ats_ptr_type_2cats_int_type (arg0) ;
return /* (tmp134) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__tmpvarmap_free] */

/*
// /home/hwxi/Research/Anairiats/src/ats_ccomp_util.dats: 6235(line=204, offs=7) -- 6507(line=212, offs=6)
*/
ATSstaticdec()
ats_void_type
aux_branchlst_20 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp142) ;
ATSlocal (ats_ptr_type, tmp143) ;
ATSlocal (ats_ptr_type, tmp144) ;
// ATSlocal_void (tmp145) ;
ATSlocal (ats_ptr_type, tmp146) ;

__ats_lab_aux_branchlst_20:
#line 205 "ats_ccomp_util.dats"
do {
/* branch: __ats_lab_27 */
#line 206 "ats_ccomp_util.dats"
__ats_lab_27_0:
#line 206 "ats_ccomp_util.dats"
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_28_0 ; }
#line 206 "ats_ccomp_util.dats"
__ats_lab_27_1:
#line 206 "ats_ccomp_util.dats"
tmp143 = ats_caselptr_mac(anairiats_sum_0, arg1, atslab_0) ;
#line 206 "ats_ccomp_util.dats"
tmp144 = ats_caselptr_mac(anairiats_sum_0, arg1, atslab_1) ;
#line 207 "ats_ccomp_util.dats"
tmp146 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_5, tmp143), atslab_branch_inss) ;
#line 207 "ats_ccomp_util.dats"
/* tmp145 = */ ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp146) ;
#line 209 "ats_ccomp_util.dats"
arg0 = arg0 ;
#line 209 "ats_ccomp_util.dats"
arg1 = tmp144 ;
#line 209 "ats_ccomp_util.dats"
goto __ats_lab_aux_branchlst_20 ; // tail call
break ;

/* branch: __ats_lab_28 */
#line 211 "ats_ccomp_util.dats"
__ats_lab_28_0:
#line 211 "ats_ccomp_util.dats"
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 211 "ats_ccomp_util.dats"
__ats_lab_28_1:
break ;
} while (0) ;
return /* (tmp142) */ ;
} /* end of [aux_branchlst_20] */

/*
// /home/hwxi/Research/Anairiats/src/ats_ccomp_util.dats: 6214(line=203, offs=21) -- 9052(line=274, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instr_tmpvarmap_add (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp141) ;
ATSlocal (ats_ptr_type, tmp147) ;
ATSlocal (ats_ptr_type, tmp148) ;
ATSlocal (ats_ptr_type, tmp149) ;
ATSlocal (ats_ptr_type, tmp150) ;
ATSlocal (ats_ptr_type, tmp151) ;
ATSlocal (ats_ptr_type, tmp152) ;
ATSlocal (ats_ptr_type, tmp153) ;
// ATSlocal_void (tmp154) ;
ATSlocal (ats_ptr_type, tmp155) ;
ATSlocal (ats_ptr_type, tmp156) ;
ATSlocal (ats_ptr_type, tmp157) ;
// ATSlocal_void (tmp158) ;
// ATSlocal_void (tmp159) ;
ATSlocal (ats_ptr_type, tmp160) ;
ATSlocal (ats_ptr_type, tmp161) ;
ATSlocal (ats_ptr_type, tmp162) ;
ATSlocal (ats_ptr_type, tmp163) ;
ATSlocal (ats_ptr_type, tmp164) ;
ATSlocal (ats_ptr_type, tmp165) ;
ATSlocal (ats_ptr_type, tmp166) ;
ATSlocal (ats_ptr_type, tmp167) ;
// ATSlocal_void (tmp168) ;
// ATSlocal_void (tmp169) ;
// ATSlocal_void (tmp170) ;
ATSlocal (ats_ptr_type, tmp171) ;
ATSlocal (ats_ptr_type, tmp172) ;
ATSlocal (ats_ptr_type, tmp173) ;
ATSlocal (ats_ptr_type, tmp174) ;
ATSlocal (ats_ptr_type, tmp175) ;
ATSlocal (ats_ptr_type, tmp176) ;
ATSlocal (ats_ptr_type, tmp177) ;
ATSlocal (ats_ptr_type, tmp178) ;
ATSlocal (ats_ptr_type, tmp179) ;
ATSlocal (ats_ptr_type, tmp180) ;
ATSlocal (ats_ptr_type, tmp181) ;
ATSlocal (ats_ptr_type, tmp182) ;
ATSlocal (ats_ptr_type, tmp183) ;
ATSlocal (ats_ptr_type, tmp184) ;
ATSlocal (ats_ptr_type, tmp185) ;
// ATSlocal_void (tmp186) ;
// ATSlocal_void (tmp187) ;
ATSlocal (ats_ptr_type, tmp188) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instr_tmpvarmap_add:
#line 214 "ats_ccomp_util.dats"
tmp147 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_6, arg1), atslab_instr_node) ;
#line 214 "ats_ccomp_util.dats"
do {
/* branch: __ats_lab_29 */
#line 216 "ats_ccomp_util.dats"
__ats_lab_29_0:
#line 216 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 0) { goto __ats_lab_30_0 ; }
#line 216 "ats_ccomp_util.dats"
__ats_lab_29_1:
#line 216 "ats_ccomp_util.dats"
tmp148 = ats_caselptr_mac(anairiats_sum_7, tmp147, atslab_0) ;
#line 216 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_root_7 (arg0, tmp148) ;
break ;

/* branch: __ats_lab_30 */
#line 217 "ats_ccomp_util.dats"
__ats_lab_30_0:
#line 217 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 1) { goto __ats_lab_31_0 ; }
#line 217 "ats_ccomp_util.dats"
__ats_lab_30_1:
#line 217 "ats_ccomp_util.dats"
tmp149 = ats_caselptr_mac(anairiats_sum_8, tmp147, atslab_0) ;
#line 217 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_root_7 (arg0, tmp149) ;
break ;

/* branch: __ats_lab_31 */
#line 219 "ats_ccomp_util.dats"
__ats_lab_31_0:
#line 219 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 3) { goto __ats_lab_32_0 ; }
#line 219 "ats_ccomp_util.dats"
__ats_lab_31_1:
#line 219 "ats_ccomp_util.dats"
tmp150 = ats_caselptr_mac(anairiats_sum_9, tmp147, atslab_1) ;
#line 219 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_0 (arg0, tmp150) ;
break ;

/* branch: __ats_lab_32 */
#line 221 "ats_ccomp_util.dats"
__ats_lab_32_0:
#line 221 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 4) { goto __ats_lab_33_0 ; }
#line 221 "ats_ccomp_util.dats"
__ats_lab_32_1:
#line 221 "ats_ccomp_util.dats"
tmp151 = ats_caselptr_mac(anairiats_sum_9, tmp147, atslab_0) ;
#line 221 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_root_7 (arg0, tmp151) ;
break ;

/* branch: __ats_lab_33 */
#line 225 "ats_ccomp_util.dats"
__ats_lab_33_0:
#line 225 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 6) { goto __ats_lab_34_0 ; }
#line 225 "ats_ccomp_util.dats"
__ats_lab_33_1:
#line 226 "ats_ccomp_util.dats"
tmp152 = ats_caselptr_mac(anairiats_sum_10, tmp147, atslab_1) ;
#line 226 "ats_ccomp_util.dats"
tmp153 = ats_caselptr_mac(anairiats_sum_10, tmp147, atslab_2) ;
#line 228 "ats_ccomp_util.dats"
/* tmp154 = */ ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp152) ;
#line 229 "ats_ccomp_util.dats"
/* tmp141 = */ ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp153) ;
break ;

/* branch: __ats_lab_34 */
#line 231 "ats_ccomp_util.dats"
__ats_lab_34_0:
#line 231 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 14) { goto __ats_lab_35_0 ; }
#line 231 "ats_ccomp_util.dats"
__ats_lab_34_1:
#line 232 "ats_ccomp_util.dats"
tmp155 = ats_caselptr_mac(anairiats_sum_9, tmp147, atslab_0) ;
#line 232 "ats_ccomp_util.dats"
tmp156 = ats_caselptr_mac(anairiats_sum_9, tmp147, atslab_2) ;
#line 232 "ats_ccomp_util.dats"
tmp157 = ats_caselptr_mac(anairiats_sum_9, tmp147, atslab_3) ;
#line 234 "ats_ccomp_util.dats"
/* tmp158 = */ tmpvarmap_add_root_7 (arg0, tmp155) ;
#line 235 "ats_ccomp_util.dats"
/* tmp159 = */ ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp156) ;
#line 236 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_root_7 (arg0, tmp157) ;
break ;

/* branch: __ats_lab_35 */
#line 238 "ats_ccomp_util.dats"
__ats_lab_35_0:
#line 238 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 17) { goto __ats_lab_36_0 ; }
#line 238 "ats_ccomp_util.dats"
__ats_lab_35_1:
#line 238 "ats_ccomp_util.dats"
tmp160 = ats_caselptr_mac(anairiats_sum_11, tmp147, atslab_0) ;
#line 238 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_root_7 (arg0, tmp160) ;
break ;

/* branch: __ats_lab_36 */
#line 239 "ats_ccomp_util.dats"
__ats_lab_36_0:
#line 239 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 18) { goto __ats_lab_37_0 ; }
#line 239 "ats_ccomp_util.dats"
__ats_lab_36_1:
#line 239 "ats_ccomp_util.dats"
tmp161 = ats_caselptr_mac(anairiats_sum_10, tmp147, atslab_0) ;
#line 239 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_root_7 (arg0, tmp161) ;
break ;

/* branch: __ats_lab_37 */
#line 240 "ats_ccomp_util.dats"
__ats_lab_37_0:
#line 240 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 19) { goto __ats_lab_38_0 ; }
#line 240 "ats_ccomp_util.dats"
__ats_lab_37_1:
#line 240 "ats_ccomp_util.dats"
tmp162 = ats_caselptr_mac(anairiats_sum_11, tmp147, atslab_0) ;
#line 240 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_root_7 (arg0, tmp162) ;
break ;

/* branch: __ats_lab_38 */
#line 241 "ats_ccomp_util.dats"
__ats_lab_38_0:
#line 241 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 20) { goto __ats_lab_39_0 ; }
#line 241 "ats_ccomp_util.dats"
__ats_lab_38_1:
#line 241 "ats_ccomp_util.dats"
tmp163 = ats_caselptr_mac(anairiats_sum_10, tmp147, atslab_0) ;
#line 241 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_root_7 (arg0, tmp163) ;
break ;

/* branch: __ats_lab_39 */
#line 242 "ats_ccomp_util.dats"
__ats_lab_39_0:
#line 242 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 21) { goto __ats_lab_40_0 ; }
#line 242 "ats_ccomp_util.dats"
__ats_lab_39_1:
#line 244 "ats_ccomp_util.dats"
tmp164 = ats_caselptr_mac(anairiats_sum_12, tmp147, atslab_3) ;
#line 244 "ats_ccomp_util.dats"
tmp165 = ats_caselptr_mac(anairiats_sum_12, tmp147, atslab_5) ;
#line 244 "ats_ccomp_util.dats"
tmp166 = ats_caselptr_mac(anairiats_sum_12, tmp147, atslab_6) ;
#line 244 "ats_ccomp_util.dats"
tmp167 = ats_caselptr_mac(anairiats_sum_12, tmp147, atslab_7) ;
#line 246 "ats_ccomp_util.dats"
/* tmp168 = */ ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp164) ;
#line 247 "ats_ccomp_util.dats"
/* tmp169 = */ ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp165) ;
#line 248 "ats_ccomp_util.dats"
/* tmp170 = */ ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp166) ;
#line 249 "ats_ccomp_util.dats"
/* tmp141 = */ ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp167) ;
break ;

/* branch: __ats_lab_40 */
#line 251 "ats_ccomp_util.dats"
__ats_lab_40_0:
#line 251 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 24) { goto __ats_lab_41_0 ; }
#line 251 "ats_ccomp_util.dats"
__ats_lab_40_1:
#line 251 "ats_ccomp_util.dats"
tmp171 = ats_caselptr_mac(anairiats_sum_9, tmp147, atslab_0) ;
#line 251 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_root_7 (arg0, tmp171) ;
break ;

/* branch: __ats_lab_41 */
#line 252 "ats_ccomp_util.dats"
__ats_lab_41_0:
#line 252 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 25) { goto __ats_lab_42_0 ; }
#line 252 "ats_ccomp_util.dats"
__ats_lab_41_1:
#line 252 "ats_ccomp_util.dats"
tmp172 = ats_caselptr_mac(anairiats_sum_8, tmp147, atslab_0) ;
#line 252 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_root_7 (arg0, tmp172) ;
break ;

/* branch: __ats_lab_42 */
#line 253 "ats_ccomp_util.dats"
__ats_lab_42_0:
#line 253 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 26) { goto __ats_lab_43_0 ; }
#line 253 "ats_ccomp_util.dats"
__ats_lab_42_1:
#line 253 "ats_ccomp_util.dats"
tmp173 = ats_caselptr_mac(anairiats_sum_8, tmp147, atslab_0) ;
#line 253 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_root_7 (arg0, tmp173) ;
break ;

/* branch: __ats_lab_43 */
#line 254 "ats_ccomp_util.dats"
__ats_lab_43_0:
#line 254 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 27) { goto __ats_lab_44_0 ; }
#line 254 "ats_ccomp_util.dats"
__ats_lab_43_1:
#line 254 "ats_ccomp_util.dats"
tmp174 = ats_caselptr_mac(anairiats_sum_10, tmp147, atslab_0) ;
#line 254 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_root_7 (arg0, tmp174) ;
break ;

/* branch: __ats_lab_44 */
#line 255 "ats_ccomp_util.dats"
__ats_lab_44_0:
#line 255 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 28) { goto __ats_lab_45_0 ; }
#line 255 "ats_ccomp_util.dats"
__ats_lab_44_1:
#line 255 "ats_ccomp_util.dats"
tmp175 = ats_caselptr_mac(anairiats_sum_10, tmp147, atslab_0) ;
#line 255 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_root_7 (arg0, tmp175) ;
break ;

/* branch: __ats_lab_45 */
#line 256 "ats_ccomp_util.dats"
__ats_lab_45_0:
#line 256 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 29) { goto __ats_lab_46_0 ; }
#line 256 "ats_ccomp_util.dats"
__ats_lab_45_1:
#line 256 "ats_ccomp_util.dats"
tmp176 = ats_caselptr_mac(anairiats_sum_11, tmp147, atslab_0) ;
#line 256 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_root_7 (arg0, tmp176) ;
break ;

/* branch: __ats_lab_46 */
#line 257 "ats_ccomp_util.dats"
__ats_lab_46_0:
#line 257 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 30) { goto __ats_lab_47_0 ; }
#line 257 "ats_ccomp_util.dats"
__ats_lab_46_1:
#line 257 "ats_ccomp_util.dats"
tmp177 = ats_caselptr_mac(anairiats_sum_11, tmp147, atslab_0) ;
#line 257 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_root_7 (arg0, tmp177) ;
break ;

/* branch: __ats_lab_47 */
#line 258 "ats_ccomp_util.dats"
__ats_lab_47_0:
#line 258 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 32) { goto __ats_lab_48_0 ; }
#line 258 "ats_ccomp_util.dats"
__ats_lab_47_1:
#line 258 "ats_ccomp_util.dats"
tmp178 = ats_caselptr_mac(anairiats_sum_11, tmp147, atslab_0) ;
#line 258 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_root_7 (arg0, tmp178) ;
break ;

/* branch: __ats_lab_48 */
#line 259 "ats_ccomp_util.dats"
__ats_lab_48_0:
#line 259 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 33) { goto __ats_lab_49_0 ; }
#line 259 "ats_ccomp_util.dats"
__ats_lab_48_1:
#line 259 "ats_ccomp_util.dats"
tmp179 = ats_caselptr_mac(anairiats_sum_10, tmp147, atslab_0) ;
#line 259 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_root_7 (arg0, tmp179) ;
break ;

/* branch: __ats_lab_49 */
#line 260 "ats_ccomp_util.dats"
__ats_lab_49_0:
#line 260 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 34) { goto __ats_lab_50_0 ; }
#line 260 "ats_ccomp_util.dats"
__ats_lab_49_1:
#line 260 "ats_ccomp_util.dats"
tmp180 = ats_caselptr_mac(anairiats_sum_13, tmp147, atslab_0) ;
#line 260 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_root_7 (arg0, tmp180) ;
break ;

/* branch: __ats_lab_50 */
#line 261 "ats_ccomp_util.dats"
__ats_lab_50_0:
#line 261 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 35) { goto __ats_lab_51_0 ; }
#line 261 "ats_ccomp_util.dats"
__ats_lab_50_1:
#line 261 "ats_ccomp_util.dats"
tmp181 = ats_caselptr_mac(anairiats_sum_13, tmp147, atslab_0) ;
#line 261 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_root_7 (arg0, tmp181) ;
break ;

/* branch: __ats_lab_51 */
#line 266 "ats_ccomp_util.dats"
__ats_lab_51_0:
#line 266 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 36) { goto __ats_lab_52_0 ; }
#line 266 "ats_ccomp_util.dats"
__ats_lab_51_1:
#line 266 "ats_ccomp_util.dats"
tmp182 = ats_caselptr_mac(anairiats_sum_14, tmp147, atslab_0) ;
#line 266 "ats_ccomp_util.dats"
/* tmp141 = */ aux_branchlst_20 (arg0, tmp182) ;
break ;

/* branch: __ats_lab_52 */
#line 267 "ats_ccomp_util.dats"
__ats_lab_52_0:
#line 267 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 45) { goto __ats_lab_53_0 ; }
#line 267 "ats_ccomp_util.dats"
__ats_lab_52_1:
#line 267 "ats_ccomp_util.dats"
tmp183 = ats_caselptr_mac(anairiats_sum_10, tmp147, atslab_0) ;
#line 267 "ats_ccomp_util.dats"
tmp184 = ats_caselptr_mac(anairiats_sum_10, tmp147, atslab_1) ;
#line 267 "ats_ccomp_util.dats"
tmp185 = ats_caselptr_mac(anairiats_sum_10, tmp147, atslab_2) ;
#line 268 "ats_ccomp_util.dats"
/* tmp186 = */ ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp183) ;
#line 270 "ats_ccomp_util.dats"
/* tmp187 = */ tmpvarmap_add_root_7 (arg0, tmp184) ;
#line 270 "ats_ccomp_util.dats"
/* tmp141 = */ aux_branchlst_20 (arg0, tmp185) ;
break ;

/* branch: __ats_lab_53 */
#line 272 "ats_ccomp_util.dats"
__ats_lab_53_0:
#line 272 "ats_ccomp_util.dats"
if (((ats_sum_ptr_type)tmp147)->tag != 46) { goto __ats_lab_54_0 ; }
#line 272 "ats_ccomp_util.dats"
__ats_lab_53_1:
#line 272 "ats_ccomp_util.dats"
tmp188 = ats_caselptr_mac(anairiats_sum_14, tmp147, atslab_0) ;
#line 272 "ats_ccomp_util.dats"
/* tmp141 = */ tmpvarmap_add_0 (arg0, tmp188) ;
break ;

/* branch: __ats_lab_54 */
#line 273 "ats_ccomp_util.dats"
__ats_lab_54_0:
#line 273 "ats_ccomp_util.dats"
__ats_lab_54_1:
break ;
} while (0) ;
return /* (tmp141) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instr_tmpvarmap_add] */

/*
// /home/hwxi/Research/Anairiats/src/ats_ccomp_util.dats: 9119(line=277, offs=24) -- 9300(line=281, offs=22)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instrlst_tmpvarmap_add (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp189) ;
ATSlocal (ats_ptr_type, tmp190) ;
ATSlocal (ats_ptr_type, tmp191) ;
// ATSlocal_void (tmp192) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instrlst_tmpvarmap_add:
#line 277 "ats_ccomp_util.dats"
do {
/* branch: __ats_lab_55 */
#line 278 "ats_ccomp_util.dats"
__ats_lab_55_0:
#line 278 "ats_ccomp_util.dats"
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_56_0 ; }
#line 278 "ats_ccomp_util.dats"
__ats_lab_55_1:
#line 278 "ats_ccomp_util.dats"
tmp190 = ats_caselptr_mac(anairiats_sum_0, arg1, atslab_0) ;
#line 278 "ats_ccomp_util.dats"
tmp191 = ats_caselptr_mac(anairiats_sum_0, arg1, atslab_1) ;
#line 279 "ats_ccomp_util.dats"
/* tmp192 = */ ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instr_tmpvarmap_add (arg0, tmp190) ;
#line 279 "ats_ccomp_util.dats"
arg0 = arg0 ;
#line 279 "ats_ccomp_util.dats"
arg1 = tmp191 ;
#line 279 "ats_ccomp_util.dats"
goto __ats_lab_ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instrlst_tmpvarmap_add ; // tail call
break ;

/* branch: __ats_lab_56 */
#line 281 "ats_ccomp_util.dats"
__ats_lab_56_0:
#line 281 "ats_ccomp_util.dats"
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 281 "ats_ccomp_util.dats"
__ats_lab_56_1:
break ;
} while (0) ;
return /* (tmp189) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instrlst_tmpvarmap_add] */

/*
// /home/hwxi/Research/Anairiats/src/ats_ccomp_util.dats: 9393(line=287, offs=26) -- 9474(line=288, offs=63)
*/
ATSglobaldec()
ats_int_type
ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__emit_tmpvarmap_dec_local (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp193) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__emit_tmpvarmap_dec_local:
#line 288 "ats_ccomp_util.dats"
tmp193 = _emit_tmpvarmap_dec_9 (arg0, 0, arg1) ;
return (tmp193) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__emit_tmpvarmap_dec_local] */

/*
// /home/hwxi/Research/Anairiats/src/ats_ccomp_util.dats: 9549(line=292, offs=27) -- 9631(line=293, offs=64)
*/
ATSglobaldec()
ats_int_type
ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__emit_tmpvarmap_dec_static (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp194) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__emit_tmpvarmap_dec_static:
#line 293 "ats_ccomp_util.dats"
tmp194 = _emit_tmpvarmap_dec_9 (arg0, 1, arg1) ;
return (tmp194) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__emit_tmpvarmap_dec_static] */

/*
// /home/hwxi/Research/Anairiats/src/ats_ccomp_util.dats: 9726(line=299, offs=25) -- 9800(line=300, offs=56)
*/
ATSglobaldec()
ats_int_type
ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__emit_tmpvarmap_markroot (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp195) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__emit_tmpvarmap_markroot:
#line 300 "ats_ccomp_util.dats"
tmp195 = _emit_tmpvarmap_markroot_13 (arg0, arg1) ;
return (tmp195) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__emit_tmpvarmap_markroot] */

/*
// /home/hwxi/Research/Anairiats/src/ats_ccomp_util.dats: 9894(line=307, offs=3) -- 10049(line=310, offs=2)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__funentry_tmpvarmap_add (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp196) ;
// ATSlocal_void (tmp197) ;
ATSlocal (ats_ptr_type, tmp198) ;
ATSlocal (ats_ptr_type, tmp199) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__funentry_tmpvarmap_add:
#line 308 "ats_ccomp_util.dats"
tmp198 = ATS_2d0_2e2_2e6_2src_2ats_ccomp_env_2esats__funentry_get_body (arg1) ;
#line 308 "ats_ccomp_util.dats"
/* tmp197 = */ ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp198) ;
#line 309 "ats_ccomp_util.dats"
tmp199 = ATS_2d0_2e2_2e6_2src_2ats_ccomp_env_2esats__funentry_get_ret (arg1) ;
#line 309 "ats_ccomp_util.dats"
/* tmp196 = */ tmpvarmap_add_root_7 (arg0, tmp199) ;
return /* (tmp196) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__funentry_tmpvarmap_add] */

/*
// /home/hwxi/Research/Anairiats/src/ats_ccomp_util.dats: 10190(line=317, offs=7) -- 10460(line=322, offs=30)
*/
ATSstaticdec()
ats_void_type
loop_27 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp201) ;
ATSlocal (ats_ptr_type, tmp202) ;
ATSlocal (ats_ptr_type, tmp203) ;
// ATSlocal_void (tmp204) ;

__ats_lab_loop_27:
#line 318 "ats_ccomp_util.dats"
do {
/* branch: __ats_lab_57 */
#line 319 "ats_ccomp_util.dats"
__ats_lab_57_0:
#line 319 "ats_ccomp_util.dats"
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_58_0 ; }
#line 319 "ats_ccomp_util.dats"
__ats_lab_57_1:
#line 319 "ats_ccomp_util.dats"
tmp202 = ats_caselptr_mac(anairiats_sum_15, arg1, atslab_2) ;
#line 319 "ats_ccomp_util.dats"
tmp203 = ats_caselptr_mac(anairiats_sum_15, arg1, atslab_3) ;
#line 320 "ats_ccomp_util.dats"
/* tmp204 = */ tmpvarmap_addlst_8 (arg0, tmp202) ;
#line 320 "ats_ccomp_util.dats"
arg0 = arg0 ;
#line 320 "ats_ccomp_util.dats"
arg1 = tmp203 ;
#line 320 "ats_ccomp_util.dats"
goto __ats_lab_loop_27 ; // tail call
break ;

/* branch: __ats_lab_58 */
#line 322 "ats_ccomp_util.dats"
__ats_lab_58_0:
#line 322 "ats_ccomp_util.dats"
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 322 "ats_ccomp_util.dats"
__ats_lab_58_1:
break ;
} while (0) ;
return /* (tmp201) */ ;
} /* end of [loop_27] */

/*
// /home/hwxi/Research/Anairiats/src/ats_ccomp_util.dats: 10145(line=316, offs=3) -- 10481(line=324, offs=2)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__tailjoinlst_tmpvarmap_add (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp200) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__tailjoinlst_tmpvarmap_add:
#line 316 "ats_ccomp_util.dats"
/* tmp200 = */ loop_27 (arg0, arg1) ;
return /* (tmp200) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__tailjoinlst_tmpvarmap_add] */

/* static load function */

extern ats_void_type ATS_2d0_2e2_2e6_2src_2ats_map_lin_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e6_2src_2ats_hiexp_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e6_2src_2ats_ccomp_env_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e6_2src_2ats_map_lin_2edats__staload (void) ;

ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_ccomp_util_2edats__staload () {
static int ATS_2d0_2e2_2e6_2src_2ats_ccomp_util_2edats__staload_flag = 0 ;
if (ATS_2d0_2e2_2e6_2src_2ats_ccomp_util_2edats__staload_flag) return ;
ATS_2d0_2e2_2e6_2src_2ats_ccomp_util_2edats__staload_flag = 1 ;

ATS_2d0_2e2_2e6_2src_2ats_map_lin_2esats__staload () ;
ATS_2d0_2e2_2e6_2src_2ats_hiexp_2esats__staload () ;
ATS_2d0_2e2_2e6_2src_2ats_ccomp_2esats__staload () ;
ATS_2d0_2e2_2e6_2src_2ats_ccomp_env_2esats__staload () ;
ATS_2d0_2e2_2e6_2src_2ats_map_lin_2edats__staload () ;

// ATS_2d0_2e2_2e6_2src_2ats_ccomp_util_2edats__ENVcon.tag = 0 ;
// ATS_2d0_2e2_2e6_2src_2ats_ccomp_util_2edats__ENVcon.tag = 0 ;
return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type ATS_2d0_2e2_2e6_2src_2ats_ccomp_util_2edats__dynload_flag ;

ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_ccomp_util_2edats__dynload () {
ATS_2d0_2e2_2e6_2src_2ats_ccomp_util_2edats__dynload_flag = 1 ;
ATS_2d0_2e2_2e6_2src_2ats_ccomp_util_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [ats_ccomp_util_dats.c] */
