/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2011-10-15: 19h:51m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/option.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"
/* external codes at top */
#line 37 "ats_staexp2_dcon.dats"

#include "ats_counter.cats" /* only needed for [ATS/Geizella] */

/* type definitions */
typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_0 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_rec_1 ;

typedef struct {
anairiats_rec_1 atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_2 ;

typedef struct {
ats_ptr_type atslab_0 ;
} anairiats_sum_3 ;

typedef struct {
ats_ptr_type atslab_d2con_loc ;
ats_ptr_type atslab_d2con_fil ;
ats_ptr_type atslab_d2con_sym ;
ats_ptr_type atslab_d2con_scst ;
ats_int_type atslab_d2con_vwtp ;
ats_ptr_type atslab_d2con_qua ;
ats_int_type atslab_d2con_npf ;
ats_ptr_type atslab_d2con_arg ;
ats_int_type atslab_d2con_arity_full ;
ats_int_type atslab_d2con_arity_real ;
ats_ptr_type atslab_d2con_ind ;
ats_ptr_type atslab_d2con_typ ;
ats_int_type atslab_d2con_tag ;
atsopt_count_type atslab_d2con_stamp ;
} anairiats_rec_4 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__list_cons) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__list_nil) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__None) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__Some) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__D2CONLSTcons) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__D2CONLSTnil) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_stdout_get) () ;
ATSextern_fun(ats_void_type, atspre_stdout_view_set) () ;
ATSextern_fun(ats_ptr_type, atspre_stderr_get) () ;
ATSextern_fun(ats_void_type, atspre_stderr_view_set) () ;
ATSextern_fun(ats_int_type, atspre_add_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_sub_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ieq) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ineq) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_string) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_int_type, ATS_2d0_2e2_2e6_2src_2ats_list_2esats__list_length) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_symbol_2esats__fprint_symbol) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_int_type, ATS_2d0_2e2_2e6_2src_2ats_stamp_2esats__compare_stamp_stamp) (atsopt_count_type, atsopt_count_type) ;
ATSextern_fun(atsopt_count_type, ATS_2d0_2e2_2e6_2src_2ats_stamp_2esats__d2con_stamp_make) () ;
ATSextern_fun(ats_bool_type, ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__s2rt_is_proof_fun) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__s2cst_get_srt) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_sym) (ats_ptr_type) ;
ATSextern_fun(ats_int_type, ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__compare_d2con_d2con) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__fprint_d2con) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__fprint_d2conlst) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__s2exp_is_proof) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__s2exp_confun) (ats_int_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__s2exp_cst) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__s2exp_cstapp) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__s2exp_uni) (ats_ptr_type, ats_ptr_type, ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e6_2prelude_2basics_dyn_2esats__file_mode_lte_w_w_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_ptr_type aux1_1 (ats_int_type arg0, ats_ptr_type arg1) ;
static
ats_int_type aux2_2 (ats_int_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type aux_3 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_int_type _compare_d2con_d2con_22 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_void_type aux_31 (ats_ref_type arg0, ats_ptr_type arg1, ats_int_type arg2) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 2624(line=84, offs=7) -- 2784(line=86, offs=33)
*/
ATSstaticdec()
ats_ptr_type
aux1_1 (ats_int_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp3) ;
ATSlocal (ats_ptr_type, tmp4) ;
ATSlocal (ats_bool_type, tmp5) ;
ATSlocal (ats_int_type, tmp6) ;

__ats_lab_aux1_1:
#line 84 "ats_staexp2_dcon.dats"
do {
/* branch: __ats_lab_0 */
#line 85 "ats_staexp2_dcon.dats"
__ats_lab_0_0:
#line 85 "ats_staexp2_dcon.dats"
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_1_0 ; }
#line 85 "ats_staexp2_dcon.dats"
__ats_lab_0_1:
#line 85 "ats_staexp2_dcon.dats"
tmp4 = ats_caselptr_mac(anairiats_sum_0, arg1, atslab_1) ;
#line 85 "ats_staexp2_dcon.dats"
tmp5 = atspre_gt_int_int (arg0, 0) ;
#line 85 "ats_staexp2_dcon.dats"
if (tmp5) {
#line 85 "ats_staexp2_dcon.dats"
tmp6 = atspre_sub_int_int (arg0, 1) ;
#line 85 "ats_staexp2_dcon.dats"
arg0 = tmp6 ;
#line 85 "ats_staexp2_dcon.dats"
arg1 = tmp4 ;
#line 85 "ats_staexp2_dcon.dats"
goto __ats_lab_aux1_1 ; // tail call
} else {
#line 85 "ats_staexp2_dcon.dats"
tmp3 = arg1 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_1 */
#line 86 "ats_staexp2_dcon.dats"
__ats_lab_1_0:
#line 86 "ats_staexp2_dcon.dats"
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 86 "ats_staexp2_dcon.dats"
__ats_lab_1_1:
#line 86 "ats_staexp2_dcon.dats"
tmp3 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp3) ;
} /* end of [aux1_1] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 2810(line=88, offs=7) -- 3027(line=92, offs=23)
*/
ATSstaticdec()
ats_int_type
aux2_2 (ats_int_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp7) ;
ATSlocal (ats_ptr_type, tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_bool_type, tmp10) ;
ATSlocal (ats_int_type, tmp11) ;

__ats_lab_aux2_2:
#line 88 "ats_staexp2_dcon.dats"
do {
/* branch: __ats_lab_2 */
#line 89 "ats_staexp2_dcon.dats"
__ats_lab_2_0:
#line 89 "ats_staexp2_dcon.dats"
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_3_0 ; }
#line 89 "ats_staexp2_dcon.dats"
__ats_lab_2_1:
#line 89 "ats_staexp2_dcon.dats"
tmp8 = ats_caselptr_mac(anairiats_sum_0, arg1, atslab_0) ;
#line 89 "ats_staexp2_dcon.dats"
tmp9 = ats_caselptr_mac(anairiats_sum_0, arg1, atslab_1) ;
#line 90 "ats_staexp2_dcon.dats"
tmp10 = ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__s2exp_is_proof (tmp8) ;
#line 90 "ats_staexp2_dcon.dats"
if (tmp10) {
#line 90 "ats_staexp2_dcon.dats"
arg0 = arg0 ;
#line 90 "ats_staexp2_dcon.dats"
arg1 = tmp9 ;
#line 90 "ats_staexp2_dcon.dats"
goto __ats_lab_aux2_2 ; // tail call
} else {
#line 90 "ats_staexp2_dcon.dats"
tmp11 = atspre_add_int_int (arg0, 1) ;
#line 90 "ats_staexp2_dcon.dats"
arg0 = tmp11 ;
#line 90 "ats_staexp2_dcon.dats"
arg1 = tmp9 ;
#line 90 "ats_staexp2_dcon.dats"
goto __ats_lab_aux2_2 ; // tail call
} /* end of [if] */
break ;

/* branch: __ats_lab_3 */
#line 92 "ats_staexp2_dcon.dats"
__ats_lab_3_0:
#line 92 "ats_staexp2_dcon.dats"
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 92 "ats_staexp2_dcon.dats"
__ats_lab_3_1:
#line 92 "ats_staexp2_dcon.dats"
tmp7 = arg0 ;
break ;
} while (0) ;
return (tmp7) ;
} /* end of [aux2_2] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 3146(line=99, offs=7) -- 3381(line=104, offs=25)
*/
ATSstaticdec()
ats_ptr_type
aux_3 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp14) ;
ATSlocal (anairiats_rec_1, tmp15) ;
ATSlocal (ats_ptr_type, tmp16) ;
ATSlocal (ats_ptr_type, tmp17) ;
ATSlocal (ats_ptr_type, tmp18) ;
ATSlocal (ats_ptr_type, tmp19) ;

__ats_lab_aux_3:
#line 100 "ats_staexp2_dcon.dats"
do {
/* branch: __ats_lab_4 */
#line 101 "ats_staexp2_dcon.dats"
__ats_lab_4_0:
#line 101 "ats_staexp2_dcon.dats"
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_5_0 ; }
#line 101 "ats_staexp2_dcon.dats"
__ats_lab_4_1:
#line 101 "ats_staexp2_dcon.dats"
tmp15 = ats_caselptr_mac(anairiats_sum_2, arg1, atslab_0) ;
#line 101 "ats_staexp2_dcon.dats"
tmp16 = ats_caselptr_mac(anairiats_sum_2, arg1, atslab_1) ;
#line 102 "ats_staexp2_dcon.dats"
tmp17 = ats_select_mac(tmp15, atslab_0) ;
#line 102 "ats_staexp2_dcon.dats"
tmp18 = ats_select_mac(tmp15, atslab_1) ;
#line 102 "ats_staexp2_dcon.dats"
tmp19 = aux_3 (arg0, tmp16) ;
#line 102 "ats_staexp2_dcon.dats"
tmp14 = ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__s2exp_uni (tmp17, tmp18, tmp19) ;
break ;

/* branch: __ats_lab_5 */
#line 104 "ats_staexp2_dcon.dats"
__ats_lab_5_0:
#line 104 "ats_staexp2_dcon.dats"
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 104 "ats_staexp2_dcon.dats"
__ats_lab_5_1:
#line 104 "ats_staexp2_dcon.dats"
tmp14 = arg0 ;
break ;
} while (0) ;
return (tmp14) ;
} /* end of [aux_3] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 2459(line=77, offs=22) -- 4158(line=139, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_make (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_int_type arg4, ats_ptr_type arg5, ats_int_type arg6, ats_ptr_type arg7, ats_ptr_type arg8) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp0) ;
ATSlocal (atsopt_count_type, tmp1) ;
ATSlocal (ats_int_type, tmp2) ;
ATSlocal (ats_int_type, tmp12) ;
ATSlocal (ats_ptr_type, tmp13) ;
ATSlocal (ats_ptr_type, tmp20) ;
ATSlocal (ats_ptr_type, tmp21) ;
ATSlocal (ats_ptr_type, tmp22) ;
ATSlocal (ats_ptr_type, tmp23) ;
ATSlocal (ats_ptr_type, tmp24) ;
ATSlocal (ats_ptr_type, tmp25) ;
// ATSlocal_void (tmp26) ;
// ATSlocal_void (tmp27) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_make:
#line 81 "ats_staexp2_dcon.dats"
tmp1 = ATS_2d0_2e2_2e6_2src_2ats_stamp_2esats__d2con_stamp_make () ;
#line 82 "ats_staexp2_dcon.dats"
tmp2 = ATS_2d0_2e2_2e6_2src_2ats_list_2esats__list_length (arg7) ;
#line 95 "ats_staexp2_dcon.dats"
tmp13 = aux1_1 (arg6, arg7) ;
#line 95 "ats_staexp2_dcon.dats"
tmp12 = aux2_2 (0, tmp13) ;
#line 106 "ats_staexp2_dcon.dats"
do {
/* branch: __ats_lab_6 */
#line 107 "ats_staexp2_dcon.dats"
__ats_lab_6_0:
#line 107 "ats_staexp2_dcon.dats"
if (arg8 == (ats_sum_ptr_type)0) { goto __ats_lab_7_0 ; }
#line 107 "ats_staexp2_dcon.dats"
__ats_lab_6_1:
#line 107 "ats_staexp2_dcon.dats"
tmp21 = ats_caselptr_mac(anairiats_sum_3, arg8, atslab_0) ;
#line 107 "ats_staexp2_dcon.dats"
tmp20 = ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__s2exp_cstapp (arg3, tmp21) ;
break ;

/* branch: __ats_lab_7 */
#line 107 "ats_staexp2_dcon.dats"
__ats_lab_7_0:
#line 107 "ats_staexp2_dcon.dats"
// if (arg8 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 107 "ats_staexp2_dcon.dats"
__ats_lab_7_1:
#line 107 "ats_staexp2_dcon.dats"
tmp20 = ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__s2exp_cst (arg3) ;
break ;
} while (0) ;
#line 110 "ats_staexp2_dcon.dats"
tmp23 = ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__s2exp_confun (arg6, arg7, tmp20) ;
#line 110 "ats_staexp2_dcon.dats"
tmp22 = aux_3 (tmp23, arg5) ;
#line 113 "ats_staexp2_dcon.dats"
tmp24 = atspre_ptr_alloc_tsz (sizeof(anairiats_rec_4)) ;
#line 113 "ats_staexp2_dcon.dats"
tmp25 = ats_selsin_mac(tmp24, atslab_2) ;
#line 117 "ats_staexp2_dcon.dats"
ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp25), atslab_d2con_loc) = arg0 ;
#line 118 "ats_staexp2_dcon.dats"
ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp25), atslab_d2con_fil) = arg1 ;
#line 119 "ats_staexp2_dcon.dats"
ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp25), atslab_d2con_sym) = arg2 ;
#line 120 "ats_staexp2_dcon.dats"
ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp25), atslab_d2con_scst) = arg3 ;
#line 121 "ats_staexp2_dcon.dats"
ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp25), atslab_d2con_vwtp) = arg4 ;
#line 122 "ats_staexp2_dcon.dats"
ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp25), atslab_d2con_qua) = arg5 ;
#line 123 "ats_staexp2_dcon.dats"
ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp25), atslab_d2con_npf) = arg6 ;
#line 124 "ats_staexp2_dcon.dats"
ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp25), atslab_d2con_arg) = arg7 ;
#line 125 "ats_staexp2_dcon.dats"
ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp25), atslab_d2con_arity_full) = tmp2 ;
#line 126 "ats_staexp2_dcon.dats"
ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp25), atslab_d2con_arity_real) = tmp12 ;
#line 127 "ats_staexp2_dcon.dats"
ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp25), atslab_d2con_ind) = arg8 ;
#line 128 "ats_staexp2_dcon.dats"
ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp25), atslab_d2con_typ) = tmp22 ;
#line 129 "ats_staexp2_dcon.dats"
ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp25), atslab_d2con_tag) = -1 ;
#line 130 "ats_staexp2_dcon.dats"
ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp25), atslab_d2con_stamp) = tmp1 ;
#line 133 "ats_staexp2_dcon.dats"
/* tmp26 = */ atspre_vbox_make_view_ptr (tmp25) ;
#line 133 "ats_staexp2_dcon.dats"
/* tmp27 = ats_selsin_mac(tmp26, atslab_1) */ ;
#line 137 "ats_staexp2_dcon.dats"
tmp0 = tmp25 ;
return (tmp0) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_make] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 4228(line=143, offs=25) -- 4285(line=144, offs=50)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_fil (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp28) ;
ATSlocal (ats_ptr_type, tmp29) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_fil:
#line 144 "ats_staexp2_dcon.dats"
tmp29 = ats_selsin_mac(arg0, atslab_1) ;
#line 144 "ats_staexp2_dcon.dats"
tmp28 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp29), atslab_d2con_fil) ;
return (tmp28) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_fil] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 4311(line=146, offs=25) -- 4368(line=147, offs=50)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_sym (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp30) ;
ATSlocal (ats_ptr_type, tmp31) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_sym:
#line 147 "ats_staexp2_dcon.dats"
tmp31 = ats_selsin_mac(arg0, atslab_1) ;
#line 147 "ats_staexp2_dcon.dats"
tmp30 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp31), atslab_d2con_sym) ;
return (tmp30) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_sym] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 4395(line=149, offs=26) -- 4453(line=150, offs=51)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_scst (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp32) ;
ATSlocal (ats_ptr_type, tmp33) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_scst:
#line 150 "ats_staexp2_dcon.dats"
tmp33 = ats_selsin_mac(arg0, atslab_1) ;
#line 150 "ats_staexp2_dcon.dats"
tmp32 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp33), atslab_d2con_scst) ;
return (tmp32) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_scst] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 4480(line=152, offs=26) -- 4538(line=153, offs=51)
*/
ATSglobaldec()
ats_int_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_vwtp (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_vwtp:
#line 153 "ats_staexp2_dcon.dats"
tmp35 = ats_selsin_mac(arg0, atslab_1) ;
#line 153 "ats_staexp2_dcon.dats"
tmp34 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp35), atslab_d2con_vwtp) ;
return (tmp34) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_vwtp] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 4564(line=155, offs=25) -- 4621(line=156, offs=50)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_qua (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp36) ;
ATSlocal (ats_ptr_type, tmp37) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_qua:
#line 156 "ats_staexp2_dcon.dats"
tmp37 = ats_selsin_mac(arg0, atslab_1) ;
#line 156 "ats_staexp2_dcon.dats"
tmp36 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp37), atslab_d2con_qua) ;
return (tmp36) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_qua] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 4647(line=158, offs=25) -- 4704(line=159, offs=50)
*/
ATSglobaldec()
ats_int_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_npf (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp38) ;
ATSlocal (ats_ptr_type, tmp39) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_npf:
#line 159 "ats_staexp2_dcon.dats"
tmp39 = ats_selsin_mac(arg0, atslab_1) ;
#line 159 "ats_staexp2_dcon.dats"
tmp38 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp39), atslab_d2con_npf) ;
return (tmp38) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_npf] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 4730(line=161, offs=25) -- 4787(line=162, offs=50)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_arg (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_arg:
#line 162 "ats_staexp2_dcon.dats"
tmp41 = ats_selsin_mac(arg0, atslab_1) ;
#line 162 "ats_staexp2_dcon.dats"
tmp40 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp41), atslab_d2con_arg) ;
return (tmp40) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_arg] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 4820(line=164, offs=32) -- 4884(line=165, offs=57)
*/
ATSglobaldec()
ats_int_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_arity_full (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp42) ;
ATSlocal (ats_ptr_type, tmp43) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_arity_full:
#line 165 "ats_staexp2_dcon.dats"
tmp43 = ats_selsin_mac(arg0, atslab_1) ;
#line 165 "ats_staexp2_dcon.dats"
tmp42 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp43), atslab_d2con_arity_full) ;
return (tmp42) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_arity_full] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 4917(line=167, offs=32) -- 4981(line=168, offs=57)
*/
ATSglobaldec()
ats_int_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_arity_real (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp44) ;
ATSlocal (ats_ptr_type, tmp45) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_arity_real:
#line 168 "ats_staexp2_dcon.dats"
tmp45 = ats_selsin_mac(arg0, atslab_1) ;
#line 168 "ats_staexp2_dcon.dats"
tmp44 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp45), atslab_d2con_arity_real) ;
return (tmp44) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_arity_real] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 5007(line=170, offs=25) -- 5064(line=171, offs=50)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_typ (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp46) ;
ATSlocal (ats_ptr_type, tmp47) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_typ:
#line 171 "ats_staexp2_dcon.dats"
tmp47 = ats_selsin_mac(arg0, atslab_1) ;
#line 171 "ats_staexp2_dcon.dats"
tmp46 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp47), atslab_d2con_typ) ;
return (tmp46) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_typ] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 5090(line=173, offs=25) -- 5147(line=174, offs=50)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_ind (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp48) ;
ATSlocal (ats_ptr_type, tmp49) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_ind:
#line 174 "ats_staexp2_dcon.dats"
tmp49 = ats_selsin_mac(arg0, atslab_1) ;
#line 174 "ats_staexp2_dcon.dats"
tmp48 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp49), atslab_d2con_ind) ;
return (tmp48) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_ind] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 5173(line=176, offs=25) -- 5230(line=177, offs=50)
*/
ATSglobaldec()
ats_int_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_tag (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp50) ;
ATSlocal (ats_ptr_type, tmp51) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_tag:
#line 177 "ats_staexp2_dcon.dats"
tmp51 = ats_selsin_mac(arg0, atslab_1) ;
#line 177 "ats_staexp2_dcon.dats"
tmp50 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp51), atslab_d2con_tag) ;
return (tmp50) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_tag] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 5256(line=179, offs=25) -- 5325(line=180, offs=57)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_set_tag (ats_ptr_type arg0, ats_int_type arg1) {
/* local vardec */
// ATSlocal_void (tmp52) ;
ATSlocal (ats_ptr_type, tmp53) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_set_tag:
#line 180 "ats_staexp2_dcon.dats"
tmp53 = ats_selsin_mac(arg0, atslab_1) ;
#line 180 "ats_staexp2_dcon.dats"
ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp53), atslab_d2con_tag) = arg1 ;
return /* (tmp52) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_set_tag] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 5353(line=182, offs=27) -- 5412(line=183, offs=52)
*/
ATSglobaldec()
atsopt_count_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_stamp (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (atsopt_count_type, tmp54) ;
ATSlocal (ats_ptr_type, tmp55) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_stamp:
#line 183 "ats_staexp2_dcon.dats"
tmp55 = ats_selsin_mac(arg0, atslab_1) ;
#line 183 "ats_staexp2_dcon.dats"
tmp54 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp55), atslab_d2con_stamp) ;
return (tmp54) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_stamp] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 5462(line=188, offs=3) -- 5513(line=188, offs=54)
*/
ATSglobaldec()
ats_bool_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__lt_d2con_d2con (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp56) ;
ATSlocal (ats_int_type, tmp57) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__lt_d2con_d2con:
#line 188 "ats_staexp2_dcon.dats"
tmp57 = ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__compare_d2con_d2con (arg0, arg1) ;
#line 188 "ats_staexp2_dcon.dats"
tmp56 = atspre_ilt (tmp57, 0) ;
return (tmp56) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__lt_d2con_d2con] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 5542(line=190, offs=3) -- 5594(line=190, offs=55)
*/
ATSglobaldec()
ats_bool_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__lte_d2con_d2con (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp58) ;
ATSlocal (ats_int_type, tmp59) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__lte_d2con_d2con:
#line 190 "ats_staexp2_dcon.dats"
tmp59 = ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__compare_d2con_d2con (arg0, arg1) ;
#line 190 "ats_staexp2_dcon.dats"
tmp58 = atspre_ilte (tmp59, 0) ;
return (tmp58) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__lte_d2con_d2con] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 5623(line=193, offs=3) -- 5674(line=193, offs=54)
*/
ATSglobaldec()
ats_bool_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__eq_d2con_d2con (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp60) ;
ATSlocal (ats_int_type, tmp61) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__eq_d2con_d2con:
#line 193 "ats_staexp2_dcon.dats"
tmp61 = ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__compare_d2con_d2con (arg0, arg1) ;
#line 193 "ats_staexp2_dcon.dats"
tmp60 = atspre_ieq (tmp61, 0) ;
return (tmp60) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__eq_d2con_d2con] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 5703(line=195, offs=3) -- 5755(line=195, offs=55)
*/
ATSglobaldec()
ats_bool_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__neq_d2con_d2con (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp62) ;
ATSlocal (ats_int_type, tmp63) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__neq_d2con_d2con:
#line 195 "ats_staexp2_dcon.dats"
tmp63 = ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__compare_d2con_d2con (arg0, arg1) ;
#line 195 "ats_staexp2_dcon.dats"
tmp62 = atspre_ineq (tmp63, 0) ;
return (tmp62) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__neq_d2con_d2con] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 5760(line=197, offs=4) -- 6054(line=207, offs=4)
*/
ATSstaticdec()
ats_int_type
_compare_d2con_d2con_22 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp64) ;
ATSlocal (ats_ptr_type, tmp65) ;
ATSlocal (atsopt_count_type, tmp66) ;
ATSlocal (ats_ptr_type, tmp67) ;
ATSlocal (atsopt_count_type, tmp68) ;

__ats_lab__compare_d2con_d2con_22:
#line 200 "ats_staexp2_dcon.dats"
tmp65 = ats_selsin_mac(arg0, atslab_1) ;
#line 200 "ats_staexp2_dcon.dats"
tmp66 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp65), atslab_d2con_stamp) ;
#line 203 "ats_staexp2_dcon.dats"
tmp67 = ats_selsin_mac(arg1, atslab_1) ;
#line 203 "ats_staexp2_dcon.dats"
tmp68 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp67), atslab_d2con_stamp) ;
#line 206 "ats_staexp2_dcon.dats"
tmp64 = ATS_2d0_2e2_2e6_2src_2ats_stamp_2esats__compare_stamp_stamp (tmp66, tmp68) ;
return (tmp64) ;
} /* end of [_compare_d2con_d2con_22] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 6118(line=210, offs=21) -- 6183(line=211, offs=51)
*/
ATSglobaldec()
ats_int_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__compare_d2con_d2con (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp69) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__compare_d2con_d2con:
#line 211 "ats_staexp2_dcon.dats"
tmp69 = _compare_d2con_d2con_22 (arg0, arg1) ;
return (tmp69) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__compare_d2con_d2con] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 6289(line=219, offs=14) -- 6362(line=221, offs=4)
*/
ATSglobaldec()
ats_bool_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_is_exn (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp70) ;
ATSlocal (ats_ptr_type, tmp71) ;
ATSlocal (ats_int_type, tmp72) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_is_exn:
#line 220 "ats_staexp2_dcon.dats"
tmp71 = ats_selsin_mac(arg0, atslab_1) ;
#line 220 "ats_staexp2_dcon.dats"
tmp72 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp71), atslab_d2con_tag) ;
#line 220 "ats_staexp2_dcon.dats"
tmp70 = atspre_eq_int_int (tmp72, -1) ;
return (tmp70) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_is_exn] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 6437(line=224, offs=24) -- 6510(line=226, offs=4)
*/
ATSglobaldec()
ats_bool_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_is_msg (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp73) ;
ATSlocal (ats_ptr_type, tmp74) ;
ATSlocal (ats_int_type, tmp75) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_is_msg:
#line 225 "ats_staexp2_dcon.dats"
tmp74 = ats_selsin_mac(arg0, atslab_1) ;
#line 225 "ats_staexp2_dcon.dats"
tmp75 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp74), atslab_d2con_tag) ;
#line 225 "ats_staexp2_dcon.dats"
tmp73 = atspre_eq_int_int (tmp75, -2) ;
return (tmp73) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_is_msg] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 6562(line=229, offs=16) -- 6681(line=233, offs=4)
*/
ATSglobaldec()
ats_bool_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_is_proof (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp76) ;
ATSlocal (ats_ptr_type, tmp77) ;
ATSlocal (ats_ptr_type, tmp78) ;
ATSlocal (ats_ptr_type, tmp79) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_is_proof:
#line 230 "ats_staexp2_dcon.dats"
tmp77 = ats_selsin_mac(arg0, atslab_1) ;
#line 230 "ats_staexp2_dcon.dats"
tmp78 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_4, tmp77), atslab_d2con_scst) ;
#line 232 "ats_staexp2_dcon.dats"
tmp79 = ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__s2cst_get_srt (tmp78) ;
#line 232 "ats_staexp2_dcon.dats"
tmp76 = ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__s2rt_is_proof_fun (tmp79) ;
return (tmp76) ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_is_proof] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 6800(line=240, offs=14) -- 6876(line=241, offs=55)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__fprint_d2con (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp80) ;
ATSlocal (ats_ptr_type, tmp81) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__fprint_d2con:
#line 241 "ats_staexp2_dcon.dats"
tmp81 = ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__d2con_get_sym (arg1) ;
#line 241 "ats_staexp2_dcon.dats"
/* tmp80 = */ ATS_2d0_2e2_2e6_2src_2ats_symbol_2esats__fprint_symbol (arg0, tmp81) ;
return /* (tmp80) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__fprint_d2con] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 6925(line=244, offs=23) -- 6962(line=244, offs=60)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__print_d2con (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp82) ;
ATSlocal (ats_ptr_type, tmp83) ;
ATSlocal (ats_ptr_type, tmp84) ;
// ATSlocal_void (tmp85) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__print_d2con:
#line 244 "ats_staexp2_dcon.dats"
tmp83 = atspre_stdout_get () ;
#line 244 "ats_staexp2_dcon.dats"
tmp84 = ats_selsin_mac(tmp83, atslab_1) ;
#line 244 "ats_staexp2_dcon.dats"
/* tmp85 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__fprint_d2con (tmp84, arg0) ;
#line 244 "ats_staexp2_dcon.dats"
/* tmp82 = */ atspre_stdout_view_set () ;
return /* (tmp82) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__print_d2con] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 6985(line=245, offs=23) -- 7022(line=245, offs=60)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__prerr_d2con (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp86) ;
ATSlocal (ats_ptr_type, tmp87) ;
ATSlocal (ats_ptr_type, tmp88) ;
// ATSlocal_void (tmp89) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__prerr_d2con:
#line 245 "ats_staexp2_dcon.dats"
tmp87 = atspre_stderr_get () ;
#line 245 "ats_staexp2_dcon.dats"
tmp88 = ats_selsin_mac(tmp87, atslab_1) ;
#line 245 "ats_staexp2_dcon.dats"
/* tmp89 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__fprint_d2con (tmp88, arg0) ;
#line 245 "ats_staexp2_dcon.dats"
/* tmp86 = */ atspre_stderr_view_set () ;
return /* (tmp86) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__prerr_d2con] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 7106(line=252, offs=7) -- 7463(line=263, offs=6)
*/
ATSstaticdec()
ats_void_type
aux_31 (ats_ref_type arg0, ats_ptr_type arg1, ats_int_type arg2) {
/* local vardec */
// ATSlocal_void (tmp91) ;
ATSlocal (ats_ptr_type, tmp92) ;
ATSlocal (ats_ptr_type, tmp93) ;
// ATSlocal_void (tmp94) ;
ATSlocal (ats_bool_type, tmp95) ;
// ATSlocal_void (tmp96) ;
ATSlocal (ats_int_type, tmp97) ;

__ats_lab_aux_31:
#line 254 "ats_staexp2_dcon.dats"
do {
/* branch: __ats_lab_8 */
#line 255 "ats_staexp2_dcon.dats"
__ats_lab_8_0:
#line 255 "ats_staexp2_dcon.dats"
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_9_0 ; }
#line 255 "ats_staexp2_dcon.dats"
__ats_lab_8_1:
#line 255 "ats_staexp2_dcon.dats"
tmp92 = ats_caselptr_mac(anairiats_sum_0, arg1, atslab_0) ;
#line 255 "ats_staexp2_dcon.dats"
tmp93 = ats_caselptr_mac(anairiats_sum_0, arg1, atslab_1) ;
#line 256 "ats_staexp2_dcon.dats"
tmp95 = atspre_gt_int_int (arg2, 0) ;
#line 256 "ats_staexp2_dcon.dats"
if (tmp95) {
#line 257 "ats_staexp2_dcon.dats"
/* tmp94 = */ atspre_fprint_string (arg0, ATSstrcst(", ")) ;
} else {
/* empty */
} /* end of [if] */
#line 258 "ats_staexp2_dcon.dats"
/* tmp96 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__fprint_d2con (arg0, tmp92) ;
#line 260 "ats_staexp2_dcon.dats"
tmp97 = atspre_add_int_int (arg2, 1) ;
#line 260 "ats_staexp2_dcon.dats"
arg0 = arg0 ;
#line 260 "ats_staexp2_dcon.dats"
arg1 = tmp93 ;
#line 260 "ats_staexp2_dcon.dats"
arg2 = tmp97 ;
#line 260 "ats_staexp2_dcon.dats"
goto __ats_lab_aux_31 ; // tail call
break ;

/* branch: __ats_lab_9 */
#line 262 "ats_staexp2_dcon.dats"
__ats_lab_9_0:
#line 262 "ats_staexp2_dcon.dats"
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 262 "ats_staexp2_dcon.dats"
__ats_lab_9_1:
break ;
} while (0) ;
return /* (tmp91) */ ;
} /* end of [aux_31] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 7077(line=251, offs=7) -- 7507(line=266, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__fprint_d2conlst (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp90) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__fprint_d2conlst:
#line 265 "ats_staexp2_dcon.dats"
/* tmp90 = */ aux_31 (arg0, arg1, 0) ;
return /* (tmp90) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__fprint_d2conlst] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 7562(line=268, offs=26) -- 7604(line=268, offs=68)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__print_d2conlst (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp98) ;
ATSlocal (ats_ptr_type, tmp99) ;
ATSlocal (ats_ptr_type, tmp100) ;
// ATSlocal_void (tmp101) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__print_d2conlst:
#line 268 "ats_staexp2_dcon.dats"
tmp99 = atspre_stdout_get () ;
#line 268 "ats_staexp2_dcon.dats"
tmp100 = ats_selsin_mac(tmp99, atslab_1) ;
#line 268 "ats_staexp2_dcon.dats"
/* tmp101 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__fprint_d2conlst (tmp100, arg0) ;
#line 268 "ats_staexp2_dcon.dats"
/* tmp98 = */ atspre_stdout_view_set () ;
return /* (tmp98) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__print_d2conlst] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp2_dcon.dats: 7630(line=269, offs=26) -- 7672(line=269, offs=68)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__prerr_d2conlst (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp102) ;
ATSlocal (ats_ptr_type, tmp103) ;
ATSlocal (ats_ptr_type, tmp104) ;
// ATSlocal_void (tmp105) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__prerr_d2conlst:
#line 269 "ats_staexp2_dcon.dats"
tmp103 = atspre_stderr_get () ;
#line 269 "ats_staexp2_dcon.dats"
tmp104 = ats_selsin_mac(tmp103, atslab_1) ;
#line 269 "ats_staexp2_dcon.dats"
/* tmp105 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__fprint_d2conlst (tmp104, arg0) ;
#line 269 "ats_staexp2_dcon.dats"
/* tmp102 = */ atspre_stderr_view_set () ;
return /* (tmp102) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__prerr_d2conlst] */

/* static load function */

extern ats_void_type ATS_2d0_2e2_2e6_2src_2ats_list_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__staload (void) ;

ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_dcon_2edats__staload () {
static int ATS_2d0_2e2_2e6_2src_2ats_staexp2_dcon_2edats__staload_flag = 0 ;
if (ATS_2d0_2e2_2e6_2src_2ats_staexp2_dcon_2edats__staload_flag) return ;
ATS_2d0_2e2_2e6_2src_2ats_staexp2_dcon_2edats__staload_flag = 1 ;

ATS_2d0_2e2_2e6_2src_2ats_list_2esats__staload () ;
ATS_2d0_2e2_2e6_2src_2ats_staexp2_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type ATS_2d0_2e2_2e6_2src_2ats_staexp2_dcon_2edats__dynload_flag ;

ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp2_dcon_2edats__dynload () {
ATS_2d0_2e2_2e6_2src_2ats_staexp2_dcon_2edats__dynload_flag = 1 ;
ATS_2d0_2e2_2e6_2src_2ats_staexp2_dcon_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e6_2prelude_2basics_dyn_2esats__file_mode_lte_w_w_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [ats_staexp2_dcon_dats.c] */
