/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2011-10-15: 19h:51m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/option.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */
/* external codes at top */
/* type definitions */
typedef struct {
ats_ptr_type atslab_e1xp_loc ;
ats_ptr_type atslab_e1xp_node ;
} anairiats_rec_0 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_1 ;

typedef struct {
int tag ;
ats_char_type atslab_0 ;
} anairiats_sum_2 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_3 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_int_type atslab_1 ;
} anairiats_sum_4 ;

typedef struct {
ats_ptr_type atslab_s1rt_loc ;
ats_ptr_type atslab_s1rt_node ;
} anairiats_rec_5 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_6 ;

typedef struct {
ats_ptr_type atslab_0 ;
} anairiats_sum_7 ;

typedef struct {
ats_ptr_type atslab_s1arg_loc ;
ats_ptr_type atslab_s1arg_sym ;
ats_ptr_type atslab_s1arg_srt ;
} anairiats_rec_8 ;

typedef struct {
ats_ptr_type atslab_s1qua_loc ;
ats_ptr_type atslab_s1qua_node ;
} anairiats_rec_9 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_10 ;

typedef struct {
ats_ptr_type atslab_s1exp_loc ;
ats_ptr_type atslab_s1exp_node ;
} anairiats_rec_11 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_12 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_int_type atslab_1 ;
ats_int_type atslab_2 ;
ats_ptr_type atslab_3 ;
} anairiats_sum_13 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_14 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_15 ;

typedef struct {
ats_ptr_type atslab_s1rtext_loc ;
ats_ptr_type atslab_s1rtext_node ;
} anairiats_rec_16 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__list_cons) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__list_nil) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__None) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2prelude_2basics_sta_2esats__Some) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__E1XPapp) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__E1XPchar) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__E1XPfloat) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__E1XPide) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__E1XPint) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__E1XPlist) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__E1XPnone) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__E1XPstring) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__E1XPundef) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__E1XPcstsp) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1RTapp) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1RTlist) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1RTqid) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1RTtup) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Qprop) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Qvars) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1TEsrt) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1TEsub) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__TMPS1EXPLSTLSTnil) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__TMPS1EXPLSTLSTcons) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__LABS1EXPLSTnil) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__LABS1EXPLSTcons) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Eann) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Eany) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Eapp) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Echar) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Eexi) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Eextype) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Eimp) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Eint) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Einvar) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Elam) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Elist) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Eqid) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Eread) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Etop) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Etrans) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Etyarr) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Etyrec) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Etyrec_ext) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Etytup) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Etytup2) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Euni) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__S1Eunion) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_ptr_type, atspre_stdout_get) () ;
ATSextern_fun(ats_void_type, atspre_stdout_view_set) () ;
ATSextern_fun(ats_ptr_type, atspre_stderr_get) () ;
ATSextern_fun(ats_void_type, atspre_stderr_view_set) () ;
ATSextern_fun(ats_void_type, atspre_fprint_char) (ats_ref_type, ats_char_type) ;
ATSextern_fun(ats_int_type, atspre_add_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_int) (ats_ref_type, ats_int_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_string) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_symbol_2esats__fprint_symbol) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_label_2esats__fprint_label) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_syntax_2esats__fprint_cstsp) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_syntax_2esats__fprint_i0delst) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_syntax_2esats__fprint_s0rtq) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_syntax_2esats__fprint_funclo) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_syntax_2esats__fprint_s0taq) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_effect_2esats__fprint_effcst) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_list_2esats__fprintlst) (ats_ref_type, ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_e1xp) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_e1xplst) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rt) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rtlst) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1explst) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1explstlst) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_labs1explst) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rtext) (ats_ref_type, ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e6_2prelude_2basics_dyn_2esats__file_mode_lte_w_w_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_void_type fprint_s1arg_13 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_void_type fprint_s1arglst_14 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_void_type fprint_s1qua_15 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_void_type aux_17 (ats_ref_type arg0, ats_int_type arg1, ats_ptr_type arg2) ;
static
ats_void_type fprint_s1qualst_16 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_void_type aux_27 (ats_ref_type arg0, ats_int_type arg1, ats_ptr_type arg2) ;
static
ats_void_type aux_29 (ats_ref_type arg0, ats_int_type arg1, ats_ptr_type arg2) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 2001(line=65, offs=13) -- 3458(line=110, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_e1xp (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp0) ;
ATSlocal (ats_ptr_type, tmp1) ;
ATSlocal (ats_ptr_type, tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;
// ATSlocal_void (tmp4) ;
// ATSlocal_void (tmp5) ;
// ATSlocal_void (tmp6) ;
// ATSlocal_void (tmp7) ;
ATSlocal (ats_char_type, tmp8) ;
// ATSlocal_void (tmp9) ;
// ATSlocal_void (tmp10) ;
ATSlocal (ats_ptr_type, tmp11) ;
// ATSlocal_void (tmp12) ;
// ATSlocal_void (tmp13) ;
ATSlocal (ats_ptr_type, tmp14) ;
ATSlocal (ats_ptr_type, tmp15) ;
// ATSlocal_void (tmp16) ;
// ATSlocal_void (tmp17) ;
ATSlocal (ats_ptr_type, tmp18) ;
// ATSlocal_void (tmp19) ;
// ATSlocal_void (tmp20) ;
ATSlocal (ats_ptr_type, tmp21) ;
ATSlocal (ats_int_type, tmp22) ;
// ATSlocal_void (tmp23) ;
// ATSlocal_void (tmp24) ;
// ATSlocal_void (tmp25) ;
// ATSlocal_void (tmp26) ;
ATSlocal (ats_ptr_type, tmp27) ;
// ATSlocal_void (tmp28) ;
// ATSlocal_void (tmp29) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_e1xp:
#line 68 "ats_staexp1_print.dats"
tmp1 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_0, arg1), atslab_e1xp_node) ;
#line 68 "ats_staexp1_print.dats"
do {
/* branch: __ats_lab_0 */
#line 69 "ats_staexp1_print.dats"
__ats_lab_0_0:
#line 69 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp1)->tag != 0) { goto __ats_lab_1_0 ; }
#line 69 "ats_staexp1_print.dats"
__ats_lab_0_1:
#line 69 "ats_staexp1_print.dats"
tmp2 = ats_caselptr_mac(anairiats_sum_1, tmp1, atslab_0) ;
#line 69 "ats_staexp1_print.dats"
tmp3 = ats_caselptr_mac(anairiats_sum_1, tmp1, atslab_2) ;
#line 70 "ats_staexp1_print.dats"
/* tmp4 = */ atspre_fprint_string (arg0, ATSstrcst("E1XPapp(")) ;
#line 71 "ats_staexp1_print.dats"
/* tmp5 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_e1xp (arg0, tmp2) ;
#line 72 "ats_staexp1_print.dats"
/* tmp6 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 73 "ats_staexp1_print.dats"
/* tmp7 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_e1xplst (arg0, tmp3) ;
#line 74 "ats_staexp1_print.dats"
/* tmp0 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_1 */
#line 76 "ats_staexp1_print.dats"
__ats_lab_1_0:
#line 76 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp1)->tag != 1) { goto __ats_lab_2_0 ; }
#line 76 "ats_staexp1_print.dats"
__ats_lab_1_1:
#line 76 "ats_staexp1_print.dats"
tmp8 = ats_caselptr_mac(anairiats_sum_2, tmp1, atslab_0) ;
#line 77 "ats_staexp1_print.dats"
/* tmp9 = */ atspre_fprint_string (arg0, ATSstrcst("E1XPchar(")) ;
#line 77 "ats_staexp1_print.dats"
/* tmp10 = */ atspre_fprint_char (arg0, tmp8) ;
#line 77 "ats_staexp1_print.dats"
/* tmp0 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_2 */
#line 79 "ats_staexp1_print.dats"
__ats_lab_2_0:
#line 79 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp1)->tag != 2) { goto __ats_lab_3_0 ; }
#line 79 "ats_staexp1_print.dats"
__ats_lab_2_1:
#line 79 "ats_staexp1_print.dats"
tmp11 = ats_caselptr_mac(anairiats_sum_3, tmp1, atslab_0) ;
#line 80 "ats_staexp1_print.dats"
/* tmp12 = */ atspre_fprint_string (arg0, ATSstrcst("E1XPfloat(")) ;
#line 80 "ats_staexp1_print.dats"
/* tmp13 = */ atspre_fprint_string (arg0, tmp11) ;
#line 80 "ats_staexp1_print.dats"
/* tmp0 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_3 */
#line 82 "ats_staexp1_print.dats"
__ats_lab_3_0:
#line 82 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp1)->tag != 3) { goto __ats_lab_4_0 ; }
#line 82 "ats_staexp1_print.dats"
__ats_lab_3_1:
#line 82 "ats_staexp1_print.dats"
tmp14 = ats_caselptr_mac(anairiats_sum_3, tmp1, atslab_0) ;
#line 83 "ats_staexp1_print.dats"
/* tmp0 = */ ATS_2d0_2e2_2e6_2src_2ats_symbol_2esats__fprint_symbol (arg0, tmp14) ;
break ;

/* branch: __ats_lab_4 */
#line 85 "ats_staexp1_print.dats"
__ats_lab_4_0:
#line 85 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp1)->tag != 4) { goto __ats_lab_5_0 ; }
#line 85 "ats_staexp1_print.dats"
__ats_lab_4_1:
#line 85 "ats_staexp1_print.dats"
tmp15 = ats_caselptr_mac(anairiats_sum_3, tmp1, atslab_0) ;
#line 86 "ats_staexp1_print.dats"
/* tmp16 = */ atspre_fprint_string (arg0, ATSstrcst("E1XPint(")) ;
#line 86 "ats_staexp1_print.dats"
/* tmp17 = */ atspre_fprint_string (arg0, tmp15) ;
#line 86 "ats_staexp1_print.dats"
/* tmp0 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_5 */
#line 88 "ats_staexp1_print.dats"
__ats_lab_5_0:
#line 88 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp1)->tag != 5) { goto __ats_lab_6_0 ; }
#line 88 "ats_staexp1_print.dats"
__ats_lab_5_1:
#line 88 "ats_staexp1_print.dats"
tmp18 = ats_caselptr_mac(anairiats_sum_3, tmp1, atslab_0) ;
#line 89 "ats_staexp1_print.dats"
/* tmp19 = */ atspre_fprint_string (arg0, ATSstrcst("E1XPlist(")) ;
#line 89 "ats_staexp1_print.dats"
/* tmp20 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_e1xplst (arg0, tmp18) ;
#line 89 "ats_staexp1_print.dats"
/* tmp0 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_6 */
#line 91 "ats_staexp1_print.dats"
__ats_lab_6_0:
#line 91 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp1)->tag != 6) { goto __ats_lab_7_0 ; }
#line 91 "ats_staexp1_print.dats"
__ats_lab_6_1:
#line 92 "ats_staexp1_print.dats"
/* tmp0 = */ atspre_fprint_string (arg0, ATSstrcst("E1XPnone()")) ;
break ;

/* branch: __ats_lab_7 */
#line 94 "ats_staexp1_print.dats"
__ats_lab_7_0:
#line 94 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp1)->tag != 7) { goto __ats_lab_8_0 ; }
#line 94 "ats_staexp1_print.dats"
__ats_lab_7_1:
#line 94 "ats_staexp1_print.dats"
tmp21 = ats_caselptr_mac(anairiats_sum_4, tmp1, atslab_0) ;
#line 94 "ats_staexp1_print.dats"
tmp22 = ats_caselptr_mac(anairiats_sum_4, tmp1, atslab_1) ;
#line 95 "ats_staexp1_print.dats"
/* tmp23 = */ atspre_fprint_string (arg0, ATSstrcst("E1XPstring(")) ;
#line 96 "ats_staexp1_print.dats"
/* tmp24 = */ atspre_fprint_string (arg0, tmp21) ;
#line 97 "ats_staexp1_print.dats"
/* tmp25 = */ atspre_fprint_string (arg0, ATSstrcst(", ")) ;
#line 98 "ats_staexp1_print.dats"
/* tmp26 = */ atspre_fprint_int (arg0, tmp22) ;
#line 99 "ats_staexp1_print.dats"
/* tmp0 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_8 */
#line 101 "ats_staexp1_print.dats"
__ats_lab_8_0:
#line 101 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp1)->tag != 8) { goto __ats_lab_9_0 ; }
#line 101 "ats_staexp1_print.dats"
__ats_lab_8_1:
#line 102 "ats_staexp1_print.dats"
/* tmp0 = */ atspre_fprint_string (arg0, ATSstrcst("E1XPundef()")) ;
break ;

/* branch: __ats_lab_9 */
#line 104 "ats_staexp1_print.dats"
__ats_lab_9_0:
#line 104 "ats_staexp1_print.dats"
// if (((ats_sum_ptr_type)tmp1)->tag != 9) { ats_deadcode_failure_handle () ; }
#line 104 "ats_staexp1_print.dats"
__ats_lab_9_1:
#line 104 "ats_staexp1_print.dats"
tmp27 = ats_caselptr_mac(anairiats_sum_3, tmp1, atslab_0) ;
#line 105 "ats_staexp1_print.dats"
/* tmp28 = */ atspre_fprint_string (arg0, ATSstrcst("E1XPcstsp(")) ;
#line 106 "ats_staexp1_print.dats"
/* tmp29 = */ ATS_2d0_2e2_2e6_2src_2ats_syntax_2esats__fprint_cstsp (arg0, tmp27) ;
#line 107 "ats_staexp1_print.dats"
/* tmp0 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;
} while (0) ;
return /* (tmp0) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_e1xp] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 3505(line=112, offs=22) -- 3537(line=112, offs=54)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__print_e1xp (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp30) ;
ATSlocal (ats_ptr_type, tmp31) ;
ATSlocal (ats_ptr_type, tmp32) ;
// ATSlocal_void (tmp33) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__print_e1xp:
#line 112 "ats_staexp1_print.dats"
tmp31 = atspre_stdout_get () ;
#line 112 "ats_staexp1_print.dats"
tmp32 = ats_selsin_mac(tmp31, atslab_1) ;
#line 112 "ats_staexp1_print.dats"
/* tmp33 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_e1xp (tmp32, arg0) ;
#line 112 "ats_staexp1_print.dats"
/* tmp30 = */ atspre_stdout_view_set () ;
return /* (tmp30) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__print_e1xp] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 3559(line=113, offs=22) -- 3591(line=113, offs=54)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__prerr_e1xp (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (ats_ptr_type, tmp36) ;
// ATSlocal_void (tmp37) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__prerr_e1xp:
#line 113 "ats_staexp1_print.dats"
tmp35 = atspre_stderr_get () ;
#line 113 "ats_staexp1_print.dats"
tmp36 = ats_selsin_mac(tmp35, atslab_1) ;
#line 113 "ats_staexp1_print.dats"
/* tmp37 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_e1xp (tmp36, arg0) ;
#line 113 "ats_staexp1_print.dats"
/* tmp34 = */ atspre_stderr_view_set () ;
return /* (tmp34) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__prerr_e1xp] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 3639(line=118, offs=16) -- 3713(line=119, offs=58)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_e1xplst (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp38) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_e1xplst:
#line 119 "ats_staexp1_print.dats"
/* tmp38 = */ ATS_2d0_2e2_2e6_2src_2ats_list_2esats__fprintlst (arg0, arg1, ATSstrcst(", "), &ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_e1xp) ;
return /* (tmp38) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_e1xplst] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 3766(line=122, offs=25) -- 3803(line=122, offs=62)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__print_e1xplst (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp39) ;
ATSlocal (ats_ptr_type, tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;
// ATSlocal_void (tmp42) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__print_e1xplst:
#line 122 "ats_staexp1_print.dats"
tmp40 = atspre_stdout_get () ;
#line 122 "ats_staexp1_print.dats"
tmp41 = ats_selsin_mac(tmp40, atslab_1) ;
#line 122 "ats_staexp1_print.dats"
/* tmp42 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_e1xplst (tmp41, arg0) ;
#line 122 "ats_staexp1_print.dats"
/* tmp39 = */ atspre_stdout_view_set () ;
return /* (tmp39) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__print_e1xplst] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 3828(line=123, offs=25) -- 3865(line=123, offs=62)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__prerr_e1xplst (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp43) ;
ATSlocal (ats_ptr_type, tmp44) ;
ATSlocal (ats_ptr_type, tmp45) ;
// ATSlocal_void (tmp46) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__prerr_e1xplst:
#line 123 "ats_staexp1_print.dats"
tmp44 = atspre_stderr_get () ;
#line 123 "ats_staexp1_print.dats"
tmp45 = ats_selsin_mac(tmp44, atslab_1) ;
#line 123 "ats_staexp1_print.dats"
/* tmp46 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_e1xplst (tmp45, arg0) ;
#line 123 "ats_staexp1_print.dats"
/* tmp43 = */ atspre_stderr_view_set () ;
return /* (tmp43) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__prerr_e1xplst] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 3910(line=128, offs=13) -- 4645(line=153, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rt (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp47) ;
ATSlocal (ats_ptr_type, tmp48) ;
ATSlocal (ats_ptr_type, tmp49) ;
ATSlocal (ats_ptr_type, tmp50) ;
// ATSlocal_void (tmp51) ;
// ATSlocal_void (tmp52) ;
// ATSlocal_void (tmp53) ;
// ATSlocal_void (tmp54) ;
ATSlocal (ats_ptr_type, tmp55) ;
// ATSlocal_void (tmp56) ;
// ATSlocal_void (tmp57) ;
ATSlocal (ats_ptr_type, tmp58) ;
ATSlocal (ats_ptr_type, tmp59) ;
// ATSlocal_void (tmp60) ;
// ATSlocal_void (tmp61) ;
// ATSlocal_void (tmp62) ;
ATSlocal (ats_ptr_type, tmp63) ;
// ATSlocal_void (tmp64) ;
// ATSlocal_void (tmp65) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rt:
#line 131 "ats_staexp1_print.dats"
tmp48 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_5, arg1), atslab_s1rt_node) ;
#line 131 "ats_staexp1_print.dats"
do {
/* branch: __ats_lab_10 */
#line 132 "ats_staexp1_print.dats"
__ats_lab_10_0:
#line 132 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp48)->tag != 0) { goto __ats_lab_11_0 ; }
#line 132 "ats_staexp1_print.dats"
__ats_lab_10_1:
#line 132 "ats_staexp1_print.dats"
tmp49 = ats_caselptr_mac(anairiats_sum_6, tmp48, atslab_0) ;
#line 132 "ats_staexp1_print.dats"
tmp50 = ats_caselptr_mac(anairiats_sum_6, tmp48, atslab_1) ;
#line 133 "ats_staexp1_print.dats"
/* tmp51 = */ atspre_fprint_string (arg0, ATSstrcst("S1RTapp(")) ;
#line 134 "ats_staexp1_print.dats"
/* tmp52 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rt (arg0, tmp49) ;
#line 135 "ats_staexp1_print.dats"
/* tmp53 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 136 "ats_staexp1_print.dats"
/* tmp54 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rtlst (arg0, tmp50) ;
#line 137 "ats_staexp1_print.dats"
/* tmp47 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_11 */
#line 139 "ats_staexp1_print.dats"
__ats_lab_11_0:
#line 139 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp48)->tag != 1) { goto __ats_lab_12_0 ; }
#line 139 "ats_staexp1_print.dats"
__ats_lab_11_1:
#line 139 "ats_staexp1_print.dats"
tmp55 = ats_caselptr_mac(anairiats_sum_3, tmp48, atslab_0) ;
#line 140 "ats_staexp1_print.dats"
/* tmp56 = */ atspre_fprint_string (arg0, ATSstrcst("S1RTlist(")) ;
#line 140 "ats_staexp1_print.dats"
/* tmp57 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rtlst (arg0, tmp55) ;
#line 140 "ats_staexp1_print.dats"
/* tmp47 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_12 */
#line 142 "ats_staexp1_print.dats"
__ats_lab_12_0:
#line 142 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp48)->tag != 2) { goto __ats_lab_13_0 ; }
#line 142 "ats_staexp1_print.dats"
__ats_lab_12_1:
#line 142 "ats_staexp1_print.dats"
tmp58 = ats_caselptr_mac(anairiats_sum_6, tmp48, atslab_0) ;
#line 142 "ats_staexp1_print.dats"
tmp59 = ats_caselptr_mac(anairiats_sum_6, tmp48, atslab_1) ;
#line 143 "ats_staexp1_print.dats"
/* tmp60 = */ atspre_fprint_string (arg0, ATSstrcst("S1RTqid(")) ;
#line 144 "ats_staexp1_print.dats"
/* tmp61 = */ ATS_2d0_2e2_2e6_2src_2ats_syntax_2esats__fprint_s0rtq (arg0, tmp58) ;
#line 145 "ats_staexp1_print.dats"
/* tmp62 = */ ATS_2d0_2e2_2e6_2src_2ats_symbol_2esats__fprint_symbol (arg0, tmp59) ;
#line 146 "ats_staexp1_print.dats"
/* tmp47 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_13 */
#line 148 "ats_staexp1_print.dats"
__ats_lab_13_0:
#line 148 "ats_staexp1_print.dats"
// if (((ats_sum_ptr_type)tmp48)->tag != 3) { ats_deadcode_failure_handle () ; }
#line 148 "ats_staexp1_print.dats"
__ats_lab_13_1:
#line 148 "ats_staexp1_print.dats"
tmp63 = ats_caselptr_mac(anairiats_sum_3, tmp48, atslab_0) ;
#line 149 "ats_staexp1_print.dats"
/* tmp64 = */ atspre_fprint_string (arg0, ATSstrcst("S1RTtup(")) ;
#line 150 "ats_staexp1_print.dats"
/* tmp65 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rtlst (arg0, tmp63) ;
#line 151 "ats_staexp1_print.dats"
/* tmp47 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;
} while (0) ;
return /* (tmp47) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rt] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 4692(line=155, offs=22) -- 4728(line=155, offs=58)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__print_s1rt (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp66) ;
ATSlocal (ats_ptr_type, tmp67) ;
ATSlocal (ats_ptr_type, tmp68) ;
// ATSlocal_void (tmp69) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__print_s1rt:
#line 155 "ats_staexp1_print.dats"
tmp67 = atspre_stdout_get () ;
#line 155 "ats_staexp1_print.dats"
tmp68 = ats_selsin_mac(tmp67, atslab_1) ;
#line 155 "ats_staexp1_print.dats"
/* tmp69 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rt (tmp68, arg0) ;
#line 155 "ats_staexp1_print.dats"
/* tmp66 = */ atspre_stdout_view_set () ;
return /* (tmp66) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__print_s1rt] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 4750(line=156, offs=22) -- 4786(line=156, offs=58)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__prerr_s1rt (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp70) ;
ATSlocal (ats_ptr_type, tmp71) ;
ATSlocal (ats_ptr_type, tmp72) ;
// ATSlocal_void (tmp73) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__prerr_s1rt:
#line 156 "ats_staexp1_print.dats"
tmp71 = atspre_stderr_get () ;
#line 156 "ats_staexp1_print.dats"
tmp72 = ats_selsin_mac(tmp71, atslab_1) ;
#line 156 "ats_staexp1_print.dats"
/* tmp73 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rt (tmp72, arg0) ;
#line 156 "ats_staexp1_print.dats"
/* tmp70 = */ atspre_stderr_view_set () ;
return /* (tmp70) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__prerr_s1rt] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 4834(line=161, offs=16) -- 4908(line=162, offs=58)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rtlst (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp74) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rtlst:
#line 162 "ats_staexp1_print.dats"
/* tmp74 = */ ATS_2d0_2e2_2e6_2src_2ats_list_2esats__fprintlst (arg0, arg1, ATSstrcst(", "), &ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rt) ;
return /* (tmp74) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rtlst] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 4961(line=165, offs=25) -- 5002(line=165, offs=66)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__print_s1rtlst (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp75) ;
ATSlocal (ats_ptr_type, tmp76) ;
ATSlocal (ats_ptr_type, tmp77) ;
// ATSlocal_void (tmp78) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__print_s1rtlst:
#line 165 "ats_staexp1_print.dats"
tmp76 = atspre_stdout_get () ;
#line 165 "ats_staexp1_print.dats"
tmp77 = ats_selsin_mac(tmp76, atslab_1) ;
#line 165 "ats_staexp1_print.dats"
/* tmp78 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rtlst (tmp77, arg0) ;
#line 165 "ats_staexp1_print.dats"
/* tmp75 = */ atspre_stdout_view_set () ;
return /* (tmp75) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__print_s1rtlst] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 5027(line=166, offs=25) -- 5068(line=166, offs=66)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__prerr_s1rtlst (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp79) ;
ATSlocal (ats_ptr_type, tmp80) ;
ATSlocal (ats_ptr_type, tmp81) ;
// ATSlocal_void (tmp82) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__prerr_s1rtlst:
#line 166 "ats_staexp1_print.dats"
tmp80 = atspre_stderr_get () ;
#line 166 "ats_staexp1_print.dats"
tmp81 = ats_selsin_mac(tmp80, atslab_1) ;
#line 166 "ats_staexp1_print.dats"
/* tmp82 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rtlst (tmp81, arg0) ;
#line 166 "ats_staexp1_print.dats"
/* tmp79 = */ atspre_stderr_view_set () ;
return /* (tmp79) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__prerr_s1rtlst] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 5118(line=171, offs=3) -- 5210(line=172, offs=60)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rtopt (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp83) ;
ATSlocal (ats_ptr_type, tmp84) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rtopt:
#line 171 "ats_staexp1_print.dats"
do {
/* branch: __ats_lab_14 */
#line 172 "ats_staexp1_print.dats"
__ats_lab_14_0:
#line 172 "ats_staexp1_print.dats"
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_15_0 ; }
#line 172 "ats_staexp1_print.dats"
__ats_lab_14_1:
#line 172 "ats_staexp1_print.dats"
tmp84 = ats_caselptr_mac(anairiats_sum_7, arg1, atslab_0) ;
#line 172 "ats_staexp1_print.dats"
/* tmp83 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rt (arg0, tmp84) ;
break ;

/* branch: __ats_lab_15 */
#line 172 "ats_staexp1_print.dats"
__ats_lab_15_0:
#line 172 "ats_staexp1_print.dats"
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 172 "ats_staexp1_print.dats"
__ats_lab_15_1:
break ;
} while (0) ;
return /* (tmp83) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rtopt] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 5263(line=177, offs=4) -- 5597(line=187, offs=4)
*/
ATSstaticdec()
ats_void_type
fprint_s1arg_13 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp85) ;
// ATSlocal_void (tmp86) ;
ATSlocal (ats_ptr_type, tmp87) ;
ATSlocal (ats_ptr_type, tmp88) ;
ATSlocal (ats_ptr_type, tmp89) ;
// ATSlocal_void (tmp90) ;

__ats_lab_fprint_s1arg_13:
#line 180 "ats_staexp1_print.dats"
tmp87 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_8, arg1), atslab_s1arg_sym) ;
#line 180 "ats_staexp1_print.dats"
/* tmp86 = */ ATS_2d0_2e2_2e6_2src_2ats_symbol_2esats__fprint_symbol (arg0, tmp87) ;
#line 182 "ats_staexp1_print.dats"
tmp88 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_8, arg1), atslab_s1arg_srt) ;
#line 182 "ats_staexp1_print.dats"
do {
/* branch: __ats_lab_16 */
#line 183 "ats_staexp1_print.dats"
__ats_lab_16_0:
#line 183 "ats_staexp1_print.dats"
if (tmp88 == (ats_sum_ptr_type)0) { goto __ats_lab_17_0 ; }
#line 183 "ats_staexp1_print.dats"
__ats_lab_16_1:
#line 183 "ats_staexp1_print.dats"
tmp89 = ats_caselptr_mac(anairiats_sum_7, tmp88, atslab_0) ;
#line 184 "ats_staexp1_print.dats"
/* tmp90 = */ atspre_fprint_string (arg0, ATSstrcst(": ")) ;
#line 184 "ats_staexp1_print.dats"
/* tmp85 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rt (arg0, tmp89) ;
break ;

/* branch: __ats_lab_17 */
#line 186 "ats_staexp1_print.dats"
__ats_lab_17_0:
#line 186 "ats_staexp1_print.dats"
// if (tmp88 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 186 "ats_staexp1_print.dats"
__ats_lab_17_1:
break ;
} while (0) ;
return /* (tmp85) */ ;
} /* end of [fprint_s1arg_13] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 5627(line=189, offs=4) -- 5785(line=192, offs=60)
*/
ATSstaticdec()
ats_void_type
fprint_s1arglst_14 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp91) ;

__ats_lab_fprint_s1arglst_14:
#line 192 "ats_staexp1_print.dats"
/* tmp91 = */ ATS_2d0_2e2_2e6_2src_2ats_list_2esats__fprintlst (arg0, arg1, ATSstrcst(", "), &fprint_s1arg_13) ;
return /* (tmp91) */ ;
} /* end of [fprint_s1arglst_14] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 5840(line=197, offs=5) -- 6353(line=215, offs=4)
*/
ATSstaticdec()
ats_void_type
fprint_s1qua_15 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp92) ;
ATSlocal (ats_ptr_type, tmp93) ;
ATSlocal (ats_ptr_type, tmp94) ;
// ATSlocal_void (tmp95) ;
// ATSlocal_void (tmp96) ;
ATSlocal (ats_ptr_type, tmp97) ;
ATSlocal (ats_ptr_type, tmp98) ;
// ATSlocal_void (tmp99) ;
// ATSlocal_void (tmp100) ;
// ATSlocal_void (tmp101) ;
// ATSlocal_void (tmp102) ;

__ats_lab_fprint_s1qua_15:
#line 202 "ats_staexp1_print.dats"
tmp93 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_9, arg1), atslab_s1qua_node) ;
#line 202 "ats_staexp1_print.dats"
do {
/* branch: __ats_lab_18 */
#line 203 "ats_staexp1_print.dats"
__ats_lab_18_0:
#line 203 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp93)->tag != 0) { goto __ats_lab_19_0 ; }
#line 203 "ats_staexp1_print.dats"
__ats_lab_18_1:
#line 203 "ats_staexp1_print.dats"
tmp94 = ats_caselptr_mac(anairiats_sum_3, tmp93, atslab_0) ;
#line 204 "ats_staexp1_print.dats"
/* tmp95 = */ atspre_fprint_string (arg0, ATSstrcst("S1Qprop(")) ;
#line 205 "ats_staexp1_print.dats"
/* tmp96 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp (arg0, tmp94) ;
#line 206 "ats_staexp1_print.dats"
/* tmp92 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_19 */
#line 208 "ats_staexp1_print.dats"
__ats_lab_19_0:
#line 208 "ats_staexp1_print.dats"
// if (((ats_sum_ptr_type)tmp93)->tag != 1) { ats_deadcode_failure_handle () ; }
#line 208 "ats_staexp1_print.dats"
__ats_lab_19_1:
#line 208 "ats_staexp1_print.dats"
tmp97 = ats_caselptr_mac(anairiats_sum_6, tmp93, atslab_0) ;
#line 208 "ats_staexp1_print.dats"
tmp98 = ats_caselptr_mac(anairiats_sum_6, tmp93, atslab_1) ;
#line 209 "ats_staexp1_print.dats"
/* tmp99 = */ atspre_fprint_string (arg0, ATSstrcst("S1Qvars(")) ;
#line 210 "ats_staexp1_print.dats"
/* tmp100 = */ ATS_2d0_2e2_2e6_2src_2ats_syntax_2esats__fprint_i0delst (arg0, tmp97) ;
#line 211 "ats_staexp1_print.dats"
/* tmp101 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 212 "ats_staexp1_print.dats"
/* tmp102 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rtext (arg0, tmp98) ;
#line 213 "ats_staexp1_print.dats"
/* tmp92 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;
} while (0) ;
return /* (tmp92) */ ;
} /* end of [fprint_s1qua_15] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 6496(line=220, offs=7) -- 6757(line=226, offs=19)
*/
ATSstaticdec()
ats_void_type
aux_17 (ats_ref_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
// ATSlocal_void (tmp104) ;
ATSlocal (ats_ptr_type, tmp105) ;
ATSlocal (ats_ptr_type, tmp106) ;
// ATSlocal_void (tmp107) ;
ATSlocal (ats_bool_type, tmp108) ;
// ATSlocal_void (tmp109) ;
ATSlocal (ats_int_type, tmp110) ;

__ats_lab_aux_17:
#line 221 "ats_staexp1_print.dats"
do {
/* branch: __ats_lab_20 */
#line 222 "ats_staexp1_print.dats"
__ats_lab_20_0:
#line 222 "ats_staexp1_print.dats"
if (arg2 == (ats_sum_ptr_type)0) { goto __ats_lab_21_0 ; }
#line 222 "ats_staexp1_print.dats"
__ats_lab_20_1:
#line 222 "ats_staexp1_print.dats"
tmp105 = ats_caselptr_mac(anairiats_sum_10, arg2, atslab_0) ;
#line 222 "ats_staexp1_print.dats"
tmp106 = ats_caselptr_mac(anairiats_sum_10, arg2, atslab_1) ;
#line 223 "ats_staexp1_print.dats"
tmp108 = atspre_gt_int_int (arg1, 0) ;
#line 223 "ats_staexp1_print.dats"
if (tmp108) {
#line 223 "ats_staexp1_print.dats"
/* tmp107 = */ atspre_fprint_string (arg0, ATSstrcst(", ")) ;
} else {
/* empty */
} /* end of [if] */
#line 224 "ats_staexp1_print.dats"
/* tmp109 = */ fprint_s1qua_15 (arg0, tmp105) ;
#line 224 "ats_staexp1_print.dats"
tmp110 = atspre_add_int_int (arg1, 1) ;
#line 224 "ats_staexp1_print.dats"
arg0 = arg0 ;
#line 224 "ats_staexp1_print.dats"
arg1 = tmp110 ;
#line 224 "ats_staexp1_print.dats"
arg2 = tmp106 ;
#line 224 "ats_staexp1_print.dats"
goto __ats_lab_aux_17 ; // tail call
break ;

/* branch: __ats_lab_21 */
#line 226 "ats_staexp1_print.dats"
__ats_lab_21_0:
#line 226 "ats_staexp1_print.dats"
// if (arg2 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 226 "ats_staexp1_print.dats"
__ats_lab_21_1:
break ;
} while (0) ;
return /* (tmp104) */ ;
} /* end of [aux_17] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 6384(line=217, offs=5) -- 6820(line=230, offs=4)
*/
ATSstaticdec()
ats_void_type
fprint_s1qualst_16 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp103) ;

__ats_lab_fprint_s1qualst_16:
#line 229 "ats_staexp1_print.dats"
/* tmp103 = */ aux_17 (arg0, 0, arg1) ;
return /* (tmp103) */ ;
} /* end of [fprint_s1qualst_16] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 6894(line=235, offs=14) -- 11726(line=403, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp111) ;
ATSlocal (ats_ptr_type, tmp112) ;
ATSlocal (ats_ptr_type, tmp113) ;
ATSlocal (ats_ptr_type, tmp114) ;
// ATSlocal_void (tmp115) ;
// ATSlocal_void (tmp116) ;
// ATSlocal_void (tmp117) ;
// ATSlocal_void (tmp118) ;
ATSlocal (ats_ptr_type, tmp119) ;
ATSlocal (ats_ptr_type, tmp120) ;
// ATSlocal_void (tmp121) ;
// ATSlocal_void (tmp122) ;
// ATSlocal_void (tmp123) ;
// ATSlocal_void (tmp124) ;
ATSlocal (ats_char_type, tmp125) ;
// ATSlocal_void (tmp126) ;
// ATSlocal_void (tmp127) ;
ATSlocal (ats_int_type, tmp128) ;
ATSlocal (ats_ptr_type, tmp129) ;
ATSlocal (ats_ptr_type, tmp130) ;
// ATSlocal_void (tmp131) ;
// ATSlocal_void (tmp132) ;
// ATSlocal_void (tmp133) ;
// ATSlocal_void (tmp134) ;
// ATSlocal_void (tmp135) ;
// ATSlocal_void (tmp136) ;
ATSlocal (ats_ptr_type, tmp137) ;
ATSlocal (ats_ptr_type, tmp138) ;
// ATSlocal_void (tmp139) ;
// ATSlocal_void (tmp140) ;
// ATSlocal_void (tmp141) ;
// ATSlocal_void (tmp142) ;
ATSlocal (ats_ptr_type, tmp143) ;
ATSlocal (ats_int_type, tmp144) ;
ATSlocal (ats_int_type, tmp145) ;
ATSlocal (ats_ptr_type, tmp146) ;
// ATSlocal_void (tmp147) ;
// ATSlocal_void (tmp148) ;
// ATSlocal_void (tmp149) ;
// ATSlocal_void (tmp150) ;
// ATSlocal_void (tmp151) ;
// ATSlocal_void (tmp152) ;
// ATSlocal_void (tmp153) ;
// ATSlocal_void (tmp154) ;
ATSlocal (ats_ptr_type, tmp155) ;
ATSlocal (ats_ptr_type, tmp156) ;
// ATSlocal_void (tmp157) ;
// ATSlocal_void (tmp158) ;
ATSlocal (ats_int_type, tmp159) ;
ATSlocal (ats_ptr_type, tmp160) ;
// ATSlocal_void (tmp161) ;
// ATSlocal_void (tmp162) ;
// ATSlocal_void (tmp163) ;
// ATSlocal_void (tmp164) ;
ATSlocal (ats_int_type, tmp165) ;
ATSlocal (ats_ptr_type, tmp166) ;
// ATSlocal_void (tmp167) ;
// ATSlocal_void (tmp168) ;
// ATSlocal_void (tmp169) ;
// ATSlocal_void (tmp170) ;
ATSlocal (ats_ptr_type, tmp171) ;
ATSlocal (ats_ptr_type, tmp172) ;
// ATSlocal_void (tmp173) ;
ATSlocal (ats_ptr_type, tmp174) ;
ATSlocal (ats_ptr_type, tmp175) ;
// ATSlocal_void (tmp176) ;
// ATSlocal_void (tmp177) ;
// ATSlocal_void (tmp178) ;
// ATSlocal_void (tmp179) ;
ATSlocal (ats_int_type, tmp180) ;
ATSlocal (ats_ptr_type, tmp181) ;
// ATSlocal_void (tmp182) ;
// ATSlocal_void (tmp183) ;
// ATSlocal_void (tmp184) ;
// ATSlocal_void (tmp185) ;
ATSlocal (ats_ptr_type, tmp186) ;
ATSlocal (ats_ptr_type, tmp187) ;
// ATSlocal_void (tmp188) ;
// ATSlocal_void (tmp189) ;
// ATSlocal_void (tmp190) ;
// ATSlocal_void (tmp191) ;
ATSlocal (ats_ptr_type, tmp192) ;
// ATSlocal_void (tmp193) ;
// ATSlocal_void (tmp194) ;
// ATSlocal_void (tmp195) ;
ATSlocal (ats_int_type, tmp196) ;
ATSlocal (ats_ptr_type, tmp197) ;
// ATSlocal_void (tmp198) ;
// ATSlocal_void (tmp199) ;
// ATSlocal_void (tmp200) ;
// ATSlocal_void (tmp201) ;
ATSlocal (ats_ptr_type, tmp202) ;
ATSlocal (ats_ptr_type, tmp203) ;
// ATSlocal_void (tmp204) ;
// ATSlocal_void (tmp205) ;
// ATSlocal_void (tmp206) ;
// ATSlocal_void (tmp207) ;
ATSlocal (ats_int_type, tmp208) ;
ATSlocal (ats_ptr_type, tmp209) ;
// ATSlocal_void (tmp210) ;
// ATSlocal_void (tmp211) ;
// ATSlocal_void (tmp212) ;
// ATSlocal_void (tmp213) ;
ATSlocal (ats_int_type, tmp214) ;
ATSlocal (ats_ptr_type, tmp215) ;
ATSlocal (ats_ptr_type, tmp216) ;
// ATSlocal_void (tmp217) ;
// ATSlocal_void (tmp218) ;
// ATSlocal_void (tmp219) ;
// ATSlocal_void (tmp220) ;
// ATSlocal_void (tmp221) ;
// ATSlocal_void (tmp222) ;
ATSlocal (ats_ptr_type, tmp223) ;
ATSlocal (ats_ptr_type, tmp224) ;
// ATSlocal_void (tmp225) ;
// ATSlocal_void (tmp226) ;
// ATSlocal_void (tmp227) ;
// ATSlocal_void (tmp228) ;
ATSlocal (ats_ptr_type, tmp229) ;
ATSlocal (ats_ptr_type, tmp230) ;
// ATSlocal_void (tmp231) ;
// ATSlocal_void (tmp232) ;
// ATSlocal_void (tmp233) ;
// ATSlocal_void (tmp234) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp:
#line 238 "ats_staexp1_print.dats"
tmp112 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_11, arg1), atslab_s1exp_node) ;
#line 238 "ats_staexp1_print.dats"
do {
/* branch: __ats_lab_22 */
#line 239 "ats_staexp1_print.dats"
__ats_lab_22_0:
#line 239 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 0) { goto __ats_lab_23_0 ; }
#line 239 "ats_staexp1_print.dats"
__ats_lab_22_1:
#line 239 "ats_staexp1_print.dats"
tmp113 = ats_caselptr_mac(anairiats_sum_6, tmp112, atslab_0) ;
#line 239 "ats_staexp1_print.dats"
tmp114 = ats_caselptr_mac(anairiats_sum_6, tmp112, atslab_1) ;
#line 240 "ats_staexp1_print.dats"
/* tmp115 = */ atspre_fprint_string (arg0, ATSstrcst("S1Eann(")) ;
#line 241 "ats_staexp1_print.dats"
/* tmp116 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp (arg0, tmp113) ;
#line 242 "ats_staexp1_print.dats"
/* tmp117 = */ atspre_fprint_string (arg0, ATSstrcst(", ")) ;
#line 243 "ats_staexp1_print.dats"
/* tmp118 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rt (arg0, tmp114) ;
#line 244 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_23 */
#line 246 "ats_staexp1_print.dats"
__ats_lab_23_0:
#line 246 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 1) { goto __ats_lab_24_0 ; }
#line 246 "ats_staexp1_print.dats"
__ats_lab_23_1:
#line 246 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst("S1Eany()")) ;
break ;

/* branch: __ats_lab_24 */
#line 247 "ats_staexp1_print.dats"
__ats_lab_24_0:
#line 247 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 2) { goto __ats_lab_25_0 ; }
#line 247 "ats_staexp1_print.dats"
__ats_lab_24_1:
#line 247 "ats_staexp1_print.dats"
tmp119 = ats_caselptr_mac(anairiats_sum_1, tmp112, atslab_0) ;
#line 247 "ats_staexp1_print.dats"
tmp120 = ats_caselptr_mac(anairiats_sum_1, tmp112, atslab_2) ;
#line 248 "ats_staexp1_print.dats"
/* tmp121 = */ atspre_fprint_string (arg0, ATSstrcst("S1Eapp(")) ;
#line 249 "ats_staexp1_print.dats"
/* tmp122 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp (arg0, tmp119) ;
#line 250 "ats_staexp1_print.dats"
/* tmp123 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 251 "ats_staexp1_print.dats"
/* tmp124 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1explst (arg0, tmp120) ;
#line 252 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_25 */
#line 254 "ats_staexp1_print.dats"
__ats_lab_25_0:
#line 254 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 3) { goto __ats_lab_26_0 ; }
#line 254 "ats_staexp1_print.dats"
__ats_lab_25_1:
#line 254 "ats_staexp1_print.dats"
tmp125 = ats_caselptr_mac(anairiats_sum_2, tmp112, atslab_0) ;
#line 255 "ats_staexp1_print.dats"
/* tmp126 = */ atspre_fprint_string (arg0, ATSstrcst("S1Echar(")) ;
#line 255 "ats_staexp1_print.dats"
/* tmp127 = */ atspre_fprint_char (arg0, tmp125) ;
#line 255 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_26 */
#line 257 "ats_staexp1_print.dats"
__ats_lab_26_0:
#line 257 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 4) { goto __ats_lab_27_0 ; }
#line 257 "ats_staexp1_print.dats"
__ats_lab_26_1:
#line 257 "ats_staexp1_print.dats"
tmp128 = ats_caselptr_mac(anairiats_sum_12, tmp112, atslab_0) ;
#line 257 "ats_staexp1_print.dats"
tmp129 = ats_caselptr_mac(anairiats_sum_12, tmp112, atslab_1) ;
#line 257 "ats_staexp1_print.dats"
tmp130 = ats_caselptr_mac(anairiats_sum_12, tmp112, atslab_2) ;
#line 258 "ats_staexp1_print.dats"
/* tmp131 = */ atspre_fprint_string (arg0, ATSstrcst("S1Eexi(")) ;
#line 259 "ats_staexp1_print.dats"
/* tmp132 = */ atspre_fprint_int (arg0, tmp128) ;
#line 260 "ats_staexp1_print.dats"
/* tmp133 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 261 "ats_staexp1_print.dats"
/* tmp134 = */ fprint_s1qualst_16 (arg0, tmp129) ;
#line 262 "ats_staexp1_print.dats"
/* tmp135 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 263 "ats_staexp1_print.dats"
/* tmp136 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp (arg0, tmp130) ;
#line 264 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_27 */
#line 266 "ats_staexp1_print.dats"
__ats_lab_27_0:
#line 266 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 5) { goto __ats_lab_28_0 ; }
#line 266 "ats_staexp1_print.dats"
__ats_lab_27_1:
#line 266 "ats_staexp1_print.dats"
tmp137 = ats_caselptr_mac(anairiats_sum_6, tmp112, atslab_0) ;
#line 266 "ats_staexp1_print.dats"
tmp138 = ats_caselptr_mac(anairiats_sum_6, tmp112, atslab_1) ;
#line 267 "ats_staexp1_print.dats"
/* tmp139 = */ atspre_fprint_string (arg0, ATSstrcst("S1Eextype(")) ;
#line 268 "ats_staexp1_print.dats"
/* tmp140 = */ atspre_fprint_string (arg0, tmp137) ;
#line 269 "ats_staexp1_print.dats"
/* tmp141 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 270 "ats_staexp1_print.dats"
/* tmp142 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1explstlst (arg0, tmp138) ;
#line 271 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_28 */
#line 273 "ats_staexp1_print.dats"
__ats_lab_28_0:
#line 273 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 6) { goto __ats_lab_31_0 ; }
#line 273 "ats_staexp1_print.dats"
__ats_lab_28_1:
#line 273 "ats_staexp1_print.dats"
tmp143 = ats_caselptr_mac(anairiats_sum_13, tmp112, atslab_0) ;
#line 273 "ats_staexp1_print.dats"
tmp144 = ats_caselptr_mac(anairiats_sum_13, tmp112, atslab_1) ;
#line 273 "ats_staexp1_print.dats"
tmp145 = ats_caselptr_mac(anairiats_sum_13, tmp112, atslab_2) ;
#line 273 "ats_staexp1_print.dats"
tmp146 = ats_caselptr_mac(anairiats_sum_13, tmp112, atslab_3) ;
#line 274 "ats_staexp1_print.dats"
/* tmp147 = */ atspre_fprint_string (arg0, ATSstrcst("S1Eimp(")) ;
#line 275 "ats_staexp1_print.dats"
/* tmp148 = */ ATS_2d0_2e2_2e6_2src_2ats_syntax_2esats__fprint_funclo (arg0, tmp143) ;
#line 275 "ats_staexp1_print.dats"
/* tmp149 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 276 "ats_staexp1_print.dats"
/* tmp150 = */ atspre_fprint_int (arg0, tmp144) ;
#line 276 "ats_staexp1_print.dats"
/* tmp151 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 277 "ats_staexp1_print.dats"
/* tmp152 = */ atspre_fprint_int (arg0, tmp145) ;
#line 277 "ats_staexp1_print.dats"
/* tmp153 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 278 "ats_staexp1_print.dats"
do {
/* branch: __ats_lab_29 */
#line 279 "ats_staexp1_print.dats"
__ats_lab_29_0:
#line 279 "ats_staexp1_print.dats"
if (tmp146 == (ats_sum_ptr_type)0) { goto __ats_lab_30_0 ; }
#line 279 "ats_staexp1_print.dats"
__ats_lab_29_1:
#line 279 "ats_staexp1_print.dats"
tmp155 = ats_caselptr_mac(anairiats_sum_7, tmp146, atslab_0) ;
#line 279 "ats_staexp1_print.dats"
/* tmp154 = */ ATS_2d0_2e2_2e6_2src_2ats_effect_2esats__fprint_effcst (arg0, tmp155) ;
break ;

/* branch: __ats_lab_30 */
#line 280 "ats_staexp1_print.dats"
__ats_lab_30_0:
#line 280 "ats_staexp1_print.dats"
// if (tmp146 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 280 "ats_staexp1_print.dats"
__ats_lab_30_1:
break ;
} while (0) ;
#line 282 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_31 */
#line 284 "ats_staexp1_print.dats"
__ats_lab_31_0:
#line 284 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 7) { goto __ats_lab_32_0 ; }
#line 284 "ats_staexp1_print.dats"
__ats_lab_31_1:
#line 284 "ats_staexp1_print.dats"
tmp156 = ats_caselptr_mac(anairiats_sum_3, tmp112, atslab_0) ;
#line 285 "ats_staexp1_print.dats"
/* tmp157 = */ atspre_fprint_string (arg0, ATSstrcst("S1Eint(")) ;
#line 285 "ats_staexp1_print.dats"
/* tmp158 = */ atspre_fprint_string (arg0, tmp156) ;
#line 285 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_32 */
#line 287 "ats_staexp1_print.dats"
__ats_lab_32_0:
#line 287 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 8) { goto __ats_lab_33_0 ; }
#line 287 "ats_staexp1_print.dats"
__ats_lab_32_1:
#line 287 "ats_staexp1_print.dats"
tmp159 = ats_caselptr_mac(anairiats_sum_14, tmp112, atslab_0) ;
#line 287 "ats_staexp1_print.dats"
tmp160 = ats_caselptr_mac(anairiats_sum_14, tmp112, atslab_1) ;
#line 288 "ats_staexp1_print.dats"
/* tmp161 = */ atspre_fprint_string (arg0, ATSstrcst("S1Einvar(")) ;
#line 289 "ats_staexp1_print.dats"
/* tmp162 = */ atspre_fprint_int (arg0, tmp159) ;
#line 290 "ats_staexp1_print.dats"
/* tmp163 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 291 "ats_staexp1_print.dats"
/* tmp164 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp (arg0, tmp160) ;
#line 292 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_33 */
#line 294 "ats_staexp1_print.dats"
__ats_lab_33_0:
#line 294 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 9) { goto __ats_lab_34_0 ; }
#line 294 "ats_staexp1_print.dats"
__ats_lab_33_1:
#line 294 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst("S1Elam(...)")) ;
break ;

/* branch: __ats_lab_34 */
#line 295 "ats_staexp1_print.dats"
__ats_lab_34_0:
#line 295 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 10) { goto __ats_lab_35_0 ; }
#line 295 "ats_staexp1_print.dats"
__ats_lab_34_1:
#line 295 "ats_staexp1_print.dats"
tmp165 = ats_caselptr_mac(anairiats_sum_14, tmp112, atslab_0) ;
#line 295 "ats_staexp1_print.dats"
tmp166 = ats_caselptr_mac(anairiats_sum_14, tmp112, atslab_1) ;
#line 296 "ats_staexp1_print.dats"
/* tmp167 = */ atspre_fprint_string (arg0, ATSstrcst("S1Elist(")) ;
#line 297 "ats_staexp1_print.dats"
/* tmp168 = */ atspre_fprint_int (arg0, tmp165) ;
#line 298 "ats_staexp1_print.dats"
/* tmp169 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 299 "ats_staexp1_print.dats"
/* tmp170 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1explst (arg0, tmp166) ;
#line 300 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_35 */
#line 320 "ats_staexp1_print.dats"
__ats_lab_35_0:
#line 320 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 11) { goto __ats_lab_36_0 ; }
#line 320 "ats_staexp1_print.dats"
__ats_lab_35_1:
#line 320 "ats_staexp1_print.dats"
tmp171 = ats_caselptr_mac(anairiats_sum_6, tmp112, atslab_0) ;
#line 320 "ats_staexp1_print.dats"
tmp172 = ats_caselptr_mac(anairiats_sum_6, tmp112, atslab_1) ;
#line 321 "ats_staexp1_print.dats"
/* tmp173 = */ ATS_2d0_2e2_2e6_2src_2ats_syntax_2esats__fprint_s0taq (arg0, tmp171) ;
#line 322 "ats_staexp1_print.dats"
/* tmp111 = */ ATS_2d0_2e2_2e6_2src_2ats_symbol_2esats__fprint_symbol (arg0, tmp172) ;
break ;

/* branch: __ats_lab_36 */
#line 324 "ats_staexp1_print.dats"
__ats_lab_36_0:
#line 324 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 12) { goto __ats_lab_37_0 ; }
#line 324 "ats_staexp1_print.dats"
__ats_lab_36_1:
#line 324 "ats_staexp1_print.dats"
tmp174 = ats_caselptr_mac(anairiats_sum_6, tmp112, atslab_0) ;
#line 324 "ats_staexp1_print.dats"
tmp175 = ats_caselptr_mac(anairiats_sum_6, tmp112, atslab_1) ;
#line 325 "ats_staexp1_print.dats"
/* tmp176 = */ atspre_fprint_string (arg0, ATSstrcst("S1Eread(")) ;
#line 326 "ats_staexp1_print.dats"
/* tmp177 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp (arg0, tmp174) ;
#line 327 "ats_staexp1_print.dats"
/* tmp178 = */ atspre_fprint_string (arg0, ATSstrcst(", ")) ;
#line 328 "ats_staexp1_print.dats"
/* tmp179 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp (arg0, tmp175) ;
#line 329 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_37 */
#line 339 "ats_staexp1_print.dats"
__ats_lab_37_0:
#line 339 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 13) { goto __ats_lab_38_0 ; }
#line 339 "ats_staexp1_print.dats"
__ats_lab_37_1:
#line 339 "ats_staexp1_print.dats"
tmp180 = ats_caselptr_mac(anairiats_sum_14, tmp112, atslab_0) ;
#line 339 "ats_staexp1_print.dats"
tmp181 = ats_caselptr_mac(anairiats_sum_14, tmp112, atslab_1) ;
#line 340 "ats_staexp1_print.dats"
/* tmp182 = */ atspre_fprint_string (arg0, ATSstrcst("S1Etop(")) ;
#line 341 "ats_staexp1_print.dats"
/* tmp183 = */ atspre_fprint_int (arg0, tmp180) ;
#line 342 "ats_staexp1_print.dats"
/* tmp184 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 343 "ats_staexp1_print.dats"
/* tmp185 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp (arg0, tmp181) ;
#line 344 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_38 */
#line 346 "ats_staexp1_print.dats"
__ats_lab_38_0:
#line 346 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 14) { goto __ats_lab_39_0 ; }
#line 346 "ats_staexp1_print.dats"
__ats_lab_38_1:
#line 346 "ats_staexp1_print.dats"
tmp186 = ats_caselptr_mac(anairiats_sum_6, tmp112, atslab_0) ;
#line 346 "ats_staexp1_print.dats"
tmp187 = ats_caselptr_mac(anairiats_sum_6, tmp112, atslab_1) ;
#line 347 "ats_staexp1_print.dats"
/* tmp188 = */ atspre_fprint_string (arg0, ATSstrcst("S1Etrans(")) ;
#line 348 "ats_staexp1_print.dats"
/* tmp189 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp (arg0, tmp186) ;
#line 349 "ats_staexp1_print.dats"
/* tmp190 = */ atspre_fprint_string (arg0, ATSstrcst(", ")) ;
#line 350 "ats_staexp1_print.dats"
/* tmp191 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp (arg0, tmp187) ;
#line 351 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_39 */
#line 353 "ats_staexp1_print.dats"
__ats_lab_39_0:
#line 353 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 15) { goto __ats_lab_40_0 ; }
#line 353 "ats_staexp1_print.dats"
__ats_lab_39_1:
#line 353 "ats_staexp1_print.dats"
tmp192 = ats_caselptr_mac(anairiats_sum_6, tmp112, atslab_0) ;
#line 354 "ats_staexp1_print.dats"
/* tmp193 = */ atspre_fprint_string (arg0, ATSstrcst("S1Earray(")) ;
#line 355 "ats_staexp1_print.dats"
/* tmp194 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp (arg0, tmp192) ;
#line 356 "ats_staexp1_print.dats"
/* tmp195 = */ atspre_fprint_string (arg0, ATSstrcst(", ...")) ;
#line 357 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_40 */
#line 359 "ats_staexp1_print.dats"
__ats_lab_40_0:
#line 359 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 16) { goto __ats_lab_41_0 ; }
#line 359 "ats_staexp1_print.dats"
__ats_lab_40_1:
#line 359 "ats_staexp1_print.dats"
tmp196 = ats_caselptr_mac(anairiats_sum_14, tmp112, atslab_0) ;
#line 359 "ats_staexp1_print.dats"
tmp197 = ats_caselptr_mac(anairiats_sum_14, tmp112, atslab_1) ;
#line 360 "ats_staexp1_print.dats"
/* tmp198 = */ atspre_fprint_string (arg0, ATSstrcst("S1Etyrec(")) ;
#line 361 "ats_staexp1_print.dats"
/* tmp199 = */ atspre_fprint_int (arg0, tmp196) ;
#line 362 "ats_staexp1_print.dats"
/* tmp200 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 363 "ats_staexp1_print.dats"
/* tmp201 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_labs1explst (arg0, tmp197) ;
#line 364 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_41 */
#line 366 "ats_staexp1_print.dats"
__ats_lab_41_0:
#line 366 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 17) { goto __ats_lab_42_0 ; }
#line 366 "ats_staexp1_print.dats"
__ats_lab_41_1:
#line 366 "ats_staexp1_print.dats"
tmp202 = ats_caselptr_mac(anairiats_sum_6, tmp112, atslab_0) ;
#line 366 "ats_staexp1_print.dats"
tmp203 = ats_caselptr_mac(anairiats_sum_6, tmp112, atslab_1) ;
#line 367 "ats_staexp1_print.dats"
/* tmp204 = */ atspre_fprint_string (arg0, ATSstrcst("S1Etyrec_ext(")) ;
#line 368 "ats_staexp1_print.dats"
/* tmp205 = */ atspre_fprint_string (arg0, tmp202) ;
#line 369 "ats_staexp1_print.dats"
/* tmp206 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 370 "ats_staexp1_print.dats"
/* tmp207 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_labs1explst (arg0, tmp203) ;
#line 371 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_42 */
#line 373 "ats_staexp1_print.dats"
__ats_lab_42_0:
#line 373 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 18) { goto __ats_lab_43_0 ; }
#line 373 "ats_staexp1_print.dats"
__ats_lab_42_1:
#line 373 "ats_staexp1_print.dats"
tmp208 = ats_caselptr_mac(anairiats_sum_14, tmp112, atslab_0) ;
#line 373 "ats_staexp1_print.dats"
tmp209 = ats_caselptr_mac(anairiats_sum_14, tmp112, atslab_1) ;
#line 374 "ats_staexp1_print.dats"
/* tmp210 = */ atspre_fprint_string (arg0, ATSstrcst("S1Etytup(")) ;
#line 375 "ats_staexp1_print.dats"
/* tmp211 = */ atspre_fprint_int (arg0, tmp208) ;
#line 376 "ats_staexp1_print.dats"
/* tmp212 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 377 "ats_staexp1_print.dats"
/* tmp213 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1explst (arg0, tmp209) ;
#line 378 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_43 */
#line 380 "ats_staexp1_print.dats"
__ats_lab_43_0:
#line 380 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 19) { goto __ats_lab_44_0 ; }
#line 380 "ats_staexp1_print.dats"
__ats_lab_43_1:
#line 380 "ats_staexp1_print.dats"
tmp214 = ats_caselptr_mac(anairiats_sum_12, tmp112, atslab_0) ;
#line 380 "ats_staexp1_print.dats"
tmp215 = ats_caselptr_mac(anairiats_sum_12, tmp112, atslab_1) ;
#line 380 "ats_staexp1_print.dats"
tmp216 = ats_caselptr_mac(anairiats_sum_12, tmp112, atslab_2) ;
#line 381 "ats_staexp1_print.dats"
/* tmp217 = */ atspre_fprint_string (arg0, ATSstrcst("S1Etytup2(")) ;
#line 382 "ats_staexp1_print.dats"
/* tmp218 = */ atspre_fprint_int (arg0, tmp214) ;
#line 383 "ats_staexp1_print.dats"
/* tmp219 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 384 "ats_staexp1_print.dats"
/* tmp220 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1explst (arg0, tmp215) ;
#line 385 "ats_staexp1_print.dats"
/* tmp221 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 386 "ats_staexp1_print.dats"
/* tmp222 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1explst (arg0, tmp216) ;
#line 387 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_44 */
#line 389 "ats_staexp1_print.dats"
__ats_lab_44_0:
#line 389 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp112)->tag != 20) { goto __ats_lab_45_0 ; }
#line 389 "ats_staexp1_print.dats"
__ats_lab_44_1:
#line 389 "ats_staexp1_print.dats"
tmp223 = ats_caselptr_mac(anairiats_sum_6, tmp112, atslab_0) ;
#line 389 "ats_staexp1_print.dats"
tmp224 = ats_caselptr_mac(anairiats_sum_6, tmp112, atslab_1) ;
#line 390 "ats_staexp1_print.dats"
/* tmp225 = */ atspre_fprint_string (arg0, ATSstrcst("S1Euni(")) ;
#line 391 "ats_staexp1_print.dats"
/* tmp226 = */ fprint_s1qualst_16 (arg0, tmp223) ;
#line 392 "ats_staexp1_print.dats"
/* tmp227 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 393 "ats_staexp1_print.dats"
/* tmp228 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp (arg0, tmp224) ;
#line 394 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_45 */
#line 396 "ats_staexp1_print.dats"
__ats_lab_45_0:
#line 396 "ats_staexp1_print.dats"
// if (((ats_sum_ptr_type)tmp112)->tag != 21) { ats_deadcode_failure_handle () ; }
#line 396 "ats_staexp1_print.dats"
__ats_lab_45_1:
#line 396 "ats_staexp1_print.dats"
tmp229 = ats_caselptr_mac(anairiats_sum_6, tmp112, atslab_0) ;
#line 396 "ats_staexp1_print.dats"
tmp230 = ats_caselptr_mac(anairiats_sum_6, tmp112, atslab_1) ;
#line 397 "ats_staexp1_print.dats"
/* tmp231 = */ atspre_fprint_string (arg0, ATSstrcst("S1Eunion(")) ;
#line 398 "ats_staexp1_print.dats"
/* tmp232 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp (arg0, tmp229) ;
#line 399 "ats_staexp1_print.dats"
/* tmp233 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 400 "ats_staexp1_print.dats"
/* tmp234 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_labs1explst (arg0, tmp230) ;
#line 401 "ats_staexp1_print.dats"
/* tmp111 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;
} while (0) ;
return /* (tmp111) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 11775(line=405, offs=23) -- 11812(line=405, offs=60)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__print_s1exp (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp235) ;
ATSlocal (ats_ptr_type, tmp236) ;
ATSlocal (ats_ptr_type, tmp237) ;
// ATSlocal_void (tmp238) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__print_s1exp:
#line 405 "ats_staexp1_print.dats"
tmp236 = atspre_stdout_get () ;
#line 405 "ats_staexp1_print.dats"
tmp237 = ats_selsin_mac(tmp236, atslab_1) ;
#line 405 "ats_staexp1_print.dats"
/* tmp238 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp (tmp237, arg0) ;
#line 405 "ats_staexp1_print.dats"
/* tmp235 = */ atspre_stdout_view_set () ;
return /* (tmp235) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__print_s1exp] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 11835(line=406, offs=23) -- 11872(line=406, offs=60)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__prerr_s1exp (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp239) ;
ATSlocal (ats_ptr_type, tmp240) ;
ATSlocal (ats_ptr_type, tmp241) ;
// ATSlocal_void (tmp242) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__prerr_s1exp:
#line 406 "ats_staexp1_print.dats"
tmp240 = atspre_stderr_get () ;
#line 406 "ats_staexp1_print.dats"
tmp241 = ats_selsin_mac(tmp240, atslab_1) ;
#line 406 "ats_staexp1_print.dats"
/* tmp242 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp (tmp241, arg0) ;
#line 406 "ats_staexp1_print.dats"
/* tmp239 = */ atspre_stderr_view_set () ;
return /* (tmp239) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__prerr_s1exp] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 11921(line=411, offs=17) -- 11997(line=412, offs=60)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1explst (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp243) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1explst:
#line 412 "ats_staexp1_print.dats"
/* tmp243 = */ ATS_2d0_2e2_2e6_2src_2ats_list_2esats__fprintlst (arg0, arg1, ATSstrcst(", "), &ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp) ;
return /* (tmp243) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1explst] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 12052(line=415, offs=26) -- 12094(line=415, offs=68)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__print_s1explst (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp244) ;
ATSlocal (ats_ptr_type, tmp245) ;
ATSlocal (ats_ptr_type, tmp246) ;
// ATSlocal_void (tmp247) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__print_s1explst:
#line 415 "ats_staexp1_print.dats"
tmp245 = atspre_stdout_get () ;
#line 415 "ats_staexp1_print.dats"
tmp246 = ats_selsin_mac(tmp245, atslab_1) ;
#line 415 "ats_staexp1_print.dats"
/* tmp247 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1explst (tmp246, arg0) ;
#line 415 "ats_staexp1_print.dats"
/* tmp244 = */ atspre_stdout_view_set () ;
return /* (tmp244) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__print_s1explst] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 12120(line=416, offs=26) -- 12162(line=416, offs=68)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__prerr_s1explst (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp248) ;
ATSlocal (ats_ptr_type, tmp249) ;
ATSlocal (ats_ptr_type, tmp250) ;
// ATSlocal_void (tmp251) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__prerr_s1explst:
#line 416 "ats_staexp1_print.dats"
tmp249 = atspre_stderr_get () ;
#line 416 "ats_staexp1_print.dats"
tmp250 = ats_selsin_mac(tmp249, atslab_1) ;
#line 416 "ats_staexp1_print.dats"
/* tmp251 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1explst (tmp250, arg0) ;
#line 416 "ats_staexp1_print.dats"
/* tmp248 = */ atspre_stderr_view_set () ;
return /* (tmp248) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__prerr_s1explst] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 12211(line=421, offs=17) -- 12312(line=423, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1expopt (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp252) ;
ATSlocal (ats_ptr_type, tmp253) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1expopt:
#line 422 "ats_staexp1_print.dats"
do {
/* branch: __ats_lab_46 */
#line 422 "ats_staexp1_print.dats"
__ats_lab_46_0:
#line 422 "ats_staexp1_print.dats"
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_47_0 ; }
#line 422 "ats_staexp1_print.dats"
__ats_lab_46_1:
#line 422 "ats_staexp1_print.dats"
tmp253 = ats_caselptr_mac(anairiats_sum_7, arg1, atslab_0) ;
#line 422 "ats_staexp1_print.dats"
/* tmp252 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp (arg0, tmp253) ;
break ;

/* branch: __ats_lab_47 */
#line 422 "ats_staexp1_print.dats"
__ats_lab_47_0:
#line 422 "ats_staexp1_print.dats"
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 422 "ats_staexp1_print.dats"
__ats_lab_47_1:
break ;
} while (0) ;
return /* (tmp252) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1expopt] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 12371(line=426, offs=20) -- 12455(line=427, offs=67)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1explstlst (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp254) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1explstlst:
#line 427 "ats_staexp1_print.dats"
/* tmp254 = */ ATS_2d0_2e2_2e6_2src_2ats_list_2esats__fprintlst (arg0, arg1, ATSstrcst(", "), &ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1explst) ;
return /* (tmp254) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1explstlst] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 12553(line=433, offs=7) -- 12979(line=445, offs=6)
*/
ATSstaticdec()
ats_void_type
aux_27 (ats_ref_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
// ATSlocal_void (tmp256) ;
ATSlocal (ats_ptr_type, tmp257) ;
ATSlocal (ats_ptr_type, tmp258) ;
ATSlocal (ats_ptr_type, tmp259) ;
// ATSlocal_void (tmp260) ;
ATSlocal (ats_bool_type, tmp261) ;
// ATSlocal_void (tmp262) ;
// ATSlocal_void (tmp263) ;
// ATSlocal_void (tmp264) ;
ATSlocal (ats_int_type, tmp265) ;

__ats_lab_aux_27:
#line 438 "ats_staexp1_print.dats"
do {
/* branch: __ats_lab_48 */
#line 439 "ats_staexp1_print.dats"
__ats_lab_48_0:
#line 439 "ats_staexp1_print.dats"
if (arg2 == (ats_sum_ptr_type)0) { goto __ats_lab_49_0 ; }
#line 439 "ats_staexp1_print.dats"
__ats_lab_48_1:
#line 439 "ats_staexp1_print.dats"
tmp257 = ats_caselptr_mac(anairiats_sum_15, arg2, atslab_0) ;
#line 439 "ats_staexp1_print.dats"
tmp258 = ats_caselptr_mac(anairiats_sum_15, arg2, atslab_1) ;
#line 439 "ats_staexp1_print.dats"
tmp259 = ats_caselptr_mac(anairiats_sum_15, arg2, atslab_2) ;
#line 440 "ats_staexp1_print.dats"
tmp261 = atspre_gt_int_int (arg1, 0) ;
#line 440 "ats_staexp1_print.dats"
if (tmp261) {
#line 440 "ats_staexp1_print.dats"
/* tmp260 = */ atspre_fprint_string (arg0, ATSstrcst(", ")) ;
} else {
/* empty */
} /* end of [if] */
#line 441 "ats_staexp1_print.dats"
/* tmp262 = */ ATS_2d0_2e2_2e6_2src_2ats_label_2esats__fprint_label (arg0, tmp257) ;
#line 441 "ats_staexp1_print.dats"
/* tmp263 = */ atspre_fprint_string (arg0, ATSstrcst("=")) ;
#line 442 "ats_staexp1_print.dats"
/* tmp264 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1exp (arg0, tmp258) ;
#line 442 "ats_staexp1_print.dats"
tmp265 = atspre_add_int_int (arg1, 1) ;
#line 442 "ats_staexp1_print.dats"
arg0 = arg0 ;
#line 442 "ats_staexp1_print.dats"
arg1 = tmp265 ;
#line 442 "ats_staexp1_print.dats"
arg2 = tmp259 ;
#line 442 "ats_staexp1_print.dats"
goto __ats_lab_aux_27 ; // tail call
break ;

/* branch: __ats_lab_49 */
#line 444 "ats_staexp1_print.dats"
__ats_lab_49_0:
#line 444 "ats_staexp1_print.dats"
// if (arg2 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 444 "ats_staexp1_print.dats"
__ats_lab_49_1:
break ;
} while (0) ;
return /* (tmp256) */ ;
} /* end of [aux_27] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 12523(line=432, offs=7) -- 13024(line=448, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_labs1explst (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp255) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_labs1explst:
#line 447 "ats_staexp1_print.dats"
/* tmp255 = */ aux_27 (arg0, 0, arg1) ;
return /* (tmp255) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_labs1explst] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 13148(line=455, offs=7) -- 13505(line=464, offs=33)
*/
ATSstaticdec()
ats_void_type
aux_29 (ats_ref_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
// ATSlocal_void (tmp267) ;
ATSlocal (ats_ptr_type, tmp268) ;
ATSlocal (ats_ptr_type, tmp269) ;
// ATSlocal_void (tmp270) ;
ATSlocal (ats_bool_type, tmp271) ;
// ATSlocal_void (tmp272) ;
ATSlocal (ats_int_type, tmp273) ;

__ats_lab_aux_29:
#line 458 "ats_staexp1_print.dats"
do {
/* branch: __ats_lab_50 */
#line 459 "ats_staexp1_print.dats"
__ats_lab_50_0:
#line 459 "ats_staexp1_print.dats"
if (arg2 == (ats_sum_ptr_type)0) { goto __ats_lab_51_0 ; }
#line 459 "ats_staexp1_print.dats"
__ats_lab_50_1:
#line 459 "ats_staexp1_print.dats"
tmp268 = ats_caselptr_mac(anairiats_sum_15, arg2, atslab_1) ;
#line 459 "ats_staexp1_print.dats"
tmp269 = ats_caselptr_mac(anairiats_sum_15, arg2, atslab_2) ;
#line 460 "ats_staexp1_print.dats"
tmp271 = atspre_gt_int_int (arg1, 0) ;
#line 460 "ats_staexp1_print.dats"
if (tmp271) {
#line 460 "ats_staexp1_print.dats"
/* tmp270 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
} else {
/* empty */
} /* end of [if] */
#line 462 "ats_staexp1_print.dats"
/* tmp272 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1explst (arg0, tmp268) ;
#line 462 "ats_staexp1_print.dats"
tmp273 = atspre_add_int_int (arg1, 1) ;
#line 462 "ats_staexp1_print.dats"
arg0 = arg0 ;
#line 462 "ats_staexp1_print.dats"
arg1 = tmp273 ;
#line 462 "ats_staexp1_print.dats"
arg2 = tmp269 ;
#line 462 "ats_staexp1_print.dats"
goto __ats_lab_aux_29 ; // tail call
break ;

/* branch: __ats_lab_51 */
#line 464 "ats_staexp1_print.dats"
__ats_lab_51_0:
#line 464 "ats_staexp1_print.dats"
// if (arg2 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
#line 464 "ats_staexp1_print.dats"
__ats_lab_51_1:
break ;
} while (0) ;
return /* (tmp267) */ ;
} /* end of [aux_29] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 13116(line=454, offs=7) -- 13554(line=468, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_tmps1explstlst (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp266) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_tmps1explstlst:
#line 467 "ats_staexp1_print.dats"
/* tmp266 = */ aux_29 (arg0, 0, arg1) ;
return /* (tmp266) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_tmps1explstlst] */

/*
// /home/hwxi/Research/Anairiats/src/ats_staexp1_print.dats: 13633(line=473, offs=16) -- 14055(line=487, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rtext (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp274) ;
ATSlocal (ats_ptr_type, tmp275) ;
ATSlocal (ats_ptr_type, tmp276) ;
ATSlocal (ats_ptr_type, tmp277) ;
ATSlocal (ats_ptr_type, tmp278) ;
ATSlocal (ats_ptr_type, tmp279) ;
// ATSlocal_void (tmp280) ;
// ATSlocal_void (tmp281) ;
// ATSlocal_void (tmp282) ;
// ATSlocal_void (tmp283) ;
// ATSlocal_void (tmp284) ;
// ATSlocal_void (tmp285) ;

__ats_lab_ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rtext:
#line 476 "ats_staexp1_print.dats"
tmp275 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_16, arg1), atslab_s1rtext_node) ;
#line 476 "ats_staexp1_print.dats"
do {
/* branch: __ats_lab_52 */
#line 477 "ats_staexp1_print.dats"
__ats_lab_52_0:
#line 477 "ats_staexp1_print.dats"
if (((ats_sum_ptr_type)tmp275)->tag != 0) { goto __ats_lab_53_0 ; }
#line 477 "ats_staexp1_print.dats"
__ats_lab_52_1:
#line 477 "ats_staexp1_print.dats"
tmp276 = ats_caselptr_mac(anairiats_sum_3, tmp275, atslab_0) ;
#line 477 "ats_staexp1_print.dats"
/* tmp274 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rt (arg0, tmp276) ;
break ;

/* branch: __ats_lab_53 */
#line 478 "ats_staexp1_print.dats"
__ats_lab_53_0:
#line 478 "ats_staexp1_print.dats"
// if (((ats_sum_ptr_type)tmp275)->tag != 1) { ats_deadcode_failure_handle () ; }
#line 478 "ats_staexp1_print.dats"
__ats_lab_53_1:
#line 478 "ats_staexp1_print.dats"
tmp277 = ats_caselptr_mac(anairiats_sum_1, tmp275, atslab_0) ;
#line 478 "ats_staexp1_print.dats"
tmp278 = ats_caselptr_mac(anairiats_sum_1, tmp275, atslab_1) ;
#line 478 "ats_staexp1_print.dats"
tmp279 = ats_caselptr_mac(anairiats_sum_1, tmp275, atslab_2) ;
#line 479 "ats_staexp1_print.dats"
/* tmp280 = */ atspre_fprint_string (arg0, ATSstrcst("S1TEsub(")) ;
#line 480 "ats_staexp1_print.dats"
/* tmp281 = */ ATS_2d0_2e2_2e6_2src_2ats_symbol_2esats__fprint_symbol (arg0, tmp277) ;
#line 481 "ats_staexp1_print.dats"
/* tmp282 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 482 "ats_staexp1_print.dats"
/* tmp283 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rtext (arg0, tmp278) ;
#line 483 "ats_staexp1_print.dats"
/* tmp284 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
#line 484 "ats_staexp1_print.dats"
/* tmp285 = */ ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1explst (arg0, tmp279) ;
#line 485 "ats_staexp1_print.dats"
/* tmp274 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;
} while (0) ;
return /* (tmp274) */ ;
} /* end of [ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__fprint_s1rtext] */

/* static load function */

extern ats_void_type ATS_2d0_2e2_2e6_2src_2ats_effect_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e6_2src_2ats_label_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e6_2src_2ats_list_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e6_2src_2ats_symbol_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e6_2src_2ats_syntax_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__staload (void) ;

ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_print_2edats__staload () {
static int ATS_2d0_2e2_2e6_2src_2ats_staexp1_print_2edats__staload_flag = 0 ;
if (ATS_2d0_2e2_2e6_2src_2ats_staexp1_print_2edats__staload_flag) return ;
ATS_2d0_2e2_2e6_2src_2ats_staexp1_print_2edats__staload_flag = 1 ;

ATS_2d0_2e2_2e6_2src_2ats_effect_2esats__staload () ;
ATS_2d0_2e2_2e6_2src_2ats_label_2esats__staload () ;
ATS_2d0_2e2_2e6_2src_2ats_list_2esats__staload () ;
ATS_2d0_2e2_2e6_2src_2ats_symbol_2esats__staload () ;
ATS_2d0_2e2_2e6_2src_2ats_syntax_2esats__staload () ;
ATS_2d0_2e2_2e6_2src_2ats_staexp1_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type ATS_2d0_2e2_2e6_2src_2ats_staexp1_print_2edats__dynload_flag ;

ats_void_type
ATS_2d0_2e2_2e6_2src_2ats_staexp1_print_2edats__dynload () {
ATS_2d0_2e2_2e6_2src_2ats_staexp1_print_2edats__dynload_flag = 1 ;
ATS_2d0_2e2_2e6_2src_2ats_staexp1_print_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e6_2prelude_2basics_dyn_2esats__file_mode_lte_w_w_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [ats_staexp1_print_dats.c] */
