(kill(all), 0);
0;

/* (Z/pZ)* p prime */
p : 2^127-1;
170141183460469231731687303715884105727;

fs : ifactors(p - 1);
[[2, 1], [3, 3], [7, 2], [19, 1], [43, 1], [73, 1], [127, 1], [337, 1], [5419, 1], [92737, 1], [649657, 1], [77158673929, 1]];

g : zn_primroot(p, fs);
43;

zn_primroot_p(power_mod(g, 7, p), p, fs);
false;

zn_primroot_p(power_mod(g, 11, p), p, fs);
true;

is(zn_order(g, p, fs) = totient(p));
true;

is(zn_order(power_mod(g, 7, p), p, fs) = zn_order(g, p, fs));
false;

is(zn_order(power_mod(g, 11, p), p, fs) = zn_order(g, p, fs));
true;

a : power_mod(g, 1234567890, p);
151915201611216996495932583752378710518;

zn_log(a, g, p, fs);
1234567890;

/* (Z/nZ)* n composite */
n : 22;
22;

g : zn_primroot(n);
7;

zn_primroot_p(power_mod(g, 2, n), n);
false;

zn_primroot_p(power_mod(g, 3, n), n);
true;

zn_order(power_mod(g, 2, n), n);
5;

zn_order(g, n);
10;

a : power_mod(g, 8, n);
9;

zn_log(a, g, n);
8;

/* CRT */
mods : [1009, 1013, 1019];
[1009, 1013, 1019];

x : 374599943;
374599943;

rems : map(lambda([z], mod(x, z)), mods);
[621, 647, 258];

chinese(rems, mods);
374599943;

(remvalue(p,fs,g,a,n,mods,x,rems), 0);
0;


(kill(all), modulus_copy : modulus, modulus : false, 0);
0;

/* Tests adapted from contrib/gf/gf_test.mac */

gf_set(123127, 5, x^5+2*x+1);
[x+4, x^5+2*x+1];

gf_set(7, 10, x^10+5*x^2+x+5);
[x, x^10+5*x^2+x+5];

gf_exp(gf_primitive(), gf_index(x^9+3*x^6+x^5+2*x^2+6));
x^9+3*x^6+x^5+2*x^2+6;

gf_minimal_poly(x^9+3*x^6+x^5+2*x^2+6);
z^10+5*z^9+6*z^8+5*z^6+3*z^5+4*z^4+z^3+2*z^2+4*z+3;

gf_set(19);
[2, x];

gf_exp(gf_primitive(), gf_index(17));
17;

gf_set(10000000019);
[2, x];

gf_exp(gf_primitive() ,gf_index(3));
3;

gf_set(32717, 11, x^11+x^5+x^2+x+1);
[x+2, x^11+x^5+x^2+x+1];

gf_set(211, 17, x^17+2*x^2+1);
[x+6, x^17+2*x^2+1];

gf_set(2, 20, x^20+x^3+x^2+x+1);
[x^2+x, x^20+x^3+x^2+x+1];

gf_exp(gf_primitive(), gf_index(x^10+1));
x^10+1;

gf_minimal_poly(x^10+1);
z^20+z^13+z^12+z^5+z^4+z^3+1;

gf_set(3, 91, x^91+x^35+x+1);
[x, x^91+x^35+x+1];

/* Tests adapted from contrib/gf/gf_hard_test.mac */

gf_set(7, 61, x^61+x^4+1);
[x+3, x^61+x^4+1];

gf_set(197, 24, x^24-x^8+2);
[x+19, x^24+196*x^8+2];

gf_set(5, 84, x^84+x^41+x^2+1);
[x^2+1, x^84+x^41+x^2+1];

gf_set(2, 102, x^102+x^29+1);
[x+1, x^102+x^29+1];

gf_set(5, 61, x^61+x^15+1);
[x+4, x^61+x^15+1];

gf_set(8796519617, 8, x^8+3*x^6+x+1);
[x+9, x^8+3*x^6+x+1];

gf_set(3, 120, x^120+x^4-1);
[x^3+x^2+2, x^120+x^4+2];

gf_set(18659817111137);
[3, x];

gf_log(7);
15962290024269;

/* Examples adapted from contrib/gf/gf_manual.pdf */

gf_set(2, 4, x^4+x+1);
[x, x^4+x+1];

(a : x^3+x^2+1, b : x^3+x+1, 0);
0;

gf_add(a, b);
x^2+x;

gf_mult(a, b);
x^2+x;

gf_inv(b);
x^2+1;

gf_div(a, b);
x^3+x^2;

gf_mult(a, gf_inv(b));
x^3+x^2;

gf_exp(a, 10);
x^2+x+1;

gf_exp(a, 15);
1;

gf_primitive();
x;

gf_index(a);
13;

ev(a = gf_exp(x, 13)), pred;
true;

(gf_make_arrays(), 0);
0;

gf_logs[10];
9;

gf_n2p(10);
x^3+x;

gf_index(x^3+x);
9;

(a : x^2+x+1, b : x^3+x^2+1, 0);
0;

gf_log(a, b);
10;

gf_primitive_p(x^3+x+1);
true;

gf_primitive_p(x^2+x);
false;

gf_order(x^2+x);
3;

gf_order(x^3+x+1);
15;

(a : x^3+x+1, 0);
0;

p : gf_minimal_poly(a);
z^4+z^3+1;

p : subst(a, z, p);
(x^3+x+1)^4+(x^3+x+1)^3+1;

gf_eval(p);
0;

gf_set(7, 4, x^4+3*x^3+5*x^2+6*x+2);
[x+4, x^4+3*x^3+5*x^2+6*x+2];

(char : 7, exp : 4, g : 3*x^3+3*x^2+6, 0);
0;

gf_primitive_p(g);
true;

a : makelist(gf_log(x+i, g),i, 0, 6);
[1028,1935,2054,1008,379,1780,223];

d : 1702;
1702;

ord : char^exp - 1;
2400;

c : makelist(mod(a[i] + d, ord), i, 1, 7);
[330,1237,1356,310,2081,1082,1925];

M : [1,0,1,1,0,0,1];
[1,0,1,1,0,0,1];

c : mod(sum(M[i] * c[i], i, 1, 7), ord);
1521;

r : mod(c - exp*d, ord);
1913;

u : gf_exp(g, r);
x^3+3*x^2+2*x+5;

s : u + gf_reduction();
x^4+4*x^3+8*x^2+8*x+7;

gf_factor(s);
x*(x+2)*(x+3)*(x+6);

gf_set(2,4,x^4+x+1);
[x, x^4+x+1];

(M : matrix([x^3+x^2+x, x^3, x^3+x^2], [x^2, x^3+x^2+1, x^3+x+1], [x^2+x, x^3+x^2+x+1, x^2]), 0);
0;

MI : gf_matinv(M);
matrix([x^2, x^3+x^2+x+1, x^3], [x^3+x+1, x^2+x, x^3+1], [x, 0, x^3+x+1]);

gf_matmult(M, MI);
matrix([1,0,0], [0,1,0], [0,0,1]);

gf_set(2, 10, x^10+x^3+1);
[x, x^10+x^3+1];

pe : gf_normal();
x^7;

M : gf_normal_basis(pe);
matrix([0,0,1,0,0,0,0,0,0,0], [0,0,1,0,0,1,0,0,0,0],
       [0,1,1,0,0,1,0,0,0,0], [1,1,1,1,0,1,0,0,0,0],
       [1,0,1,1,1,0,0,1,1,0], [0,1,1,0,1,1,1,0,1,1],
       [1,1,1,0,0,1,1,1,0,0], [1,0,1,0,0,1,0,0,1,0],
       [0,0,1,0,0,0,0,1,1,0], [0,0,1,0,0,0,0,1,0,0]);

gf_normal_basis_rep(pe, M);
[0,0,0,0,0,0,0,0,0,1];

(a : x^9+x^7+x^6+x^5+x^3+x^2+x, 0);
0;

gf_normal_basis_rep(a, M);
[0,1,1,1,0,1,0,1,1,1];

gf_normal_basis_rep(gf_exp(a, 2), M);
[1,1,1,0,1,0,1,1,1,0];

gf_set(2, 20, x^20+x^3+1);
[x,x^20+x^3+1];

(a : x^15+x^5+1, 0);
0;

gf_index(a);
720548;

gf_exp(a, 3^12);
x^17+x^16+x^13+x^12+x^11+x^3+x^2+x;

/* some new tests */

gf_set(2, 12, x^12+x^3+1);
[x+1, x^12+x^3+1];

gf_log(gf_exp(x+1, 1234));
1234;

gf_set(8796519617, 2, x^2+3);
[x+9, x^2+3];

gf_log(gf_exp(x+9, 1234567890));
1234567890;

gf_set(2, 4);
[x, x^4+x+1];

(prod : (z - 0), for i:1 thru 15 do prod : prod*(z - gf_exp(x,i)), gf_eval(prod));
z^16+z;

(kill(a), gf_set(2, 4, a^4+a+1), p : z^4+z+1, 0);
0;

map(gf_eval, divide(p, z - a));
[z^3+a*z^2+a^2*z+a^3+1, 0];

gf_set(13, 7,x^7+3*x+2);
[x,x^7+3*x+2];

p : 9*x^6+12*x^5+5*x^4+x^3+8*x^2+2*x;
9*x^6+12*x^5+5*x^4+x^3+8*x^2+2*x;

gf_normal_p(p);
true;

M : gf_normal_basis(p);
matrix([9,12,5,1,8,2,0],[7,1,12,5,4,2,6],[10,8,8,6,11,12,10],
       [4,5,9,8,6,11,2],[4,9,10,11,12,1,2],[2,2,3,8,6,5,8],
       [3,2,5,0,5,6,5]);

gf_normal_basis_rep(p, M);
[0,0,0,0,0,0,1];

gf_set(2, x^8+x^4+x^3+x+1);
[x+1, x^8+x^4+x^3+x+1];

M : matrix([2,3,1,1], [1,2,3,1], [1,1,2,3], [3,1,1,2]);
matrix([2,3,1,1], [1,2,3,1], [1,1,2,3], [3,1,1,2]);

MP : matrixmap(gf_n2p, M);
matrix([x,x+1,1,1], [1,x,x+1,1], [1,1,x,x+1], [x+1,1,1,x]);

MPI : gf_matinv(MP);
matrix([x^3+x^2+x, x^3+x+1,   x^3+x^2+1, x^3+1    ],
       [x^3+1,     x^3+x^2+x, x^3+x+1,   x^3+x^2+1],
       [x^3+x^2+1, x^3+1,     x^3+x^2+x, x^3+x+1  ],
       [x^3+x+1,   x^3+x^2+1, x^3+1,     x^3+x^2+x]);

matrixmap(gf_p2n, MPI);
matrix([14,11,13,9], [9,14,11,13], [13,9,14,11], [11,13,9,14]);

fs_ord : ifactors(7^4-1);
[[2,5],[3,1],[5,2]];

gf_set(7, 4);
[x+5, x^4+x+1];

gf_set(7, 4, fs_ord);
[x+5, x^4+x+1];

gf_set(7, x^4+x^2+3);
[x+1, x^4+x^2+3];

gf_set(7, 4, x^4+x^2+3);
[x+1, x^4+x^2+3];

gf_set(7, x^4+x^2+3, fs_ord);
[x+1, x^4+x^2+3];

gf_set(7, 4, x^4+x^2+3, fs_ord);
[x+1, x^4+x^2+3];

gf_set(2, x^8+1);
[false, x^8+1];

gf_order();
128;

gf_inv(x);
x^7;

gf_inv(x+1);
false;

gf_gcdex(x+1, gf_reduction());
[1, 0, x+1];

gf_set(3, x^8+1);
[false, x^8+1];

gf_order();
6400;

gf_set(3, x^8+x+1);
[false, x^8+x+1];

gf_order();
4368;

gf_set(13, x^8+2);
[x+2, x^8+2];

(a : x^7+x+1, b : x^3+3*x^2+9*x+7, 0);
0;

gf_gcd(a, b);
x^2+2*x+7;

gf_gcdex(a, b);
[7, 6*x^4+8*x^3+3*x, x^2+2*x+7];

(remvalue(a,b,c,d,p,g,M,MI,ord,pe,r,s,u,prod,MP,MPI,fs_ord), modulus : modulus_copy, 0);
0;

gf_unset();
true;
