# this is not actually a makefile, but a shell fragment which will be sourced
# by genmakefile.sh.
CURSORS="X_cursor base_arrow_down base_arrow_up boat bottom_left_corner bottom_right_corner bottom_side bottom_tee center_ptr circle cross dot dot_box_mask double_arrow draped_box exchange fleur gumby hand1 hand2 left_ptr left_ptr_watch left_side left_tee ll_angle lr_angle pencil pirate question_arrow right_ptr right_side right_tee sailboat sb_down_arrow sb_h_double_arrow sb_left_arrow sb_right_arrow sb_up_arrow sb_v_double_arrow shuttle sizing target top_left_corner top_right_corner top_side top_tee trek ul_angle ur_angle watch xterm"

DIST="Makefile.cfg Makefile.cursors gumby-128.png basic_arrow-16.png basic_arrow-24.png basic_arrow-32.png basic_arrow-48.png basic_arrow-64.png basic_arrow.cfg basic_arrow.xcf"
