.TH "XFI" "1" "13 june 2007" "Roland Baudin" ""
.SH "NAME"
xfi \- A simple image viewer for X Window
.SH "SYNOPSIS"
\fBxfi\fP [\-h] [\-\-help] [\-v] [\-\-version] [\fIimage filename\fP]
.SH "DESCRIPTION"
X File Image (xfi) is a simple image viewer, to be used with X File Explorer (xfe) or stand alone. It features image rotations, mirroring and zooming.
.SH "AUTHOR"
Roland Baudin <roland65@free.fr>.

.SH "OPTIONS"
xfi accepts the following options:
.TP 
.B \-h, \-\-help
Print the help screen and exit.
.TP 
.B \-v, \-\-version
Print xfe version information and exit.
.TP 
.B image filename
Specifies the path to the image file to open when starting xfi.



.SH "SEE ALSO"
.BR xfe (1), 
.BR xfw (1), 
.BR xfv (1), 
.BR xfp (1)
