.TH "XFP" "1" "13 June 2007" "Roland Baudin" ""
.SH "NAME"
xfp \- A simple package manager for X Window
.SH "SYNOPSIS"
\fBxfp\fP [\-h] [\-\-help] [\-v] [\-\-version] [\fIpackage filename\fP]
.SH "DESCRIPTION"
X File Package (xfp) is a simple package manager, to be used with X File Explorer (xfe) or stand alone.
.SH "AUTHOR"
Roland Baudin <roland65@free.fr>.
.SH "OPTIONS"
xfp accepts the following options:
.TP 
.B \-h, \-\-help
Print the help screen and exit.
.TP 
.B \-v, \-\-version
Print xfe version information and exit.
.TP 
.B package filename (rpm or deb)
Specifies the path to the package file to open when starting xfp.


.SH "SEE ALSO"
.BR xfe (1), 
.BR xfw (1), 
.BR xfv (1), 
.BR xfi (1)
