@menu
* Functions and Variables for Contexts::
@end menu

@c -----------------------------------------------------------------------------
@node Functions and Variables for Contexts,  , Contexts, Contexts
@section Functions and Variables for Contexts
@c -----------------------------------------------------------------------------

The documentation of this chapter has been moved to the file Database.texi



