@menu
* Functions and Variables for Floating Point::  
@end menu

@c -----------------------------------------------------------------------------
@node Functions and Variables for Floating Point,  , Floating Point, Floating Point
@section Functions and Variables for Floating Point
@c -----------------------------------------------------------------------------

The contents of this file has been moved to the files:
DataTypes.texi
Equations.texi
Special.texi

