#!/bin/sh

# Build zipfile distribution of libglade for Win32. Separate runtime
# and developer zipfiles. Run after make install.

ZIP=/tmp/libglade-2.6.4.zip
DEVZIP=/tmp/libglade-dev-2.6.4.zip

cd /usr/local
rm $ZIP

zip $ZIP -@ <<EOF
bin/libglade-2.0-0.dll
EOF

rm $DEVZIP
zip -r $DEVZIP -@ <<EOF
bin/libglade-convert
lib/libglade-2.0.dll.a
lib/pkgconfig/libglade-2.0.pc
include/libglade-2.0
share/xml/libglade
share/gtk-doc/html/libglade
EOF
