@c Language: Brazilian Portuguese, Encoding: iso-8859-1
@c /bode.texi/1.2/Sat Jun  2 00:13:11 2007//
@menu
* Fun@value{cedilha}@~{o}es e Vari@'{a}veis Definidas para bode::
@end menu

@node Fun@value{cedilha}@~{o}es e Vari@'{a}veis Definidas para bode,  , bode, bode
@section Fun@value{cedilha}@~{o}es e Vari@'{a}veis Definidas para bode


@deffn {Fun@value{cedilha}@~{a}o} bode_gain (@var{H}, @var{range}, ...@var{plot_opts}...)
Fun@value{cedilha}@~{a}o para desenhar gr@'{a}ficos de ganho para Bode.

Exemplos (1 a 7 provenientes de 
@example
http://www.swarthmore.edu/NatSci/echeeve1/Ref/Bode/BodeHow.html,
@end example
8 proveniente de Ron Crummett):
@example
(%i1) load("bode")$

(%i2) H1 (s) := 100 * (1 + s) / ((s + 10) * (s + 100))$

(%i3) bode_gain (H1 (s), [w, 1/1000, 1000])$

(%i4) H2 (s) := 1 / (1 + s/omega0)$

(%i5) bode_gain (H2 (s), [w, 1/1000, 1000]), omega0 = 10$

(%i6) H3 (s) := 1 / (1 + s/omega0)^2$

(%i7) bode_gain (H3 (s), [w, 1/1000, 1000]), omega0 = 10$

(%i8) H4 (s) := 1 + s/omega0$

(%i9) bode_gain (H4 (s), [w, 1/1000, 1000]), omega0 = 10$

(%i10) H5 (s) := 1/s$

(%i11) bode_gain (H5 (s), [w, 1/1000, 1000])$

(%i12) H6 (s) := 1/((s/omega0)^2 + 2 * zeta * (s/omega0) + 1)$

(%i13) bode_gain (H6 (s), [w, 1/1000, 1000]), 
                  omega0 = 10, zeta = 1/10$

(%i14) H7 (s) := (s/omega0)^2 + 2 * zeta * (s/omega0) + 1$

(%i15) bode_gain (H7 (s), [w, 1/1000, 1000]),
                  omega0 = 10, zeta = 1/10$

(%i16) H8 (s) := 0.5 / (0.0001 * s^3 + 0.002 * s^2 + 0.01 * s)$

(%i17) bode_gain (H8 (s), [w, 1/1000, 1000])$
@end example

Para usar essa fun@value{cedilha}@~{a}o escreva primeiramente @code{load("bode")}. Veja tamb@'{e}m @code{bode_phase}
@end deffn


@deffn {Fun@value{cedilha}@~{a}o} bode_phase (@var{H}, @var{range}, ...@var{plot_opts}...)
Fun@value{cedilha}@~{a}o para desenhar gr@'{a}ficos de fase para Bode

Exemplos (1 a 7 provenientes de
@example
http://www.swarthmore.edu/NatSci/echeeve1/Ref/Bode/BodeHow.html,
@end example
8 proveniente de Ron Crummett):
@example
(%i1) load("bode")$

(%i2) H1 (s) := 100 * (1 + s) / ((s + 10) * (s + 100))$

(%i3) bode_phase (H1 (s), [w, 1/1000, 1000])$

(%i4) H2 (s) := 1 / (1 + s/omega0)$

(%i5) bode_phase (H2 (s), [w, 1/1000, 1000]), omega0 = 10$

(%i6) H3 (s) := 1 / (1 + s/omega0)^2$

(%i7) bode_phase (H3 (s), [w, 1/1000, 1000]), omega0 = 10$

(%i8) H4 (s) := 1 + s/omega0$

(%i9) bode_phase (H4 (s), [w, 1/1000, 1000]), omega0 = 10$

(%i10) H5 (s) := 1/s$

(%i11) bode_phase (H5 (s), [w, 1/1000, 1000])$

(%i12) H6 (s) := 1/((s/omega0)^2 + 2 * zeta * (s/omega0) + 1)$

(%i13) bode_phase (H6 (s), [w, 1/1000, 1000]), 
                   omega0 = 10, zeta = 1/10$

(%i14) H7 (s) := (s/omega0)^2 + 2 * zeta * (s/omega0) + 1$

(%i15) bode_phase (H7 (s), [w, 1/1000, 1000]), 
                   omega0 = 10, zeta = 1/10$

(%i16) H8 (s) := 0.5 / (0.0001 * s^3 + 0.002 * s^2 + 0.01 * s)$

(%i17) bode_phase (H8 (s), [w, 1/1000, 1000])$

(%i18) block ([bode_phase_unwrap : false],
              bode_phase (H8 (s), [w, 1/1000, 1000]));

(%i19) block ([bode_phase_unwrap : true], 
              bode_phase (H8 (s), [w, 1/1000, 1000]));
@end example

Para usar essa fun@value{cedilha}@~{a}o escreva primeiramente @code{load("bode")}. Veja tamb@'{e}m @code{bode_gain}
@end deffn

