@c @c Language: Brazilian Portuguese, Encoding: iso-8859-1
@c /f90.texi/1.2/Sat Jun  2 00:13:21 2007//
@menu
* Fun@value{cedilha}@~{o}es e Vari@'{a}veis Definidas para f90::
@end menu

@node Fun@value{cedilha}@~{o}es e Vari@'{a}veis Definidas para f90,  , f90, f90
@section Fun@value{cedilha}@~{o}es e Vari@'{a}veis Definidas para f90


@deffn {Fun@value{cedilha}@~{a}o} f90 (@var{expr})
O comando f90 @'{e} uma atualiza@value{cedilha}@~{a}o para o comando @code{fortran} original do
maxima. A diferen@value{cedilha}a prim@'{a}ria @'{e} o caminho atrav@'{e}s do qual linhas longas s@~{a}o quebradas.

No exemplo seguinte, observe como o comando @code{fortran} para linhas dentro de s@'{i}mbolos. O comando
@code{f90} jamais para linha dentro de um s@'{i}mbolo.

@example
(%i1) load("f90")$

(%i2) expr:expand((xxx+yyy+7)^4);
         4            3         3        2    2
(%o2) yyy  + 4 xxx yyy  + 28 yyy  + 6 xxx  yyy
             2          2        3             2
 + 84 xxx yyy  + 294 yyy  + 4 xxx  yyy + 84 xxx  yyy
                               4         3          2
 + 588 xxx yyy + 1372 yyy + xxx  + 28 xxx  + 294 xxx
 + 1372 xxx + 2401
(%i3) fortran(expr);
      yyy**4+4*xxx*yyy**3+28*yyy**3+6*xxx**2*yyy**2+84*xxx*yyy**2+294*yy
     1   y**2+4*xxx**3*yyy+84*xxx**2*yyy+588*xxx*yyy+1372*yyy+xxx**4+28*
     2   xxx**3+294*xxx**2+1372*xxx+2401
(%o3)                       done
(%i4) f90(expr);
yyy**4+4*xxx*yyy**3+28*yyy**3+6*xxx**2*yyy**2+84*xxx*yyy**2+294* &
     yyy**2+4*xxx**3*yyy+84*xxx**2*yyy+588*xxx*yyy+1372*yyy+xxx** &
     4+28*xxx**3+294*xxx**2+1372*xxx+2401
(%o4)                       done
@end example

A implementa@value{cedilha}@~{a}o @code{f90} termina como um r@'{a}pido reparo em @code{fortran}. N@~{a}o @'{e}
necess@'{a}riamente um bom exemplo sobre o qual se deva basear outros tradutores do
Maxima para outras linguagens de programa@value{cedilha}@~{a}o.

Para usar essa fun@value{cedilha}@~{a}o escreva primeiro @code{load("f90")}.
@end deffn

