set -o pipefail
'opt' '-basicaa' '-aa-eval' '-print-all-alias-modref-info' '-disable-output' 2>& '1' < '/private/var/chris/llvm-2.8/test/Analysis/BasicAA/2007-08-01-NoAliasAndGEP.ll' |
  'grep' '9 no alias'  &&

'opt' '-basicaa' '-aa-eval' '-print-all-alias-modref-info' '-disable-output' 2>& '1' < '/private/var/chris/llvm-2.8/test/Analysis/BasicAA/2007-08-01-NoAliasAndGEP.ll' |
  'grep' '6 may alias'  &&

'opt' '-basicaa' '-aa-eval' '-print-all-alias-modref-info' '-disable-output' 2>& '1' < '/private/var/chris/llvm-2.8/test/Analysis/BasicAA/2007-08-01-NoAliasAndGEP.ll' |
  'grep' 'MayAlias:.*i32\* %Ipointer, i32\* %Jpointer'