set -o pipefail
'opt' '-basicaa' '-gvn' '-S' < '/private/var/chris/llvm-2.8/test/Analysis/BasicAA/pure-const-dce.ll' |
  'grep' 'TestConst' |
  'count' '2'  &&

'opt' '-basicaa' '-gvn' '-S' < '/private/var/chris/llvm-2.8/test/Analysis/BasicAA/pure-const-dce.ll' |
  'grep' 'TestPure' |
  'count' '3'  &&

'opt' '-basicaa' '-gvn' '-S' < '/private/var/chris/llvm-2.8/test/Analysis/BasicAA/pure-const-dce.ll' |
  'grep' 'TestNone' |
  'count' '4'