/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "poatest.h"

static ORBitSmallSkeleton get_skel_small_poatest(POA_poatest *servant,
const char *opname,gpointer *m_data, gpointer *impl)
{
switch(opname[0]) {
case 't':
if(strcmp((opname + 1), "est")) break;
*impl = (gpointer)servant->vepv->poatest_epv->test;
{ORBit_IInterface *volatile _t_=&poatest__iinterface;*m_data = (gpointer)&_t_->methods._buffer [0];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_poatest_test;
break;
default: break; 
}
return NULL;
}

void POA_poatest__init(PortableServer_Servant servant,
CORBA_Environment *env)
{
  static PortableServer_ClassInfo class_info = {NULL, (ORBit_small_impl_finder)&get_skel_small_poatest, "IDL:poatest:1.0", &poatest__classid, NULL, &poatest__iinterface};
  PortableServer_ServantBase__init (       ((PortableServer_ServantBase *)servant), env);
   ORBit_skel_class_register (&class_info,
   (PortableServer_ServantBase *)servant, POA_poatest__fini,
   ORBIT_VEPV_OFFSET (POA_poatest__vepv, poatest_epv),
   (CORBA_unsigned_long) 0);}

void POA_poatest__fini(PortableServer_Servant servant,
CORBA_Environment *env)
{
  PortableServer_ServantBase__fini(servant, env);
}

