set -o pipefail
'opt' '-regions' '-analyze' < '/private/var/chris/llvm-2.8/test/Analysis/RegionInfo/block_sort.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/Analysis/RegionInfo/block_sort.ll'  &&

'opt' '-regions' '-stats' '-analyze' 2>& '1' < '/private/var/chris/llvm-2.8/test/Analysis/RegionInfo/block_sort.ll' |
  'FileCheck' '-check-prefix=STAT' '/private/var/chris/llvm-2.8/test/Analysis/RegionInfo/block_sort.ll'  &&

'opt' '-regions' '-print-region-style=bb' '-analyze' 2>& '1' < '/private/var/chris/llvm-2.8/test/Analysis/RegionInfo/block_sort.ll' |
  'FileCheck' '-check-prefix=BBIT' '/private/var/chris/llvm-2.8/test/Analysis/RegionInfo/block_sort.ll'  &&

'opt' '-regions' '-print-region-style=rn' '-analyze' 2>& '1' < '/private/var/chris/llvm-2.8/test/Analysis/RegionInfo/block_sort.ll' |
  'FileCheck' '-check-prefix=RNIT' '/private/var/chris/llvm-2.8/test/Analysis/RegionInfo/block_sort.ll'