set -o pipefail
'opt' '-regions' '-print-region-style=bb' '-analyze' 2>& '1' < '/private/var/chris/llvm-2.8/test/Analysis/RegionInfo/multiple_exiting_edge.ll' |
  'FileCheck' '-check-prefix=BBIT' '/private/var/chris/llvm-2.8/test/Analysis/RegionInfo/multiple_exiting_edge.ll'  &&

'opt' '-regions' '-print-region-style=rn' '-analyze' 2>& '1' < '/private/var/chris/llvm-2.8/test/Analysis/RegionInfo/multiple_exiting_edge.ll' |
  'FileCheck' '-check-prefix=RNIT' '/private/var/chris/llvm-2.8/test/Analysis/RegionInfo/multiple_exiting_edge.ll'