## Makefile for building the glade DLL with gcc -mno-cygwin for mingw.
## Use: make -f makefile.mingw

TOP = ..
include $(TOP)/win32build/make.mingw

CFLAGS = $(OPTIMIZE) -DHAVE_CONFIG_H -I . -I $(INTL) -I $(GLIB) -I $(GLIB)/gmodule -I $(GTK)/gdk -I $(GTK) -I $(LIBXML)

all : \
	config.h \
	test-libglade.exe
	
config.h : config.h.win32
	cp $< $@

test-libglade.exe : test-libglade.o
	$(CC) -o $@ $< -L glade -lglade-$(LIBGLADE_VER) -L $(GTK)/gtk -lgtk-$(GTK_VER) -L $(GLIB) -lglib-$(GLIB_VER)

