set -o pipefail
'llc' '-mtriple=thumbv6-apple-darwin10' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb/2010-07-15-debugOrdering.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb/2010-07-15-debugOrdering.ll'  &&

'opt' '-strip-debug' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb/2010-07-15-debugOrdering.ll' |
  'llc' '-mtriple=thumbv6-apple-darwin10' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb/2010-07-15-debugOrdering.ll'