set -o pipefail
'llc' '-mtriple=thumbv6-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb/barrier.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb/barrier.ll' '-check-prefix=V6'  &&

'llc' '-march=thumb' '-mattr=+v6m' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb/barrier.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/Thumb/barrier.ll' '-check-prefix=V6M'