set -o pipefail
'llc' '-march=thumb' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb/long.ll' |
  'grep' 'mvn' |
  'count' '1'  &&

'llc' '-march=thumb' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb/long.ll' |
  'grep' 'adc' |
  'count' '1'  &&

'llc' '-march=thumb' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb/long.ll' |
  'grep' 'sbc' |
  'count' '1'  &&

'llc' '-march=thumb' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb/long.ll' |
  'grep' '__muldi3'