set -o pipefail
'llc' '-march=thumb' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb/select.ll' |
  'grep' 'beq' |
  'count' '1'  &&

'llc' '-march=thumb' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb/select.ll' |
  'grep' 'bgt' |
  'count' '1'  &&

'llc' '-march=thumb' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb/select.ll' |
  'grep' 'blt' |
  'count' '3'  &&

'llc' '-march=thumb' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb/select.ll' |
  'grep' 'ble' |
  'count' '1'  &&

'llc' '-march=thumb' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb/select.ll' |
  'grep' 'bls' |
  'count' '1'  &&

'llc' '-march=thumb' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb/select.ll' |
  'grep' 'bhi' |
  'count' '1'  &&

'llc' '-march=thumb' < '/private/var/chris/llvm-2.8/test/CodeGen/Thumb/select.ll' |
  'grep' '__ltdf2'