/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <endian.h> header file. */
/* #undef HAVE_ENDIAN_H */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "libXfont"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "keithp@keithp.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "libXfont"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libXfont 1.4.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libXfont"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.4.2"

/* Support PCF format fonts */
#define PCFFORMAT 

/* Define to 1 if you have the ANSI C header files. */
/* #undef STDC_HEADERS */

/* Version number of package */
#define VERSION "1.4.2"

/* Support bitmap font files */
#define XFONT_BITMAP 1

/* Support built-in fonts */
#define XFONT_BUILTINS 1

/* Support the X Font Services Protocol */
/* #undef XFONT_FC */

/* Support fonts in files */
#define XFONT_FONTFILE 

/* Support FreeType fonts */
/* #undef XFONT_FREETYPE */

/* Support gzip fonts */
#define X_GZIP_FONT_COMPRESSION 
