.TH gnutls\-serv 1 "December 1st 2003"
.SH NAME
gnutls\-serv \- GnuTLS test server
.SH SYNOPSIS
gnutls\-serv [\fIoptions\fR]
.SH DESCRIPTION
Simple server program that listens to incoming TLS connections.
.SH OPTIONS
.SS Program control options
.IP "\-d, \-\-debug LEVEL"
Specify the debug level. Default is 1.
.IP "\-h, \-\-help"
prints this help
.IP "\-l, \-\-list"
Print a list of the supported algorithms and modes.
.IP "\-q, \-\-quiet"
Suppress some messages.
.IP "\-v, \-\-version"
prints the program's version number

.SS Server options
.IP "\-p, \-\-port \fIinteger\fR"
The port to listen on.
.IP "\-\-nodb"
Does not use the resume database.
.IP "\-\-http"
Act as an HTTP Server.
.IP "\-\-echo"
Act as an Echo Server.

.SS TLS/SSL control options
.IP "\-\-priority \fIPRIORITY STRING\fR"
TLS algorithms and protocols to enable.
You can use predefined sets of ciphersuites such as: 
.IP
.B "PERFORMANCE"
all the "secure" ciphersuites are enabled, limited to 128 bit
ciphers and sorted by terms of speed performance.
.IP 
.B "NORMAL" 
option enables all "secure" ciphersuites. The 256-bit ciphers
are included as a fallback only. The ciphers are sorted by security
margin.
.IP 
.B "SECURE128" 
flag enables all "secure" ciphersuites with ciphers up to
128 bits, sorted by security margin.
.IP 
.B "SECURE256" 
flag enables all "secure" ciphersuites including the 256 bit
ciphers, sorted by security margin.
.IP 
.B "EXPORT" 
all the ciphersuites are enabled, including the
low-security 40 bit ciphers.
.IP 
.B "NONE" 
nothing is enabled. This disables even protocols and
compression methods.
.IP
.IP
Check the GnuTLS manual on section "Priority strings" for
more information on allowed keywords.
.IP 
.B Examples:
.IP 
"NORMAL"
.IP 
"NONE:+VERS-TLS-ALL:+MAC-ALL:+RSA:+AES-128-CBC:+SIGN-ALL:+COMP-NULL"
.IP 
"NORMAL:-ARCFOUR-128" means normal ciphers except for ARCFOUR-128.
.IP 
"SECURE:-VERS-SSL3.0:+COMP-DEFLATE" means that only secure ciphers are
enabled, SSL3.0 is disabled, and libz compression enabled.
.IP
 "NONE:+VERS-TLS-ALL:+AES-128-CBC:+RSA:+SHA1:+COMP-NULL:+SIGN-RSA-SHA1"
.IP 
"NORMAL:%COMPAT" is the most compatible mode

.IP "\-g, \-\-generate"
Generate Diffie-Hellman Parameters.
.IP "\-\-kx \fIkx1 kx2...\fR"
Key exchange methods to enable (use \fBgnutls\-cli \-\-list\fR to show
the supported key exchange methods).
.IP "\-p, \-\-port \fIinteger\fR"
The port to connect to.

.SS Certificate options
.IP "\-\-pgpcertfile \fIFILE\fR"
PGP Public Key (certificate) file to use.
.IP "\-\-pgpkeyfile \fIFILE\fR"
PGP Key file to use.
.IP "\-\-pgpkeyring \fIFILE\fR"
PGP Key ring file to use.
.IP "\-\-pgptrustdb \fIFILE\fR"
PGP trustdb file to use.
.IP "\-\-srppasswd \fIFILE\fR"
SRP password file to use.
.IP "\-\-srppasswdconf \fIFILE\fR"
SRP password configuration file to use.
.IP "\-\-x509cafile \fIFILE\fR"
Certificate file to use.
.IP "\-\-x509certfile \fIFILE\fR"
X.509 Certificate file to use.
.IP "\-\-x509fmtder"
Use DER format for certificates
.IP "\-\-x509keyfile \fIFILE\fR"
X.509 key file to use.

.SH "SEE ALSO"
.BR gnutls\-cli (1),
.BR gnutls\-cli\-debug (1)
.SH AUTHOR
.PP
Nikos Mavrogiannopoulos <nmav@gnutls.org> and others; see
/usr/share/doc/gnutls\-bin/AUTHORS for a complete list.
.PP
This manual page was written by Ivo Timmermans <ivo@debian.org>, for
the Debian GNU/Linux system (but may be used by others).
