.TH psktool 1 "February 21st 2005"
.SH NAME
psktool \- Simple PSK password tool
.SH SYNOPSIS
psktool [\fIoptions\fR]
.SH DESCRIPTION
Very simple program that generates random keys for use with
TLS-PSK. The keys are stored in hexadecimal format in a file.

.SH OPTIONS
.IP "\-\-keysize \fIBYTES\fR"
specify the number of bytes of the key
.IP "\-p, \-\-passwd \fIFILE\fR"
Specify a password file.
.IP "\-u, \-\-username \fIusername\fR"
Specify username.
.IP "\-h, \-\-help"
Prints a short reminder of the command line options.
.SH EXAMPLES
To create a passwd.psk with a user called test for use with gnuTLS run:

.RS
.nf
$ psktool \-\-passwd /etc/passwd.psk \-u test
.fi
.RE

.SH AUTHOR
.PP
Nikos Mavroyanopoulos <nmav@gnutls.org> and others; see
/usr/share/doc/gnutls\-bin/AUTHORS for a complete list.
