/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#ifndef Bonobo_Activation_types_H
#define Bonobo_Activation_types_H 1
#include <glib.h>
#define ORBIT_IDL_SERIAL 20
#include <orbit/orbit-types.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/** typedefs **/
#if !defined(ORBIT_DECL_CORBA_sequence_CORBA_string)
#define ORBIT_DECL_CORBA_sequence_CORBA_string 1
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_0 'B'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_1 'o'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_2 'n'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_3 'o'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_4 'b'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_5 'o'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_6 '_'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_7 'A'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_8 'c'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_9 't'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_10 'i'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_11 'v'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_12 'a'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_13 't'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_14 'i'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_15 'o'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_16 'n'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_17 '_'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_18 't'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_19 'y'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_20 'p'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_21 'e'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_22 's'
#if !defined(_CORBA_sequence_CORBA_string_defined)
#define _CORBA_sequence_CORBA_string_defined 1
typedef struct { CORBA_unsigned_long _maximum, _length; CORBA_string* _buffer; CORBA_boolean _release; } CORBA_sequence_CORBA_string;
#endif
#if !defined(TC_IMPL_TC_CORBA_sequence_CORBA_string_0)
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_0 'B'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_1 'o'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_2 'n'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_3 'o'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_4 'b'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_5 'o'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_6 '_'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_7 'A'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_8 'c'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_9 't'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_10 'i'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_11 'v'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_12 'a'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_13 't'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_14 'i'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_15 'o'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_16 'n'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_17 '_'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_18 't'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_19 'y'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_20 'p'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_21 'e'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct;
#define TC_CORBA_sequence_CORBA_string ((CORBA_TypeCode)&TC_CORBA_sequence_CORBA_string_struct)
#endif
#define CORBA_sequence_CORBA_string__alloc() ((CORBA_sequence_CORBA_string *)ORBit_small_alloc (TC_CORBA_sequence_CORBA_string))
#define CORBA_sequence_CORBA_string__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_CORBA_string,(m),(d))
#define CORBA_sequence_CORBA_string_allocbuf(l) ((CORBA_string*)ORBit_small_allocbuf (TC_CORBA_sequence_CORBA_string, (l)))
#define CORBA_sequence_CORBA_string_allocbuf(l) ((CORBA_string*)ORBit_small_allocbuf (TC_CORBA_sequence_CORBA_string, (l)))
#endif
#if !defined(_Bonobo_StringList_defined)
#define _Bonobo_StringList_defined 1
typedef CORBA_sequence_CORBA_string Bonobo_StringList;
#define Bonobo_StringList_marshal(x,y,z) CORBA_sequence_CORBA_string_marshal((x),(y),(z))
#define Bonobo_StringList_demarshal(x,y,z,i) CORBA_sequence_CORBA_string_demarshal((x),(y),(z),(i))
#if !defined(TC_IMPL_TC_Bonobo_StringList_0)
#define TC_IMPL_TC_Bonobo_StringList_0 'B'
#define TC_IMPL_TC_Bonobo_StringList_1 'o'
#define TC_IMPL_TC_Bonobo_StringList_2 'n'
#define TC_IMPL_TC_Bonobo_StringList_3 'o'
#define TC_IMPL_TC_Bonobo_StringList_4 'b'
#define TC_IMPL_TC_Bonobo_StringList_5 'o'
#define TC_IMPL_TC_Bonobo_StringList_6 '_'
#define TC_IMPL_TC_Bonobo_StringList_7 'A'
#define TC_IMPL_TC_Bonobo_StringList_8 'c'
#define TC_IMPL_TC_Bonobo_StringList_9 't'
#define TC_IMPL_TC_Bonobo_StringList_10 'i'
#define TC_IMPL_TC_Bonobo_StringList_11 'v'
#define TC_IMPL_TC_Bonobo_StringList_12 'a'
#define TC_IMPL_TC_Bonobo_StringList_13 't'
#define TC_IMPL_TC_Bonobo_StringList_14 'i'
#define TC_IMPL_TC_Bonobo_StringList_15 'o'
#define TC_IMPL_TC_Bonobo_StringList_16 'n'
#define TC_IMPL_TC_Bonobo_StringList_17 '_'
#define TC_IMPL_TC_Bonobo_StringList_18 't'
#define TC_IMPL_TC_Bonobo_StringList_19 'y'
#define TC_IMPL_TC_Bonobo_StringList_20 'p'
#define TC_IMPL_TC_Bonobo_StringList_21 'e'
#define TC_IMPL_TC_Bonobo_StringList_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_StringList_struct;
#define TC_Bonobo_StringList ((CORBA_TypeCode)&TC_Bonobo_StringList_struct)
#endif
#define Bonobo_StringList__alloc() ((Bonobo_StringList *)ORBit_small_alloc (TC_CORBA_sequence_CORBA_string))
#define Bonobo_StringList__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_CORBA_string,(m),(d))
#define Bonobo_StringList_allocbuf(l) ((CORBA_string*)ORBit_small_allocbuf (TC_CORBA_sequence_CORBA_string, (l)))
#endif
#undef ex_Bonobo_GeneralError
#define ex_Bonobo_GeneralError "IDL:Bonobo/GeneralError:1.0"
#if !defined(_Bonobo_GeneralError_defined)
#define _Bonobo_GeneralError_defined 1
typedef struct Bonobo_GeneralError_type Bonobo_GeneralError;
struct Bonobo_GeneralError_type {
CORBA_string description;
};

#if !defined(TC_IMPL_TC_Bonobo_GeneralError_0)
#define TC_IMPL_TC_Bonobo_GeneralError_0 'B'
#define TC_IMPL_TC_Bonobo_GeneralError_1 'o'
#define TC_IMPL_TC_Bonobo_GeneralError_2 'n'
#define TC_IMPL_TC_Bonobo_GeneralError_3 'o'
#define TC_IMPL_TC_Bonobo_GeneralError_4 'b'
#define TC_IMPL_TC_Bonobo_GeneralError_5 'o'
#define TC_IMPL_TC_Bonobo_GeneralError_6 '_'
#define TC_IMPL_TC_Bonobo_GeneralError_7 'A'
#define TC_IMPL_TC_Bonobo_GeneralError_8 'c'
#define TC_IMPL_TC_Bonobo_GeneralError_9 't'
#define TC_IMPL_TC_Bonobo_GeneralError_10 'i'
#define TC_IMPL_TC_Bonobo_GeneralError_11 'v'
#define TC_IMPL_TC_Bonobo_GeneralError_12 'a'
#define TC_IMPL_TC_Bonobo_GeneralError_13 't'
#define TC_IMPL_TC_Bonobo_GeneralError_14 'i'
#define TC_IMPL_TC_Bonobo_GeneralError_15 'o'
#define TC_IMPL_TC_Bonobo_GeneralError_16 'n'
#define TC_IMPL_TC_Bonobo_GeneralError_17 '_'
#define TC_IMPL_TC_Bonobo_GeneralError_18 't'
#define TC_IMPL_TC_Bonobo_GeneralError_19 'y'
#define TC_IMPL_TC_Bonobo_GeneralError_20 'p'
#define TC_IMPL_TC_Bonobo_GeneralError_21 'e'
#define TC_IMPL_TC_Bonobo_GeneralError_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_GeneralError_struct;
#define TC_Bonobo_GeneralError ((CORBA_TypeCode)&TC_Bonobo_GeneralError_struct)
#endif
#define Bonobo_GeneralError__alloc() ((Bonobo_GeneralError *)ORBit_small_alloc (TC_Bonobo_GeneralError))
#define Bonobo_GeneralError__freekids(m,d) ORBit_small_freekids (TC_Bonobo_GeneralError,(m),(d))
#endif
#undef ex_Bonobo_Activation_NotListed
#define ex_Bonobo_Activation_NotListed "IDL:Bonobo/Activation/NotListed:1.0"
#if !defined(_Bonobo_Activation_NotListed_defined)
#define _Bonobo_Activation_NotListed_defined 1
typedef struct Bonobo_Activation_NotListed_type Bonobo_Activation_NotListed;
struct Bonobo_Activation_NotListed_type {
int dummy;
};

#if !defined(TC_IMPL_TC_Bonobo_Activation_NotListed_0)
#define TC_IMPL_TC_Bonobo_Activation_NotListed_0 'B'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_1 'o'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_2 'n'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_3 'o'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_4 'b'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_5 'o'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_6 '_'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_7 'A'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_8 'c'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_9 't'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_10 'i'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_11 'v'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_12 'a'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_13 't'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_14 'i'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_15 'o'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_16 'n'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_17 '_'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_18 't'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_19 'y'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_20 'p'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_21 'e'
#define TC_IMPL_TC_Bonobo_Activation_NotListed_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_Activation_NotListed_struct;
#define TC_Bonobo_Activation_NotListed ((CORBA_TypeCode)&TC_Bonobo_Activation_NotListed_struct)
#endif
#define Bonobo_Activation_NotListed__alloc() ((Bonobo_Activation_NotListed *)ORBit_small_alloc (TC_Bonobo_Activation_NotListed))
#define Bonobo_Activation_NotListed__freekids(m,d) ORBit_small_freekids (TC_Bonobo_Activation_NotListed,(m),(d))
#endif
#undef ex_Bonobo_Activation_AlreadyListed
#define ex_Bonobo_Activation_AlreadyListed "IDL:Bonobo/Activation/AlreadyListed:1.0"
#if !defined(_Bonobo_Activation_AlreadyListed_defined)
#define _Bonobo_Activation_AlreadyListed_defined 1
typedef struct Bonobo_Activation_AlreadyListed_type Bonobo_Activation_AlreadyListed;
struct Bonobo_Activation_AlreadyListed_type {
int dummy;
};

#if !defined(TC_IMPL_TC_Bonobo_Activation_AlreadyListed_0)
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_0 'B'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_1 'o'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_2 'n'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_3 'o'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_4 'b'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_5 'o'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_6 '_'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_7 'A'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_8 'c'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_9 't'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_10 'i'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_11 'v'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_12 'a'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_13 't'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_14 'i'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_15 'o'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_16 'n'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_17 '_'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_18 't'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_19 'y'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_20 'p'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_21 'e'
#define TC_IMPL_TC_Bonobo_Activation_AlreadyListed_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_Activation_AlreadyListed_struct;
#define TC_Bonobo_Activation_AlreadyListed ((CORBA_TypeCode)&TC_Bonobo_Activation_AlreadyListed_struct)
#endif
#define Bonobo_Activation_AlreadyListed__alloc() ((Bonobo_Activation_AlreadyListed *)ORBit_small_alloc (TC_Bonobo_Activation_AlreadyListed))
#define Bonobo_Activation_AlreadyListed__freekids(m,d) ORBit_small_freekids (TC_Bonobo_Activation_AlreadyListed,(m),(d))
#endif
#undef ex_Bonobo_Activation_IncompleteContext
#define ex_Bonobo_Activation_IncompleteContext "IDL:Bonobo/Activation/IncompleteContext:1.0"
#if !defined(_Bonobo_Activation_IncompleteContext_defined)
#define _Bonobo_Activation_IncompleteContext_defined 1
typedef struct Bonobo_Activation_IncompleteContext_type Bonobo_Activation_IncompleteContext;
struct Bonobo_Activation_IncompleteContext_type {
int dummy;
};

#if !defined(TC_IMPL_TC_Bonobo_Activation_IncompleteContext_0)
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_0 'B'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_1 'o'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_2 'n'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_3 'o'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_4 'b'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_5 'o'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_6 '_'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_7 'A'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_8 'c'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_9 't'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_10 'i'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_11 'v'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_12 'a'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_13 't'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_14 'i'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_15 'o'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_16 'n'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_17 '_'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_18 't'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_19 'y'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_20 'p'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_21 'e'
#define TC_IMPL_TC_Bonobo_Activation_IncompleteContext_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_Activation_IncompleteContext_struct;
#define TC_Bonobo_Activation_IncompleteContext ((CORBA_TypeCode)&TC_Bonobo_Activation_IncompleteContext_struct)
#endif
#define Bonobo_Activation_IncompleteContext__alloc() ((Bonobo_Activation_IncompleteContext *)ORBit_small_alloc (TC_Bonobo_Activation_IncompleteContext))
#define Bonobo_Activation_IncompleteContext__freekids(m,d) ORBit_small_freekids (TC_Bonobo_Activation_IncompleteContext,(m),(d))
#endif
#undef ex_Bonobo_Activation_ParseFailed
#define ex_Bonobo_Activation_ParseFailed "IDL:Bonobo/Activation/ParseFailed:1.0"
#if !defined(_Bonobo_Activation_ParseFailed_defined)
#define _Bonobo_Activation_ParseFailed_defined 1
typedef struct Bonobo_Activation_ParseFailed_type Bonobo_Activation_ParseFailed;
struct Bonobo_Activation_ParseFailed_type {
CORBA_string description;
};

#if !defined(TC_IMPL_TC_Bonobo_Activation_ParseFailed_0)
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_0 'B'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_1 'o'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_2 'n'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_3 'o'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_4 'b'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_5 'o'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_6 '_'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_7 'A'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_8 'c'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_9 't'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_10 'i'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_11 'v'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_12 'a'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_13 't'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_14 'i'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_15 'o'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_16 'n'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_17 '_'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_18 't'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_19 'y'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_20 'p'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_21 'e'
#define TC_IMPL_TC_Bonobo_Activation_ParseFailed_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_Activation_ParseFailed_struct;
#define TC_Bonobo_Activation_ParseFailed ((CORBA_TypeCode)&TC_Bonobo_Activation_ParseFailed_struct)
#endif
#define Bonobo_Activation_ParseFailed__alloc() ((Bonobo_Activation_ParseFailed *)ORBit_small_alloc (TC_Bonobo_Activation_ParseFailed))
#define Bonobo_Activation_ParseFailed__freekids(m,d) ORBit_small_freekids (TC_Bonobo_Activation_ParseFailed,(m),(d))
#endif
#if !defined(_Bonobo_ImplementationID_defined)
#define _Bonobo_ImplementationID_defined 1
typedef CORBA_string Bonobo_ImplementationID;
#define Bonobo_ImplementationID_marshal(x,y,z) CORBA_string_marshal((x),(y),(z))
#define Bonobo_ImplementationID_demarshal(x,y,z,i) CORBA_string_demarshal((x),(y),(z),(i))
#if !defined(TC_IMPL_TC_Bonobo_ImplementationID_0)
#define TC_IMPL_TC_Bonobo_ImplementationID_0 'B'
#define TC_IMPL_TC_Bonobo_ImplementationID_1 'o'
#define TC_IMPL_TC_Bonobo_ImplementationID_2 'n'
#define TC_IMPL_TC_Bonobo_ImplementationID_3 'o'
#define TC_IMPL_TC_Bonobo_ImplementationID_4 'b'
#define TC_IMPL_TC_Bonobo_ImplementationID_5 'o'
#define TC_IMPL_TC_Bonobo_ImplementationID_6 '_'
#define TC_IMPL_TC_Bonobo_ImplementationID_7 'A'
#define TC_IMPL_TC_Bonobo_ImplementationID_8 'c'
#define TC_IMPL_TC_Bonobo_ImplementationID_9 't'
#define TC_IMPL_TC_Bonobo_ImplementationID_10 'i'
#define TC_IMPL_TC_Bonobo_ImplementationID_11 'v'
#define TC_IMPL_TC_Bonobo_ImplementationID_12 'a'
#define TC_IMPL_TC_Bonobo_ImplementationID_13 't'
#define TC_IMPL_TC_Bonobo_ImplementationID_14 'i'
#define TC_IMPL_TC_Bonobo_ImplementationID_15 'o'
#define TC_IMPL_TC_Bonobo_ImplementationID_16 'n'
#define TC_IMPL_TC_Bonobo_ImplementationID_17 '_'
#define TC_IMPL_TC_Bonobo_ImplementationID_18 't'
#define TC_IMPL_TC_Bonobo_ImplementationID_19 'y'
#define TC_IMPL_TC_Bonobo_ImplementationID_20 'p'
#define TC_IMPL_TC_Bonobo_ImplementationID_21 'e'
#define TC_IMPL_TC_Bonobo_ImplementationID_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_ImplementationID_struct;
#define TC_Bonobo_ImplementationID ((CORBA_TypeCode)&TC_Bonobo_ImplementationID_struct)
#endif
#define Bonobo_ImplementationID__alloc() ((Bonobo_ImplementationID *)ORBit_small_alloc (TC_CORBA_string))
#define Bonobo_ImplementationID__freekids(m,d) ORBit_small_freekids (TC_CORBA_string,(m),(d))
#endif
#if !defined(_Bonobo_ActivationID_defined)
#define _Bonobo_ActivationID_defined 1
typedef CORBA_string Bonobo_ActivationID;
#define Bonobo_ActivationID_marshal(x,y,z) CORBA_string_marshal((x),(y),(z))
#define Bonobo_ActivationID_demarshal(x,y,z,i) CORBA_string_demarshal((x),(y),(z),(i))
#if !defined(TC_IMPL_TC_Bonobo_ActivationID_0)
#define TC_IMPL_TC_Bonobo_ActivationID_0 'B'
#define TC_IMPL_TC_Bonobo_ActivationID_1 'o'
#define TC_IMPL_TC_Bonobo_ActivationID_2 'n'
#define TC_IMPL_TC_Bonobo_ActivationID_3 'o'
#define TC_IMPL_TC_Bonobo_ActivationID_4 'b'
#define TC_IMPL_TC_Bonobo_ActivationID_5 'o'
#define TC_IMPL_TC_Bonobo_ActivationID_6 '_'
#define TC_IMPL_TC_Bonobo_ActivationID_7 'A'
#define TC_IMPL_TC_Bonobo_ActivationID_8 'c'
#define TC_IMPL_TC_Bonobo_ActivationID_9 't'
#define TC_IMPL_TC_Bonobo_ActivationID_10 'i'
#define TC_IMPL_TC_Bonobo_ActivationID_11 'v'
#define TC_IMPL_TC_Bonobo_ActivationID_12 'a'
#define TC_IMPL_TC_Bonobo_ActivationID_13 't'
#define TC_IMPL_TC_Bonobo_ActivationID_14 'i'
#define TC_IMPL_TC_Bonobo_ActivationID_15 'o'
#define TC_IMPL_TC_Bonobo_ActivationID_16 'n'
#define TC_IMPL_TC_Bonobo_ActivationID_17 '_'
#define TC_IMPL_TC_Bonobo_ActivationID_18 't'
#define TC_IMPL_TC_Bonobo_ActivationID_19 'y'
#define TC_IMPL_TC_Bonobo_ActivationID_20 'p'
#define TC_IMPL_TC_Bonobo_ActivationID_21 'e'
#define TC_IMPL_TC_Bonobo_ActivationID_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_ActivationID_struct;
#define TC_Bonobo_ActivationID ((CORBA_TypeCode)&TC_Bonobo_ActivationID_struct)
#endif
#define Bonobo_ActivationID__alloc() ((Bonobo_ActivationID *)ORBit_small_alloc (TC_CORBA_string))
#define Bonobo_ActivationID__freekids(m,d) ORBit_small_freekids (TC_CORBA_string,(m),(d))
#endif
#if !defined(_Bonobo_ActivationFlags_defined)
#define _Bonobo_ActivationFlags_defined 1
typedef CORBA_long Bonobo_ActivationFlags;
#define Bonobo_ActivationFlags_marshal(x,y,z) CORBA_long_marshal((x),(y),(z))
#define Bonobo_ActivationFlags_demarshal(x,y,z,i) CORBA_long_demarshal((x),(y),(z),(i))
#if !defined(TC_IMPL_TC_Bonobo_ActivationFlags_0)
#define TC_IMPL_TC_Bonobo_ActivationFlags_0 'B'
#define TC_IMPL_TC_Bonobo_ActivationFlags_1 'o'
#define TC_IMPL_TC_Bonobo_ActivationFlags_2 'n'
#define TC_IMPL_TC_Bonobo_ActivationFlags_3 'o'
#define TC_IMPL_TC_Bonobo_ActivationFlags_4 'b'
#define TC_IMPL_TC_Bonobo_ActivationFlags_5 'o'
#define TC_IMPL_TC_Bonobo_ActivationFlags_6 '_'
#define TC_IMPL_TC_Bonobo_ActivationFlags_7 'A'
#define TC_IMPL_TC_Bonobo_ActivationFlags_8 'c'
#define TC_IMPL_TC_Bonobo_ActivationFlags_9 't'
#define TC_IMPL_TC_Bonobo_ActivationFlags_10 'i'
#define TC_IMPL_TC_Bonobo_ActivationFlags_11 'v'
#define TC_IMPL_TC_Bonobo_ActivationFlags_12 'a'
#define TC_IMPL_TC_Bonobo_ActivationFlags_13 't'
#define TC_IMPL_TC_Bonobo_ActivationFlags_14 'i'
#define TC_IMPL_TC_Bonobo_ActivationFlags_15 'o'
#define TC_IMPL_TC_Bonobo_ActivationFlags_16 'n'
#define TC_IMPL_TC_Bonobo_ActivationFlags_17 '_'
#define TC_IMPL_TC_Bonobo_ActivationFlags_18 't'
#define TC_IMPL_TC_Bonobo_ActivationFlags_19 'y'
#define TC_IMPL_TC_Bonobo_ActivationFlags_20 'p'
#define TC_IMPL_TC_Bonobo_ActivationFlags_21 'e'
#define TC_IMPL_TC_Bonobo_ActivationFlags_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_ActivationFlags_struct;
#define TC_Bonobo_ActivationFlags ((CORBA_TypeCode)&TC_Bonobo_ActivationFlags_struct)
#endif
#define Bonobo_ActivationFlags__alloc() ((Bonobo_ActivationFlags *)ORBit_small_alloc (TC_CORBA_long))
#define Bonobo_ActivationFlags__freekids(m,d) ORBit_small_freekids (TC_CORBA_long,(m),(d))
#endif
#ifndef Bonobo_ACTIVATION_FLAG_NO_LOCAL
#define Bonobo_ACTIVATION_FLAG_NO_LOCAL 1
#endif /* !Bonobo_ACTIVATION_FLAG_NO_LOCAL */

#ifndef Bonobo_ACTIVATION_FLAG_PRIVATE
#define Bonobo_ACTIVATION_FLAG_PRIVATE 2
#endif /* !Bonobo_ACTIVATION_FLAG_PRIVATE */

#ifndef Bonobo_ACTIVATION_FLAG_EXISTING_ONLY
#define Bonobo_ACTIVATION_FLAG_EXISTING_ONLY 4
#endif /* !Bonobo_ACTIVATION_FLAG_EXISTING_ONLY */

#if !defined(_Bonobo_ActivationEnvValue_defined)
#define _Bonobo_ActivationEnvValue_defined 1
typedef struct Bonobo_ActivationEnvValue_type Bonobo_ActivationEnvValue;
struct Bonobo_ActivationEnvValue_type {
CORBA_string name;
CORBA_string value;
CORBA_boolean unset;
};

#if !defined(TC_IMPL_TC_Bonobo_ActivationEnvValue_0)
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_0 'B'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_1 'o'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_2 'n'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_3 'o'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_4 'b'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_5 'o'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_6 '_'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_7 'A'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_8 'c'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_9 't'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_10 'i'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_11 'v'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_12 'a'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_13 't'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_14 'i'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_15 'o'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_16 'n'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_17 '_'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_18 't'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_19 'y'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_20 'p'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_21 'e'
#define TC_IMPL_TC_Bonobo_ActivationEnvValue_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_ActivationEnvValue_struct;
#define TC_Bonobo_ActivationEnvValue ((CORBA_TypeCode)&TC_Bonobo_ActivationEnvValue_struct)
#endif
#define Bonobo_ActivationEnvValue__alloc() ((Bonobo_ActivationEnvValue *)ORBit_small_alloc (TC_Bonobo_ActivationEnvValue))
#define Bonobo_ActivationEnvValue__freekids(m,d) ORBit_small_freekids (TC_Bonobo_ActivationEnvValue,(m),(d))
#endif
#if !defined(ORBIT_DECL_CORBA_sequence_Bonobo_ActivationEnvValue)
#define ORBIT_DECL_CORBA_sequence_Bonobo_ActivationEnvValue 1
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_0 'B'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_1 'o'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_2 'n'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_3 'o'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_4 'b'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_5 'o'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_6 '_'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_7 'A'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_8 'c'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_9 't'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_10 'i'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_11 'v'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_12 'a'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_13 't'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_14 'i'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_15 'o'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_16 'n'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_17 '_'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_18 't'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_19 'y'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_20 'p'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_21 'e'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationEnvValue_22 's'
#if !defined(_CORBA_sequence_Bonobo_ActivationEnvValue_defined)
#define _CORBA_sequence_Bonobo_ActivationEnvValue_defined 1
typedef struct { CORBA_unsigned_long _maximum, _length; Bonobo_ActivationEnvValue* _buffer; CORBA_boolean _release; } CORBA_sequence_Bonobo_ActivationEnvValue;
#endif
#if !defined(TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_0)
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_0 'B'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_1 'o'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_2 'n'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_3 'o'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_4 'b'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_5 'o'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_6 '_'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_7 'A'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_8 'c'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_9 't'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_10 'i'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_11 'v'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_12 'a'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_13 't'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_14 'i'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_15 'o'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_16 'n'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_17 '_'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_18 't'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_19 'y'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_20 'p'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_21 'e'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationEnvValue_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_CORBA_sequence_Bonobo_ActivationEnvValue_struct;
#define TC_CORBA_sequence_Bonobo_ActivationEnvValue ((CORBA_TypeCode)&TC_CORBA_sequence_Bonobo_ActivationEnvValue_struct)
#endif
#define CORBA_sequence_Bonobo_ActivationEnvValue__alloc() ((CORBA_sequence_Bonobo_ActivationEnvValue *)ORBit_small_alloc (TC_CORBA_sequence_Bonobo_ActivationEnvValue))
#define CORBA_sequence_Bonobo_ActivationEnvValue__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_Bonobo_ActivationEnvValue,(m),(d))
#define CORBA_sequence_Bonobo_ActivationEnvValue_allocbuf(l) ((Bonobo_ActivationEnvValue*)ORBit_small_allocbuf (TC_CORBA_sequence_Bonobo_ActivationEnvValue, (l)))
#define CORBA_sequence_Bonobo_ActivationEnvValue_allocbuf(l) ((Bonobo_ActivationEnvValue*)ORBit_small_allocbuf (TC_CORBA_sequence_Bonobo_ActivationEnvValue, (l)))
#endif
#if !defined(_Bonobo_ActivationEnvironment_defined)
#define _Bonobo_ActivationEnvironment_defined 1
typedef CORBA_sequence_Bonobo_ActivationEnvValue Bonobo_ActivationEnvironment;
#define Bonobo_ActivationEnvironment_marshal(x,y,z) CORBA_sequence_Bonobo_ActivationEnvValue_marshal((x),(y),(z))
#define Bonobo_ActivationEnvironment_demarshal(x,y,z,i) CORBA_sequence_Bonobo_ActivationEnvValue_demarshal((x),(y),(z),(i))
#if !defined(TC_IMPL_TC_Bonobo_ActivationEnvironment_0)
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_0 'B'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_1 'o'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_2 'n'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_3 'o'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_4 'b'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_5 'o'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_6 '_'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_7 'A'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_8 'c'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_9 't'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_10 'i'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_11 'v'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_12 'a'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_13 't'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_14 'i'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_15 'o'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_16 'n'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_17 '_'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_18 't'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_19 'y'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_20 'p'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_21 'e'
#define TC_IMPL_TC_Bonobo_ActivationEnvironment_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_ActivationEnvironment_struct;
#define TC_Bonobo_ActivationEnvironment ((CORBA_TypeCode)&TC_Bonobo_ActivationEnvironment_struct)
#endif
#define Bonobo_ActivationEnvironment__alloc() ((Bonobo_ActivationEnvironment *)ORBit_small_alloc (TC_CORBA_sequence_Bonobo_ActivationEnvValue))
#define Bonobo_ActivationEnvironment__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_Bonobo_ActivationEnvValue,(m),(d))
#define Bonobo_ActivationEnvironment_allocbuf(l) ((Bonobo_ActivationEnvValue*)ORBit_small_allocbuf (TC_CORBA_sequence_Bonobo_ActivationEnvValue, (l)))
#endif
#if !defined(_Bonobo_ActivationResultType_defined)
#define _Bonobo_ActivationResultType_defined 1
typedef enum {
  Bonobo_ACTIVATION_RESULT_OBJECT,
  Bonobo_ACTIVATION_RESULT_SHLIB,
  Bonobo_ACTIVATION_RESULT_NONE
} Bonobo_ActivationResultType;
#if !defined(TC_IMPL_TC_Bonobo_ActivationResultType_0)
#define TC_IMPL_TC_Bonobo_ActivationResultType_0 'B'
#define TC_IMPL_TC_Bonobo_ActivationResultType_1 'o'
#define TC_IMPL_TC_Bonobo_ActivationResultType_2 'n'
#define TC_IMPL_TC_Bonobo_ActivationResultType_3 'o'
#define TC_IMPL_TC_Bonobo_ActivationResultType_4 'b'
#define TC_IMPL_TC_Bonobo_ActivationResultType_5 'o'
#define TC_IMPL_TC_Bonobo_ActivationResultType_6 '_'
#define TC_IMPL_TC_Bonobo_ActivationResultType_7 'A'
#define TC_IMPL_TC_Bonobo_ActivationResultType_8 'c'
#define TC_IMPL_TC_Bonobo_ActivationResultType_9 't'
#define TC_IMPL_TC_Bonobo_ActivationResultType_10 'i'
#define TC_IMPL_TC_Bonobo_ActivationResultType_11 'v'
#define TC_IMPL_TC_Bonobo_ActivationResultType_12 'a'
#define TC_IMPL_TC_Bonobo_ActivationResultType_13 't'
#define TC_IMPL_TC_Bonobo_ActivationResultType_14 'i'
#define TC_IMPL_TC_Bonobo_ActivationResultType_15 'o'
#define TC_IMPL_TC_Bonobo_ActivationResultType_16 'n'
#define TC_IMPL_TC_Bonobo_ActivationResultType_17 '_'
#define TC_IMPL_TC_Bonobo_ActivationResultType_18 't'
#define TC_IMPL_TC_Bonobo_ActivationResultType_19 'y'
#define TC_IMPL_TC_Bonobo_ActivationResultType_20 'p'
#define TC_IMPL_TC_Bonobo_ActivationResultType_21 'e'
#define TC_IMPL_TC_Bonobo_ActivationResultType_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_ActivationResultType_struct;
#define TC_Bonobo_ActivationResultType ((CORBA_TypeCode)&TC_Bonobo_ActivationResultType_struct)
#endif
#endif
#if !defined(_Bonobo_ActivationResultData_defined)
#define _Bonobo_ActivationResultData_defined 1
typedef struct Bonobo_ActivationResultData_type Bonobo_ActivationResultData;
struct Bonobo_ActivationResultData_type {
Bonobo_ActivationResultType _d;
union {
CORBA_Object res_object;
Bonobo_StringList res_shlib;
} _u;
};
#if !defined(TC_IMPL_TC_Bonobo_ActivationResultData_0)
#define TC_IMPL_TC_Bonobo_ActivationResultData_0 'B'
#define TC_IMPL_TC_Bonobo_ActivationResultData_1 'o'
#define TC_IMPL_TC_Bonobo_ActivationResultData_2 'n'
#define TC_IMPL_TC_Bonobo_ActivationResultData_3 'o'
#define TC_IMPL_TC_Bonobo_ActivationResultData_4 'b'
#define TC_IMPL_TC_Bonobo_ActivationResultData_5 'o'
#define TC_IMPL_TC_Bonobo_ActivationResultData_6 '_'
#define TC_IMPL_TC_Bonobo_ActivationResultData_7 'A'
#define TC_IMPL_TC_Bonobo_ActivationResultData_8 'c'
#define TC_IMPL_TC_Bonobo_ActivationResultData_9 't'
#define TC_IMPL_TC_Bonobo_ActivationResultData_10 'i'
#define TC_IMPL_TC_Bonobo_ActivationResultData_11 'v'
#define TC_IMPL_TC_Bonobo_ActivationResultData_12 'a'
#define TC_IMPL_TC_Bonobo_ActivationResultData_13 't'
#define TC_IMPL_TC_Bonobo_ActivationResultData_14 'i'
#define TC_IMPL_TC_Bonobo_ActivationResultData_15 'o'
#define TC_IMPL_TC_Bonobo_ActivationResultData_16 'n'
#define TC_IMPL_TC_Bonobo_ActivationResultData_17 '_'
#define TC_IMPL_TC_Bonobo_ActivationResultData_18 't'
#define TC_IMPL_TC_Bonobo_ActivationResultData_19 'y'
#define TC_IMPL_TC_Bonobo_ActivationResultData_20 'p'
#define TC_IMPL_TC_Bonobo_ActivationResultData_21 'e'
#define TC_IMPL_TC_Bonobo_ActivationResultData_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_ActivationResultData_struct;
#define TC_Bonobo_ActivationResultData ((CORBA_TypeCode)&TC_Bonobo_ActivationResultData_struct)
#endif
#define Bonobo_ActivationResultData__alloc() ((Bonobo_ActivationResultData *)ORBit_small_alloc (TC_Bonobo_ActivationResultData))
#define Bonobo_ActivationResultData__freekids(m,d) ORBit_small_freekids (TC_Bonobo_ActivationResultData,(m),(d))
#endif
#if !defined(_Bonobo_ActivationResult_defined)
#define _Bonobo_ActivationResult_defined 1
typedef struct Bonobo_ActivationResult_type Bonobo_ActivationResult;
struct Bonobo_ActivationResult_type {
CORBA_string aid;
Bonobo_ActivationResultData res;
};

#if !defined(TC_IMPL_TC_Bonobo_ActivationResult_0)
#define TC_IMPL_TC_Bonobo_ActivationResult_0 'B'
#define TC_IMPL_TC_Bonobo_ActivationResult_1 'o'
#define TC_IMPL_TC_Bonobo_ActivationResult_2 'n'
#define TC_IMPL_TC_Bonobo_ActivationResult_3 'o'
#define TC_IMPL_TC_Bonobo_ActivationResult_4 'b'
#define TC_IMPL_TC_Bonobo_ActivationResult_5 'o'
#define TC_IMPL_TC_Bonobo_ActivationResult_6 '_'
#define TC_IMPL_TC_Bonobo_ActivationResult_7 'A'
#define TC_IMPL_TC_Bonobo_ActivationResult_8 'c'
#define TC_IMPL_TC_Bonobo_ActivationResult_9 't'
#define TC_IMPL_TC_Bonobo_ActivationResult_10 'i'
#define TC_IMPL_TC_Bonobo_ActivationResult_11 'v'
#define TC_IMPL_TC_Bonobo_ActivationResult_12 'a'
#define TC_IMPL_TC_Bonobo_ActivationResult_13 't'
#define TC_IMPL_TC_Bonobo_ActivationResult_14 'i'
#define TC_IMPL_TC_Bonobo_ActivationResult_15 'o'
#define TC_IMPL_TC_Bonobo_ActivationResult_16 'n'
#define TC_IMPL_TC_Bonobo_ActivationResult_17 '_'
#define TC_IMPL_TC_Bonobo_ActivationResult_18 't'
#define TC_IMPL_TC_Bonobo_ActivationResult_19 'y'
#define TC_IMPL_TC_Bonobo_ActivationResult_20 'p'
#define TC_IMPL_TC_Bonobo_ActivationResult_21 'e'
#define TC_IMPL_TC_Bonobo_ActivationResult_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_ActivationResult_struct;
#define TC_Bonobo_ActivationResult ((CORBA_TypeCode)&TC_Bonobo_ActivationResult_struct)
#endif
#define Bonobo_ActivationResult__alloc() ((Bonobo_ActivationResult *)ORBit_small_alloc (TC_Bonobo_ActivationResult))
#define Bonobo_ActivationResult__freekids(m,d) ORBit_small_freekids (TC_Bonobo_ActivationResult,(m),(d))
#endif
#if !defined(_Bonobo_ActivationPropertyType_defined)
#define _Bonobo_ActivationPropertyType_defined 1
typedef enum {
  Bonobo_ACTIVATION_P_STRING,
  Bonobo_ACTIVATION_P_NUMBER,
  Bonobo_ACTIVATION_P_BOOLEAN,
  Bonobo_ACTIVATION_P_STRINGV
} Bonobo_ActivationPropertyType;
#if !defined(TC_IMPL_TC_Bonobo_ActivationPropertyType_0)
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_0 'B'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_1 'o'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_2 'n'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_3 'o'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_4 'b'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_5 'o'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_6 '_'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_7 'A'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_8 'c'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_9 't'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_10 'i'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_11 'v'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_12 'a'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_13 't'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_14 'i'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_15 'o'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_16 'n'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_17 '_'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_18 't'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_19 'y'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_20 'p'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_21 'e'
#define TC_IMPL_TC_Bonobo_ActivationPropertyType_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_ActivationPropertyType_struct;
#define TC_Bonobo_ActivationPropertyType ((CORBA_TypeCode)&TC_Bonobo_ActivationPropertyType_struct)
#endif
#endif
#if !defined(_Bonobo_ActivationPropertyValue_defined)
#define _Bonobo_ActivationPropertyValue_defined 1
typedef struct Bonobo_ActivationPropertyValue_type Bonobo_ActivationPropertyValue;
struct Bonobo_ActivationPropertyValue_type {
Bonobo_ActivationPropertyType _d;
union {
CORBA_string value_string;
CORBA_double value_number;
CORBA_boolean value_boolean;
Bonobo_StringList value_stringv;
} _u;
};
#if !defined(TC_IMPL_TC_Bonobo_ActivationPropertyValue_0)
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_0 'B'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_1 'o'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_2 'n'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_3 'o'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_4 'b'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_5 'o'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_6 '_'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_7 'A'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_8 'c'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_9 't'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_10 'i'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_11 'v'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_12 'a'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_13 't'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_14 'i'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_15 'o'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_16 'n'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_17 '_'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_18 't'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_19 'y'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_20 'p'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_21 'e'
#define TC_IMPL_TC_Bonobo_ActivationPropertyValue_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_ActivationPropertyValue_struct;
#define TC_Bonobo_ActivationPropertyValue ((CORBA_TypeCode)&TC_Bonobo_ActivationPropertyValue_struct)
#endif
#define Bonobo_ActivationPropertyValue__alloc() ((Bonobo_ActivationPropertyValue *)ORBit_small_alloc (TC_Bonobo_ActivationPropertyValue))
#define Bonobo_ActivationPropertyValue__freekids(m,d) ORBit_small_freekids (TC_Bonobo_ActivationPropertyValue,(m),(d))
#endif
#if !defined(_Bonobo_ActivationProperty_defined)
#define _Bonobo_ActivationProperty_defined 1
typedef struct Bonobo_ActivationProperty_type Bonobo_ActivationProperty;
struct Bonobo_ActivationProperty_type {
CORBA_string name;
Bonobo_ActivationPropertyValue v;
};

#if !defined(TC_IMPL_TC_Bonobo_ActivationProperty_0)
#define TC_IMPL_TC_Bonobo_ActivationProperty_0 'B'
#define TC_IMPL_TC_Bonobo_ActivationProperty_1 'o'
#define TC_IMPL_TC_Bonobo_ActivationProperty_2 'n'
#define TC_IMPL_TC_Bonobo_ActivationProperty_3 'o'
#define TC_IMPL_TC_Bonobo_ActivationProperty_4 'b'
#define TC_IMPL_TC_Bonobo_ActivationProperty_5 'o'
#define TC_IMPL_TC_Bonobo_ActivationProperty_6 '_'
#define TC_IMPL_TC_Bonobo_ActivationProperty_7 'A'
#define TC_IMPL_TC_Bonobo_ActivationProperty_8 'c'
#define TC_IMPL_TC_Bonobo_ActivationProperty_9 't'
#define TC_IMPL_TC_Bonobo_ActivationProperty_10 'i'
#define TC_IMPL_TC_Bonobo_ActivationProperty_11 'v'
#define TC_IMPL_TC_Bonobo_ActivationProperty_12 'a'
#define TC_IMPL_TC_Bonobo_ActivationProperty_13 't'
#define TC_IMPL_TC_Bonobo_ActivationProperty_14 'i'
#define TC_IMPL_TC_Bonobo_ActivationProperty_15 'o'
#define TC_IMPL_TC_Bonobo_ActivationProperty_16 'n'
#define TC_IMPL_TC_Bonobo_ActivationProperty_17 '_'
#define TC_IMPL_TC_Bonobo_ActivationProperty_18 't'
#define TC_IMPL_TC_Bonobo_ActivationProperty_19 'y'
#define TC_IMPL_TC_Bonobo_ActivationProperty_20 'p'
#define TC_IMPL_TC_Bonobo_ActivationProperty_21 'e'
#define TC_IMPL_TC_Bonobo_ActivationProperty_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_ActivationProperty_struct;
#define TC_Bonobo_ActivationProperty ((CORBA_TypeCode)&TC_Bonobo_ActivationProperty_struct)
#endif
#define Bonobo_ActivationProperty__alloc() ((Bonobo_ActivationProperty *)ORBit_small_alloc (TC_Bonobo_ActivationProperty))
#define Bonobo_ActivationProperty__freekids(m,d) ORBit_small_freekids (TC_Bonobo_ActivationProperty,(m),(d))
#endif
#if !defined(_Bonobo_ServerInfo_defined)
#define _Bonobo_ServerInfo_defined 1
typedef struct Bonobo_ServerInfo_type Bonobo_ServerInfo;
#if !defined(ORBIT_DECL_CORBA_sequence_Bonobo_ActivationProperty)
#define ORBIT_DECL_CORBA_sequence_Bonobo_ActivationProperty 1
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_0 'B'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_1 'o'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_2 'n'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_3 'o'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_4 'b'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_5 'o'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_6 '_'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_7 'A'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_8 'c'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_9 't'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_10 'i'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_11 'v'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_12 'a'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_13 't'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_14 'i'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_15 'o'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_16 'n'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_17 '_'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_18 't'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_19 'y'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_20 'p'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_21 'e'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ActivationProperty_22 's'
#if !defined(_CORBA_sequence_Bonobo_ActivationProperty_defined)
#define _CORBA_sequence_Bonobo_ActivationProperty_defined 1
typedef struct { CORBA_unsigned_long _maximum, _length; Bonobo_ActivationProperty* _buffer; CORBA_boolean _release; } CORBA_sequence_Bonobo_ActivationProperty;
#endif
#if !defined(TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_0)
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_0 'B'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_1 'o'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_2 'n'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_3 'o'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_4 'b'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_5 'o'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_6 '_'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_7 'A'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_8 'c'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_9 't'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_10 'i'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_11 'v'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_12 'a'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_13 't'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_14 'i'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_15 'o'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_16 'n'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_17 '_'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_18 't'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_19 'y'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_20 'p'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_21 'e'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ActivationProperty_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_CORBA_sequence_Bonobo_ActivationProperty_struct;
#define TC_CORBA_sequence_Bonobo_ActivationProperty ((CORBA_TypeCode)&TC_CORBA_sequence_Bonobo_ActivationProperty_struct)
#endif
#define CORBA_sequence_Bonobo_ActivationProperty__alloc() ((CORBA_sequence_Bonobo_ActivationProperty *)ORBit_small_alloc (TC_CORBA_sequence_Bonobo_ActivationProperty))
#define CORBA_sequence_Bonobo_ActivationProperty__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_Bonobo_ActivationProperty,(m),(d))
#define CORBA_sequence_Bonobo_ActivationProperty_allocbuf(l) ((Bonobo_ActivationProperty*)ORBit_small_allocbuf (TC_CORBA_sequence_Bonobo_ActivationProperty, (l)))
#define CORBA_sequence_Bonobo_ActivationProperty_allocbuf(l) ((Bonobo_ActivationProperty*)ORBit_small_allocbuf (TC_CORBA_sequence_Bonobo_ActivationProperty, (l)))
#endif
struct Bonobo_ServerInfo_type {
Bonobo_ImplementationID iid;
CORBA_string server_type;
CORBA_string location_info;
CORBA_string username;
CORBA_string hostname;
CORBA_string domain;
CORBA_sequence_Bonobo_ActivationProperty props;
};

#if !defined(TC_IMPL_TC_Bonobo_ServerInfo_0)
#define TC_IMPL_TC_Bonobo_ServerInfo_0 'B'
#define TC_IMPL_TC_Bonobo_ServerInfo_1 'o'
#define TC_IMPL_TC_Bonobo_ServerInfo_2 'n'
#define TC_IMPL_TC_Bonobo_ServerInfo_3 'o'
#define TC_IMPL_TC_Bonobo_ServerInfo_4 'b'
#define TC_IMPL_TC_Bonobo_ServerInfo_5 'o'
#define TC_IMPL_TC_Bonobo_ServerInfo_6 '_'
#define TC_IMPL_TC_Bonobo_ServerInfo_7 'A'
#define TC_IMPL_TC_Bonobo_ServerInfo_8 'c'
#define TC_IMPL_TC_Bonobo_ServerInfo_9 't'
#define TC_IMPL_TC_Bonobo_ServerInfo_10 'i'
#define TC_IMPL_TC_Bonobo_ServerInfo_11 'v'
#define TC_IMPL_TC_Bonobo_ServerInfo_12 'a'
#define TC_IMPL_TC_Bonobo_ServerInfo_13 't'
#define TC_IMPL_TC_Bonobo_ServerInfo_14 'i'
#define TC_IMPL_TC_Bonobo_ServerInfo_15 'o'
#define TC_IMPL_TC_Bonobo_ServerInfo_16 'n'
#define TC_IMPL_TC_Bonobo_ServerInfo_17 '_'
#define TC_IMPL_TC_Bonobo_ServerInfo_18 't'
#define TC_IMPL_TC_Bonobo_ServerInfo_19 'y'
#define TC_IMPL_TC_Bonobo_ServerInfo_20 'p'
#define TC_IMPL_TC_Bonobo_ServerInfo_21 'e'
#define TC_IMPL_TC_Bonobo_ServerInfo_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_ServerInfo_struct;
#define TC_Bonobo_ServerInfo ((CORBA_TypeCode)&TC_Bonobo_ServerInfo_struct)
#endif
#define Bonobo_ServerInfo__alloc() ((Bonobo_ServerInfo *)ORBit_small_alloc (TC_Bonobo_ServerInfo))
#define Bonobo_ServerInfo__freekids(m,d) ORBit_small_freekids (TC_Bonobo_ServerInfo,(m),(d))
#endif
#if !defined(ORBIT_DECL_CORBA_sequence_Bonobo_ServerInfo)
#define ORBIT_DECL_CORBA_sequence_Bonobo_ServerInfo 1
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_0 'B'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_1 'o'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_2 'n'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_3 'o'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_4 'b'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_5 'o'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_6 '_'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_7 'A'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_8 'c'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_9 't'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_10 'i'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_11 'v'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_12 'a'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_13 't'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_14 'i'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_15 'o'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_16 'n'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_17 '_'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_18 't'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_19 'y'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_20 'p'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_21 'e'
#define ORBIT_IMPL_CORBA_sequence_Bonobo_ServerInfo_22 's'
#if !defined(_CORBA_sequence_Bonobo_ServerInfo_defined)
#define _CORBA_sequence_Bonobo_ServerInfo_defined 1
typedef struct { CORBA_unsigned_long _maximum, _length; Bonobo_ServerInfo* _buffer; CORBA_boolean _release; } CORBA_sequence_Bonobo_ServerInfo;
#endif
#if !defined(TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_0)
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_0 'B'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_1 'o'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_2 'n'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_3 'o'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_4 'b'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_5 'o'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_6 '_'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_7 'A'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_8 'c'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_9 't'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_10 'i'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_11 'v'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_12 'a'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_13 't'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_14 'i'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_15 'o'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_16 'n'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_17 '_'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_18 't'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_19 'y'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_20 'p'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_21 'e'
#define TC_IMPL_TC_CORBA_sequence_Bonobo_ServerInfo_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_CORBA_sequence_Bonobo_ServerInfo_struct;
#define TC_CORBA_sequence_Bonobo_ServerInfo ((CORBA_TypeCode)&TC_CORBA_sequence_Bonobo_ServerInfo_struct)
#endif
#define CORBA_sequence_Bonobo_ServerInfo__alloc() ((CORBA_sequence_Bonobo_ServerInfo *)ORBit_small_alloc (TC_CORBA_sequence_Bonobo_ServerInfo))
#define CORBA_sequence_Bonobo_ServerInfo__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_Bonobo_ServerInfo,(m),(d))
#define CORBA_sequence_Bonobo_ServerInfo_allocbuf(l) ((Bonobo_ServerInfo*)ORBit_small_allocbuf (TC_CORBA_sequence_Bonobo_ServerInfo, (l)))
#define CORBA_sequence_Bonobo_ServerInfo_allocbuf(l) ((Bonobo_ServerInfo*)ORBit_small_allocbuf (TC_CORBA_sequence_Bonobo_ServerInfo, (l)))
#endif
#if !defined(_Bonobo_ServerInfoList_defined)
#define _Bonobo_ServerInfoList_defined 1
typedef CORBA_sequence_Bonobo_ServerInfo Bonobo_ServerInfoList;
#define Bonobo_ServerInfoList_marshal(x,y,z) CORBA_sequence_Bonobo_ServerInfo_marshal((x),(y),(z))
#define Bonobo_ServerInfoList_demarshal(x,y,z,i) CORBA_sequence_Bonobo_ServerInfo_demarshal((x),(y),(z),(i))
#if !defined(TC_IMPL_TC_Bonobo_ServerInfoList_0)
#define TC_IMPL_TC_Bonobo_ServerInfoList_0 'B'
#define TC_IMPL_TC_Bonobo_ServerInfoList_1 'o'
#define TC_IMPL_TC_Bonobo_ServerInfoList_2 'n'
#define TC_IMPL_TC_Bonobo_ServerInfoList_3 'o'
#define TC_IMPL_TC_Bonobo_ServerInfoList_4 'b'
#define TC_IMPL_TC_Bonobo_ServerInfoList_5 'o'
#define TC_IMPL_TC_Bonobo_ServerInfoList_6 '_'
#define TC_IMPL_TC_Bonobo_ServerInfoList_7 'A'
#define TC_IMPL_TC_Bonobo_ServerInfoList_8 'c'
#define TC_IMPL_TC_Bonobo_ServerInfoList_9 't'
#define TC_IMPL_TC_Bonobo_ServerInfoList_10 'i'
#define TC_IMPL_TC_Bonobo_ServerInfoList_11 'v'
#define TC_IMPL_TC_Bonobo_ServerInfoList_12 'a'
#define TC_IMPL_TC_Bonobo_ServerInfoList_13 't'
#define TC_IMPL_TC_Bonobo_ServerInfoList_14 'i'
#define TC_IMPL_TC_Bonobo_ServerInfoList_15 'o'
#define TC_IMPL_TC_Bonobo_ServerInfoList_16 'n'
#define TC_IMPL_TC_Bonobo_ServerInfoList_17 '_'
#define TC_IMPL_TC_Bonobo_ServerInfoList_18 't'
#define TC_IMPL_TC_Bonobo_ServerInfoList_19 'y'
#define TC_IMPL_TC_Bonobo_ServerInfoList_20 'p'
#define TC_IMPL_TC_Bonobo_ServerInfoList_21 'e'
#define TC_IMPL_TC_Bonobo_ServerInfoList_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_ServerInfoList_struct;
#define TC_Bonobo_ServerInfoList ((CORBA_TypeCode)&TC_Bonobo_ServerInfoList_struct)
#endif
#define Bonobo_ServerInfoList__alloc() ((Bonobo_ServerInfoList *)ORBit_small_alloc (TC_CORBA_sequence_Bonobo_ServerInfo))
#define Bonobo_ServerInfoList__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_Bonobo_ServerInfo,(m),(d))
#define Bonobo_ServerInfoList_allocbuf(l) ((Bonobo_ServerInfo*)ORBit_small_allocbuf (TC_CORBA_sequence_Bonobo_ServerInfo, (l)))
#endif
#if !defined(_Bonobo_RegistrationResult_defined)
#define _Bonobo_RegistrationResult_defined 1
typedef enum {
  Bonobo_ACTIVATION_REG_SUCCESS,
  Bonobo_ACTIVATION_REG_NOT_LISTED,
  Bonobo_ACTIVATION_REG_ALREADY_ACTIVE,
  Bonobo_ACTIVATION_REG_ERROR
} Bonobo_RegistrationResult;
#if !defined(TC_IMPL_TC_Bonobo_RegistrationResult_0)
#define TC_IMPL_TC_Bonobo_RegistrationResult_0 'B'
#define TC_IMPL_TC_Bonobo_RegistrationResult_1 'o'
#define TC_IMPL_TC_Bonobo_RegistrationResult_2 'n'
#define TC_IMPL_TC_Bonobo_RegistrationResult_3 'o'
#define TC_IMPL_TC_Bonobo_RegistrationResult_4 'b'
#define TC_IMPL_TC_Bonobo_RegistrationResult_5 'o'
#define TC_IMPL_TC_Bonobo_RegistrationResult_6 '_'
#define TC_IMPL_TC_Bonobo_RegistrationResult_7 'A'
#define TC_IMPL_TC_Bonobo_RegistrationResult_8 'c'
#define TC_IMPL_TC_Bonobo_RegistrationResult_9 't'
#define TC_IMPL_TC_Bonobo_RegistrationResult_10 'i'
#define TC_IMPL_TC_Bonobo_RegistrationResult_11 'v'
#define TC_IMPL_TC_Bonobo_RegistrationResult_12 'a'
#define TC_IMPL_TC_Bonobo_RegistrationResult_13 't'
#define TC_IMPL_TC_Bonobo_RegistrationResult_14 'i'
#define TC_IMPL_TC_Bonobo_RegistrationResult_15 'o'
#define TC_IMPL_TC_Bonobo_RegistrationResult_16 'n'
#define TC_IMPL_TC_Bonobo_RegistrationResult_17 '_'
#define TC_IMPL_TC_Bonobo_RegistrationResult_18 't'
#define TC_IMPL_TC_Bonobo_RegistrationResult_19 'y'
#define TC_IMPL_TC_Bonobo_RegistrationResult_20 'p'
#define TC_IMPL_TC_Bonobo_RegistrationResult_21 'e'
#define TC_IMPL_TC_Bonobo_RegistrationResult_22 's'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_Activation_types
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_RegistrationResult_struct;
#define TC_Bonobo_RegistrationResult ((CORBA_TypeCode)&TC_Bonobo_RegistrationResult_struct)
#endif
#endif

/** POA structures **/

/** skel prototypes **/

/** stub prototypes **/
#include <orbit/orb-core/orbit-interface.h>


/** IMethods index */

#ifndef __ORBIT_IMETHODS_INDEX
#define __ORBIT_IMETHODS_INDEX
#define ORBIT_IMETHODS_INDEX(m) (m ## __imethods_index)
#endif /* __ORBIT_IMETHODS_INDEX */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#ifndef EXCLUDE_ORBIT_H
#include <orbit/orbit.h>

#endif /* EXCLUDE_ORBIT_H */
#endif
#undef ORBIT_IDL_SERIAL
