/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#ifndef Bonobo_GenericFactory_H
#define Bonobo_GenericFactory_H 1
#include <glib.h>
#define ORBIT_IDL_SERIAL 20
#include <orbit/orbit-types.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/** typedefs **/
#include <bonobo-activation/Bonobo_Unknown.h>
#include <bonobo-activation/Bonobo_Activation_types.h>
#if !defined(ORBIT_DECL_Bonobo_GenericFactory) && !defined(_Bonobo_GenericFactory_defined)
#define ORBIT_DECL_Bonobo_GenericFactory 1
#define _Bonobo_GenericFactory_defined 1
#define Bonobo_GenericFactory__freekids CORBA_Object__freekids
typedef CORBA_Object Bonobo_GenericFactory;
extern CORBA_unsigned_long Bonobo_GenericFactory__classid;
#if !defined(TC_IMPL_TC_Bonobo_GenericFactory_0)
#define TC_IMPL_TC_Bonobo_GenericFactory_0 'B'
#define TC_IMPL_TC_Bonobo_GenericFactory_1 'o'
#define TC_IMPL_TC_Bonobo_GenericFactory_2 'n'
#define TC_IMPL_TC_Bonobo_GenericFactory_3 'o'
#define TC_IMPL_TC_Bonobo_GenericFactory_4 'b'
#define TC_IMPL_TC_Bonobo_GenericFactory_5 'o'
#define TC_IMPL_TC_Bonobo_GenericFactory_6 '_'
#define TC_IMPL_TC_Bonobo_GenericFactory_7 'G'
#define TC_IMPL_TC_Bonobo_GenericFactory_8 'e'
#define TC_IMPL_TC_Bonobo_GenericFactory_9 'n'
#define TC_IMPL_TC_Bonobo_GenericFactory_10 'e'
#define TC_IMPL_TC_Bonobo_GenericFactory_11 'r'
#define TC_IMPL_TC_Bonobo_GenericFactory_12 'i'
#define TC_IMPL_TC_Bonobo_GenericFactory_13 'c'
#define TC_IMPL_TC_Bonobo_GenericFactory_14 'F'
#define TC_IMPL_TC_Bonobo_GenericFactory_15 'a'
#define TC_IMPL_TC_Bonobo_GenericFactory_16 'c'
#define TC_IMPL_TC_Bonobo_GenericFactory_17 't'
#define TC_IMPL_TC_Bonobo_GenericFactory_18 'o'
#define TC_IMPL_TC_Bonobo_GenericFactory_19 'r'
#define TC_IMPL_TC_Bonobo_GenericFactory_20 'y'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_GenericFactory
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_GenericFactory_struct;
#define TC_Bonobo_GenericFactory ((CORBA_TypeCode)&TC_Bonobo_GenericFactory_struct)
#endif
#endif
#undef ex_Bonobo_GenericFactory_CannotActivate
#define ex_Bonobo_GenericFactory_CannotActivate "IDL:Bonobo/GenericFactory/CannotActivate:1.0"
#if !defined(_Bonobo_GenericFactory_CannotActivate_defined)
#define _Bonobo_GenericFactory_CannotActivate_defined 1
typedef struct Bonobo_GenericFactory_CannotActivate_type Bonobo_GenericFactory_CannotActivate;
struct Bonobo_GenericFactory_CannotActivate_type {
int dummy;
};

#if !defined(TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_0)
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_0 'B'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_1 'o'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_2 'n'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_3 'o'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_4 'b'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_5 'o'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_6 '_'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_7 'G'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_8 'e'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_9 'n'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_10 'e'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_11 'r'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_12 'i'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_13 'c'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_14 'F'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_15 'a'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_16 'c'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_17 't'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_18 'o'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_19 'r'
#define TC_IMPL_TC_Bonobo_GenericFactory_CannotActivate_20 'y'
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_GenericFactory
static
#else
extern
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_Bonobo_GenericFactory_CannotActivate_struct;
#define TC_Bonobo_GenericFactory_CannotActivate ((CORBA_TypeCode)&TC_Bonobo_GenericFactory_CannotActivate_struct)
#endif
#define Bonobo_GenericFactory_CannotActivate__alloc() ((Bonobo_GenericFactory_CannotActivate *)ORBit_small_alloc (TC_Bonobo_GenericFactory_CannotActivate))
#define Bonobo_GenericFactory_CannotActivate__freekids(m,d) ORBit_small_freekids (TC_Bonobo_GenericFactory_CannotActivate,(m),(d))
#endif

/** POA structures **/
#ifndef _defined_POA_Bonobo_GenericFactory
#define _defined_POA_Bonobo_GenericFactory 1
typedef struct {
  void *_private;
CORBA_Object (*createObject)(PortableServer_Servant _servant, const CORBA_char * iid, CORBA_Environment *ev);
} POA_Bonobo_GenericFactory__epv;
typedef struct {
  PortableServer_ServantBase__epv *_base_epv;
  POA_Bonobo_Unknown__epv *Bonobo_Unknown_epv;
  POA_Bonobo_GenericFactory__epv *Bonobo_GenericFactory_epv;
} POA_Bonobo_GenericFactory__vepv;
typedef struct {
  void *_private;
  POA_Bonobo_GenericFactory__vepv *vepv;
} POA_Bonobo_GenericFactory;
extern void POA_Bonobo_GenericFactory__init(PortableServer_Servant servant, CORBA_Environment *ev);
extern void POA_Bonobo_GenericFactory__fini(PortableServer_Servant servant, CORBA_Environment *ev);
#endif /* _defined_POA_Bonobo_GenericFactory */

/** skel prototypes **/
void _ORBIT_skel_small_Bonobo_GenericFactory_createObject(POA_Bonobo_GenericFactory *_ORBIT_servant, gpointer _ORBIT_retval, gpointer *_ORBIT_args, CORBA_Context ctx,CORBA_Environment *ev, CORBA_Object (*_impl_createObject)(PortableServer_Servant _servant, const CORBA_char * iid, CORBA_Environment *ev));

/** stub prototypes **/
#define Bonobo_GenericFactory_ref Bonobo_Unknown_ref
#define Bonobo_GenericFactory_unref Bonobo_Unknown_unref
#define Bonobo_GenericFactory_queryInterface Bonobo_Unknown_queryInterface
CORBA_Object Bonobo_GenericFactory_createObject(Bonobo_GenericFactory _obj, const CORBA_char * iid, CORBA_Environment *ev);
#include <orbit/orb-core/orbit-interface.h>

#ifdef ORBIT_IDL_C_IMODULE_Bonobo_GenericFactory
static 
#else
extern 
#endif
ORBit_IInterface Bonobo_GenericFactory__iinterface;
#define Bonobo_GenericFactory_IMETHODS_LEN 1
#ifdef ORBIT_IDL_C_IMODULE_Bonobo_GenericFactory
static 
#else
extern 
#endif
ORBit_IMethod Bonobo_GenericFactory__imethods[Bonobo_GenericFactory_IMETHODS_LEN];

/** IMethods index */

#ifndef __Bonobo_GenericFactory__imethods_index
#define __Bonobo_GenericFactory__imethods_index
typedef enum {
	Bonobo_GenericFactory_createObject__imethods_index
} Bonobo_GenericFactory__imethods_index;
#endif /* __Bonobo_GenericFactory__imethods_index */

#ifndef __ORBIT_IMETHODS_INDEX
#define __ORBIT_IMETHODS_INDEX
#define ORBIT_IMETHODS_INDEX(m) (m ## __imethods_index)
#endif /* __ORBIT_IMETHODS_INDEX */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#ifndef EXCLUDE_ORBIT_H
#include <orbit/orbit.h>

#endif /* EXCLUDE_ORBIT_H */
#endif
#undef ORBIT_IDL_SERIAL
