#ifndef MSDefaultsHEADER
#define MSDefaultsHEADER

///////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 1997-2008 Morgan Stanley All rights reserved. 
// See .../src/LICENSE for terms of distribution
//
//
///////////////////////////////////////////////////////////////////////////////


extern unsigned long MSDefaultBackground;
extern unsigned long MSDefaultForeground;
extern const char *MSDefaultBackgroundColorSpec;
extern const char *MSDefaultForegroundColorSpec;
extern const char *MSDefaultFont;
extern const char *DefaultAPLFont;
extern const int MSDefaultBorderWidth;
extern const int MSDefaultWindowBorderWidth;
extern const int MSDefaultWidth;
extern const int MSDefaultHeight;
extern const int MSDefaultX;
extern const int MSDefaultY;

#endif







