set -o pipefail
'llc' '-mtriple=arm-apple-darwin' '-relocation-model=pic' '-mattr=+v6' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/2007-03-13-InstrSched.ll' |
  'grep' 'r9'  &&

'llc' '-mtriple=arm-apple-darwin' '-relocation-model=pic' '-mattr=+v6' '-arm-reserve-r9' '-ifcvt-limit=0' '-stats' 2>& '1' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/2007-03-13-InstrSched.ll' |
  'grep' 'asm-printer'