set -o pipefail
'llc' '-march=arm' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/2007-05-22-tailmerge-3.ll' |
  'grep' 'bl.*baz' |
  'count' '1'  &&

'llc' '-march=arm' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/2007-05-22-tailmerge-3.ll' |
  'grep' 'bl.*quux' |
  'count' '1'  &&

'llc' '-march=arm' '-enable-tail-merge=0' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/2007-05-22-tailmerge-3.ll' |
  'grep' 'bl.*baz' |
  'count' '2'  &&

'llc' '-march=arm' '-enable-tail-merge=0' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/2007-05-22-tailmerge-3.ll' |
  'grep' 'bl.*quux' |
  'count' '2'