set -o pipefail
'llc' '-mtriple=armv4-unknown-eabi' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/2010-03-18-ldm-rtrn.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/2010-03-18-ldm-rtrn.ll'  &&

'llc' '-mtriple=armv5-unknown-eabi' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/2010-03-18-ldm-rtrn.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/2010-03-18-ldm-rtrn.ll'  &&

'llc' '-mtriple=armv6-unknown-eabi' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/2010-03-18-ldm-rtrn.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/2010-03-18-ldm-rtrn.ll'