set -o pipefail
'llc' '-mtriple=armv7-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/2010-05-18-PostIndexBug.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/2010-05-18-PostIndexBug.ll' '-check-prefix=ARM'  &&

'llc' '-mtriple=thumbv7-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/2010-05-18-PostIndexBug.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/2010-05-18-PostIndexBug.ll' '-check-prefix=THUMB'