set -o pipefail
'llc' '-mtriple=arm-linux-gnueabi' '-o' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/aliases.ll.tmp' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/aliases.ll'  &&

'grep' ' = ' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/aliases.ll.tmp' |
  'count' '5'  &&

'grep' 'globl' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/aliases.ll.tmp' |
  'count' '4'  &&

'grep' 'weak' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/aliases.ll.tmp' |
  'count' '1'