set -o pipefail
'llc' '-mtriple=arm-linux-gnueabi' '-mattr=+vfp2' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/arguments.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/arguments.ll' '-check-prefix=ELF'  &&

'llc' '-mtriple=arm-apple-darwin' '-mattr=+vfp2' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/arguments.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/arguments.ll' '-check-prefix=DARWIN'