set -o pipefail
'llc' '-mtriple=arm-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/arm-frameaddr.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/arm-frameaddr.ll' '-check-prefix=DARWIN'  &&

'llc' '-mtriple=arm-linux-gnueabi' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/arm-frameaddr.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/arm-frameaddr.ll' '-check-prefix=LINUX'