set -o pipefail
'llc' '-mtriple=arm-unknown-eabi' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/armv4.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/armv4.ll' '-check-prefix=THUMB'  &&

'llc' '-mtriple=arm-unknown-eabi' '-mcpu=strongarm' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/armv4.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/armv4.ll' '-check-prefix=ARM'  &&

'llc' '-mtriple=arm-unknown-eabi' '-mcpu=cortex-a8' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/armv4.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/armv4.ll' '-check-prefix=THUMB'  &&

'llc' '-mtriple=arm-unknown-eabi' '-mattr=+v6' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/armv4.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/armv4.ll' '-check-prefix=THUMB'  &&

'llc' '-mtriple=armv4-unknown-eabi' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/armv4.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/armv4.ll' '-check-prefix=ARM'  &&

'llc' '-mtriple=armv4t-unknown-eabi' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/armv4.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/armv4.ll' '-check-prefix=THUMB'