set -o pipefail
'llc' '-march=arm' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/bits.ll' > '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/bits.ll.tmp'  &&

'grep' 'and' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/bits.ll.tmp' |
  'count' '1'  &&

'grep' 'orr' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/bits.ll.tmp' |
  'count' '1'  &&

'grep' 'eor' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/bits.ll.tmp' |
  'count' '1'  &&

'grep' 'mov.*lsl' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/bits.ll.tmp' |
  'count' '1'  &&

'grep' 'mov.*asr' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/bits.ll.tmp' |
  'count' '1'