set -o pipefail
'llc' '-march=arm' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/call.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/call.ll' '-check-prefix=CHECKV4'  &&

'llc' '-march=arm' '-mattr=+v5t' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/call.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/call.ll' '-check-prefix=CHECKV5'  &&

'llc' '-march=arm' '-mtriple=arm-linux-gnueabi' '-relocation-model=pic' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/call.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/call.ll' '-check-prefix=CHECKELF'