set -o pipefail
'llc' '-mtriple=arm-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/ctors_dtors.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/ctors_dtors.ll' '-check-prefix=DARWIN'  &&

'llc' '-mtriple=arm-linux-gnu' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/ctors_dtors.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/ctors_dtors.ll' '-check-prefix=ELF'  &&

'llc' '-mtriple=arm-linux-gnueabi' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/ctors_dtors.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/ctors_dtors.ll' '-check-prefix=GNUEABI'