set -o pipefail
'llc' '-march=arm' '-mattr=+vfp2' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fmscs.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fmscs.ll' '-check-prefix=VFP2'  &&

'llc' '-march=arm' '-mattr=+neon' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fmscs.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fmscs.ll' '-check-prefix=NFP0'  &&

'llc' '-march=arm' '-mcpu=cortex-a8' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fmscs.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fmscs.ll' '-check-prefix=CORTEXA8'  &&

'llc' '-march=arm' '-mcpu=cortex-a9' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fmscs.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fmscs.ll' '-check-prefix=CORTEXA9'