set -o pipefail
'llc' '-march=arm' '-mattr=+vfp2' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fnmacs.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fnmacs.ll' '-check-prefix=VFP2'  &&

'llc' '-march=arm' '-mattr=+neon' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fnmacs.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fnmacs.ll' '-check-prefix=NEON'  &&

'llc' '-march=arm' '-mcpu=cortex-a8' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fnmacs.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fnmacs.ll' '-check-prefix=NEONFP'