set -o pipefail
'llc' '-march=arm' '-mattr=+vfp2' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fnmuls.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fnmuls.ll'  &&

'llc' '-march=arm' '-mattr=+neon' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fnmuls.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fnmuls.ll'  &&

'llc' '-march=arm' '-mcpu=cortex-a8' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fnmuls.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fnmuls.ll'  &&

'llc' '-march=arm' '-mcpu=cortex-a9' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fnmuls.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fnmuls.ll'