set -o pipefail
'llc' '-march=arm' '-mcpu=cortex-a8' '-mattr=+vfp2' '-enable-unsafe-fp-math' '-enable-no-nans-fp-math' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fpcmp-opt.ll' |
  'FileCheck' '-check-prefix=FINITE' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fpcmp-opt.ll'  &&

'llc' '-march=arm' '-mcpu=cortex-a8' '-mattr=+vfp2' '-enable-unsafe-fp-math' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fpcmp-opt.ll' |
  'FileCheck' '-check-prefix=NAN' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/fpcmp-opt.ll'