set -o pipefail
'llc' '-mtriple=arm-apple-darwin' '-relocation-model=static' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/globals.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/globals.ll' '-check-prefix=DarwinStatic'  &&

'llc' '-mtriple=arm-apple-darwin' '-relocation-model=dynamic-no-pic' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/globals.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/globals.ll' '-check-prefix=DarwinDynamic'  &&

'llc' '-mtriple=arm-apple-darwin' '-relocation-model=pic' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/globals.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/globals.ll' '-check-prefix=DarwinPIC'  &&

'llc' '-mtriple=arm-linux-gnueabi' '-relocation-model=pic' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/globals.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/globals.ll' '-check-prefix=LinuxPIC'