set -o pipefail
'llc' '-march=arm' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/hello.ll'  &&

'llc' '-mtriple=arm-linux-gnueabi' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/hello.ll' |
  'grep' 'mov' |
  'count' '1'  &&

'llc' '-mtriple=arm-linux-gnu' '--disable-fp-elim' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/hello.ll' |
  'grep' 'mov' |
  'count' '3'  &&

'llc' '-mtriple=arm-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/hello.ll' |
  'grep' 'mov' |
  'count' '2'