set -o pipefail
'llc' '-mtriple=arm-linux' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/hidden-vis.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/hidden-vis.ll' '-check-prefix=LINUX'  &&

'llc' '-mtriple=arm-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/hidden-vis.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/hidden-vis.ll' '-check-prefix=DARWIN'