set -o pipefail
'llc' '-march=arm' '-mtriple=arm-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/ifcvt7.ll' |
  'grep' 'cmpeq' |
  'count' '1'  &&

'llc' '-march=arm' '-mtriple=arm-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/ifcvt7.ll' |
  'grep' 'moveq' |
  'count' '1'  &&

'llc' '-march=arm' '-mtriple=arm-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/ifcvt7.ll' |
  'grep' 'ldmiaeq' |
  'count' '1'