set -o pipefail
'llc' '-relocation-model=pic' '-mtriple=arm-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/indirectbr.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/indirectbr.ll' '-check-prefix=ARM'  &&

'llc' '-relocation-model=pic' '-mtriple=thumb-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/indirectbr.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/indirectbr.ll' '-check-prefix=THUMB'  &&

'llc' '-relocation-model=static' '-mtriple=thumbv7-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/indirectbr.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/indirectbr.ll' '-check-prefix=THUMB2'