set -o pipefail
'llc' '-mtriple=armv6-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/ldrd.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/ldrd.ll' '-check-prefix=V6'  &&

'llc' '-mtriple=armv5-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/ldrd.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/ldrd.ll' '-check-prefix=V5'  &&

'llc' '-mtriple=armv6-eabi' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/ldrd.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/ldrd.ll' '-check-prefix=EABI'