set -o pipefail
'llc' '-march=arm' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/load.ll' > '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/load.ll.tmp'  &&

'grep' 'ldrsb' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/load.ll.tmp'  &&

'grep' 'ldrb' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/load.ll.tmp'  &&

'grep' 'ldrsh' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/load.ll.tmp'  &&

'grep' 'ldrh' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/load.ll.tmp'