set -o pipefail
'llc' '-mtriple=arm-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/memcpy-inline.ll' |
  'grep' 'ldmia'  &&

'llc' '-mtriple=arm-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/memcpy-inline.ll' |
  'grep' 'stmia'  &&

'llc' '-mtriple=arm-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/memcpy-inline.ll' |
  'grep' 'ldrb'  &&

'llc' '-mtriple=arm-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/memcpy-inline.ll' |
  'grep' 'ldrh'