set -o pipefail
'llc' '-march=arm' '-mattr=+neon' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/neon_ld2.ll' |
  'grep' 'vldmia' |
  'count' '4'  &&

'llc' '-march=arm' '-mattr=+neon' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/neon_ld2.ll' |
  'grep' 'vstmia' |
  'count' '1'  &&

'llc' '-march=arm' '-mattr=+neon' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/neon_ld2.ll' |
  'grep' 'vmov' |
  'count' '2'