set -o pipefail
'llc' '-mtriple=arm-linux-gnueabi' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/private.ll' > '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/private.ll.tmp'  &&

'grep' '.Lfoo:' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/private.ll.tmp'  &&

'egrep' 'bl.*.Lfoo' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/private.ll.tmp'  &&

'grep' '.Lbaz:' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/private.ll.tmp'  &&

'grep' 'long.*.Lbaz' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/Output/private.ll.tmp'