set -o pipefail
'llc' '-march=arm' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/select.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/select.ll'  &&

'llc' '-march=arm' '-mattr=+vfp2' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/select.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/select.ll' '--check-prefix=CHECK-VFP'  &&

'llc' '-mattr=+neon,+thumb2' '-mtriple=thumbv7-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/select.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/select.ll' '--check-prefix=CHECK-NEON'