set -o pipefail
'llc' '-march=arm' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/smul.ll'  &&

'llc' '-march=arm' '-mattr=+v5TE' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/smul.ll'  &&

'llc' '-march=arm' '-mattr=+v5TE' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/smul.ll' |
  'grep' 'smulbt' |
  'count' '1'  &&

'llc' '-march=arm' '-mattr=+v5TE' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/smul.ll' |
  'grep' 'smultt' |
  'count' '1'  &&

'llc' '-march=arm' '-mattr=+v5TE' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/smul.ll' |
  'grep' 'smlabt' |
  'count' '1'