set -o pipefail
'llc' '-march=arm' '-mattr=+v6' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/sxt_rot.ll' |
  'grep' 'sxtb' |
  'count' '2'  &&

'llc' '-march=arm' '-mattr=+v6' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/sxt_rot.ll' |
  'grep' 'sxtb' |
  'grep' 'ror' |
  'count' '1'  &&

'llc' '-march=arm' '-mattr=+v6' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/sxt_rot.ll' |
  'grep' 'sxtab' |
  'count' '1'