set -o pipefail
'llc' '-march=arm' '-mtriple=arm-linux-gnueabi' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/tls1.ll' |
  'grep' 'i(tpoff)'  &&

'llc' '-march=arm' '-mtriple=arm-linux-gnueabi' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/tls1.ll' |
  'grep' '__aeabi_read_tp'  &&

'llc' '-march=arm' '-mtriple=arm-linux-gnueabi' '-relocation-model=pic' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/tls1.ll' |
  'grep' '__tls_get_addr'