set -o pipefail
'llc' '-march=arm' '-mtriple=arm-linux-gnueabi' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/tls2.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/tls2.ll' '-check-prefix=CHECK-NONPIC'  &&

'llc' '-march=arm' '-mtriple=arm-linux-gnueabi' '-relocation-model=pic' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/tls2.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/tls2.ll' '-check-prefix=CHECK-PIC'