set -o pipefail
'llc' '-march=arm' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/unaligned_load_store.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/unaligned_load_store.ll' '-check-prefix=GENERIC'  &&

'llc' '-mtriple=armv6-apple-darwin' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/unaligned_load_store.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/unaligned_load_store.ll' '-check-prefix=DARWIN_V6'  &&

'llc' '-mtriple=armv6-linux' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/unaligned_load_store.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/unaligned_load_store.ll' '-check-prefix=GENERIC'