set -o pipefail
'llc' '-march=arm' '-mattr=+v6' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/uxt_rot.ll' |
  'grep' 'uxtb' |
  'count' '1'  &&

'llc' '-march=arm' '-mattr=+v6' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/uxt_rot.ll' |
  'grep' 'uxtab' |
  'count' '1'  &&

'llc' '-march=arm' '-mattr=+v6' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/uxt_rot.ll' |
  'grep' 'uxth' |
  'count' '1'