set -o pipefail
'llc' '-march=arm' '-mtriple=arm-linux-gnueabi' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/vargs_align.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/vargs_align.ll' '-check-prefix=EABI'  &&

'llc' '-march=arm' '-mtriple=arm-linux-gnu' < '/private/var/chris/llvm-2.8/test/CodeGen/ARM/vargs_align.ll' |
  'FileCheck' '/private/var/chris/llvm-2.8/test/CodeGen/ARM/vargs_align.ll' '-check-prefix=OABI'