set -o pipefail
'opt' '-indvars' '-S' < '/private/var/chris/llvm-2.8/test/Analysis/ScalarEvolution/avoid-smax-1.ll' > '/private/var/chris/llvm-2.8/test/Analysis/ScalarEvolution/Output/avoid-smax-1.ll.tmp'  &&

'grep' 'select' '/private/var/chris/llvm-2.8/test/Analysis/ScalarEvolution/Output/avoid-smax-1.ll.tmp' |
  'count' '2'  &&

'grep' 'icmp ne i32.* ' '/private/var/chris/llvm-2.8/test/Analysis/ScalarEvolution/Output/avoid-smax-1.ll.tmp'