set -o pipefail
'opt' '-analyze' '-scalar-evolution' < '/private/var/chris/llvm-2.8/test/Analysis/ScalarEvolution/sext-inreg.ll' > '/private/var/chris/llvm-2.8/test/Analysis/ScalarEvolution/Output/sext-inreg.ll.tmp'  &&

'grep' 'sext i57 {0,+,199}<%bb> to i64' '/private/var/chris/llvm-2.8/test/Analysis/ScalarEvolution/Output/sext-inreg.ll.tmp' |
  'count' '1'  &&

'grep' 'sext i59 {0,+,199}<%bb> to i64' '/private/var/chris/llvm-2.8/test/Analysis/ScalarEvolution/Output/sext-inreg.ll.tmp' |
  'count' '1'