set -o pipefail
'opt' '-analyze' '-scalar-evolution' < '/private/var/chris/llvm-2.8/test/Analysis/ScalarEvolution/trip-count5.ll' > '/private/var/chris/llvm-2.8/test/Analysis/ScalarEvolution/Output/trip-count5.ll.tmp'  &&

'grep' 'sext' '/private/var/chris/llvm-2.8/test/Analysis/ScalarEvolution/Output/trip-count5.ll.tmp' |
  'count' '2'  &&

'not' 'grep' '(sext' '/private/var/chris/llvm-2.8/test/Analysis/ScalarEvolution/Output/trip-count5.ll.tmp'