#! /bin/sh

for i in cxs a cxb cxc cxsys dap esf MSTypes MSIPC MSGUI IPC AplusGUI
do
  cd src/$i
  sed -e 's/^\.\(.\)\.lo:/.\1.ng:/' \
    -e 's/\.lo/.o/g' \
    -e 's/$(LIBTOOL) --mode=link //' \
    -e "s/^	\$(CXXLINK) -rpath .*/	libtool -o lib${i}.a \$(lib${i}_la_OBJECTS)/" \
    -e "s/^	\$(LINK) -rpath .*/	libtool -o lib${i}.a \$(lib${i}_la_OBJECTS)/" \
    -e 's/lib\(.*\)\.la/lib\1.a/' Makefile > Makefile.mac
  mv Makefile.mac Makefile
  cd ../..
done

sed 's;^	\$(CXXLINK) .*;	\$(CXX) -all_load \$(aplus_OBJECTS) \$(aplus_LDADD) \$(LIBS) -framework CoreServices -o \$@;' src/main/Makefile > src/main/Makefile.mac
mv src/main/Makefile.mac src/main/Makefile

  sed -e 's/libcxs\.la/libcxs.a/g' \
      -e 's/liba\.la/liba.a/g' \
      -e 's/libcxb\.la/libcxb.a/g' \
      -e 's/libcxc\.la/libcxc.a/g' \
      -e 's/libcxsys\.la/libcxsys.a/g' \
      -e 's/libdap\.la/libdap.a/g' \
      -e 's/libesf\.la/libesf.a/g' \
      -e 's/libAplusGUI\.la/libAplusGUI.a/g' \
      -e 's/libIPC\.la/libIPC.a/g' \
      -e 's/libMSGUI\.la/libMSGUI.a/g' \
      -e 's/libMSIPC\.la/libMSIPC.a/g' \
      -e 's/libMSTypes\.la/libMSTypes.a/g' \
     src/main/Makefile > src/main/Makefile.mac
mv src/main/Makefile.mac src/main/Makefile

