/*
 * The Bonobo Document Model
 *
 * Author: 
 *     Miguel de Icaza (miguel@gnu.org)
 *
 */
#ifndef _BONOBO_IDL_INCLUDED_
#define _BONOBO_IDL_INCLUDED_

#if !defined(__Bonobo_COMPILATION) && defined(__ORBIT_IDL__)
%{
#pragma include_defs bonobo/Bonobo.h
%}
#pragma inhibit push
#endif

/* From bonobo-activation */
#include <Bonobo_Unknown.idl>
#include <Bonobo_GenericFactory.idl>

/* Basics */
#include <Bonobo_Exception.idl>
#include <Bonobo_Moniker.idl>
#include <Bonobo_Context.idl>

/* Storage stuff. */
#include <Bonobo_Storage.idl>
#include <Bonobo_Persist.idl>

/* Control stuff. */
#include <Bonobo_Listener.idl>
#include <Bonobo_Gdk.idl>
#include <Bonobo_UI.idl>
#include <Bonobo_Property.idl>
#include <Bonobo_Control.idl>
#include <Bonobo_Zoomable.idl>

/* Subdocument stuff. */
#include <Bonobo_ItemContainer.idl>
#include <Bonobo_Canvas.idl>
#include <Bonobo_Embeddable.idl>

/* Printing stuff */
#include <Bonobo_Print.idl>

/* Clipboard */
#include <Bonobo_Clipboard.idl>

#if !defined(__Bonobo_COMPILATION) && defined(__ORBIT_IDL__)
#pragma inhibit pop
#endif

#endif /* _BONOBO_IDL_INCLUDED_ */
