'\" t
.\" $Header: /cvsroot/lesstif/lesstif/doc/lessdox/widgets/OverrideShell.3,v 1.3 2009/04/29 12:23:30 paulgevers Exp $
.\"
.\" Copyright (C) 1997-1998 Free Software Foundation, Inc.
.\" 
.\" This file is part of the GNU LessTif Library.
.\" This library is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU Library General Public
.\" License as published by the Free Software Foundation; either
.\" version 2 of the License, or (at your option) any later version.
.\" 
.\" This library is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" Library General Public License for more details.
.\" 
.\" You should have received a copy of the GNU Library General Public
.\" License along with this library; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\" 
.TH OverrideShell 3 "October 1998" "LessTif Project" "LessTif Manuals"
.SH NAME
OverrideShell \- core widget from X toolkit
.SH SYNOPSIS
.B #include <X11/Shell.h>
.SH DESCRIPTION
OverrideShell
is a widget which is defined in the X Toolkit.
We document its existence here for completeness.
Please refer to the X Window System documentation for
the real information regarding this widget.
.SH X RESOURCES
.TS
tab(;);
l l l l l.
Name;Class;Type;Default;Access
_
XtNoverrideRedirect;XtCOverrideRedirect;Boolean;NULL;CSG
XtNsaveUnder;XtCSaveUnder;Boolean;NULL;CSG
.TE
.PP
.BR XtNoverrideRedirect
.PP
.BR XtNsaveUnder
.PP
.SH CLASS HIERARCHY
.BR Object (3)
.BR Rect (3)
.BR UnNamedObj (3)
.BR Core (3)
.BR Composite (3)
.BR Shell (3)
.BR OverrideShell (3)
.SH CALLBACKS
.SH CONVENIENCE FUNCTIONS
.SH SEE ALSO
