'\" t
.\" $Header: /cvsroot/lesstif/lesstif/doc/lessdox/widgets/XmComboBox.3,v 1.5 2009/04/29 12:23:30 paulgevers Exp $
.\"
.\" Copyright (C) 1997-1998 Free Software Foundation, Inc.
.\" 
.\" This file is part of the GNU LessTif Library.
.\" This library is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU Library General Public
.\" License as published by the Free Software Foundation; either
.\" version 2 of the License, or (at your option) any later version.
.\" 
.\" This library is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" Library General Public License for more details.
.\" 
.\" You should have received a copy of the GNU Library General Public
.\" License along with this library; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\" 
.TH XmComboBox 3 "April 1998" "LessTif Project" "LessTif Manuals"
.SH NAME
XmComboBox \- Motif-compatible combination-box widget
.SH SYNOPSIS
.B #include <Xm/ComboBox.h>
.PP
.B XmComboBox
.PP
.B XmCreateComboBox
.SH DESCRIPTION
XmComboBox
.SH X RESOURCES
.TS
tab(;);
l l l l l.
Name;Class;Type;Default;Access
_
XmNarrowSize;XmCArrowSize;HorizontalDimension;NULL;CSG
XmNarrowSpacing;XmCArrowSpacing;HorizontalDimension;NULL;CSG
XmNcomboBoxType;XmCComboBoxType;ComboBoxType;NULL;CSG
XmNfontList;XmCFontList;FontList;NULL;CSG
XmNhighlightThickness;XmCHighlightThickness;HorizontalDimension;NULL;CSG
XmNmarginWidth;XmCMarginWidth;HorizontalDimension;NULL;CSG
XmNmarginHeight;XmCMarginHeight;VerticalDimension;NULL;CSG
XmNmatchBehavior;XmCMatchBehavior;MatchBehavior;NULL;CSG
XmNrenderTable;XmCRenderTable;RenderTable;NULL;CSG
XmNselectedItem;XmCSelectedItem;XmString;NULL;CSG
XmNselectedPosition;XmCSelectedPosition;Int;0;CSG
XmNselectionCallback;XmCCallback;Callback;NULL;CSG
XmNshadowThickness;XmCShadowThickness;HorizontalDimension;NULL;CSG
.TE
.PP
.BR XmNarrowSize
.PP
.BR XmNarrowSpacing
.PP
.BR XmNcomboBoxType
.PP
.BR XmNfontList
.PP
.BR XmNhighlightThickness
.PP
.BR XmNmarginWidth
.PP
.BR XmNmarginHeight
.PP
.BR XmNmatchBehavior
.PP
.BR XmNrenderTable
.PP
.BR XmNselectedItem
.PP
.BR XmNselectedPosition
.PP
.BR XmNselectionCallback
.PP
.BR XmNshadowThickness
.PP
.SH CLASS HIERARCHY
.BR Object (3)
.BR Rect (3)
.BR UnNamedObj (3)
.BR Core (3)
.BR Composite (3)
.BR Constraint (3)
.BR XmManager (3)
.BR XmComboBox (3)
.SH CALLBACKS
.SH CONVENIENCE FUNCTIONS
.SH SEE ALSO
