'\" t
.\" $Header: /cvsroot/lesstif/lesstif/doc/lessdox/widgets/XmLabelGadget.3,v 1.5 2009/04/29 12:23:30 paulgevers Exp $
.\"
.\" Copyright (C) 1997-1998 Free Software Foundation, Inc.
.\" 
.\" This file is part of the GNU LessTif Library.
.\" This library is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU Library General Public
.\" License as published by the Free Software Foundation; either
.\" version 2 of the License, or (at your option) any later version.
.\" 
.\" This library is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" Library General Public License for more details.
.\" 
.\" You should have received a copy of the GNU Library General Public
.\" License along with this library; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\" 
.TH XmLabelGadget 3 "April 1998" "LessTif Project" "LessTif Manuals"
.SH NAME
XmLabelGadget \- Motif-compatible label gadget
.SH SYNOPSIS
.B #include <Xm/LabelG.h>
.PP
.B XmLabelGadget
.PP
.B XmCreateLabelGadget
.SH DESCRIPTION
XmLabelGadget
.SH X RESOURCES
.TS
tab(;);
l l l l l.
Name;Class;Type;Default;Access
_
XmNshadowThickness;XmCShadowThickness;HorizontalDimension;NULL;CSG
XmNlabelPixmap;XmCLabelPixmap;GadgetPixmap;NULL;CSG
XmNlabelInsensitivePixmap;XmCLabelInsensitivePixmap;GadgetPixmap;NULL;CSG
XmNlabelString;XmCXmString;XmString;NULL;CSG
XmNfontList;XmCFontList;FontList;NULL;CSG
XmNmnemonic;XmCMnemonic;KeySym;NULL;CSG
XmNmnemonicCharSet;XmCMnemonicCharSet;String;NULL;CSG
XmNaccelerator;XmCAccelerator;String;NULL;CSG
XmNacceleratorText;XmCAcceleratorText;XmString;NULL;CSG
XmNtraversalOn;XmCTraversalOn;Boolean;NULL;CSG
XmNhighlightThickness;XmCHighlightThickness;HorizontalDimension;NULL;CSG
.TE
.PP
.BR XmNshadowThickness
.PP
.BR XmNlabelPixmap
.PP
.BR XmNlabelInsensitivePixmap
.PP
.BR XmNlabelString
.PP
.BR XmNfontList
.PP
.BR XmNmnemonic
.PP
.BR XmNmnemonicCharSet
.PP
.BR XmNaccelerator
.PP
.BR XmNacceleratorText
.PP
.BR XmNtraversalOn
.PP
.BR XmNhighlightThickness
.PP
.SH CLASS HIERARCHY
.BR Object (3)
.BR Rect (3)
.BR XmGadget (3)
.BR XmLabelGadget (3)
.SH CALLBACKS
.SH CONVENIENCE FUNCTIONS
.SH SEE ALSO
