'\" t
.\" $Header: /cvsroot/lesstif/lesstif/doc/lessdox/widgets/XmScreen.3,v 1.5 2009/04/29 12:23:30 paulgevers Exp $
.\"
.\" Copyright (C) 1997-1998 Free Software Foundation, Inc.
.\" 
.\" This file is part of the GNU LessTif Library.
.\" This library is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU Library General Public
.\" License as published by the Free Software Foundation; either
.\" version 2 of the License, or (at your option) any later version.
.\" 
.\" This library is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" Library General Public License for more details.
.\" 
.\" You should have received a copy of the GNU Library General Public
.\" License along with this library; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\" 
.TH XmScreen 3 "April 1998" "LessTif Project" "LessTif Manuals"
.SH NAME
XmScreen \- Motif-compatible screen widget
.SH SYNOPSIS
.B #include <Xm/Screen.h>
.PP
.B XmScreen
.SH DESCRIPTION
XmScreen is an internal class,
it should not be used by application programs.
.SH X RESOURCES
.TS
tab(;);
l l l l l.
Name;Class;Type;Default;Access
_
XmNdarkThreshold;XmCDarkThreshold;Int;0;CSG
XmNlightThreshold;XmCLightThreshold;Int;0;CSG
XmNforegroundThreshold;XmCForegroundThreshold;Int;0;CSG
XmNdefaultNoneCursorIcon;XmCDefaultNoneCursorIcon;Widget;NULL;CSG
XmNdefaultValidCursorIcon;XmCDefaultValidCursorIcon;Widget;NULL;CSG
XmNdefaultInvalidCursorIcon;XmCDefaultInvalidCursorIcon;Widget;NULL;CSG
XmNdefaultMoveCursorIcon;XmCDefaultMoveCursorIcon;Widget;NULL;CSG
XmNdefaultLinkCursorIcon;XmCDefaultLinkCursorIcon;Widget;NULL;CSG
XmNdefaultCopyCursorIcon;XmCDefaultCopyCursorIcon;Widget;NULL;CSG
XmNdefaultSourceCursorIcon;XmCDefaultSourceCursorIcon;Widget;NULL;CSG
XmNmenuCursor;XmCCursor;Cursor;arrow;CSG
XmNunpostBehavior;XmCUnpostBehavior;UnpostBehavior;NULL;CSG
XmNfont;XmCFont;FontStruct;Fixed;CSG
XmNhorizontalFontUnit;XmCHorizontalFontUnit;Int;-1;CSG
XmNverticalFontUnit;XmCVerticalFontUnit;Int;-1;CSG
XmNmoveOpaque;XmCMoveOpaque;Boolean;NULL;CSG
.TE
.PP
.BR XmNdarkThreshold
.PP
.BR XmNlightThreshold
.PP
.BR XmNforegroundThreshold
.PP
.BR XmNdefaultNoneCursorIcon
.PP
.BR XmNdefaultValidCursorIcon
.PP
.BR XmNdefaultInvalidCursorIcon
.PP
.BR XmNdefaultMoveCursorIcon
.PP
.BR XmNdefaultLinkCursorIcon
.PP
.BR XmNdefaultCopyCursorIcon
.PP
.BR XmNdefaultSourceCursorIcon
.PP
.BR XmNmenuCursor
.PP
.BR XmNunpostBehavior
.PP
.BR XmNfont
.PP
.BR XmNhorizontalFontUnit
.PP
.BR XmNverticalFontUnit
.PP
.BR XmNmoveOpaque
.PP
.SH CLASS HIERARCHY
.BR Object (3)
.BR Rect (3)
.BR UnNamedObj (3)
.BR Core (3)
.BR XmScreen (3)
.SH CALLBACKS
.SH CONVENIENCE FUNCTIONS
.SH SEE ALSO
