set -o pipefail
'/usr/local/bin/ocamlopt' '-cc' 'g++ -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT' '-I' '/private/var/chris/llvm-2.8/Release/lib/ocaml' '-warn-error' 'A' 'unix.cmxa' 'llvm.cmxa' 'llvm_bitwriter.cmxa' '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/bitwriter.ml' '-o' '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/bitwriter.ml.tmp'  &&

'/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/bitwriter.ml.tmp' '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/bitwriter.ml.tmp.bc'  &&

'llvm-dis' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/bitwriter.ml.tmp.bc' |
  'grep' 'caml_int_ty'