set -o pipefail
'/usr/local/bin/ocamlopt' '-cc' 'g++ -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT' '-I' '/private/var/chris/llvm-2.8/Release/lib/ocaml' '-warn-error' 'A' 'llvm.cmxa' 'llvm_target.cmxa' '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/target.ml' '-o' '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/target.ml.tmp'  &&

'/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/target.ml.tmp' '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/target.ml.tmp.bc'