set -o pipefail
'/usr/local/bin/ocamlopt' '-cc' 'g++ -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT' '-I' '/private/var/chris/llvm-2.8/Release/lib/ocaml' '-warn-error' 'A' 'llvm.cmxa' 'llvm_analysis.cmxa' 'llvm_bitwriter.cmxa' '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/vmcore.ml' '-o' '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp'  &&

'/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp' '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.bc'  &&

'llvm-dis' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.bc' > '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'i686-apple-darwin8' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'bogus' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'void_type.*void' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'i1_type.*i1' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'i32_type.*i32' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'i42_type.*i42' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'float_type.*float' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'double_type.*double' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'function_type.*i32.*i1, double' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'var_arg_type.*...' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'array_type.*\[7 x i8\]' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'pointer_type.*float*' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'qualified_pointer_type.*i8.*3.**' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'vector_type.*<4 x i16>' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'opaque_type.*opaque' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '-v' 'delete_type' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'type_name.*opaque' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '-v' 'recursive_type.*recursive_type' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_int.*i32.*-1' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_sext_int.*i64.*-1' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_zext_int64.*i64.*4294967295' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_int_string.*i32.*-1' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_string.*"cruel\\00world"' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_stringz.*"hi\\00again\\00"' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_single.*2.75' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_double.*3.1459' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_double_string.*1.25' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_array.*\[i32 3, i32 4\]' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_vector.*<i16 1, i16 2.*>' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_structure.*.i16 1, i16 2, i32 3, i32 4' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_null.*zeroinit' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_all_ones.*-1' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_pointer_null = global i64\* null' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_undef.*undef' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_neg = global i64 sub' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_nsw_neg = global i64 sub nsw ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_nuw_neg = global i64 sub nuw ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_fneg = global double fsub ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_not = global i64 xor ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_add = global i64 add ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_nsw_add = global i64 add nsw ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_nuw_add = global i64 add nuw ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_fadd = global double fadd ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_sub = global i64 sub ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_nsw_sub = global i64 sub nsw ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_nuw_sub = global i64 sub nuw ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_fsub = global double fsub ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_mul = global i64 mul ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_nsw_mul = global i64 mul nsw ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_nuw_mul = global i64 mul nuw ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_fmul = global double fmul ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_udiv = global i64 udiv ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_sdiv = global i64 sdiv ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_exact_sdiv = global i64 sdiv exact ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_fdiv = global double fdiv ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_urem = global i64 urem ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_srem = global i64 srem ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_frem = global double frem ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_and = global i64 and ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_or = global i64 or ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_xor = global i64 xor ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_icmp = global i1 icmp sle ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@const_fcmp = global i1 fcmp ole ' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_trunc.*trunc' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_sext.*sext' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_zext.*zext' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_fptrunc.*fptrunc' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_fpext.*fpext' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_uitofp.*uitofp' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_sitofp.*sitofp' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_fptoui.*fptoui' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_fptosi.*fptosi' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_ptrtoint.*ptrtoint' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_inttoptr.*inttoptr' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_bitcast.*bitcast' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_size_of.*getelementptr.*null' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_gep.*getelementptr' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_select.*select' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_extractelement.*extractelement' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_insertelement.*insertelement' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'const_shufflevector = global <4 x i32> <i32 0, i32 1, i32 1, i32 0>' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'GVal01' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'GVal02.*linkonce' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'GVal03.*Hanalei' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'GVal04.*hidden' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'GVal05.*align 128' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'GVar01.*external' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'GVar02.*42' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'GVar03.*42' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'GVar04.*thread_local' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '-v' 'GVar05' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '-v' 'ConstGlobalVar.*constant' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '@alias = alias i32\* @aliasee' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'declare i32 @Fn1(i32, i64)' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '-v' 'Fn2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'define.*Fn3' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'define.*Fn4.*Param1.*Param2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'fastcc.*Fn5' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'Fn6.*gc.*shadowstack' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'Bb1' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '-v' 'Bb2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'Bb3' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'ret void' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'ret.*P1' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'br.*Bb02' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'br.*build_br.*Bb03.*Bb00' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'switch.*P1.*SwiBlock3' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '2,.*SwiBlock2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'indirectbr i8\* blockaddress(@X7, %IBRBlock2), \[label %IBRBlock2, label %IBRBlock3\]' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'build_invoke.*invoke.*P1.*P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'to.*Bb04.*unwind.*Bb00' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'unwind' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'unreachable' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_add = add i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_nsw_add = add nsw i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_nuw_add = add nuw i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_fadd = fadd float %F1, %F2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_sub = sub i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_nsw_sub = sub nsw i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_nuw_sub = sub nuw i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_fsub = fsub float %F1, %F2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_mul = mul i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_nsw_mul = mul nsw i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_nuw_mul = mul nuw i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_fmul = fmul float %F1, %F2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_udiv = udiv i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_sdiv = sdiv i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_exact_sdiv = sdiv exact i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_fdiv = fdiv float %F1, %F2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_urem = urem i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_srem = srem i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_frem = frem float %F1, %F2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_shl = shl i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_lshl = lshr i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_ashl = ashr i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_and = and i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_or = or i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_xor = xor i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_neg = sub i32 0, %P1' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_nsw_neg = sub nsw i32 0, %P1' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_nuw_neg = sub nuw i32 0, %P1' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_fneg = fsub float .*0.*, %F1' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_not = xor i32 %P1, -1' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_alloca = alloca i32' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_array_alloca = alloca i32, i32 %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_load = load i32\* %build_array_alloca' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'store i32 %P2, i32\* %build_alloca' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_gep = getelementptr i32\* %build_array_alloca, i32 %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_trunc = trunc i32 %P1 to i8' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_zext = zext i8 %build_trunc to i32' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_sext = sext i32 %build_zext to i64' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_uitofp = uitofp i64 %build_sext to float' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_sitofp = sitofp i32 %build_zext to double' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_fptoui = fptoui float %build_uitofp to i32' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_fptosi = fptosi double %build_sitofp to i64' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_fptrunc = fptrunc double %build_sitofp to float' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_fpext = fpext float %build_fptrunc to double' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_inttoptr = inttoptr i32 %P1 to i8\*' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_ptrtoint = ptrtoint i8\* %build_inttoptr to i64' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_bitcast = bitcast i64 %build_ptrtoint to double' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_icmp_ne = icmp ne i32 %P1, %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_icmp_sle = icmp sle i32 %P2, %P1' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_fcmp_false = fcmp false float %F1, %F2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_fcmp_true = fcmp true float %F2, %F1' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_call = tail call cc63 i32 @.*(i32 signext %P2, i32 %P1)' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_select = select i1 %build_icmp, i32 %P1, i32 %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_va_arg = va_arg i8\*\* null, i32' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_extractelement = extractelement <4 x i32> %Vec1, i32 %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_insertelement = insertelement <4 x i32> %Vec1, i32 %P1, i32 %P2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%build_shufflevector = shufflevector <4 x i32> %Vec1, <4 x i32> %Vec2, <4 x i32> <i32 1, i32 1, i32 0, i32 0>' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%metadata = add i32 %P1, %P2, !test !0' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '!0 = metadata !{i32 1, metadata !"metadata test"}' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '%dbg = add i32 %P1, %P2, !dbg !1' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' '!1 = metadata !{i32 2, i32 3, metadata !2, metadata !2}' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'  &&

'grep' 'PhiNode.*P1.*PhiBlock1.*P2.*PhiBlock2' < '/private/var/chris/llvm-2.8/test/Bindings/Ocaml/Output/vmcore.ml.tmp.ll'