'\" t
.\"     Title: i3-sensible-pager
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 11/11/2011
.\"    Manual: i3 Manual
.\"    Source: i3 4.1
.\"  Language: English
.\"
.TH "I3\-SENSIBLE\-PAGER" "1" "11/11/2011" "i3 4\&.1" "i3 Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
i3-sensible-pager \- launches $PAGER with fallbacks
.SH "SYNOPSIS"
.sp
i3\-sensible\-pager [arguments]
.SH "DESCRIPTION"
.sp
i3\-sensible\-pager is used by i3\-nagbar(1) when you click on the view button\&.
.sp
It tries to start one of the following (in that order):
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
$PAGER
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
most
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
less
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
i3\-sensible\-editor(1)
.RE
.sp
Please don\(cqt complain about the order: If the user has any preference, he will have $PAGER set\&.
.SH "SEE ALSO"
.sp
i3(1)
.SH "AUTHOR"
.sp
Michael Stapelberg and contributors
