/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* set background image */
#define BACKGROUND_IMAGE 

/* set cursor blinking support */
#define CURSOR_BLINK 

/* set DEBUG mode */
/* #undef DEBUG */

/* the width of external border */
#define EXTERNALBORDERWIDTH 0

/* set Greek keyboard support */
/* #undef GREEK_SUPPORT */

/* set half shadow rxvt scrollbar support */
#define HALFSHADOW 

/* Define to 1 if you have the <arpa/inet.h> header file. */
#define HAVE_ARPA_INET_H 1

/* Define to 1 if you have the <assert.h> header file. */
#define HAVE_ASSERT_H 1

/* Define to 1 if your system has a working `chown' function. */
#define HAVE_CHOWN 1

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the <fontconfig/fontconfig.h> header file. */
/* #undef HAVE_FONTCONFIG_FONTCONFIG_H */

/* Define to 1 if you have the `fork' function. */
#define HAVE_FORK 1

/* Define to 1 if you have the `getcwd' function. */
#define HAVE_GETCWD 1

/* Define to 1 if you have the `getpt' function. */
/* #undef HAVE_GETPT */

/* Define to 1 if you have the `getpwuid' function. */
#define HAVE_GETPWUID 1

/* Define to 1 if you have the `grantpt' function. */
#define HAVE_GRANTPT 1

/* Define to 1 if you have the <iconv.h> header file. */
#define HAVE_ICONV_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `isastream' function. */
/* #undef HAVE_ISASTREAM */

/* Define to 1 if you have the <langinfo.h> header file. */
#define HAVE_LANGINFO_H 1

/* Define to 1 if you have the <lastlog.h> header file. */
/* #undef HAVE_LASTLOG_H */

/* Define to 1 if you have the `fontconfig' library (-lfontconfig). */
/* #undef HAVE_LIBFONTCONFIG */

/* Define to 1 if you have the `ICE' library (-lICE). */
#define HAVE_LIBICE 1

/* Define to 1 if you have the `iconv' library (-liconv). */
/* #undef HAVE_LIBICONV */

/* Define to 1 if you have the `jpeg' library (-ljpeg). */
#define HAVE_LIBJPEG 1

/* Define to 1 if you have the `png' library (-lpng). */
/* #undef HAVE_LIBPNG */

/* Define to 1 if you have the `SM' library (-lSM). */
#define HAVE_LIBSM 1

/* Define to 1 if you have the `utempter' library (-lutempter). */
/* #undef HAVE_LIBUTEMPTER */

/* Define to 1 if you have the `util' library (-lutil). */
/* #undef HAVE_LIBUTIL */

/* Define to 1 if you have the `X11' library (-lX11). */
#define HAVE_LIBX11 1

/* Define to 1 if you have the `Xft' library (-lXft). */
/* #undef HAVE_LIBXFT */

/* Define to 1 if you have the `xpg4' library (-lxpg4). */
/* #undef HAVE_LIBXPG4 */

/* Define to 1 if you have the `Xpm' library (-lXpm). */
#define HAVE_LIBXPM 1

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if `lstat' has the bug that it succeeds when given the
   zero-length file name argument. */
/* #undef HAVE_LSTAT_EMPTY_STRING_BUG */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* set menu bar */
#define HAVE_MENUBAR 

/* Define to 1 if you have the `nanosleep' function. */
#define HAVE_NANOSLEEP 1

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define to 1 if you have the <net/if_arp.h> header file. */
/* #undef HAVE_NET_IF_ARP_H */

/* Define to 1 if you have the <net/if.h> header file. */
#define HAVE_NET_IF_H 1

/* Define to 1 if you have the `openpty' function. */
#define HAVE_OPENPTY 1

/* Define to 1 if you have the <pty.h> header file. */
/* #undef HAVE_PTY_H */

/* Define to 1 if you have the `putenv' function. */
#define HAVE_PUTENV 1

/* Define to 1 if you have the `revoke' function. */
#define HAVE_REVOKE 1

/* set scroll bar support */
#define HAVE_SCROLLBARS 

/* Define to 1 if you have the `select' function. */
#define HAVE_SELECT 1

/* Define to 1 if you have the `seteuid' function. */
#define HAVE_SETEUID 1

/* Define to 1 if you have the `setlocale' function. */
#define HAVE_SETLOCALE 1

/* Define to 1 if you have the `setpgid' function. */
#define HAVE_SETPGID 1

/* Define to 1 if you have the `setpgrp' function. */
#define HAVE_SETPGRP 1

/* Define to 1 if you have the `setreuid' function. */
#define HAVE_SETREUID 1

/* Define to 1 if you have the `setsid' function. */
#define HAVE_SETSID 1

/* Define to 1 if you have the `setutent' function. */
/* #undef HAVE_SETUTENT */

/* Define to 1 if you have the <sgtty.h> header file. */
/* #undef HAVE_SGTTY_H */

/* Define to 1 if you have the `socket' function. */
#define HAVE_SOCKET 1

/* Define to 1 if you have the <stdarg.h> header file. */
#define HAVE_STDARG_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strchr' function. */
#define HAVE_STRCHR 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strndup' function. */
/* #undef HAVE_STRNDUP */

/* Define to 1 if you have the `strrchr' function. */
#define HAVE_STRRCHR 1

/* Define if utmp.h or lastlog.h has struct lastlog */
/* #undef HAVE_STRUCT_LASTLOG */

/* Define if utmp.h has struct utmp */
/* #undef HAVE_STRUCT_UTMP */

/* Define if utmpx.h has struct utmpx */
/* #undef HAVE_STRUCT_UTMPX */

/* Define to 1 if you have the <sys/byteorder.h> header file. */
/* #undef HAVE_SYS_BYTEORDER_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/select.h> header file. */
#define HAVE_SYS_SELECT_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/sockio.h> header file. */
#define HAVE_SYS_SOCKIO_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/stropts.h> header file. */
/* #undef HAVE_SYS_STROPTS_H */

/* Define to 1 if you have the <sys/strredir.h> header file. */
/* #undef HAVE_SYS_STRREDIR_H */

/* Define to 1 if you have the <sys/times.h> header file. */
#define HAVE_SYS_TIMES_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/wait.h> header file. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <termios.h> header file. */
#define HAVE_TERMIOS_H 1

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define to 1 if you have the `ttyslot' function. */
#define HAVE_TTYSLOT 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `unlockpt' function. */
#define HAVE_UNLOCKPT 1

/* Define to 1 if you have the `unsetenv' function. */
#define HAVE_UNSETENV 1

/* Define to 1 if you have the `updwtmp' function. */
/* #undef HAVE_UPDWTMP */

/* Define to 1 if you have the `updwtmpx' function. */
/* #undef HAVE_UPDWTMPX */

/* Define to 1 if you have the <utmpx.h> header file. */
#define HAVE_UTMPX_H 1

/* Define if struct utmpx contains ut_host */
/* #undef HAVE_UTMPX_HOST */

/* Define if struct utmpx contains ut_session */
/* #undef HAVE_UTMPX_SESSION */

/* Define to 1 if you have the <utmp.h> header file. */
#define HAVE_UTMP_H 1

/* Define if struct utmp contains ut_host */
/* #undef HAVE_UTMP_HOST */

/* Define if struct utmp contains ut_pid */
/* #undef HAVE_UTMP_PID */

/* Define to 1 if you have the `vfork' function. */
#define HAVE_VFORK 1

/* Define to 1 if you have the <vfork.h> header file. */
/* #undef HAVE_VFORK_H */

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Define to 1 if you have the <wchar.h> header file. */
#define HAVE_WCHAR_H 1

/* Define to 1 if `fork' works. */
#define HAVE_WORKING_FORK 1

/* Define to 1 if `vfork' works. */
#define HAVE_WORKING_VFORK 1

/* Define to 1 if you have the <X11/SM/SMlib.h> header file. */
#define HAVE_X11_SM_SMLIB_H 1

/* Define to 1 if you have the <X11/Xft/Xft.h> header file. */
/* #undef HAVE_X11_XFT_XFT_H */

/* Define if you have XPointer typedef */
#define HAVE_XPOINTER 1

/* Define to 1 if you have the `xsetlocale' function. */
/* #undef HAVE_XSETLOCALE */

/* Define to 1 if you have the `_getpty' function. */
/* #undef HAVE__GETPTY */

/* the width of internal border */
#define INTERNALBORDERWIDTH 0

/* set lastlog support */
/* #undef LASTLOG_SUPPORT */

/* the space between lines */
#define LINESPACE 0

/* Define to 1 if `lstat' dereferences a symlink specified with a trailing
   slash. */
/* #undef LSTAT_FOLLOWS_SLASHED_SYMLINK */

/* the max number of vt that can be open */
#define MAX_PAGES 15

/* enable slip scrolling via mouse wheel */
/* #undef MOUSE_SLIP_WHEELING */

/* enable scrolling via mouse wheel */
#define MOUSE_WHEEL 

/* default encoding */
/* #undef MULTICHAR_ENCODING */

/* set CJK multichar set support */
/* #undef MULTICHAR_SET */

/* unset DEBUG mode */
#define NDEBUG 

/* set next style scroll bar */
#define NEXT_SCROLLBAR 

/* disable handling of backspace key */
/* #undef NO_BACKSPACE_KEY */

/* disable handling of the delete key */
/* #undef NO_DELETE_KEY */

/* enable rarely used features */
#define NO_FRILLS 

/* unset linespace support */
/* #undef NO_LINESPACE */

/* enable old mouse selection */
/* #undef NO_NEW_SELECTION */

/* disable old mouse selection */
#define NO_OLD_SELECTION 

/* disable all resource checking */
/* #undef NO_RESOURCES */

/* enable continual scrolling on scrollbar arrow press */
/* #undef NO_SCROLLBAR_BUTTON_CONTINUAL_SCROLLING */

/* disable swap screen support */
/* #undef NO_SECONDARY_SCREEN */

/* set fading support */
#define OFF_FOCUS_FADING 

/* set OS to aix */
/* #undef OS_AIX */

/* set OS to bsd */
#define OS_BSD 

/* set OS to cygwin */
/* #undef OS_CYGWIN */

/* set OS to darwin */
#define OS_DARWIN 

/* set OS to freebsd */
/* #undef OS_FREEBSD */

/* set OS to hp-ux */
/* #undef OS_HPUX */

/* set OS to irix */
/* #undef OS_IRIX */

/* set OS to linux */
/* #undef OS_LINUX */

/* set OS to netbsd */
/* #undef OS_NETBSD */

/* set OS to openbsd */
/* #undef OS_OPENBSD */

/* set OS to osf */
/* #undef OS_OSF */

/* set OS to sco */
/* #undef OS_SCO */

/* set OS to solaris */
/* #undef OS_SOLARIS */

/* set OS to sunos */
/* #undef OS_SUNOS */

/* set OS to svr4 */
/* #undef OS_SVR4 */

/* use our own string functions */
/* #undef OUR_STRINGS */

/* Name of package */
#define PACKAGE "mrxvt"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "jimmyzhou@users.sourceforge.net"

/* Define to the full name of this package. */
#define PACKAGE_NAME "mrxvt"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "mrxvt 0.4.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "mrxvt"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.4.2"

/* set plain style scroll bar */
#define PLAIN_SCROLLBAR 

/* set blank pointer support */
#define POINTER_BLANK 

/* set 24 bits color support */
/* #undef PREFER_24BIT */

/* Define for first char in devptyXX */
#define PTYCHAR1 "p"

/* Define for second char in devptyXX */
#define PTYCHAR2 "0123456789abcdef"

/* Define for this pty type */
/* #undef PTYS_ARE_CLONE */

/* Define for this pty type */
/* #undef PTYS_ARE_GETPT */

/* Define for this pty type */
/* #undef PTYS_ARE_GETPTY */

/* Define for this pty type */
/* #undef PTYS_ARE_NUMERIC */

/* Define for this pty type */
#define PTYS_ARE_OPENPTY 1

/* Define for this pty type */
/* #undef PTYS_ARE_PTC */

/* Define for this pty type */
/* #undef PTYS_ARE_PTMX */

/* Define for this pty type */
/* #undef PTYS_ARE_SEARCHED */

/* Define for this pty type */
/* #undef PTYS_ARE__GETPTY */

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* typedef */
#define RINT16T short

/* typedef */
#define RINT32T int

/* typedef */
#define RINTPT int

/* typedef */
#define RUINT16T unsigned short

/* typedef */
#define RUINT32T unsigned int

/* typedef */
#define RUINTPT unsigned int

/* set rxvt style scroll bar */
#define RXVT_SCROLLBAR 

/* terminfo path */
/* #undef RXVT_TERMINFO */

/* the lines to save in scroll */
#define SAVELINES 100

/* enable continual scrolling on selection */
#define SELECTION_SCROLLING 

/* Define to 1 if the `setpgrp' function takes no argument. */
#define SETPGRP_VOID 1

/* set sgi style scroll bar */
#define SGI_SCROLLBAR 

/* The size of a `char', as computed by sizeof. */
#define SIZEOF_CHAR 1

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `int *', as computed by sizeof. */
#define SIZEOF_INT_P 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* The size of a `long long', as computed by sizeof. */
#define SIZEOF_LONG_LONG 8

/* The size of a `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* set smart resizing support */
/* #undef SMART_RESIZE */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* term name */
#define TERMENV "xterm"

/* set text shadow support */
/* #undef TEXT_SHADOW */

/* set thai support */
/* #undef THAI */

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* set tinting support */
#define TINTING_SUPPORT 

/* Define to 1 if your <sys/time.h> declares `struct tm'. */
/* #undef TM_IN_SYS_TIME */

/* set transparent background */
#define TRANSPARENT 

/* set 256 color support */
#define TTY_256COLOR 

/* set ttygid support */
#define TTY_GID_SUPPORT 

/* set JPEG background */
#define USE_JPEG 

/* set PNG background */
/* #undef USE_PNG */

/* enable resources via X instead of our small version */
/* #undef USE_XGETDEFAULT */

/* set XIM support */
/* #undef USE_XIM */

/* set utempter library support */
/* #undef UTEMPTER_SUPPORT */

/* set utmp support */
/* #undef UTMP_SUPPORT */

/* Version number of package */
#define VERSION "0.4.2"

/* set wtmp support */
/* #undef WTMP_SUPPORT */

/* set XFT support */
/* #undef XFT_SUPPORT */

/* set xterm style scroll bar */
#define XTERM_SCROLLBAR 

/* set GNU source flag for linux */
/* #undef _GNU_SOURCE */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef gid_t */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to `int' if <sys/types.h> does not define. */
/* #undef mode_t */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef pid_t */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef uid_t */

/* Define as `fork' if `vfork' does not work. */
/* #undef vfork */
