#!/bin/sh
#
# Eterm Search Utility
#
# $Id: Etsearch 2048 2000-02-11 00:25:07Z mej $

if [ $# -gt 1 -o "X$1" = "X-h" -o "X$1" = "X--help" ]; then
  echo "Syntax:  Etsearch [string]"
  echo "   (To clear the highlighting from a previous search,"
  echo "    do not specify a string.)"
  echo
  exit 0
fi

# Code to figure out if we need 'echo -n' or 'echo "\c"', stolen from configure
if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null; then
  # Stardent Vistra SVR4 grep lacks -e, says ghazi@caip.rutgers.edu.
  if (echo -n testing; echo 1,2,3) | sed s/-n/xn/ | grep xn >/dev/null; then
    ac_n= ac_c='
'
  else
    ac_n=-n ac_c=
  fi
else
  ac_n= ac_c='\c'
fi

STR="$1"

echo $ac_n "]6;72;${STR}$ac_c"
