#ifndef AGIFmstkHEADER
#define AGIFmstkHEADER

///////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 1997-2008 Morgan Stanley All rights reserved.
// See .../src/LICENSE for terms of distribution.
//
//
///////////////////////////////////////////////////////////////////////////////

#if HAVE_IOSTREAM
#include <iostream>
#else
#include <iostream.h>
#endif
#include <X11/Xlib.h>

#include <MSTypes/MSUnsignedLongVector.H>
#include <MSTypes/MSHashTable.H>
#include <MSGUI/MSWidget.H>
#include <MSGUI/MSApplication.H>
#include <MSGUI/MSPixmap.H>
#include <MSGUI/MSManager.H>
#include <MSGUI/MSActionBox.H>
#include <MSGUI/MSScale.H>
#include <MSGUI/MSWidgetOutput.H>
#include <MSGUI/MSDisplayPrint.H>
#include <MSGUI/MSPostScript.H>
#include <MSGUI/MSScrolledWindow.H>

#include <AplusGUI/AplusCommon.H>
#include <AplusGUI/AGIF.H>
#include <AplusGUI/AplusShell.H>
#include <AplusGUI/AplusPopup.H>
#include <AplusGUI/AplusText.H>
#include <AplusGUI/AplusLabel.H>
#include <AplusGUI/AplusPage.H>
#include <AplusGUI/AplusScale.H>
#include <AplusGUI/AplusReference.H>
#include <AplusGUI/AplusEntryField.H>
#include <AplusGUI/AplusButton.H>
#include <AplusGUI/AplusLayout.H>
#include <AplusGUI/AplusArray.H>
#include <AplusGUI/AplusTable.H>
#include <AplusGUI/AplusTableColumn.H>
#include <AplusGUI/AplusCollapsible.H>
#include <AplusGUI/AplusPanes.H>
#include <AplusGUI/AplusScrolledWindow.H>
#include <AplusGUI/AplusButtonBox.H>
#include <AplusGUI/AplusCheckBox.H>
#include <AplusGUI/AplusRadioBox.H>
#include <AplusGUI/AplusTreeView.H>
#include <AplusGUI/AplusPassword.H>
#include <AplusGUI/AplusSlot.H>
#include <AplusGUI/AplusCommand.H>
#include <AplusGUI/AplusView.H>
#include <AplusGUI/AplusChoice.H>
#include <AplusGUI/AplusMenu.H>
#include <AplusGUI/AplusMatrix.H>
#include <AplusGUI/AplusManager.H>
#include <AplusGUI/AplusNotebook.H>

#endif  //AGIFmstkHEADER
