#ifndef AGIFGraphHEADER
#define AGIFGraphHEADER

///////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 1997-2008 Morgan Stanley All rights reserved.
// See .../src/LICENSE for terms of distribution.
//
//
///////////////////////////////////////////////////////////////////////////////

#include <AplusGUI/AplusGraph.H>
#include <AplusGUI/AplusTrace.H>

#endif //AGIFGraphHEADER

