.\"
.\" $Header: /cvsroot/lesstif/lesstif/doc/lessdox/clients/VirtualBindings.5,v 1.2 2009/04/29 12:23:30 paulgevers Exp $
.\"
.\" Copyright (C) 2001 LessTif Development Team
.\"
.\" This is free software; you can redistribute it and/or modify it under
.\" the terms of the GNU General Public License as published by the Free
.\" Software Foundation; either version 2, or (at your option) any later
.\" version.
.\"
.\" This is distributed in the hope that it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\"
.\" You should have received a copy of the GNU General Public License with
.\" your Debian GNU/Linux system, in /usr/doc/copyright/GPL, or with the
.\" dpkg source package as the file COPYING.  If not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH VirtualBindings 1x "January 2001" "LessTif Project" "LessTif Manuals"
.SH NAME
VirtualBindings \- Lesstif virtual-bindings facility
.SH SYNOPSIS
To be written
.SH SEE ALSO
.BR lesstif (1)
.BR xmbind (1)
