/* build-Darwin-gtk/testament.h
 * 
 * Revision testament.
 *
 * *WARNING* this file is automatically generated by git-testament.pl 
 *
 * Copyright 2012 NetSurf Browser Project
 */

#ifndef NETSURF_REVISION_TESTAMENT
#define NETSURF_REVISION_TESTAMENT "aa23554846edb41be9e26bf74ce23d32"

/* Revision testament checksum:
 * MD5:aa23554846edb41be9e26bf74ce23d32
 */

/* Revision testament: */
#define USERNAME "chris"
#define GECOS "Chris User"
#define WT_ROOT "/private/var/chris/netsurf-all-3.3/netsurf/"
#define WT_HOSTNAME "Chriss-iPad"
#define WT_COMPILEDATE "19.10.2015"
#define WT_BRANCHPATH "tarball"
#define WT_NO_GIT 1
#define WT_REVID "unknown"
#define WT_MODIFIED 0
#define WT_MODIFICATIONS {\
 \
}

#endif
