set -o pipefail
'llvm-as' '/private/var/chris/llvm-2.8/test/Analysis/Profiling/profiling-tool-chain.ll' '-o' '/private/var/chris/llvm-2.8/test/Analysis/Profiling/Output/profiling-tool-chain.ll.tmp1'  &&

'opt' '/private/var/chris/llvm-2.8/test/Analysis/Profiling/Output/profiling-tool-chain.ll.tmp1' '-insert-optimal-edge-profiling' '-o' '/private/var/chris/llvm-2.8/test/Analysis/Profiling/Output/profiling-tool-chain.ll.tmp2'  &&

'opt' '/private/var/chris/llvm-2.8/test/Analysis/Profiling/Output/profiling-tool-chain.ll.tmp1' '-profile-estimator' '-profile-verifier' '-o' '/private/var/chris/llvm-2.8/test/Analysis/Profiling/Output/profiling-tool-chain.ll.tmp3'